Paparazzi UAS: sw/airborne/modules/ahrs/ahrs_infrared.h File Reference
ahrs_infrared.h File Reference
#include "std.h"
Functions
void ahrs_infrared_init (void)
void ahrs_infrared_periodic (void)
Detailed Description
Fixedwing attitude estimation using infrared sensors.
Definition in file ahrs_infrared.h.
Function Documentation
ahrs_infrared_init()
void ahrs_infrared_init (void)
Definition at line 96 of file ahrs_infrared.c.
References AHRS_INFRARED_GPS_ID, AHRS_INFRARED_GYRO_ID, DefaultPeriodic, gps_cb(), gps_ev, gyro_cb(), gyro_ev, heading, register_periodic_telemetry(), send_infrared(), and send_status().
ahrs_infrared_periodic()
void ahrs_infrared_periodic (void)
Definition at line 126 of file ahrs_infrared.c.
References Infrared::correction_down, Infrared::correction_left, Infrared::correction_right, Infrared::correction_up, heading, infrared, FloatEulers::phi, Infrared::pitch, Infrared::pitch_neutral, Infrared::roll, Infrared::roll_neutral, stateSetNedToBodyEulers_f(), FloatEulers::theta, and Infrared::top.