Paparazzi UAS: sw/airborne/subsystems/ahrs/ahrs_vectornav_wrapper.h File Reference
ahrs_vectornav_wrapper.h File Reference
#include "subsystems/ahrs/ahrs_vectornav.h"
Macros
#define PRIMARY_AHRS ahrs_vectornav
Functions
void ahrs_vectornav_register (void)
bool ahrs_vectornav_is_enabled (void)
Detailed Description
Vectornav VN-200 as AHRS
Author
Michal Podhradsky micha.nosp@m.l.po.nosp@m.dhrad.nosp@m.sky@.nosp@m.aggie.nosp@m.mail.nosp@m..usu..nosp@m.edu
Definition in file ahrs_vectornav_wrapper.h.
Macro Definition Documentation
PRIMARY_AHRS
#define PRIMARY_AHRS ahrs_vectornav
Definition at line 34 of file ahrs_vectornav_wrapper.h.
Function Documentation
ahrs_vectornav_is_enabled()
bool ahrs_vectornav_is_enabled (void)
Definition at line 62 of file ahrs_vectornav_wrapper.c.
References ahrs_vectornav_output_enabled.
Referenced by ahrs_vectornav_event().
ahrs_vectornav_register()
void ahrs_vectornav_register (void)
Definition at line 66 of file ahrs_vectornav_wrapper.c.
References ahrs_register_impl(), ahrs_vectornav_enable_output(), ahrs_vectornav_init(), AHRS_VECTORNAV_OUTPUT_ENABLED, ahrs_vectornav_output_enabled, DefaultPeriodic, register_periodic_telemetry(), and send_euler().