Paparazzi UAS: sw/airborne/subsystems/ahrs/ahrs_float_invariant_wrapper.c File Reference
ahrs_float_invariant_wrapper.c File Reference
#include "subsystems/ahrs/ahrs_float_invariant_wrapper.h"
#include "subsystems/ahrs.h"
#include "subsystems/abi.h"
#include "mcu_periph/sys_time.h"
#include "message_pragmas.h"
#include "state.h"
#include "subsystems/datalink/telemetry.h"
Macros
#define AHRS_FINV_OUTPUT_ENABLED TRUE
#define AHRS_FINV_IMU_ID ABI_BROADCAST
IMU (gyro, accel)
#define AHRS_FINV_MAG_ID AHRS_FINV_IMU_ID
magnetometer
Functions
static void compute_body_orientation_and_rates (void)
Compute body orientation and rates from imu orientation and rates.
static void send_att (struct transport_tx *trans, struct link_device *dev)
static void send_geo_mag (struct transport_tx *trans, struct link_device *dev)
static void send_filter_status (struct transport_tx *trans, struct link_device *dev)
static void gyro_cb (uint8_t sender_id, uint32_t stamp, struct Int32Rates *gyro)
Call ahrs_float_invariant_propagate on new gyro measurements.
static void accel_cb (uint8_t sender_id, uint32_t stamp, struct Int32Vect3 *accel)
static void mag_cb (uint8_t sender_id, uint32_t stamp, struct Int32Vect3 *mag)
static void aligner_cb (uint8_t sender_id, uint32_t stamp, struct Int32Rates *lp_gyro, struct Int32Vect3 *lp_accel, struct Int32Vect3 *lp_mag)
static void body_to_imu_cb (uint8_t sender_id, struct FloatQuat *q_b2i_f)
static void geo_mag_cb (uint8_t sender_id, struct FloatVect3 *h)
static bool ahrs_float_invariant_enable_output (bool enable)
void ahrs_float_invariant_register (void)
Variables
static bool ahrs_finv_output_enabled
if TRUE with push the estimation results to the state interface
static uint32_t ahrs_finv_last_stamp = 0
last gyro msg timestamp
static uint8_t ahrs_finv_id = AHRS_COMP_ID_FINV
static abi_event mag_ev
static abi_event gyro_ev
static abi_event accel_ev
static abi_event aligner_ev
static abi_event body_to_imu_ev
static abi_event geo_mag_ev
Detailed Description
Paparazzi specific wrapper to run INVARIANT ahrs filter.
Definition in file ahrs_float_invariant_wrapper.c.
Macro Definition Documentation
AHRS_FINV_IMU_ID
#define AHRS_FINV_IMU_ID ABI_BROADCAST
IMU (gyro, accel)
Definition at line 104 of file ahrs_float_invariant_wrapper.c.
AHRS_FINV_MAG_ID
#define AHRS_FINV_MAG_ID AHRS_FINV_IMU_ID
magnetometer
Definition at line 110 of file ahrs_float_invariant_wrapper.c.
AHRS_FINV_OUTPUT_ENABLED
#define AHRS_FINV_OUTPUT_ENABLED TRUE
Definition at line 36 of file ahrs_float_invariant_wrapper.c.
Function Documentation
accel_cb()
static void accel_cb (uint8_t sender_id, uint32_t stamp, struct Int32Vect3 * accel) static
Definition at line 156 of file ahrs_float_invariant_wrapper.c.
References ACCELS_FLOAT_OF_BFP, ahrs_float_inv, ahrs_float_invariant_update_accel(), and AhrsFloatInv::is_aligned.
Referenced by ahrs_float_invariant_register().
ahrs_float_invariant_enable_output()
static bool ahrs_float_invariant_enable_output (bool enable) static
Definition at line 207 of file ahrs_float_invariant_wrapper.c.
References ahrs_finv_output_enabled.
Referenced by ahrs_float_invariant_register().
ahrs_float_invariant_register()
void ahrs_float_invariant_register (void)
Definition at line 237 of file ahrs_float_invariant_wrapper.c.
References ABI_BROADCAST, accel_cb(), accel_ev, AHRS_FINV_IMU_ID, AHRS_FINV_MAG_ID, AHRS_FINV_OUTPUT_ENABLED, ahrs_finv_output_enabled, ahrs_float_invariant_enable_output(), ahrs_float_invariant_init(), ahrs_register_impl(), aligner_cb(), aligner_ev, body_to_imu_cb(), body_to_imu_ev, DefaultPeriodic, geo_mag_cb(), geo_mag_ev, gyro_cb(), gyro_ev, mag_cb(), mag_ev, register_periodic_telemetry(), send_att(), send_filter_status(), and send_geo_mag().
aligner_cb()
static void aligner_cb (uint8_t sender_id, uint32_t stamp, struct Int32Rates * lp_gyro, struct Int32Vect3 * lp_accel, struct Int32Vect3 * lp_mag) static
Definition at line 178 of file ahrs_float_invariant_wrapper.c.
References ACCELS_FLOAT_OF_BFP, ahrs_float_inv, ahrs_float_invariant_align(), compute_body_orientation_and_rates(), AhrsFloatInv::is_aligned, MAGS_FLOAT_OF_BFP, and RATES_FLOAT_OF_BFP.
Referenced by ahrs_float_invariant_register().
body_to_imu_cb()
static void body_to_imu_cb (uint8_t sender_id, struct FloatQuat * q_b2i_f) static
Definition at line 196 of file ahrs_float_invariant_wrapper.c.
References ahrs_float_inv_set_body_to_imu_quat().
Referenced by ahrs_float_invariant_register().
compute_body_orientation_and_rates()
static void compute_body_orientation_and_rates (void) static
Compute body orientation and rates from imu orientation and rates.
Definition at line 216 of file ahrs_float_invariant_wrapper.c.
References ahrs_finv_output_enabled, ahrs_float_inv, inv_state::bias, AhrsFloatInv::body_to_imu, AhrsFloatInv::cmd, float_quat_comp_inv(), float_rmat_transp_ratemult(), orientationGetQuat_f(), orientationGetRMat_f(), inv_state::quat, inv_command::rates, RATES_DIFF, AhrsFloatInv::state, stateSetBodyRates_f(), and stateSetNedToBodyQuat_f().
Referenced by aligner_cb(), and gyro_cb().
geo_mag_cb()
static void geo_mag_cb (uint8_t sender_id, struct FloatVect3 * h) static
Definition at line 202 of file ahrs_float_invariant_wrapper.c.
References ahrs_float_inv, h(), and AhrsFloatInv::mag_h.
Referenced by ahrs_float_invariant_register().
gyro_cb()
static void gyro_cb (uint8_t sender_id, uint32_t stamp, struct Int32Rates * gyro) static
Call ahrs_float_invariant_propagate on new gyro measurements.
Since acceleration measurement is also needed for propagation, use the last stored accel from #ahrs_finv_accel.
Definition at line 126 of file ahrs_float_invariant_wrapper.c.
References ahrs_finv_last_stamp, ahrs_float_inv, ahrs_float_invariant_propagate(), AHRS_PROPAGATE_FREQUENCY, compute_body_orientation_and_rates(), AhrsFloatInv::is_aligned, PRINT_CONFIG_MSG(), and RATES_FLOAT_OF_BFP.
Referenced by ahrs_float_invariant_register().
mag_cb()
static void mag_cb (uint8_t sender_id, uint32_t stamp, struct Int32Vect3 * mag) static
Definition at line 167 of file ahrs_float_invariant_wrapper.c.
References ahrs_float_inv, ahrs_float_invariant_update_mag(), AhrsFloatInv::is_aligned, and MAGS_FLOAT_OF_BFP.
Referenced by ahrs_float_invariant_register().
send_att()
static void send_att (struct transport_tx * trans, struct link_device * dev) static
Definition at line 51 of file ahrs_float_invariant_wrapper.c.
References ahrs_finv_id, ahrs_float_inv, AhrsFloatInv::body_to_imu, dev, EULERS_BFP_OF_REAL, float_eulers_of_quat(), float_quat_comp_inv(), orientationGetQuat_f(), Int32Eulers::phi, Int32Eulers::psi, inv_state::quat, AhrsFloatInv::state, and Int32Eulers::theta.
Referenced by ahrs_float_invariant_register().
send_filter_status()
static void send_filter_status (struct transport_tx * trans, struct link_device * dev) static
Definition at line 86 of file ahrs_float_invariant_wrapper.c.
References ahrs_finv_id, ahrs_finv_last_stamp, ahrs_float_inv, dev, get_sys_time_usec(), AhrsFloatInv::is_aligned, and val.
Referenced by ahrs_float_invariant_register().
send_geo_mag()
static void send_geo_mag (struct transport_tx * trans, struct link_device * dev) static
Definition at line 78 of file ahrs_float_invariant_wrapper.c.
References ahrs_finv_id, ahrs_float_inv, dev, AhrsFloatInv::mag_h, FloatVect3::x, FloatVect3::y, and FloatVect3::z.
Referenced by ahrs_float_invariant_register().
Variable Documentation
accel_ev
abi_event accel_ev static
Definition at line 116 of file ahrs_float_invariant_wrapper.c.
Referenced by ahrs_float_invariant_register().
ahrs_finv_id
uint8_t ahrs_finv_id = AHRS_COMP_ID_FINV static
Definition at line 44 of file ahrs_float_invariant_wrapper.c.
Referenced by send_att(), send_filter_status(), and send_geo_mag().
ahrs_finv_last_stamp
uint32_t ahrs_finv_last_stamp = 0 static
last gyro msg timestamp
Definition at line 43 of file ahrs_float_invariant_wrapper.c.
Referenced by gyro_cb(), and send_filter_status().
ahrs_finv_output_enabled
bool ahrs_finv_output_enabled static
if TRUE with push the estimation results to the state interface
Definition at line 41 of file ahrs_float_invariant_wrapper.c.
Referenced by ahrs_float_invariant_enable_output(), ahrs_float_invariant_register(), and compute_body_orientation_and_rates().
aligner_ev
abi_event aligner_ev static
Definition at line 117 of file ahrs_float_invariant_wrapper.c.
Referenced by ahrs_float_invariant_register().
body_to_imu_ev
abi_event body_to_imu_ev static
Definition at line 118 of file ahrs_float_invariant_wrapper.c.
Referenced by ahrs_float_invariant_register().
geo_mag_ev
abi_event geo_mag_ev static
Definition at line 119 of file ahrs_float_invariant_wrapper.c.
Referenced by ahrs_float_invariant_register().
gyro_ev
abi_event gyro_ev static
Definition at line 115 of file ahrs_float_invariant_wrapper.c.
Referenced by ahrs_float_invariant_register().
mag_ev
abi_event mag_ev static
Definition at line 114 of file ahrs_float_invariant_wrapper.c.
Referenced by ahrs_float_invariant_register().