Paparazzi UAS: sw/airborne/modules/sensors/airspeed_otf.c File Reference
airspeed_otf.c File Reference
#include <stdbool.h>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include "mcu_periph/uart.h"
#include "pprzlink/messages.h"
#include "subsystems/datalink/downlink.h"
#include <ctype.h>
#include "met_module.h"
#include "airspeed_otf.h"
Macros
#define OTF_UNINIT 0x00
#define OTF_WAIT_START OTF_UNINIT
#define OTF_WAIT_COUNTER 0x01
#define OTF_WAIT_ANGLES 0x02
#define OTF_WAIT_ALTITUDE 0x03
#define OTF_WAIT_CHECKSUM 0x04
#define OTF_START 0x0A
#define OTF_LIMITER ','
#define OTF_END 0x0D
Functions
void * _sbrk (int)
void airspeed_otf_parse (char c)
void airspeed_otf_init (void)
void airspeed_otf_event (void)
void airspeed_otf_periodic (void)
Detailed Description
UART interface for Aeroprobe On-The-Fly! air data computer.
Definition in file airspeed_otf.c.
Macro Definition Documentation
OTF_END
#define OTF_END 0x0D
Definition at line 51 of file airspeed_otf.c.
OTF_LIMITER
#define OTF_LIMITER ','
Definition at line 50 of file airspeed_otf.c.
OTF_START
#define OTF_START 0x0A
Definition at line 49 of file airspeed_otf.c.
OTF_UNINIT
#define OTF_UNINIT 0x00
Definition at line 42 of file airspeed_otf.c.
OTF_WAIT_ALTITUDE
#define OTF_WAIT_ALTITUDE 0x03
Definition at line 46 of file airspeed_otf.c.
OTF_WAIT_ANGLES
#define OTF_WAIT_ANGLES 0x02
Definition at line 45 of file airspeed_otf.c.
OTF_WAIT_CHECKSUM
#define OTF_WAIT_CHECKSUM 0x04
Definition at line 47 of file airspeed_otf.c.
OTF_WAIT_COUNTER
#define OTF_WAIT_COUNTER 0x01
Definition at line 44 of file airspeed_otf.c.
OTF_WAIT_START
#define OTF_WAIT_START OTF_UNINIT
Definition at line 43 of file airspeed_otf.c.
Function Documentation
_sbrk()
void * _sbrk (int a)
Definition at line 55 of file airspeed_otf.c.
airspeed_otf_event()
void airspeed_otf_event (void)
Definition at line 155 of file airspeed_otf.c.
References airspeed_otf_parse(), MetBuffer, and MetGetch.
airspeed_otf_init()
void airspeed_otf_init (void)
Definition at line 151 of file airspeed_otf.c.
airspeed_otf_parse()
void airspeed_otf_parse (char c)
Definition at line 58 of file airspeed_otf.c.
References altitude, c(), checksum, counter, course, DefaultChannel, DefaultDevice, foo, OTF_END, OTF_LIMITER, OTF_START, OTF_UNINIT, OTF_WAIT_ALTITUDE, OTF_WAIT_ANGLES, OTF_WAIT_CHECKSUM, OTF_WAIT_COUNTER, and OTF_WAIT_START.
Referenced by airspeed_otf_event().
airspeed_otf_periodic()
void airspeed_otf_periodic (void)
Definition at line 163 of file airspeed_otf.c.