Paparazzi UAS: sw/airborne/arch/lpc21/armVIC.c File Reference
armVIC.c File Reference
#include "types.h"
#include "armVIC.h"
Macros
#define IRQ_MASK 0x00000080
#define FIQ_MASK 0x00000040
#define INT_MASK (IRQ_MASK | FIQ_MASK)
Functions
static unsigned __get_cpsr (void)
static void __set_cpsr (unsigned val)
unsigned disableIRQ (void)
unsigned restoreIRQ (unsigned oldCPSR)
unsigned enableIRQ (void)
unsigned disableFIQ (void)
unsigned restoreFIQ (unsigned oldCPSR)
unsigned enableFIQ (void)
Macro Definition Documentation
FIQ_MASK
#define FIQ_MASK 0x00000040
Definition at line 18 of file armVIC.c.
INT_MASK
#define INT_MASK (IRQ_MASK | FIQ_MASK)
Definition at line 19 of file armVIC.c.
IRQ_MASK
#define IRQ_MASK 0x00000080
Definition at line 17 of file armVIC.c.
Function Documentation
__get_cpsr()
static unsigned __get_cpsr (void) inline static
Definition at line 21 of file armVIC.c.
Referenced by disableFIQ(), disableIRQ(), enableFIQ(), enableIRQ(), restoreFIQ(), and restoreIRQ().
__set_cpsr()
static void __set_cpsr (unsigned val) inline static
Definition at line 28 of file armVIC.c.
References val.
Referenced by disableFIQ(), disableIRQ(), enableFIQ(), enableIRQ(), restoreFIQ(), and restoreIRQ().
disableFIQ()
unsigned disableFIQ (void)
Definition at line 60 of file armVIC.c.
References __get_cpsr(), __set_cpsr(), and FIQ_MASK.
disableIRQ()
unsigned disableIRQ (void)
Definition at line 33 of file armVIC.c.
References __get_cpsr(), __set_cpsr(), and IRQ_MASK.
Referenced by flash_detect(), i2c_lpc21_submit(), pflash_erase_page(), pflash_program_array(), spi_submit(), uart_put_byte(), and VCOM_getchar().
enableFIQ()
unsigned enableFIQ (void)
Definition at line 78 of file armVIC.c.
References __get_cpsr(), __set_cpsr(), and FIQ_MASK.
enableIRQ()
unsigned enableIRQ (void)
Definition at line 51 of file armVIC.c.
References __get_cpsr(), __set_cpsr(), and IRQ_MASK.
Referenced by flash_detect(), i2c_lpc21_submit(), pflash_erase_page(), pflash_program_array(), spi_submit(), and VCOM_getchar().
restoreFIQ()
unsigned restoreFIQ (unsigned oldCPSR)
Definition at line 69 of file armVIC.c.
References __get_cpsr(), __set_cpsr(), and FIQ_MASK.
restoreIRQ()
unsigned restoreIRQ (unsigned oldCPSR)
Definition at line 42 of file armVIC.c.
References __get_cpsr(), __set_cpsr(), and IRQ_MASK.
Referenced by uart_put_byte().