Paparazzi UAS: sw/airborne/boards/baro_board_ms5611_spi.c File Reference
baro_board_ms5611_spi.c File Reference
#include "subsystems/sensors/baro.h"
#include "peripherals/ms5611_spi.h"
#include "mcu_periph/sys_time.h"
#include "led.h"
#include "std.h"
#include "subsystems/abi.h"
#include "mcu_periph/uart.h"
#include "pprzlink/messages.h"
#include "subsystems/datalink/downlink.h"
#include "filters/median_filter.h"
Macros
#define BB_MS5611_TYPE_MS5607 FALSE
set to TRUE if baro is actually a MS5607
Functions
void baro_init (void)
void baro_periodic (void)
void baro_event (void)
Variables
struct Ms5611_Spi bb_ms5611
struct MedianFilterFloat bb_ms5611_filt
Detailed Description
Driver for onboard MS5611 baro via SPI.
Definition in file baro_board_ms5611_spi.c.
Macro Definition Documentation
BB_MS5611_TYPE_MS5607
#define BB_MS5611_TYPE_MS5607 FALSE
set to TRUE if baro is actually a MS5607
Definition at line 53 of file baro_board_ms5611_spi.c.
Function Documentation
baro_event()
void baro_event (void)
Definition at line 92 of file baro_board_ms5611_spi.c.
References BARO_BOARD_SENDER_ID, bb_ms5611, bb_ms5611_filt, Ms5611Data::d1, Ms5611Data::d2, Ms5611_Spi::data, Ms5611_Spi::data_available, DefaultChannel, DefaultDevice, fbaroms, get_sys_time_usec(), LED_TOGGLE, ms5611_spi_event(), sys_time::nb_sec, Ms5611Data::pressure, Ms5611Data::temperature, and update_median_filter_f().
baro_init()
void baro_init (void)
Definition at line 59 of file baro_board_ms5611_spi.c.
References bb_ms5611, bb_ms5611_filt, BB_MS5611_TYPE_MS5607, init_median_filter_f(), LED_OFF, and ms5611_spi_init().
baro_periodic()
void baro_periodic (void)
Definition at line 70 of file baro_board_ms5611_spi.c.
References bb_ms5611, Ms5611Data::c, Ms5611_Spi::data, DefaultChannel, DefaultDevice, Ms5611_Spi::initialized, ms5611_spi_periodic(), and sys_time::nb_sec.
Variable Documentation
bb_ms5611
struct Ms5611_Spi bb_ms5611
Definition at line 56 of file baro_board_ms5611_spi.c.
Referenced by baro_event(), baro_init(), and baro_periodic().
bb_ms5611_filt
struct MedianFilterFloat bb_ms5611_filt
Definition at line 57 of file baro_board_ms5611_spi.c.
Referenced by baro_event(), and baro_init().