Paparazzi UAS: sw/airborne/modules/sensors/baro_bmp280_i2c.c File Reference
baro_bmp280_i2c.c File Reference
#include "baro_bmp280_i2c.h"
#include "subsystems/abi.h"
#include "mcu_periph/uart.h"
#include "pprzlink/messages.h"
#include "subsystems/datalink/downlink.h"
#include "math/pprz_isa.h"
#include "subsystems/datalink/telemetry.h"
Macros
#define BMP280_SLAVE_ADDR BMP280_I2C_ADDR
default slave address
Functions
static void send_baro_bmp_data (struct transport_tx *trans, struct link_device *dev)
void baro_bmp280_init (void)
void baro_bmp280_periodic (void)
void baro_bmp280_event (void)
Variables
float baro_alt = 0
float baro_temp = 0
float baro_press = 0
bool baro_alt_valid = 0
struct Bmp280_I2c baro_bmp280
Detailed Description
Bosch BMP280 I2C sensor interface.
This reads the values for pressure and temperature from the Bosch BMP280 sensor through I2C.
Definition in file baro_bmp280_i2c.c.
Macro Definition Documentation
BMP280_SLAVE_ADDR
#define BMP280_SLAVE_ADDR BMP280_I2C_ADDR
default slave address
Definition at line 43 of file baro_bmp280_i2c.c.
Function Documentation
baro_bmp280_event()
void baro_bmp280_event (void)
Definition at line 82 of file baro_bmp280_i2c.c.
References baro_alt, baro_alt_valid, baro_bmp280, BARO_BMP_SENDER_ID, baro_press, baro_temp, bmp280_i2c_event(), Bmp280_I2c::data_available, DefaultChannel, DefaultDevice, get_sys_time_usec(), p, pprz_isa_altitude_of_pressure(), Bmp280_I2c::pressure, Bmp280_I2c::raw_pressure, Bmp280_I2c::raw_temperature, Bmp280_I2c::temperature, and up.
baro_bmp280_init()
void baro_bmp280_init (void)
Definition at line 68 of file baro_bmp280_i2c.c.
References baro_bmp280, bmp280_i2c_init(), BMP280_SLAVE_ADDR, DefaultPeriodic, register_periodic_telemetry(), and send_baro_bmp_data().
baro_bmp280_periodic()
void baro_bmp280_periodic (void)
Definition at line 77 of file baro_bmp280_i2c.c.
References baro_bmp280, and bmp280_i2c_periodic().
send_baro_bmp_data()
static void send_baro_bmp_data (struct transport_tx * trans, struct link_device * dev) static
Definition at line 55 of file baro_bmp280_i2c.c.
References baro_alt, baro_press, baro_temp, and dev.
Referenced by baro_bmp280_init().
Variable Documentation
baro_alt
float baro_alt = 0
Definition at line 46 of file baro_bmp280_i2c.c.
Referenced by baro_bmp280_event(), baro_cb(), ins_mekf_wind_update_baro(), and send_baro_bmp_data().
baro_alt_valid
bool baro_alt_valid = 0
Definition at line 49 of file baro_bmp280_i2c.c.
Referenced by baro_bmp280_event().
baro_bmp280
struct Bmp280_I2c baro_bmp280
Definition at line 52 of file baro_bmp280_i2c.c.
Referenced by baro_bmp280_event(), baro_bmp280_init(), and baro_bmp280_periodic().
baro_press
float baro_press = 0
Definition at line 48 of file baro_bmp280_i2c.c.
Referenced by baro_bmp280_event(), and send_baro_bmp_data().
baro_temp
float baro_temp = 0
Definition at line 47 of file baro_bmp280_i2c.c.
Referenced by baro_bmp280_event(), and send_baro_bmp_data().