Paparazzi UAS: sw/airborne/boards/booz/baro_board.h File Reference
baro_board.h File Reference
#include "std.h"
#include "subsystems/sensors/baro.h"
#include "mcu_periph/adc.h"
#include "mcu_periph/dac.h"
Data Structures
struct BaroBoard
Macros
#define BaroEvent() {}
Enumerations
enum BaroBoardStatus { BB_UNINITIALIZED, BB_RUNNING }
Functions
void baro_board_calibrate (void)
static void baro_board_SetOffset (uint16_t _o)
Variables
struct BaroBoard baro_board
Data Structure Documentation
BaroBoard
struct BaroBoard
Definition at line 42 of file baro_board.h.
Data Fields
int32_t absolute
struct adc_buf buf
uint16_t offset
bool running
enum BaroBoardStatus status
enum LisaBaroStatus status
uint16_t value_filtered
Macro Definition Documentation
BaroEvent
#define BaroEvent () {}
Definition at line 53 of file baro_board.h.
Enumeration Type Documentation
BaroBoardStatus
enum BaroBoardStatus
Enumerator
BB_UNINITIALIZED
BB_RUNNING
Definition at line 37 of file baro_board.h.
Function Documentation
baro_board_calibrate()
void baro_board_calibrate (void)
Definition at line 95 of file baro_board.c.
References baro_board, BB_RUNNING, BOOZ_ANALOG_BARO_THRESHOLD, DACSet(), LED_ON, LED_TOGGLE, BaroBoard::offset, BaroBoard::status, and BaroBoard::value_filtered.
Referenced by baro_periodic().
baro_board_SetOffset()
static void baro_board_SetOffset (uint16_t _o) inline static
Definition at line 55 of file baro_board.h.
References baro_board, DACSet(), and BaroBoard::offset.
Variable Documentation
baro_board
struct BaroBoard baro_board
Definition at line 63 of file baro_board.c.
Referenced by baro_board_calibrate(), baro_board_SetOffset(), baro_init(), baro_periodic(), and lisa_l_baro_event().