Paparazzi UAS: sw/airborne/modules/cartography/cartography.h File Reference
cartography.h File Reference
Functions
void init_carto (void)
Automatic survey of an oriented rectangle (defined by three points)
void periodic_downlink_carto (void)
void start_carto (void)
void stop_carto (void)
bool nav_survey_Inc_railnumberSinceBoot (void)
bool nav_survey_Snapshoot (void)
bool nav_survey_Snapshoot_Continu (void)
bool nav_survey_StopSnapshoot (void)
bool nav_survey_computefourth_corner (uint8_t wp1, uint8_t wp2, uint8_t wp3, uint8_t wp4)
bool nav_survey_losange_carto_init (uint8_t wp1, uint8_t wp2, uint8_t wp3, float distrail, float distplus)
bool nav_survey_losange_carto (void)
Variables
float distrailinteractif
Function Documentation
init_carto()
void init_carto (void)
Automatic survey of an oriented rectangle (defined by three points)
Definition at line 148 of file cartography.c.
nav_survey_computefourth_corner()
bool nav_survey_computefourth_corner (uint8_t wp1, uint8_t wp2, uint8_t wp3, uint8_t wp4)
Definition at line 211 of file cartography.c.
References f, nav_survey_computefourth_corner(), PRTDEB, PRTDEBSTR, waypoints, point::x, and point::y.
Referenced by nav_survey_computefourth_corner().
nav_survey_Inc_railnumberSinceBoot()
bool nav_survey_Inc_railnumberSinceBoot (void)
Definition at line 177 of file cartography.c.
References railnumberSinceBoot.
nav_survey_losange_carto()
bool nav_survey_losange_carto (void)
Definition at line 423 of file cartography.c.
References angle_between, camera_snapshot_image_number, circleradiusmin, course_next_rail, distancefromrail, DISTLIMIT, distplus, distrail, DISTXY, f, FALSE, nav_route_xy(), nav_survey_ComputeProjectionOnLine(), nav_survey_losange_carto(), NavCircleWaypoint, norm12, norm13, normAM, normBM, numberofrailtodo, pointC, ProjectionInsideLimitOfRail, PRTDEB, PRTDEBSTR, railnumber, railnumberSinceBoot, signforturn, stateGetHorizontalSpeedDir_f(), stateGetPositionEnu_f(), survey_losange_uturn, tempcircleradius, tempx, tempy, UTURN, vec13, waypoints, point::x, and point::y.
Referenced by nav_survey_losange_carto().
nav_survey_losange_carto_init()
bool nav_survey_losange_carto_init (uint8_t wp1, uint8_t wp2, uint8_t wp3, float distrail, float distplus)
Definition at line 322 of file cartography.c.
References angle1213, distplus, distrail, f, norm12, norm13, NORMXY, numberofrailtodo, point3, PRTDEB, railnumber, railnumberSinceBoot, signforturn, survey_losange_uturn, vec13, waypoints, point::x, and point::y.
nav_survey_Snapshoot()
bool nav_survey_Snapshoot (void)
Definition at line 183 of file cartography.c.
References camera_snapshot_image_number, PRTDEBSTR, and railnumberSinceBoot.
nav_survey_Snapshoot_Continu()
bool nav_survey_Snapshoot_Continu (void)
Definition at line 192 of file cartography.c.
References camera_snapshot_image_number, PRTDEBSTR, and railnumberSinceBoot.
nav_survey_StopSnapshoot()
bool nav_survey_StopSnapshoot (void)
Definition at line 201 of file cartography.c.
References camera_snapshot_image_number, PRTDEBSTR, and STOP.
periodic_downlink_carto()
void periodic_downlink_carto (void)
Definition at line 152 of file cartography.c.
References camera_snapshot_image_number, DefaultChannel, and DefaultDevice.
start_carto()
void start_carto (void)
Definition at line 166 of file cartography.c.
stop_carto()
void stop_carto (void)
Definition at line 170 of file cartography.c.
Variable Documentation
distrailinteractif
float distrailinteractif
Definition at line 107 of file cartography.c.