Paparazzi UAS: sw/airborne/subsystems/radio_control/cc2500_frsky/cc2500_paparazzi.c File Reference
cc2500_paparazzi.c File Reference
#include "cc2500_paparazzi.h"
#include "subsystems/radio_control.h"
#include "peripherals/cc2500.h"
#include "cc2500_common.h"
#include "cc2500_frsky_common.h"
#include "cc2500_settings.h"
#include "cc2500_rx.h"
#include <stdint.h>
#include "subsystems/datalink/telemetry.h"
Functions
static void send_cc2500_ppm (struct transport_tx *trans, struct link_device *dev)
void radio_control_impl_init (void)
void radio_control_impl_event (void(*_received_frame_handler)(void))
RC event function with handler callback.
Variables
static uint16_t frsky_raw [RADIO_CTL_NB]
Function Documentation
radio_control_impl_event()
void radio_control_impl_event (void(*)(void) _received_frame_handler)
RC event function with handler callback.
PPM frames are normalized using the IIR filter.
Definition at line 61 of file cc2500_paparazzi.c.
radio_control_impl_init()
void radio_control_impl_init (void)
Definition at line 50 of file cc2500_paparazzi.c.
References cc2500_init(), cc2500_settings_init(), cc2500Reset(), DefaultPeriodic, register_periodic_telemetry(), rxInit(), and send_cc2500_ppm().
send_cc2500_ppm()
static void send_cc2500_ppm (struct transport_tx * trans, struct link_device * dev) static
Definition at line 40 of file cc2500_paparazzi.c.
References dev, RadioControl::frame_rate, frsky_raw, and radio_control.
Referenced by radio_control_impl_init().
Variable Documentation
frsky_raw
uint16_t frsky_raw[RADIO_CTL_NB] static
Definition at line 34 of file cc2500_paparazzi.c.
Referenced by radio_control_impl_event(), and send_cc2500_ppm().