Paparazzi UAS: sw/airborne/arch/chibios/mcu_periph/sys_time_arch.h File Reference
sys_time_arch.h File Reference
#include "mcu_periph/sys_time.h"
#include <ch.h>
Functions
uint32_t get_sys_time_usec (void)
Get the time in microseconds since startup.
uint32_t get_sys_time_msec (void)
Get the time in milliseconds since startup.
void sys_time_usleep (uint32_t us)
sys_time_usleep(uint32_t us)
void sys_time_msleep (uint16_t ms)
void sys_time_ssleep (uint8_t s)
Detailed Description
Implementation of system time functions for ChibiOS arch
Mostly empty functions for Paparazzi compatibility, since ChibiOS uses different system time functions.
Definition in file sys_time_arch.h.
Function Documentation
get_sys_time_msec()
uint32_t get_sys_time_msec (void)
Get the time in milliseconds since startup.
Returns
milliseconds since startup as uint32_t
Definition at line 78 of file sys_time_arch.c.
get_sys_time_usec()
uint32_t get_sys_time_usec (void)
Get the time in microseconds since startup.
WARNING: overflows after 70min!
Returns
microseconds since startup as uint32_t
WARNING: overflows after 71min34seconds!
Returns
current system time as uint32_t
Definition at line 68 of file sys_time_arch.c.
sys_time_msleep()
void sys_time_msleep (uint16_t ms)
Definition at line 108 of file sys_time_arch.c.
References CH_CFG_ST_FREQUENCY.
sys_time_ssleep()
void sys_time_ssleep (uint8_t s)
Definition at line 114 of file sys_time_arch.c.
References s.
sys_time_usleep()
void sys_time_usleep (uint32_t us)
sys_time_usleep(uint32_t us)
using intermediate 64 bits variable to avoid wrapping
max sleep time is around 10 days (2^32 / CH_CFG_ST_FREQUENCY) at 10kHz
Definition at line 95 of file sys_time_arch.c.
References CH_CFG_ST_FREQUENCY.
Referenced by bf_delayMicroseconds(), cyrf6936_init(), initializeSensor(), main(), pcap01_init(), px4flash_event(), readRegister_blocking(), received_spektrum_soft_bind(), send_spektrum_bind(), spektrum_bind(), spektrum_try_bind(), VCOM_putchar(), video_thread_function(), w5100_init(), and xbee_dl_init().