Paparazzi UAS: sw/airborne/modules/config/config_mkk_v2.c File Reference
config_mkk_v2.c File Reference
#include "config_mkk_v2.h"
#include "generated/airframe.h"
#include "subsystems/actuators.h"
#include "subsystems/actuators/actuators_mkk_v2.h"
#include "mcu_periph/uart.h"
#include "pprzlink/messages.h"
#include "subsystems/datalink/downlink.h"
Macros
#define BL_READMODE_CONFIG 16
#define config_mkk_v2_EEPROM_REVISION 2
#define RETURN_IF_NOT_KILLMODE()
Functions
void config_mkk_v2_parse_eeprom (void)
void config_mkk_v2_init (void)
void config_mkk_v2_periodic_read_status (void)
void config_mkk_v2_periodic_telemetry (void)
uint8_t config_mkk_v2_crc (uint8_t offset)
void config_mkk_v2_read_eeprom (void)
void config_mkk_v2_send_eeprom (void)
Variables
struct config_mkk_v2_struct config_mkk_v2
config_mkk_v2_eeprom_t config_mkk_v2_eeprom
Macro Definition Documentation
BL_READMODE_CONFIG
#define BL_READMODE_CONFIG 16
Definition at line 117 of file config_mkk_v2.c.
config_mkk_v2_EEPROM_REVISION
#define config_mkk_v2_EEPROM_REVISION 2
Definition at line 118 of file config_mkk_v2.c.
RETURN_IF_NOT_KILLMODE
#define RETURN_IF_NOT_KILLMODE ()
Value:
  {                                \
    if (!actuators_delay_done)     \
      return;                      \
  }
Definition at line 121 of file config_mkk_v2.c.
Function Documentation
config_mkk_v2_crc()
uint8_t config_mkk_v2_crc (uint8_t offset)
Definition at line 104 of file config_mkk_v2.c.
References i2c_transaction::buf, config_mkk_v2, crc, offset, and config_mkk_v2_struct::trans.
Referenced by config_mkk_v2_parse_eeprom(), and config_mkk_v2_send_eeprom().
config_mkk_v2_init()
void config_mkk_v2_init (void)
Definition at line 31 of file config_mkk_v2.c.
References config_mkk_v2, I2CTransSuccess, config_mkk_v2_struct::nb_err, config_mkk_v2_struct::read_config, i2c_transaction::status, and config_mkk_v2_struct::trans.
config_mkk_v2_parse_eeprom()
void config_mkk_v2_parse_eeprom (void)
Definition at line 146 of file config_mkk_v2.c.
References config_mkk_v2_eeprom_t::BitConfig, i2c_transaction::buf, config_mkk_v2, config_mkk_v2_crc(), config_mkk_v2_eeprom, config_mkk_v2_eeprom_t::crc, config_mkk_v2_eeprom_t::CurrentLimit, config_mkk_v2_eeprom_t::CurrentScaling, config_mkk_v2_struct::nb_err, config_mkk_v2_eeprom_t::PwmScaling, config_mkk_v2_eeprom_t::revision, config_mkk_v2_eeprom_t::SetMask, config_mkk_v2_eeprom_t::TempLimit, and config_mkk_v2_struct::trans.
Referenced by config_mkk_v2_periodic_read_status().
config_mkk_v2_periodic_read_status()
void config_mkk_v2_periodic_read_status (void)
Definition at line 42 of file config_mkk_v2.c.
References config_mkk_v2, config_mkk_v2_parse_eeprom(), I2CTransDone, I2CTransFailed, I2CTransSuccess, config_mkk_v2_struct::read_config, i2c_transaction::status, and config_mkk_v2_struct::trans.
config_mkk_v2_periodic_telemetry()
void config_mkk_v2_periodic_telemetry (void)
Definition at line 66 of file config_mkk_v2.c.
References actuators_mkk_v2, actuators_mkk_v2_telemetry_struct::Current, actuators_mkk_v2_struct::data, DefaultChannel, DefaultDevice, actuators_mkk_v2_telemetry_struct::MaxPWM, and actuators_mkk_v2_telemetry_struct::Temperature.
config_mkk_v2_read_eeprom()
void config_mkk_v2_read_eeprom (void)
Definition at line 127 of file config_mkk_v2.c.
References config_mkk_v2_struct::addr, BL_READMODE_CONFIG, i2c_transaction::buf, config_mkk_v2, i2c_submit(), I2CTransTxRx, i2c_transaction::len_r, i2c_transaction::len_w, config_mkk_v2_struct::read_config, RETURN_IF_NOT_KILLMODE, i2c_transaction::slave_addr, config_mkk_v2_struct::trans, and i2c_transaction::type.
config_mkk_v2_send_eeprom()
void config_mkk_v2_send_eeprom (void)
Definition at line 163 of file config_mkk_v2.c.
References config_mkk_v2_struct::addr, config_mkk_v2_eeprom_t::BitConfig, BL_READMODE_CONFIG, i2c_transaction::buf, config_mkk_v2, config_mkk_v2_crc(), config_mkk_v2_eeprom, config_mkk_v2_EEPROM_REVISION, config_mkk_v2_eeprom_t::CurrentLimit, config_mkk_v2_eeprom_t::CurrentScaling, i2c_submit(), I2CTransTx, i2c_transaction::len_w, config_mkk_v2_eeprom_t::PwmScaling, RETURN_IF_NOT_KILLMODE, config_mkk_v2_eeprom_t::revision, config_mkk_v2_eeprom_t::SetMask, i2c_transaction::slave_addr, config_mkk_v2_eeprom_t::TempLimit, config_mkk_v2_struct::trans, and i2c_transaction::type.
Variable Documentation
config_mkk_v2
struct config_mkk_v2_struct config_mkk_v2
Definition at line 29 of file config_mkk_v2.c.
Referenced by config_mkk_v2_crc(), config_mkk_v2_init(), config_mkk_v2_parse_eeprom(), config_mkk_v2_periodic_read_status(), config_mkk_v2_read_eeprom(), and config_mkk_v2_send_eeprom().
config_mkk_v2_eeprom
config_mkk_v2_eeprom_t config_mkk_v2_eeprom
Definition at line 114 of file config_mkk_v2.c.
Referenced by config_mkk_v2_parse_eeprom(), and config_mkk_v2_send_eeprom().