Paparazzi UAS: sw/airborne/modules/computer_vision/detect_contour.c File Reference
detect_contour.c File Reference
#include "modules/computer_vision/cv.h"
#include "modules/computer_vision/detect_contour.h"
#include "modules/computer_vision/opencv_contour.h"
Macros
#define DETECT_CONTOUR_FPS 0
Default FPS (zero means run at camera fps)
Functions
struct image_t * contour_func (struct image_t *img, uint8_t camera_id)
void detect_contour_init (void)
Detailed Description
Author
Roland Meertens and Peng Lu
Definition in file detect_contour.c.
Macro Definition Documentation
DETECT_CONTOUR_FPS
#define DETECT_CONTOUR_FPS 0
Default FPS (zero means run at camera fps)
Definition at line 31 of file detect_contour.c.
Function Documentation
contour_func()
struct image_t * contour_func (struct image_t * img, uint8_t camera_id)
Definition at line 37 of file detect_contour.c.
References image_t::buf, find_contour(), image_t::h, IMAGE_YUV422, image_t::type, and image_t::w.
Referenced by detect_contour_init().
detect_contour_init()
void detect_contour_init (void)
Definition at line 47 of file detect_contour.c.
References cont_thres, contour_func(), cv_add_to_device(), DETECT_CONTOUR_FPS, contour_threshold::lower_u, contour_threshold::lower_v, contour_threshold::lower_y, contour_threshold::upper_u, contour_threshold::upper_v, and contour_threshold::upper_y.