Paparazzi UAS: sw/airborne/modules/loggers/direct_memory_logger.h File Reference
direct_memory_logger.h File Reference
Write logs directly to flash memory chips.
#include "peripherals/sst25vfxxxx.h"
Data Structures
struct DirectMemoryLogger
Macros
#define DML_BUF_SIZE 128
The read buffer size.
Enumerations
enum DMLStatus {
DML_INIT, DML_IDLE, DML_ERASE, DML_START,
DML_LOGGING, DML_STOP, DML_READ, DML_READING
}
Functions
void direct_memory_logger_init (void)
void direct_memory_logger_periodic (void)
void direct_memory_logger_set (uint8_t val)
Variables
struct DirectMemoryLogger dml
Detailed Description
Write logs directly to flash memory chips.
Definition in file direct_memory_logger.h.
Data Structure Documentation
DirectMemoryLogger
struct DirectMemoryLogger
Definition at line 48 of file direct_memory_logger.h.
Data Fields
uint8_t buffer[DML_BUF_SIZE] The buffer for writing and reading.
struct SST25VFxxxx sst The memory chip.
enum DMLStatus status The status of the Direct Memory Logger.
uint32_t write_addr
Macro Definition Documentation
DML_BUF_SIZE
#define DML_BUF_SIZE 128
The read buffer size.
Definition at line 33 of file direct_memory_logger.h.
Enumeration Type Documentation
DMLStatus
enum DMLStatus
Enumerator
DML_INIT
The DML is initializing.
DML_IDLE
The DML is idle.
DML_ERASE
The DML is busy erasing itself.
DML_START
The DML is starting the logger.
DML_LOGGING
The DML is busy logging.
DML_STOP
The DML is busy stopping.
DML_READ
The DML is busy starting read.
DML_READING
The DML is busy reading.
Definition at line 36 of file direct_memory_logger.h.
Function Documentation
direct_memory_logger_init()
void direct_memory_logger_init (void)
Definition at line 91 of file direct_memory_logger.c.
References direct_memory_spi_cb(), dml, DML_INIT, DirectMemoryLogger::sst, sst25vfxxxx_init(), and DirectMemoryLogger::status.
direct_memory_logger_periodic()
void direct_memory_logger_periodic (void)
Definition at line 99 of file direct_memory_logger.c.
References Imu::accel, LogStruct::accel_z, DirectMemoryLogger::buffer, LogStruct::counter, dm_counter, dml, DML_BUF_SIZE, DML_IDLE, DML_LOGGING, DML_READ, DML_READING, DML_START, DML_STOP, SST25VFxxxx::flash_addr, Imu::gyro, LogStruct::gyro_p, LogStruct::gyro_q, LogStruct::gyro_r, imu, log_struct, Int32Rates::p, Int32Rates::q, Int32Rates::r, seq_in_array(), DirectMemoryLogger::sst, SST25VFXXXX_IDLE, sst25vfxxxx_read(), sst25vfxxxx_write(), stabilization_cmd, DirectMemoryLogger::status, SST25VFxxxx::status, stop_log_sequence, LogStruct::thrust, uart_put_byte(), DirectMemoryLogger::write_addr, and Int32Vect3::z.
direct_memory_logger_set()
void direct_memory_logger_set (uint8_t val)
Definition at line 180 of file direct_memory_logger.c.
References DirectMemoryLogger::buffer, dml, DML_BUF_SIZE, DML_ERASE, DML_IDLE, DML_LOGGING, DML_READ, DML_START, DML_STOP, SST25VFxxxx::flash_addr, DirectMemoryLogger::sst, sst25vfxxxx_chip_erase(), sst25vfxxxx_read(), sst25vfxxxx_write(), start_log_sequence, DirectMemoryLogger::status, val, and DirectMemoryLogger::write_addr.
Variable Documentation
dml
struct DirectMemoryLogger dml
Definition at line 33 of file direct_memory_logger.c.
Referenced by direct_memory_logger_init(), direct_memory_logger_periodic(), direct_memory_logger_set(), and direct_memory_spi_cb().