Paparazzi UAS: sw/airborne/subsystems/datalink/downlink.c File Reference
downlink.c File Reference
Common code for AP and FBW telemetry.
#include "subsystems/datalink/downlink.h"
#include "subsystems/datalink/datalink.h"
#include "subsystems/datalink/telemetry.h"
#include "mcu_periph/sys_time.h"
Functions
static void send_downlink (struct transport_tx *trans, struct link_device *dev)
void downlink_init (void)
Variables
static uint32_t last_down_nb_bytes = 0
static uint32_t last_up_nb_msgs = 0
static uint32_t last_ts = 0
Detailed Description
Common code for AP and FBW telemetry.
Definition in file downlink.c.
Function Documentation
downlink_init()
void downlink_init (void)
Definition at line 67 of file downlink.c.
References datalink_nb_msgs, DefaultDevice, DefaultPeriodic, register_periodic_telemetry(), and send_downlink().
Referenced by init_ap(), main(), and main_init().
send_downlink()
static void send_downlink (struct transport_tx * trans, struct link_device * dev) static
Definition at line 43 of file downlink.c.
References datalink_nb_msgs, datalink_time, dev, get_sys_time_msec(), last_down_nb_bytes, last_ts, and last_up_nb_msgs.
Referenced by downlink_init().
Variable Documentation
last_down_nb_bytes
uint32_t last_down_nb_bytes = 0 static
Definition at line 39 of file downlink.c.
Referenced by send_downlink().
last_ts
uint32_t last_ts = 0 static
Definition at line 41 of file downlink.c.
Referenced by send_downlink().
last_up_nb_msgs
uint32_t last_up_nb_msgs = 0 static
Definition at line 40 of file downlink.c.
Referenced by send_downlink().