Paparazzi UAS: sw/airborne/firmwares/fixedwing/main_fbw.h File Reference
main_fbw.h File Reference
#include "std.h"
Macros
#define FBW_MODE_MANUAL 0
Fly by wire modes.
#define FBW_MODE_AUTO 1
#define FBW_MODE_FAILSAFE 2
#define FBW_MODE_OF_PPRZ(mode) ((mode) < THRESHOLD_MANUAL_PPRZ ? FBW_MODE_MANUAL : FBW_MODE_AUTO)
Functions
void init_fbw (void)
void handle_periodic_tasks_fbw (void)
void periodic_task_fbw (void)
void event_task_fbw (void)
void radio_control_event (void)
void fbw_datalink_periodic_handle (void)
void fbw_datalink_event_handle (void)
void radio_control_periodic_handle (void)
void inter_mcu_periodic_handle (void)
void inter_mcu_event_handle (void)
void periodic_telemetry_handle (void)
Variables
uint8_t fbw_mode
Fly by wire modes.
bool failsafe_mode
Detailed Description
FBW (FlyByWire) process API
Definition in file main_fbw.h.
Macro Definition Documentation
FBW_MODE_AUTO
#define FBW_MODE_AUTO 1
Definition at line 35 of file main_fbw.h.
FBW_MODE_FAILSAFE
#define FBW_MODE_FAILSAFE 2
Definition at line 36 of file main_fbw.h.
FBW_MODE_MANUAL
#define FBW_MODE_MANUAL 0
Fly by wire modes.
Definition at line 34 of file main_fbw.h.
FBW_MODE_OF_PPRZ
#define FBW_MODE_OF_PPRZ (mode) ((mode) < THRESHOLD_MANUAL_PPRZ ? FBW_MODE_MANUAL : FBW_MODE_AUTO)
Definition at line 37 of file main_fbw.h.
Function Documentation
event_task_fbw()
void event_task_fbw (void)
Definition at line 421 of file main_fbw.c.
References fbw_datalink_event_handle(), inter_mcu_event_handle(), mcu_event(), and radio_control_event().
Referenced by sim_periodic_task().
fbw_datalink_event_handle()
void fbw_datalink_event_handle (void)
Definition at line 150 of file main_fbw.c.
Referenced by event_task_fbw().
fbw_datalink_periodic_handle()
void fbw_datalink_periodic_handle (void)
Definition at line 149 of file main_fbw.c.
Referenced by periodic_task_fbw().
handle_periodic_tasks_fbw()
void handle_periodic_tasks_fbw (void)
Definition at line 445 of file main_fbw.c.
References electrical_periodic(), electrical_tid, fbw_periodic_tid, periodic_task_fbw(), and sys_time_check_and_ack_timer().
init_fbw()
void init_fbw (void)
Definition at line 362 of file main_fbw.c.
References commands_failsafe, DefaultPeriodic, electrical_init(), electrical_tid, fbw_mode, FBW_MODE_FAILSAFE, fbw_new_actuators, fbw_periodic_tid, link_mcu_init(), mcu_init(), mcu_int_enable, radio_control_init(), register_periodic_telemetry(), send_actuators(), send_commands(), send_fbw_status(), send_rc(), SetCommands, and sys_time_register_timer().
Referenced by sim_init().
inter_mcu_event_handle()
void inter_mcu_event_handle (void)
Definition at line 314 of file main_fbw.c.
Referenced by event_task_fbw().
inter_mcu_periodic_handle()
void inter_mcu_periodic_handle (void)
Definition at line 313 of file main_fbw.c.
Referenced by periodic_task_fbw().
periodic_task_fbw()
void periodic_task_fbw (void)
Definition at line 434 of file main_fbw.c.
References fbw_datalink_periodic_handle(), inter_mcu_periodic_handle(), periodic_telemetry_handle(), and radio_control_periodic_handle().
Referenced by handle_periodic_tasks_fbw(), and sim_periodic_task().
periodic_telemetry_handle()
void periodic_telemetry_handle (void)
Definition at line 352 of file main_fbw.c.
References DefaultChannel, DefaultDevice, and DefaultPeriodic.
Referenced by periodic_task_fbw().
radio_control_event()
void radio_control_event (void)
Definition at line 121 of file main_fbw.c.
References handle_rc_frame(), and RadioControlEvent.
Referenced by event_task_fbw().
radio_control_periodic_handle()
void radio_control_periodic_handle (void)
Definition at line 126 of file main_fbw.c.
References fbw_mode, FBW_MODE_MANUAL, radio_control, radio_control_periodic_task(), radio_lost_mode(), RC_REALLY_LOST, and RadioControl::status.
Referenced by periodic_task_fbw().
Variable Documentation
failsafe_mode
bool failsafe_mode
fbw_mode
uint8_t fbw_mode
Fly by wire modes.
Definition at line 63 of file main_fbw.c.