Paparazzi UAS: sw/airborne/modules/multi/follow.c File Reference
follow.c File Reference
Follow a certain AC ID. Only for rotorcraft firmware.
#include "multi/follow.h"
#include "generated/airframe.h"
#include "generated/flight_plan.h"
#include "subsystems/navigation/waypoints.h"
#include "state.h"
Macros
#define FOLLOW_OFFSET_X 0.0
#define FOLLOW_OFFSET_Y 0.0
#define FOLLOW_OFFSET_Z 0.0
Functions
void follow_init (void)
void follow_wp (void)
Detailed Description
Follow a certain AC ID. Only for rotorcraft firmware.
Definition in file follow.c.
Macro Definition Documentation
FOLLOW_OFFSET_X
#define FOLLOW_OFFSET_X 0.0
Definition at line 38 of file follow.c.
FOLLOW_OFFSET_Y
#define FOLLOW_OFFSET_Y 0.0
Definition at line 42 of file follow.c.
FOLLOW_OFFSET_Z
#define FOLLOW_OFFSET_Z 0.0
Definition at line 46 of file follow.c.
Function Documentation
follow_init()
void follow_init (void)
Definition at line 57 of file follow.c.
follow_wp()
void follow_wp (void)
Definition at line 64 of file follow.c.
References acInfoGetPositionEnu_i(), FOLLOW_OFFSET_X, FOLLOW_OFFSET_Y, FOLLOW_OFFSET_Z, POS_BFP_OF_REAL, stateGetPositionEnu_i(), waypoint_set_enu_i(), EnuCoor_i::x, EnuCoor_i::y, and EnuCoor_i::z.