Paparazzi UAS: sw/airborne/modules/multi/follow.h File Reference
follow.h File Reference
Follow a certain AC id.
Functions
void follow_init (void)
void follow_wp (void)
Detailed Description
Follow a certain AC id.
Definition in file follow.h.
Function Documentation
follow_init()
void follow_init (void)
Definition at line 57 of file follow.c.
follow_wp()
void follow_wp (void)
Definition at line 64 of file follow.c.
References acInfoGetPositionEnu_i(), FOLLOW_OFFSET_X, FOLLOW_OFFSET_Y, FOLLOW_OFFSET_Z, POS_BFP_OF_REAL, stateGetPositionEnu_i(), waypoint_set_enu_i(), EnuCoor_i::x, EnuCoor_i::y, and EnuCoor_i::z.