Paparazzi UAS: sw/airborne/subsystems/gps/gps_sim_nps.h File Reference
gps_sim_nps.h File Reference
#include "std.h"
Macros
#define PRIMARY_GPS GPS_SIM
#define gps_nps_periodic_check() gps_periodic_check(&gps_nps)
Functions
void gps_feed_value ()
void gps_nps_init ()
Variables
struct GpsState gps_nps
bool gps_has_fix
Macro Definition Documentation
gps_nps_periodic_check
#define gps_nps_periodic_check () gps_periodic_check(&gps_nps)
Definition at line 17 of file gps_sim_nps.h.
PRIMARY_GPS
#define PRIMARY_GPS GPS_SIM
Definition at line 7 of file gps_sim_nps.h.
Function Documentation
gps_feed_value()
void gps_feed_value ()
Definition at line 31 of file gps_sim_nps.c.
References LlaCoor_i::alt, GpsState::course, GpsState::ecef_pos, GpsState::ecef_vel, fdm, GpsState::fix, get_sys_time_usec(), GPS_FIX_3D, GPS_FIX_NONE, gps_has_fix, gps_nps, GPS_SIM_ID, GPS_VALID_COURSE_BIT, GPS_VALID_HMSL_BIT, GPS_VALID_POS_ECEF_BIT, GPS_VALID_POS_LLA_BIT, GPS_VALID_VEL_ECEF_BIT, GPS_VALID_VEL_NED_BIT, GpsState::gspeed, GpsState::hacc, GpsState::hmsl, GpsState::last_3dfix_ticks, GpsState::last_3dfix_time, GpsState::last_msg_ticks, GpsState::last_msg_time, LlaCoor_i::lat, GpsState::lla_pos, LlaCoor_i::lon, ltp_def_from_ecef_d(), NpsFdm::ltp_to_body_eulers, sys_time::nb_sec, sys_time::nb_sec_rem, ned_of_ecef_vect_d(), GpsState::ned_vel, GpsState::num_sv, GpsState::pacc, GpsState::pdop, DoubleEulers::psi, GpsState::sacc, sensors, GpsState::speed_3d, NpsFdm::time, GpsState::tow, GpsState::vacc, GpsState::valid_fields, GpsState::week, EcefCoor_i::x, NedCoor_d::x, NedCoor_i::x, EcefCoor_i::y, NedCoor_d::y, NedCoor_i::y, EcefCoor_i::z, NedCoor_d::z, and NedCoor_i::z.
Referenced by nps_autopilot_run_step().
gps_nps_init()
void gps_nps_init ()
Definition at line 103 of file gps_sim_nps.c.
References gps_has_fix.
Variable Documentation
gps_has_fix
bool gps_has_fix
Definition at line 29 of file gps_sim_nps.c.
Referenced by gps_feed_value(), gps_nps_init(), and on_WORLD_ENV().
gps_nps
struct GpsState gps_nps
Definition at line 28 of file gps_sim_nps.c.
Referenced by gps_feed_value().