Paparazzi UAS: Angular rate representations
Angular rate representations
State interface
Macros
#define RATE_I 0
#define RATE_F 1
Functions
void stateCalcBodyRates_i (void)
void stateCalcBodyRates_f (void)
static bool stateIsRateValid (void)
Test if rates are valid.
static void stateSetBodyRates_i (struct Int32Rates *body_rate)
Set vehicle body angular rate (int).
static void stateSetBodyRates_f (struct FloatRates *body_rate)
Set vehicle body angular rate (float).
static struct Int32Rates * stateGetBodyRates_i (void)
Get vehicle body angular rate (int).
static struct FloatRates * stateGetBodyRates_f (void)
Get vehicle body angular rate (float).
Variables
uint8_t State::rate_status
Holds the status bits for all angular rate representations.
struct Int32Rates State::body_rates_i
Angular rates in body frame.
struct FloatRates State::body_rates_f
Angular rates in body frame.
Detailed Description
Macro Definition Documentation
RATE_F
#define RATE_F 1
Definition at line 113 of file state.h.
RATE_I
#define RATE_I 0
Definition at line 112 of file state.h.
Function Documentation
stateCalcBodyRates_f()
void stateCalcBodyRates_f (void)
Definition at line 1222 of file state.c.
References State::body_rates_f, State::body_rates_i, RATE_F, RATE_I, State::rate_status, RATES_FLOAT_OF_BFP, and state.
Referenced by stateGetBodyRates_f().
stateCalcBodyRates_i()
void stateCalcBodyRates_i (void)
Definition at line 1207 of file state.c.
References State::body_rates_f, State::body_rates_i, RATE_F, RATE_I, State::rate_status, RATES_BFP_OF_REAL, and state.
Referenced by stateGetBodyRates_i().
stateGetBodyRates_f()
static struct FloatRates* stateGetBodyRates_f (void) inline static
Get vehicle body angular rate (float).
Definition at line 1200 of file state.h.
References State::body_rates_f, RATE_F, State::rate_status, state, and stateCalcBodyRates_f().
Referenced by CN_potential_heading(), CN_potential_velocity(), decawave_anchorless_communication_periodic(), file_logger_write_row(), h_ctl_pitch_loop(), h_ctl_roll_loop(), indi_init_filters(), lms_estimation(), mavlink_send_attitude(), mavlink_send_attitude_quaternion(), mavlink_send_highres_imu(), mf_daq_send_state(), opticflow_pmw3901_publish(), parse_mf_daq_msg(), pose_periodic(), process_data(), range_msg_callback(), rover_guidance_run(), rover_holo_guidance_run(), send_att(), send_tune_roll(), stabilization_attitude_run(), stabilization_indi_rate_run(), stabilization_rate_run(), and wind_estimator_periodic().
stateGetBodyRates_i()
static struct Int32Rates* stateGetBodyRates_i (void) inline static
Get vehicle body angular rate (int).
Definition at line 1191 of file state.h.
References State::body_rates_i, RATE_I, State::rate_status, state, and stateCalcBodyRates_i().
Referenced by ctrl_module_run(), logger_control_effectiveness_periodic(), send_att(), and stabilization_attitude_run().
stateIsRateValid()
static bool stateIsRateValid (void) inline static
Test if rates are valid.
Definition at line 1165 of file state.h.
References State::rate_status, and state.
stateSetBodyRates_f()
static void stateSetBodyRates_f (struct FloatRates * body_rate) inline static
Set vehicle body angular rate (float).
Definition at line 1181 of file state.h.
References State::body_rates_f, RATE_F, State::rate_status, RATES_COPY, and state.
Referenced by ahrs_vectornav_propagate(), ArduIMU_event(), ArduIMU_periodic(), compute_body_orientation_and_rates(), gx3_packet_read_message(), ins_ekf2_publish_attitude(), ins_float_invariant_propagate(), ins_vectornav_propagate(), parse_ins_msg(), set_body_orientation_and_rates(), set_body_state_from_quat(), set_state_from_ins(), sim_overwrite_ahrs(), update_ahrs_from_sim(), update_state_interface(), and vn100_event_task().
stateSetBodyRates_i()
static void stateSetBodyRates_i (struct Int32Rates * body_rate) inline static
Set vehicle body angular rate (int).
Definition at line 1173 of file state.h.
References State::body_rates_i, RATE_I, State::rate_status, RATES_COPY, and state.
Referenced by gyro_cb(), set_body_state_from_euler(), and set_body_state_from_quat().
Variable Documentation
body_rates_f
struct FloatRates State::body_rates_f
Angular rates in body frame.
Units: rad/s
Definition at line 390 of file state.h.
Referenced by stateCalcBodyRates_f(), stateCalcBodyRates_i(), stateGetBodyRates_f(), and stateSetBodyRates_f().
body_rates_i
struct Int32Rates State::body_rates_i
Angular rates in body frame.
Units: rad/s in BFP with INT32_RATE_FRAC
Definition at line 384 of file state.h.
Referenced by stateCalcBodyRates_f(), stateCalcBodyRates_i(), stateGetBodyRates_i(), and stateSetBodyRates_i().
rate_status
uint8_t State::rate_status
Holds the status bits for all angular rate representations.
When the corresponding bit is one the representation is already computed.
Definition at line 378 of file state.h.
Referenced by stateCalcBodyRates_f(), stateCalcBodyRates_i(), stateGetBodyRates_f(), stateGetBodyRates_i(), stateInit(), stateIsRateValid(), stateSetBodyRates_f(), and stateSetBodyRates_i().