Paparazzi UAS: Geomagnetic field model
Geomagnetic field model
Math » Geodetic functions
Macros
#define WMM2020_FRAC 2
#define N_MAX_OF_GH 12
#define GEO_EPOCH 2020.
#define YR_MIN 2020.
#define YR_MAX 2025.
#define NMAX_1 12
#define NMAX_2 12
#define IEXT 0
#define EXT_COEFF1 (double)0
#define EXT_COEFF2 (double)0
#define EXT_COEFF3 (double)0
#define GPS_EPOCH_BEGIN (double)1980.016393442623
Begin of the GPS epoch.
#define GPS_EPOCH_YEAR 1980
#define GPS_EPOCH_MONTH 1
#define GPS_EPOCH_DAY 6
#define WEEKS_IN_YEAR 52.14285
#define SECS_IN_YEAR 31536000
#define MAXDEG 13
#define MAXCOEFF (MAXDEG*(MAXDEG+2)+1)
Functions
int16_t extrapsh (double date, double dte1, int16_t nmax1, int16_t nmax2, double *gh)
int16_t mag_calc (int16_t igdgc, double flat, double flon, double elev, int16_t nmax, double *gh, double *geo_mag_x, double *geo_mag_y, double *geo_mag_z, int16_t iext, double ext1, double ext2, double ext3)
Variables
const double gh1 []
const double gh2 []
Detailed Description
Macro Definition Documentation
EXT_COEFF1
#define EXT_COEFF1 (double)0
Definition at line 52 of file pprz_geodetic_wmm2020.h.
EXT_COEFF2
#define EXT_COEFF2 (double)0
Definition at line 53 of file pprz_geodetic_wmm2020.h.
EXT_COEFF3
#define EXT_COEFF3 (double)0
Definition at line 54 of file pprz_geodetic_wmm2020.h.
GEO_EPOCH
#define GEO_EPOCH 2020.
Definition at line 45 of file pprz_geodetic_wmm2020.h.
GPS_EPOCH_BEGIN
#define GPS_EPOCH_BEGIN (double)1980.016393442623
Begin of the GPS epoch.
Definition at line 57 of file pprz_geodetic_wmm2020.h.
GPS_EPOCH_DAY
#define GPS_EPOCH_DAY 6
Definition at line 60 of file pprz_geodetic_wmm2020.h.
GPS_EPOCH_MONTH
#define GPS_EPOCH_MONTH 1
Definition at line 59 of file pprz_geodetic_wmm2020.h.
GPS_EPOCH_YEAR
#define GPS_EPOCH_YEAR 1980
Definition at line 58 of file pprz_geodetic_wmm2020.h.
IEXT
#define IEXT 0
Definition at line 51 of file pprz_geodetic_wmm2020.h.
MAXCOEFF
#define MAXCOEFF (MAXDEG*(MAXDEG+2)+1)
Definition at line 67 of file pprz_geodetic_wmm2020.h.
MAXDEG
#define MAXDEG 13
Definition at line 66 of file pprz_geodetic_wmm2020.h.
N_MAX_OF_GH
#define N_MAX_OF_GH 12
Definition at line 42 of file pprz_geodetic_wmm2020.h.
NMAX_1
#define NMAX_1 12
Definition at line 48 of file pprz_geodetic_wmm2020.h.
NMAX_2
#define NMAX_2 12
Definition at line 49 of file pprz_geodetic_wmm2020.h.
SECS_IN_YEAR
#define SECS_IN_YEAR 31536000
Definition at line 64 of file pprz_geodetic_wmm2020.h.
WEEKS_IN_YEAR
#define WEEKS_IN_YEAR 52.14285
Definition at line 63 of file pprz_geodetic_wmm2020.h.
WMM2020_FRAC
#define WMM2020_FRAC 2
Definition at line 41 of file pprz_geodetic_wmm2020.h.
YR_MAX
#define YR_MAX 2025.
Definition at line 47 of file pprz_geodetic_wmm2020.h.
YR_MIN
#define YR_MIN 2020.
Definition at line 46 of file pprz_geodetic_wmm2020.h.
Function Documentation
extrapsh()
int16_t extrapsh (double date, double dte1, int16_t nmax1, int16_t nmax2, double * gh)
Definition at line 64 of file pprz_geodetic_wmm2020.c.
References gh1, and gh2.
Referenced by geo_mag_event(), and init_ltp().
mag_calc()
int16_t mag_calc (int16_t igdgc, double flat, double flon, double elev, int16_t nmax, double * gh, double * geo_mag_x, double * geo_mag_y, double * geo_mag_z, int16_t iext, double ext1, double ext2, double ext3)
Definition at line 105 of file pprz_geodetic_wmm2020.c.
References logger_uart_parse::a2, Int32RMat::m, and p.
Referenced by geo_mag_event(), and init_ltp().
Variable Documentation
gh1
const double gh1[]
Definition at line 32 of file pprz_geodetic_wmm2020.c.
Referenced by extrapsh().
gh2
const double gh2[]
Definition at line 48 of file pprz_geodetic_wmm2020.c.
Referenced by extrapsh().