Paparazzi UAS: MCU Peripherals
MCU Peripherals
Modules
I2C Interface
SPI Interface
Functions
void mcu_init (void)
Microcontroller peripherals initialization.
void mcu_event (void)
MCU event functions.
void board_init (void)
Optional board init function called at the start of mcu_init().
void board_init2 (void)
Optional board init function called at the end of mcu_init().
Detailed Description
Function Documentation
board_init()
void board_init (void)
Optional board init function called at the start of mcu_init().
Definition at line 130 of file board.c.
References bat_read(), button_read(), kill_gracefull(), and KillGracefully().
Referenced by mcu_init().
board_init2()
void board_init2 (void)
Optional board init function called at the end of mcu_init().
Definition at line 92 of file board.c.
Referenced by mcu_init().
mcu_event()
void mcu_event (void)
MCU event functions.
Calls the event functions of used peripherals like i2c, uart, etc.
Definition at line 258 of file mcu.c.
References i2c_event(), softi2c_event(), and VCOM_event().
Referenced by event_task_ap(), event_task_fbw(), main_event(), and main_event_task().
mcu_init()
void mcu_init (void)
Microcontroller peripherals initialization.
This function is responisble for setting up the microcontroller after Reset.
Definition at line 87 of file mcu.c.
References adc_init(), board_init(), board_init2(), BTN_ON, BTN_ON_PIN, dac_init(), gpio_get(), gpio_setup_input(), gpio_setup_output(), led_init(), mcu_arch_init(), MCU_PWR, MCU_PWR_OFF, MCU_PWR_ON, MCU_PWR_PIN, PERIPHERAL3V3_ENABLE_ON, PERIPHERAL3V3_ENABLE_PIN, PERIPHERAL3V3_ENABLE_PORT, RADIO_CONTROL_POWER_ON, RADIO_CONTROL_POWER_PIN, RADIO_CONTROL_POWER_PORT, rng_init(), spi0_init(), spi1_init(), spi2_init(), spi_init_slaves(), spi_slave_hs_init(), sys_time_init(), uart_arch_init(), udp_arch_init(), and VCOM_init().
Referenced by init_fbw(), main(), and main_init().