Paparazzi UAS: sw/airborne/boards/hbmini/baro_board.c File Reference
baro_board.c File Reference
#include "std.h"
#include "baro_board.h"
#include "subsystems/sensors/baro.h"
#include "peripherals/bmp085.h"
#include "peripherals/bmp085_regs.h"
#include "subsystems/abi.h"
#include "led.h"
Functions
void baro_init (void)
void baro_periodic (void)
void bmp_baro_event (void)
Variables
struct Bmp085 baro_bmp085
Detailed Description
Baro board interface for Bosch BMP085 on HBmini I2C1 with EOC check.
Definition in file baro_board.c.
Function Documentation
baro_init()
void baro_init (void)
Definition at line 37 of file baro_board.c.
References baro_bmp085, bmp085_init(), BMP085_SLAVE_ADDR, and LED_OFF.
baro_periodic()
void baro_periodic (void)
Definition at line 45 of file baro_board.c.
References baro_bmp085, bmp085_periodic(), bmp085_read_eeprom_calib(), and Bmp085::initialized.
bmp_baro_event()
void bmp_baro_event (void)
Definition at line 54 of file baro_board.c.
References baro_bmp085, BARO_BOARD_SENDER_ID, bmp085_event(), Bmp085::data_available, get_sys_time_usec(), LED_TOGGLE, and Bmp085::pressure.
Variable Documentation
baro_bmp085
struct Bmp085 baro_bmp085
Definition at line 35 of file baro_board.c.
Referenced by baro_event(), baro_init(), baro_periodic(), and bmp_baro_event().