Paparazzi UAS: sw/airborne/modules/meteo/humid_sht_i2c.h File Reference
humid_sht_i2c.h File Reference
#include "std.h"
Macros
#define SHT2_WRITE_USER 0xE6
#define SHT2_READ_USER 0xE7
#define SHT2_TRIGGER_TEMP 0xF3
#define SHT2_TRIGGER_HUMID 0xF5
#define SHT2_SOFT_RESET 0xFE
Enumerations
enum sht_stat_i2c {
SHT2_UNINIT, SHT2_IDLE, SHT2_RESET, SHT2_SERIAL,
SHT2_SERIAL1, SHT2_SERIAL2, SHT2_SET_CONFIG, SHT2_READ_SERIAL,
SHT2_TRIG_TEMP, SHT2_GET_TEMP, SHT2_READ_TEMP, SHT2_TRIG_HUMID,
SHT2_GET_HUMID, SHT2_READ_HUMID
}
Functions
int8_t humid_sht_crc (volatile uint8_t *data)
void humid_sht_init_i2c (void)
void humid_sht_periodic_i2c (void)
void humid_sht_p_temp (void)
void humid_sht_p_humid (void)
void humid_sht_event_i2c (void)
Variables
uint16_t humidsht_i2c
uint16_t tempsht_i2c
float fhumidsht_i2c
float ftempsht_i2c
Macro Definition Documentation
SHT2_READ_USER
#define SHT2_READ_USER 0xE7
Definition at line 7 of file humid_sht_i2c.h.
SHT2_SOFT_RESET
#define SHT2_SOFT_RESET 0xFE
Definition at line 10 of file humid_sht_i2c.h.
SHT2_TRIGGER_HUMID
#define SHT2_TRIGGER_HUMID 0xF5
Definition at line 9 of file humid_sht_i2c.h.
SHT2_TRIGGER_TEMP
#define SHT2_TRIGGER_TEMP 0xF3
Definition at line 8 of file humid_sht_i2c.h.
SHT2_WRITE_USER
#define SHT2_WRITE_USER 0xE6
Definition at line 6 of file humid_sht_i2c.h.
Enumeration Type Documentation
sht_stat_i2c
enum sht_stat_i2c
Enumerator
SHT2_UNINIT
SHT2_IDLE
SHT2_RESET
SHT2_SERIAL
SHT2_SERIAL1
SHT2_SERIAL2
SHT2_SET_CONFIG
SHT2_READ_SERIAL
SHT2_TRIG_TEMP
SHT2_GET_TEMP
SHT2_READ_TEMP
SHT2_TRIG_HUMID
SHT2_GET_HUMID
SHT2_READ_HUMID
Definition at line 12 of file humid_sht_i2c.h.
Function Documentation
humid_sht_crc()
int8_t humid_sht_crc (volatile uint8_t * data)
Definition at line 50 of file humid_sht_i2c.c.
References crc.
Referenced by humid_sht_event_i2c().
humid_sht_event_i2c()
void humid_sht_event_i2c (void)
Definition at line 130 of file humid_sht_i2c.c.
References i2c_transaction::buf, DefaultChannel, DefaultDevice, fhumidsht_i2c, ftempsht_i2c, humid_sht_crc(), humidsht_i2c, i2c_transceive(), i2c_transmit(), I2CTransDone, I2CTransSuccess, if(), SHT2_GET_HUMID, SHT2_GET_TEMP, SHT2_IDLE, SHT2_READ_HUMID, SHT2_READ_TEMP, SHT2_RESET, SHT2_SERIAL, SHT2_SERIAL1, SHT2_SERIAL2, SHT2_TRIG_HUMID, SHT2_TRIG_TEMP, SHT2_TRIGGER_HUMID, SHT_I2C_DEV, sht_serial, sht_serial1, sht_serial2, SHT_SLAVE_ADDR, sht_status, sht_trans, i2c_transaction::status, and tempsht_i2c.
humid_sht_init_i2c()
void humid_sht_init_i2c (void)
Definition at line 71 of file humid_sht_i2c.c.
References SHT2_UNINIT, and sht_status.
humid_sht_p_humid()
void humid_sht_p_humid (void)
Definition at line 121 of file humid_sht_i2c.c.
References i2c_receive(), SHT2_GET_HUMID, SHT2_READ_HUMID, SHT_I2C_DEV, SHT_SLAVE_ADDR, sht_status, and sht_trans.
humid_sht_p_temp()
void humid_sht_p_temp (void)
Definition at line 111 of file humid_sht_i2c.c.
References i2c_receive(), SHT2_GET_TEMP, SHT2_READ_TEMP, SHT_I2C_DEV, SHT_SLAVE_ADDR, sht_status, and sht_trans.
humid_sht_periodic_i2c()
void humid_sht_periodic_i2c (void)
Definition at line 76 of file humid_sht_i2c.c.
References i2c_transaction::buf, DefaultChannel, DefaultDevice, i2c_transceive(), i2c_transmit(), SHT2_RESET, SHT2_SERIAL, SHT2_SERIAL1, SHT2_SERIAL2, SHT2_SOFT_RESET, SHT2_TRIG_TEMP, SHT2_TRIGGER_TEMP, SHT2_UNINIT, SHT_I2C_DEV, sht_serial1, sht_serial2, SHT_SLAVE_ADDR, sht_status, and sht_trans.
Variable Documentation
fhumidsht_i2c
float fhumidsht_i2c
Definition at line 48 of file humid_sht_i2c.c.
Referenced by humid_sht_event_i2c().
ftempsht_i2c
float ftempsht_i2c
Definition at line 37 of file humid_sht_i2c.h.
humidsht_i2c
uint16_t humidsht_i2c
Definition at line 47 of file humid_sht_i2c.c.
Referenced by humid_sht_event_i2c().
tempsht_i2c
uint16_t tempsht_i2c
Definition at line 36 of file humid_sht_i2c.h.