Paparazzi UAS: sw/airborne/modules/computer_vision/blob/imavmarker.h File Reference
imavmarker.h File Reference
#include "modules/computer_vision/lib/vision/image.h"
Data Structures
struct marker_deviation_t
Functions
struct marker_deviation_t marker (struct image_t *input, uint8_t M)
Detailed Description
Find a IMAV pattern
Definition in file imavmarker.h.
Data Structure Documentation
marker_deviation_t
struct marker_deviation_t
Definition at line 32 of file imavmarker.h.
Data Fields
uint16_t inlier
int32_t x
int32_t y
Function Documentation
marker()
struct marker_deviation_t marker (struct image_t * input, uint8_t M)
Definition at line 51 of file imavmarker.c.
References AbsDiff(), if(), Img, marker_deviation_t::inlier, Out, marker_deviation_t::x, and marker_deviation_t::y.
Referenced by cv_marker_func().