Paparazzi UAS: sw/airborne/boards/apogee/imu_apogee.h File Reference
imu_apogee.h File Reference
#include "std.h"
#include "generated/airframe.h"
#include "subsystems/imu.h"
#include "peripherals/mpu60x0_i2c.h"
Data Structures
struct ImuApogee
Macros
#define IMU_GYRO_P_SIGN 1
#define IMU_GYRO_Q_SIGN 1
#define IMU_GYRO_R_SIGN 1
#define IMU_ACCEL_X_SIGN 1
#define IMU_ACCEL_Y_SIGN 1
#define IMU_ACCEL_Z_SIGN 1
#define APOGEE_GYRO_RANGE MPU60X0_GYRO_RANGE_1000
#define APOGEE_ACCEL_RANGE MPU60X0_ACCEL_RANGE_8G
#define IMU_GYRO_P_SENS MPU60X0_GYRO_SENS[APOGEE_GYRO_RANGE]
#define IMU_GYRO_P_SENS_NUM MPU60X0_GYRO_SENS_FRAC[APOGEE_GYRO_RANGE][0]
#define IMU_GYRO_P_SENS_DEN MPU60X0_GYRO_SENS_FRAC[APOGEE_GYRO_RANGE][1]
#define IMU_GYRO_Q_SENS MPU60X0_GYRO_SENS[APOGEE_GYRO_RANGE]
#define IMU_GYRO_Q_SENS_NUM MPU60X0_GYRO_SENS_FRAC[APOGEE_GYRO_RANGE][0]
#define IMU_GYRO_Q_SENS_DEN MPU60X0_GYRO_SENS_FRAC[APOGEE_GYRO_RANGE][1]
#define IMU_GYRO_R_SENS MPU60X0_GYRO_SENS[APOGEE_GYRO_RANGE]
#define IMU_GYRO_R_SENS_NUM MPU60X0_GYRO_SENS_FRAC[APOGEE_GYRO_RANGE][0]
#define IMU_GYRO_R_SENS_DEN MPU60X0_GYRO_SENS_FRAC[APOGEE_GYRO_RANGE][1]
#define IMU_GYRO_P_NEUTRAL 0
#define IMU_GYRO_Q_NEUTRAL 0
#define IMU_GYRO_R_NEUTRAL 0
#define IMU_ACCEL_X_SENS MPU60X0_ACCEL_SENS[APOGEE_ACCEL_RANGE]
#define IMU_ACCEL_X_SENS_NUM MPU60X0_ACCEL_SENS_FRAC[APOGEE_ACCEL_RANGE][0]
#define IMU_ACCEL_X_SENS_DEN MPU60X0_ACCEL_SENS_FRAC[APOGEE_ACCEL_RANGE][1]
#define IMU_ACCEL_Y_SENS MPU60X0_ACCEL_SENS[APOGEE_ACCEL_RANGE]
#define IMU_ACCEL_Y_SENS_NUM MPU60X0_ACCEL_SENS_FRAC[APOGEE_ACCEL_RANGE][0]
#define IMU_ACCEL_Y_SENS_DEN MPU60X0_ACCEL_SENS_FRAC[APOGEE_ACCEL_RANGE][1]
#define IMU_ACCEL_Z_SENS MPU60X0_ACCEL_SENS[APOGEE_ACCEL_RANGE]
#define IMU_ACCEL_Z_SENS_NUM MPU60X0_ACCEL_SENS_FRAC[APOGEE_ACCEL_RANGE][0]
#define IMU_ACCEL_Z_SENS_DEN MPU60X0_ACCEL_SENS_FRAC[APOGEE_ACCEL_RANGE][1]
#define IMU_ACCEL_X_NEUTRAL 0
#define IMU_ACCEL_Y_NEUTRAL 0
#define IMU_ACCEL_Z_NEUTRAL 0
Functions
void imu_apogee_init (void)
void imu_apogee_periodic (void)
void imu_apogee_event (void)
void imu_apogee_downlink_raw (void)
Variables
struct ImuApogee imu_apogee
Detailed Description
Driver for the IMU on the Apogee board.
Invensense MPU-6050
Definition in file imu_apogee.h.
Data Structure Documentation
ImuApogee
struct ImuApogee
Definition at line 98 of file imu_apogee.h.
Data Fields
struct Mpu60x0_I2c mpu
Macro Definition Documentation
APOGEE_ACCEL_RANGE
#define APOGEE_ACCEL_RANGE MPU60X0_ACCEL_RANGE_8G
Definition at line 58 of file imu_apogee.h.
APOGEE_GYRO_RANGE
#define APOGEE_GYRO_RANGE MPU60X0_GYRO_RANGE_1000
Definition at line 55 of file imu_apogee.h.
IMU_ACCEL_X_NEUTRAL
#define IMU_ACCEL_X_NEUTRAL 0
Definition at line 93 of file imu_apogee.h.
IMU_ACCEL_X_SENS
#define IMU_ACCEL_X_SENS MPU60X0_ACCEL_SENS[APOGEE_ACCEL_RANGE]
Definition at line 82 of file imu_apogee.h.
IMU_ACCEL_X_SENS_DEN
#define IMU_ACCEL_X_SENS_DEN MPU60X0_ACCEL_SENS_FRAC[APOGEE_ACCEL_RANGE][1]
Definition at line 84 of file imu_apogee.h.
IMU_ACCEL_X_SENS_NUM
#define IMU_ACCEL_X_SENS_NUM MPU60X0_ACCEL_SENS_FRAC[APOGEE_ACCEL_RANGE][0]
Definition at line 83 of file imu_apogee.h.
IMU_ACCEL_X_SIGN
#define IMU_ACCEL_X_SIGN 1
Definition at line 49 of file imu_apogee.h.
IMU_ACCEL_Y_NEUTRAL
#define IMU_ACCEL_Y_NEUTRAL 0
Definition at line 94 of file imu_apogee.h.
IMU_ACCEL_Y_SENS
#define IMU_ACCEL_Y_SENS MPU60X0_ACCEL_SENS[APOGEE_ACCEL_RANGE]
Definition at line 85 of file imu_apogee.h.
IMU_ACCEL_Y_SENS_DEN
#define IMU_ACCEL_Y_SENS_DEN MPU60X0_ACCEL_SENS_FRAC[APOGEE_ACCEL_RANGE][1]
Definition at line 87 of file imu_apogee.h.
IMU_ACCEL_Y_SENS_NUM
#define IMU_ACCEL_Y_SENS_NUM MPU60X0_ACCEL_SENS_FRAC[APOGEE_ACCEL_RANGE][0]
Definition at line 86 of file imu_apogee.h.
IMU_ACCEL_Y_SIGN
#define IMU_ACCEL_Y_SIGN 1
Definition at line 50 of file imu_apogee.h.
IMU_ACCEL_Z_NEUTRAL
#define IMU_ACCEL_Z_NEUTRAL 0
Definition at line 95 of file imu_apogee.h.
IMU_ACCEL_Z_SENS
#define IMU_ACCEL_Z_SENS MPU60X0_ACCEL_SENS[APOGEE_ACCEL_RANGE]
Definition at line 88 of file imu_apogee.h.
IMU_ACCEL_Z_SENS_DEN
#define IMU_ACCEL_Z_SENS_DEN MPU60X0_ACCEL_SENS_FRAC[APOGEE_ACCEL_RANGE][1]
Definition at line 90 of file imu_apogee.h.
IMU_ACCEL_Z_SENS_NUM
#define IMU_ACCEL_Z_SENS_NUM MPU60X0_ACCEL_SENS_FRAC[APOGEE_ACCEL_RANGE][0]
Definition at line 89 of file imu_apogee.h.
IMU_ACCEL_Z_SIGN
#define IMU_ACCEL_Z_SIGN 1
Definition at line 51 of file imu_apogee.h.
IMU_GYRO_P_NEUTRAL
#define IMU_GYRO_P_NEUTRAL 0
Definition at line 74 of file imu_apogee.h.
IMU_GYRO_P_SENS
#define IMU_GYRO_P_SENS MPU60X0_GYRO_SENS[APOGEE_GYRO_RANGE]
Definition at line 63 of file imu_apogee.h.
IMU_GYRO_P_SENS_DEN
#define IMU_GYRO_P_SENS_DEN MPU60X0_GYRO_SENS_FRAC[APOGEE_GYRO_RANGE][1]
Definition at line 65 of file imu_apogee.h.
IMU_GYRO_P_SENS_NUM
#define IMU_GYRO_P_SENS_NUM MPU60X0_GYRO_SENS_FRAC[APOGEE_GYRO_RANGE][0]
Definition at line 64 of file imu_apogee.h.
IMU_GYRO_P_SIGN
#define IMU_GYRO_P_SIGN 1
Definition at line 44 of file imu_apogee.h.
IMU_GYRO_Q_NEUTRAL
#define IMU_GYRO_Q_NEUTRAL 0
Definition at line 75 of file imu_apogee.h.
IMU_GYRO_Q_SENS
#define IMU_GYRO_Q_SENS MPU60X0_GYRO_SENS[APOGEE_GYRO_RANGE]
Definition at line 66 of file imu_apogee.h.
IMU_GYRO_Q_SENS_DEN
#define IMU_GYRO_Q_SENS_DEN MPU60X0_GYRO_SENS_FRAC[APOGEE_GYRO_RANGE][1]
Definition at line 68 of file imu_apogee.h.
IMU_GYRO_Q_SENS_NUM
#define IMU_GYRO_Q_SENS_NUM MPU60X0_GYRO_SENS_FRAC[APOGEE_GYRO_RANGE][0]
Definition at line 67 of file imu_apogee.h.
IMU_GYRO_Q_SIGN
#define IMU_GYRO_Q_SIGN 1
Definition at line 45 of file imu_apogee.h.
IMU_GYRO_R_NEUTRAL
#define IMU_GYRO_R_NEUTRAL 0
Definition at line 76 of file imu_apogee.h.
IMU_GYRO_R_SENS
#define IMU_GYRO_R_SENS MPU60X0_GYRO_SENS[APOGEE_GYRO_RANGE]
Definition at line 69 of file imu_apogee.h.
IMU_GYRO_R_SENS_DEN
#define IMU_GYRO_R_SENS_DEN MPU60X0_GYRO_SENS_FRAC[APOGEE_GYRO_RANGE][1]
Definition at line 71 of file imu_apogee.h.
IMU_GYRO_R_SENS_NUM
#define IMU_GYRO_R_SENS_NUM MPU60X0_GYRO_SENS_FRAC[APOGEE_GYRO_RANGE][0]
Definition at line 70 of file imu_apogee.h.
IMU_GYRO_R_SIGN
#define IMU_GYRO_R_SIGN 1
Definition at line 46 of file imu_apogee.h.
Function Documentation
imu_apogee_downlink_raw()
void imu_apogee_downlink_raw (void)
Definition at line 129 of file imu_apogee.c.
References Imu::accel_unscaled, DefaultChannel, DefaultDevice, Imu::gyro_unscaled, imu, Int32Rates::p, Int32Rates::q, Int32Rates::r, Int32Vect3::x, Int32Vect3::y, and Int32Vect3::z.
imu_apogee_event()
void imu_apogee_event (void)
Definition at line 138 of file imu_apogee.c.
References Imu::accel, Imu::accel_unscaled, ak8975_event(), Mpu60x0_I2c::data_accel, Mpu60x0_I2c::data_available, Mpu60x0_I2c::data_rates, get_sys_time_usec(), Imu::gyro, Imu::gyro_unscaled, imu, imu_apogee, IMU_APOGEE_CHAN_X, IMU_APOGEE_CHAN_Y, IMU_APOGEE_CHAN_Z, IMU_BOARD_ID, imu_scale_accel(), imu_scale_gyro(), imu_scale_mag(), Imu::mag, Imu::mag_unscaled, ImuApogee::mpu, mpu60x0_i2c_event(), RATES_COPY, and VECT3_COPY.
imu_apogee_init()
void imu_apogee_init (void)
Definition at line 94 of file imu_apogee.c.
References Mpu60x0Config::accel_range, AK8975_I2C_SLV_ADDR, ak8975_init(), APOGEE_ACCEL_RANGE, APOGEE_GYRO_RANGE, APOGEE_LOWPASS_FILTER, APOGEE_SMPLRT_DIV, Mpu60x0_I2c::config, Mpu60x0I2cSlave::configure, configure_baro_slave(), Mpu60x0Config::dlpf_cfg, Mpu60x0Config::gyro_range, Mpu60x0Config::i2c_bypass, imu_apogee, ImuApogee::mpu, MPU60X0_ADDR_ALT, mpu60x0_i2c_init(), Mpu60x0Config::nb_slaves, Mpu60x0Config::slaves, and Mpu60x0Config::smplrt_div.
imu_apogee_periodic()
void imu_apogee_periodic (void)
Definition at line 116 of file imu_apogee.c.
References ak8975_periodic(), imu_apogee, ImuApogee::mpu, and mpu60x0_i2c_periodic().
Variable Documentation
imu_apogee
struct ImuApogee imu_apogee
Definition at line 85 of file imu_apogee.c.
Referenced by baro_periodic(), imu_apogee_event(), imu_apogee_init(), and imu_apogee_periodic().