Paparazzi UAS: sw/airborne/subsystems/imu/imu_aspirin_2_spi.h File Reference
imu_aspirin_2_spi.h File Reference
#include "std.h"
#include "generated/airframe.h"
#include "subsystems/imu.h"
#include "peripherals/mpu60x0_spi.h"
Data Structures
struct ImuAspirin2Spi
Macros
#define ASPIRIN_2_GYRO_RANGE MPU60X0_GYRO_RANGE_2000
#define ASPIRIN_2_ACCEL_RANGE MPU60X0_ACCEL_RANGE_16G
#define IMU_GYRO_P_SENS MPU60X0_GYRO_SENS[ASPIRIN_2_GYRO_RANGE]
#define IMU_GYRO_P_SENS_NUM MPU60X0_GYRO_SENS_FRAC[ASPIRIN_2_GYRO_RANGE][0]
#define IMU_GYRO_P_SENS_DEN MPU60X0_GYRO_SENS_FRAC[ASPIRIN_2_GYRO_RANGE][1]
#define IMU_GYRO_Q_SENS MPU60X0_GYRO_SENS[ASPIRIN_2_GYRO_RANGE]
#define IMU_GYRO_Q_SENS_NUM MPU60X0_GYRO_SENS_FRAC[ASPIRIN_2_GYRO_RANGE][0]
#define IMU_GYRO_Q_SENS_DEN MPU60X0_GYRO_SENS_FRAC[ASPIRIN_2_GYRO_RANGE][1]
#define IMU_GYRO_R_SENS MPU60X0_GYRO_SENS[ASPIRIN_2_GYRO_RANGE]
#define IMU_GYRO_R_SENS_NUM MPU60X0_GYRO_SENS_FRAC[ASPIRIN_2_GYRO_RANGE][0]
#define IMU_GYRO_R_SENS_DEN MPU60X0_GYRO_SENS_FRAC[ASPIRIN_2_GYRO_RANGE][1]
#define IMU_ACCEL_X_SENS MPU60X0_ACCEL_SENS[ASPIRIN_2_ACCEL_RANGE]
#define IMU_ACCEL_X_SENS_NUM MPU60X0_ACCEL_SENS_FRAC[ASPIRIN_2_ACCEL_RANGE][0]
#define IMU_ACCEL_X_SENS_DEN MPU60X0_ACCEL_SENS_FRAC[ASPIRIN_2_ACCEL_RANGE][1]
#define IMU_ACCEL_Y_SENS MPU60X0_ACCEL_SENS[ASPIRIN_2_ACCEL_RANGE]
#define IMU_ACCEL_Y_SENS_NUM MPU60X0_ACCEL_SENS_FRAC[ASPIRIN_2_ACCEL_RANGE][0]
#define IMU_ACCEL_Y_SENS_DEN MPU60X0_ACCEL_SENS_FRAC[ASPIRIN_2_ACCEL_RANGE][1]
#define IMU_ACCEL_Z_SENS MPU60X0_ACCEL_SENS[ASPIRIN_2_ACCEL_RANGE]
#define IMU_ACCEL_Z_SENS_NUM MPU60X0_ACCEL_SENS_FRAC[ASPIRIN_2_ACCEL_RANGE][0]
#define IMU_ACCEL_Z_SENS_DEN MPU60X0_ACCEL_SENS_FRAC[ASPIRIN_2_ACCEL_RANGE][1]
Functions
void imu_aspirin2_init (void)
void imu_aspirin2_event (void)
void imu_aspirin2_periodic (void)
Variables
struct ImuAspirin2Spi imu_aspirin2
Detailed Description
Driver for the Aspirin v2.x IMU using SPI for the MPU6000.
Definition in file imu_aspirin_2_spi.h.
Data Structure Documentation
ImuAspirin2Spi
struct ImuAspirin2Spi
Definition at line 70 of file imu_aspirin_2_spi.h.
Data Fields
struct Mpu60x0_Spi mpu
volatile bool slave4_ready
volatile uint8_t wait_slave4_rx_buf[2]
struct spi_transaction wait_slave4_trans
volatile uint8_t wait_slave4_tx_buf[1]
Macro Definition Documentation
ASPIRIN_2_ACCEL_RANGE
#define ASPIRIN_2_ACCEL_RANGE MPU60X0_ACCEL_RANGE_16G
Definition at line 41 of file imu_aspirin_2_spi.h.
ASPIRIN_2_GYRO_RANGE
#define ASPIRIN_2_GYRO_RANGE MPU60X0_GYRO_RANGE_2000
Definition at line 37 of file imu_aspirin_2_spi.h.
IMU_ACCEL_X_SENS
#define IMU_ACCEL_X_SENS MPU60X0_ACCEL_SENS[ASPIRIN_2_ACCEL_RANGE]
Definition at line 59 of file imu_aspirin_2_spi.h.
IMU_ACCEL_X_SENS_DEN
#define IMU_ACCEL_X_SENS_DEN MPU60X0_ACCEL_SENS_FRAC[ASPIRIN_2_ACCEL_RANGE][1]
Definition at line 61 of file imu_aspirin_2_spi.h.
IMU_ACCEL_X_SENS_NUM
#define IMU_ACCEL_X_SENS_NUM MPU60X0_ACCEL_SENS_FRAC[ASPIRIN_2_ACCEL_RANGE][0]
Definition at line 60 of file imu_aspirin_2_spi.h.
IMU_ACCEL_Y_SENS
#define IMU_ACCEL_Y_SENS MPU60X0_ACCEL_SENS[ASPIRIN_2_ACCEL_RANGE]
Definition at line 62 of file imu_aspirin_2_spi.h.
IMU_ACCEL_Y_SENS_DEN
#define IMU_ACCEL_Y_SENS_DEN MPU60X0_ACCEL_SENS_FRAC[ASPIRIN_2_ACCEL_RANGE][1]
Definition at line 64 of file imu_aspirin_2_spi.h.
IMU_ACCEL_Y_SENS_NUM
#define IMU_ACCEL_Y_SENS_NUM MPU60X0_ACCEL_SENS_FRAC[ASPIRIN_2_ACCEL_RANGE][0]
Definition at line 63 of file imu_aspirin_2_spi.h.
IMU_ACCEL_Z_SENS
#define IMU_ACCEL_Z_SENS MPU60X0_ACCEL_SENS[ASPIRIN_2_ACCEL_RANGE]
Definition at line 65 of file imu_aspirin_2_spi.h.
IMU_ACCEL_Z_SENS_DEN
#define IMU_ACCEL_Z_SENS_DEN MPU60X0_ACCEL_SENS_FRAC[ASPIRIN_2_ACCEL_RANGE][1]
Definition at line 67 of file imu_aspirin_2_spi.h.
IMU_ACCEL_Z_SENS_NUM
#define IMU_ACCEL_Z_SENS_NUM MPU60X0_ACCEL_SENS_FRAC[ASPIRIN_2_ACCEL_RANGE][0]
Definition at line 66 of file imu_aspirin_2_spi.h.
IMU_GYRO_P_SENS
#define IMU_GYRO_P_SENS MPU60X0_GYRO_SENS[ASPIRIN_2_GYRO_RANGE]
Definition at line 46 of file imu_aspirin_2_spi.h.
IMU_GYRO_P_SENS_DEN
#define IMU_GYRO_P_SENS_DEN MPU60X0_GYRO_SENS_FRAC[ASPIRIN_2_GYRO_RANGE][1]
Definition at line 48 of file imu_aspirin_2_spi.h.
IMU_GYRO_P_SENS_NUM
#define IMU_GYRO_P_SENS_NUM MPU60X0_GYRO_SENS_FRAC[ASPIRIN_2_GYRO_RANGE][0]
Definition at line 47 of file imu_aspirin_2_spi.h.
IMU_GYRO_Q_SENS
#define IMU_GYRO_Q_SENS MPU60X0_GYRO_SENS[ASPIRIN_2_GYRO_RANGE]
Definition at line 49 of file imu_aspirin_2_spi.h.
IMU_GYRO_Q_SENS_DEN
#define IMU_GYRO_Q_SENS_DEN MPU60X0_GYRO_SENS_FRAC[ASPIRIN_2_GYRO_RANGE][1]
Definition at line 51 of file imu_aspirin_2_spi.h.
IMU_GYRO_Q_SENS_NUM
#define IMU_GYRO_Q_SENS_NUM MPU60X0_GYRO_SENS_FRAC[ASPIRIN_2_GYRO_RANGE][0]
Definition at line 50 of file imu_aspirin_2_spi.h.
IMU_GYRO_R_SENS
#define IMU_GYRO_R_SENS MPU60X0_GYRO_SENS[ASPIRIN_2_GYRO_RANGE]
Definition at line 52 of file imu_aspirin_2_spi.h.
IMU_GYRO_R_SENS_DEN
#define IMU_GYRO_R_SENS_DEN MPU60X0_GYRO_SENS_FRAC[ASPIRIN_2_GYRO_RANGE][1]
Definition at line 54 of file imu_aspirin_2_spi.h.
IMU_GYRO_R_SENS_NUM
#define IMU_GYRO_R_SENS_NUM MPU60X0_GYRO_SENS_FRAC[ASPIRIN_2_GYRO_RANGE][0]
Definition at line 53 of file imu_aspirin_2_spi.h.
Function Documentation
imu_aspirin2_event()
void imu_aspirin2_event (void)
Definition at line 154 of file imu_aspirin_2_spi.c.
References Imu::accel, Imu::accel_unscaled, Mpu60x0_Spi::data_accel, Mpu60x0_Spi::data_available, Mpu60x0_Spi::data_ext, Mpu60x0_Spi::data_rates, get_sys_time_usec(), Imu::gyro, Imu::gyro_unscaled, imu, imu_aspirin2, IMU_ASPIRIN2_ID, imu_scale_accel(), imu_scale_gyro(), imu_scale_mag(), Int16FromBuf, Imu::mag, Imu::mag_unscaled, ImuAspirin2Spi::mpu, mpu60x0_spi_event(), RATES_ASSIGN, RATES_COPY, VECT3_ASSIGN, VECT3_COPY, Int32Vect3::x, Int32Vect3::y, and Int32Vect3::z.
imu_aspirin2_init()
void imu_aspirin2_init (void)
Definition at line 99 of file imu_aspirin_2_spi.c.
References Mpu60x0Config::accel_range, spi_transaction::after_cb, ASPIRIN_2_ACCEL_RANGE, ASPIRIN_2_GYRO_RANGE, ASPIRIN_2_SPI_DEV, ASPIRIN_2_SPI_SLAVE_IDX, spi_transaction::before_cb, spi_transaction::bitorder, spi_transaction::cdiv, Mpu60x0_Spi::config, Mpu60x0I2cSlave::configure, spi_transaction::cpha, spi_transaction::cpol, Mpu60x0Config::dlpf_cfg, spi_transaction::dss, Mpu60x0Config::gyro_range, Mpu60x0Config::i2c_mst_clk, Mpu60x0Config::i2c_mst_delay, imu_aspirin2, imu_aspirin2_configure_mag_slave(), spi_transaction::input_buf, spi_transaction::input_length, ImuAspirin2Spi::mpu, MPU60X0_MST_CLK_400KHZ, mpu60x0_spi_init(), mpu_wait_slave4_ready_cb(), Mpu60x0Config::nb_bytes, Mpu60x0Config::nb_slaves, spi_transaction::output_buf, spi_transaction::output_length, spi_transaction::select, ImuAspirin2Spi::slave4_ready, spi_transaction::slave_idx, Mpu60x0Config::slaves, Mpu60x0Config::smplrt_div, SPICphaEdge2, SPICpolIdleHigh, SPIDiv64, SPIDss8bit, SPIMSBFirst, SPISelectUnselect, SPITransDone, spi_transaction::status, ImuAspirin2Spi::wait_slave4_rx_buf, ImuAspirin2Spi::wait_slave4_trans, and ImuAspirin2Spi::wait_slave4_tx_buf.
imu_aspirin2_periodic()
void imu_aspirin2_periodic (void)
Definition at line 147 of file imu_aspirin_2_spi.c.
References imu_aspirin2, ImuAspirin2Spi::mpu, and mpu60x0_spi_periodic().
Variable Documentation
imu_aspirin2
struct ImuAspirin2Spi imu_aspirin2
Definition at line 93 of file imu_aspirin_2_spi.c.
Referenced by imu_aspirin2_event(), imu_aspirin2_init(), imu_aspirin2_periodic(), mpu_set_and_wait(), mpu_wait_slave4_ready(), and mpu_wait_slave4_ready_cb().