Paparazzi UAS: sw/airborne/modules/imu/imu_bmi088_i2c.h File Reference
imu_bmi088_i2c.h File Reference
#include "std.h"
#include "generated/airframe.h"
#include "subsystems/imu.h"
#include "peripherals/bmi088_i2c.h"
Data Structures
struct ImuBmi088
Macros
#define IMU_BMI088_GYRO_RANGE BMI088_GYRO_RANGE_1000
#define IMU_BMI088_ACCEL_RANGE BMI088_ACCEL_RANGE_6G
#define IMU_GYRO_P_SENS BMI088_GYRO_SENS[IMU_BMI088_GYRO_RANGE]
#define IMU_GYRO_P_SENS_NUM BMI088_GYRO_SENS_FRAC[IMU_BMI088_GYRO_RANGE][0]
#define IMU_GYRO_P_SENS_DEN BMI088_GYRO_SENS_FRAC[IMU_BMI088_GYRO_RANGE][1]
#define IMU_GYRO_Q_SENS BMI088_GYRO_SENS[IMU_BMI088_GYRO_RANGE]
#define IMU_GYRO_Q_SENS_NUM BMI088_GYRO_SENS_FRAC[IMU_BMI088_GYRO_RANGE][0]
#define IMU_GYRO_Q_SENS_DEN BMI088_GYRO_SENS_FRAC[IMU_BMI088_GYRO_RANGE][1]
#define IMU_GYRO_R_SENS BMI088_GYRO_SENS[IMU_BMI088_GYRO_RANGE]
#define IMU_GYRO_R_SENS_NUM BMI088_GYRO_SENS_FRAC[IMU_BMI088_GYRO_RANGE][0]
#define IMU_GYRO_R_SENS_DEN BMI088_GYRO_SENS_FRAC[IMU_BMI088_GYRO_RANGE][1]
#define IMU_ACCEL_X_SENS BMI088_ACCEL_SENS[IMU_BMI088_ACCEL_RANGE]
#define IMU_ACCEL_X_SENS_NUM BMI088_ACCEL_SENS_FRAC[IMU_BMI088_ACCEL_RANGE][0]
#define IMU_ACCEL_X_SENS_DEN BMI088_ACCEL_SENS_FRAC[IMU_BMI088_ACCEL_RANGE][1]
#define IMU_ACCEL_Y_SENS BMI088_ACCEL_SENS[IMU_BMI088_ACCEL_RANGE]
#define IMU_ACCEL_Y_SENS_NUM BMI088_ACCEL_SENS_FRAC[IMU_BMI088_ACCEL_RANGE][0]
#define IMU_ACCEL_Y_SENS_DEN BMI088_ACCEL_SENS_FRAC[IMU_BMI088_ACCEL_RANGE][1]
#define IMU_ACCEL_Z_SENS BMI088_ACCEL_SENS[IMU_BMI088_ACCEL_RANGE]
#define IMU_ACCEL_Z_SENS_NUM BMI088_ACCEL_SENS_FRAC[IMU_BMI088_ACCEL_RANGE][0]
#define IMU_ACCEL_Z_SENS_DEN BMI088_ACCEL_SENS_FRAC[IMU_BMI088_ACCEL_RANGE][1]
Functions
void imu_bmi088_init (void)
void imu_bmi088_periodic (void)
void imu_bmi088_event (void)
Variables
struct ImuBmi088 imu_bmi088
Data Structure Documentation
ImuBmi088
struct ImuBmi088
Definition at line 73 of file imu_bmi088_i2c.h.
Data Fields
struct Bmi088_I2c bmi
Macro Definition Documentation
IMU_ACCEL_X_SENS
#define IMU_ACCEL_X_SENS BMI088_ACCEL_SENS[IMU_BMI088_ACCEL_RANGE]
Definition at line 61 of file imu_bmi088_i2c.h.
IMU_ACCEL_X_SENS_DEN
#define IMU_ACCEL_X_SENS_DEN BMI088_ACCEL_SENS_FRAC[IMU_BMI088_ACCEL_RANGE][1]
Definition at line 63 of file imu_bmi088_i2c.h.
IMU_ACCEL_X_SENS_NUM
#define IMU_ACCEL_X_SENS_NUM BMI088_ACCEL_SENS_FRAC[IMU_BMI088_ACCEL_RANGE][0]
Definition at line 62 of file imu_bmi088_i2c.h.
IMU_ACCEL_Y_SENS
#define IMU_ACCEL_Y_SENS BMI088_ACCEL_SENS[IMU_BMI088_ACCEL_RANGE]
Definition at line 64 of file imu_bmi088_i2c.h.
IMU_ACCEL_Y_SENS_DEN
#define IMU_ACCEL_Y_SENS_DEN BMI088_ACCEL_SENS_FRAC[IMU_BMI088_ACCEL_RANGE][1]
Definition at line 66 of file imu_bmi088_i2c.h.
IMU_ACCEL_Y_SENS_NUM
#define IMU_ACCEL_Y_SENS_NUM BMI088_ACCEL_SENS_FRAC[IMU_BMI088_ACCEL_RANGE][0]
Definition at line 65 of file imu_bmi088_i2c.h.
IMU_ACCEL_Z_SENS
#define IMU_ACCEL_Z_SENS BMI088_ACCEL_SENS[IMU_BMI088_ACCEL_RANGE]
Definition at line 67 of file imu_bmi088_i2c.h.
IMU_ACCEL_Z_SENS_DEN
#define IMU_ACCEL_Z_SENS_DEN BMI088_ACCEL_SENS_FRAC[IMU_BMI088_ACCEL_RANGE][1]
Definition at line 69 of file imu_bmi088_i2c.h.
IMU_ACCEL_Z_SENS_NUM
#define IMU_ACCEL_Z_SENS_NUM BMI088_ACCEL_SENS_FRAC[IMU_BMI088_ACCEL_RANGE][0]
Definition at line 68 of file imu_bmi088_i2c.h.
IMU_BMI088_ACCEL_RANGE
#define IMU_BMI088_ACCEL_RANGE BMI088_ACCEL_RANGE_6G
Definition at line 43 of file imu_bmi088_i2c.h.
IMU_BMI088_GYRO_RANGE
#define IMU_BMI088_GYRO_RANGE BMI088_GYRO_RANGE_1000
Definition at line 39 of file imu_bmi088_i2c.h.
IMU_GYRO_P_SENS
#define IMU_GYRO_P_SENS BMI088_GYRO_SENS[IMU_BMI088_GYRO_RANGE]
Definition at line 48 of file imu_bmi088_i2c.h.
IMU_GYRO_P_SENS_DEN
#define IMU_GYRO_P_SENS_DEN BMI088_GYRO_SENS_FRAC[IMU_BMI088_GYRO_RANGE][1]
Definition at line 50 of file imu_bmi088_i2c.h.
IMU_GYRO_P_SENS_NUM
#define IMU_GYRO_P_SENS_NUM BMI088_GYRO_SENS_FRAC[IMU_BMI088_GYRO_RANGE][0]
Definition at line 49 of file imu_bmi088_i2c.h.
IMU_GYRO_Q_SENS
#define IMU_GYRO_Q_SENS BMI088_GYRO_SENS[IMU_BMI088_GYRO_RANGE]
Definition at line 51 of file imu_bmi088_i2c.h.
IMU_GYRO_Q_SENS_DEN
#define IMU_GYRO_Q_SENS_DEN BMI088_GYRO_SENS_FRAC[IMU_BMI088_GYRO_RANGE][1]
Definition at line 53 of file imu_bmi088_i2c.h.
IMU_GYRO_Q_SENS_NUM
#define IMU_GYRO_Q_SENS_NUM BMI088_GYRO_SENS_FRAC[IMU_BMI088_GYRO_RANGE][0]
Definition at line 52 of file imu_bmi088_i2c.h.
IMU_GYRO_R_SENS
#define IMU_GYRO_R_SENS BMI088_GYRO_SENS[IMU_BMI088_GYRO_RANGE]
Definition at line 54 of file imu_bmi088_i2c.h.
IMU_GYRO_R_SENS_DEN
#define IMU_GYRO_R_SENS_DEN BMI088_GYRO_SENS_FRAC[IMU_BMI088_GYRO_RANGE][1]
Definition at line 56 of file imu_bmi088_i2c.h.
IMU_GYRO_R_SENS_NUM
#define IMU_GYRO_R_SENS_NUM BMI088_GYRO_SENS_FRAC[IMU_BMI088_GYRO_RANGE][0]
Definition at line 55 of file imu_bmi088_i2c.h.
Function Documentation
imu_bmi088_event()
void imu_bmi088_event (void)
Definition at line 108 of file imu_bmi088_i2c.c.
References Imu::accel, Bmi088_I2c::accel_available, Imu::accel_unscaled, ImuBmi088::bmi, bmi088_i2c_event(), Bmi088_I2c::data_accel, Bmi088_I2c::data_rates, get_sys_time_usec(), Imu::gyro, Bmi088_I2c::gyro_available, Imu::gyro_unscaled, imu, imu_bmi088, IMU_BMI088_CHAN_X, IMU_BMI088_CHAN_Y, IMU_BMI088_CHAN_Z, IMU_BMI088_ID, IMU_BMI088_X_SIGN, IMU_BMI088_Y_SIGN, IMU_BMI088_Z_SIGN, imu_scale_accel(), imu_scale_gyro(), RATES_COPY, and VECT3_COPY.
imu_bmi088_init()
void imu_bmi088_init (void)
Definition at line 91 of file imu_bmi088_i2c.c.
References Bmi088Config::accel_bw, Bmi088Config::accel_odr, Bmi088Config::accel_range, ImuBmi088::bmi, bmi088_i2c_init(), Bmi088_I2c::config, Bmi088Config::gyro_odr, Bmi088Config::gyro_range, imu_bmi088, IMU_BMI088_ACCEL_BW, IMU_BMI088_ACCEL_I2C_ADDR, IMU_BMI088_ACCEL_ODR, IMU_BMI088_ACCEL_RANGE, IMU_BMI088_GYRO_I2C_ADDR, IMU_BMI088_GYRO_ODR, and IMU_BMI088_GYRO_RANGE.
imu_bmi088_periodic()
void imu_bmi088_periodic (void)
Definition at line 103 of file imu_bmi088_i2c.c.
References ImuBmi088::bmi, bmi088_i2c_periodic(), and imu_bmi088.
Variable Documentation
imu_bmi088
struct ImuBmi088 imu_bmi088
Definition at line 89 of file imu_bmi088_i2c.c.
Referenced by imu_bmi088_event(), imu_bmi088_init(), and imu_bmi088_periodic().