Paparazzi UAS: sw/airborne/subsystems/imu/imu_disco.h File Reference
imu_disco.h File Reference
#include "generated/airframe.h"
#include "subsystems/imu.h"
#include "peripherals/ak8963.h"
#include "peripherals/mpu60x0_i2c.h"
Data Structures
struct ImuDisco
Everything that is in the disco IMU.
Macros
#define DISCO_GYRO_RANGE MPU60X0_GYRO_RANGE_1000
#define DISCO_ACCEL_RANGE MPU60X0_ACCEL_RANGE_8G
#define IMU_GYRO_P_SENS MPU60X0_GYRO_SENS[DISCO_GYRO_RANGE]
#define IMU_GYRO_P_SENS_NUM MPU60X0_GYRO_SENS_FRAC[DISCO_GYRO_RANGE][0]
#define IMU_GYRO_P_SENS_DEN MPU60X0_GYRO_SENS_FRAC[DISCO_GYRO_RANGE][1]
#define IMU_GYRO_Q_SENS MPU60X0_GYRO_SENS[DISCO_GYRO_RANGE]
#define IMU_GYRO_Q_SENS_NUM MPU60X0_GYRO_SENS_FRAC[DISCO_GYRO_RANGE][0]
#define IMU_GYRO_Q_SENS_DEN MPU60X0_GYRO_SENS_FRAC[DISCO_GYRO_RANGE][1]
#define IMU_GYRO_R_SENS MPU60X0_GYRO_SENS[DISCO_GYRO_RANGE]
#define IMU_GYRO_R_SENS_NUM MPU60X0_GYRO_SENS_FRAC[DISCO_GYRO_RANGE][0]
#define IMU_GYRO_R_SENS_DEN MPU60X0_GYRO_SENS_FRAC[DISCO_GYRO_RANGE][1]
#define IMU_ACCEL_X_SENS MPU60X0_ACCEL_SENS[DISCO_ACCEL_RANGE]
#define IMU_ACCEL_X_SENS_NUM MPU60X0_ACCEL_SENS_FRAC[DISCO_ACCEL_RANGE][0]
#define IMU_ACCEL_X_SENS_DEN MPU60X0_ACCEL_SENS_FRAC[DISCO_ACCEL_RANGE][1]
#define IMU_ACCEL_Y_SENS MPU60X0_ACCEL_SENS[DISCO_ACCEL_RANGE]
#define IMU_ACCEL_Y_SENS_NUM MPU60X0_ACCEL_SENS_FRAC[DISCO_ACCEL_RANGE][0]
#define IMU_ACCEL_Y_SENS_DEN MPU60X0_ACCEL_SENS_FRAC[DISCO_ACCEL_RANGE][1]
#define IMU_ACCEL_Z_SENS MPU60X0_ACCEL_SENS[DISCO_ACCEL_RANGE]
#define IMU_ACCEL_Z_SENS_NUM MPU60X0_ACCEL_SENS_FRAC[DISCO_ACCEL_RANGE][0]
#define IMU_ACCEL_Z_SENS_DEN MPU60X0_ACCEL_SENS_FRAC[DISCO_ACCEL_RANGE][1]
Functions
void imu_disco_init (void)
Disco IMU initializtion of the MPU-60x0 and HMC58xx.
void imu_disco_periodic (void)
Handle all the periodic tasks of the Disco IMU components.
void imu_disco_event (void)
Handle all the events of the Disco IMU components.
Variables
struct ImuDisco imu_disco
Disco IMU data.
Detailed Description
Interface for the Disco magnetometer, accelerometer and gyroscope
Definition in file imu_disco.h.
Data Structure Documentation
ImuDisco
struct ImuDisco
Everything that is in the disco IMU.
Definition at line 72 of file imu_disco.h.
Data Fields
struct Ak8963 ak The AK8963 mag.
struct Mpu60x0_I2c mpu The MPU gyro/accel device.
Macro Definition Documentation
DISCO_ACCEL_RANGE
#define DISCO_ACCEL_RANGE MPU60X0_ACCEL_RANGE_8G
Definition at line 42 of file imu_disco.h.
DISCO_GYRO_RANGE
#define DISCO_GYRO_RANGE MPU60X0_GYRO_RANGE_1000
Definition at line 38 of file imu_disco.h.
IMU_ACCEL_X_SENS
#define IMU_ACCEL_X_SENS MPU60X0_ACCEL_SENS[DISCO_ACCEL_RANGE]
Definition at line 60 of file imu_disco.h.
IMU_ACCEL_X_SENS_DEN
#define IMU_ACCEL_X_SENS_DEN MPU60X0_ACCEL_SENS_FRAC[DISCO_ACCEL_RANGE][1]
Definition at line 62 of file imu_disco.h.
IMU_ACCEL_X_SENS_NUM
#define IMU_ACCEL_X_SENS_NUM MPU60X0_ACCEL_SENS_FRAC[DISCO_ACCEL_RANGE][0]
Definition at line 61 of file imu_disco.h.
IMU_ACCEL_Y_SENS
#define IMU_ACCEL_Y_SENS MPU60X0_ACCEL_SENS[DISCO_ACCEL_RANGE]
Definition at line 63 of file imu_disco.h.
IMU_ACCEL_Y_SENS_DEN
#define IMU_ACCEL_Y_SENS_DEN MPU60X0_ACCEL_SENS_FRAC[DISCO_ACCEL_RANGE][1]
Definition at line 65 of file imu_disco.h.
IMU_ACCEL_Y_SENS_NUM
#define IMU_ACCEL_Y_SENS_NUM MPU60X0_ACCEL_SENS_FRAC[DISCO_ACCEL_RANGE][0]
Definition at line 64 of file imu_disco.h.
IMU_ACCEL_Z_SENS
#define IMU_ACCEL_Z_SENS MPU60X0_ACCEL_SENS[DISCO_ACCEL_RANGE]
Definition at line 66 of file imu_disco.h.
IMU_ACCEL_Z_SENS_DEN
#define IMU_ACCEL_Z_SENS_DEN MPU60X0_ACCEL_SENS_FRAC[DISCO_ACCEL_RANGE][1]
Definition at line 68 of file imu_disco.h.
IMU_ACCEL_Z_SENS_NUM
#define IMU_ACCEL_Z_SENS_NUM MPU60X0_ACCEL_SENS_FRAC[DISCO_ACCEL_RANGE][0]
Definition at line 67 of file imu_disco.h.
IMU_GYRO_P_SENS
#define IMU_GYRO_P_SENS MPU60X0_GYRO_SENS[DISCO_GYRO_RANGE]
Definition at line 47 of file imu_disco.h.
IMU_GYRO_P_SENS_DEN
#define IMU_GYRO_P_SENS_DEN MPU60X0_GYRO_SENS_FRAC[DISCO_GYRO_RANGE][1]
Definition at line 49 of file imu_disco.h.
IMU_GYRO_P_SENS_NUM
#define IMU_GYRO_P_SENS_NUM MPU60X0_GYRO_SENS_FRAC[DISCO_GYRO_RANGE][0]
Definition at line 48 of file imu_disco.h.
IMU_GYRO_Q_SENS
#define IMU_GYRO_Q_SENS MPU60X0_GYRO_SENS[DISCO_GYRO_RANGE]
Definition at line 50 of file imu_disco.h.
IMU_GYRO_Q_SENS_DEN
#define IMU_GYRO_Q_SENS_DEN MPU60X0_GYRO_SENS_FRAC[DISCO_GYRO_RANGE][1]
Definition at line 52 of file imu_disco.h.
IMU_GYRO_Q_SENS_NUM
#define IMU_GYRO_Q_SENS_NUM MPU60X0_GYRO_SENS_FRAC[DISCO_GYRO_RANGE][0]
Definition at line 51 of file imu_disco.h.
IMU_GYRO_R_SENS
#define IMU_GYRO_R_SENS MPU60X0_GYRO_SENS[DISCO_GYRO_RANGE]
Definition at line 53 of file imu_disco.h.
IMU_GYRO_R_SENS_DEN
#define IMU_GYRO_R_SENS_DEN MPU60X0_GYRO_SENS_FRAC[DISCO_GYRO_RANGE][1]
Definition at line 55 of file imu_disco.h.
IMU_GYRO_R_SENS_NUM
#define IMU_GYRO_R_SENS_NUM MPU60X0_GYRO_SENS_FRAC[DISCO_GYRO_RANGE][0]
Definition at line 54 of file imu_disco.h.
Function Documentation
imu_disco_event()
void imu_disco_event (void)
Handle all the events of the Disco IMU components.
When there is data available convert it to the correct axis and save it in the imu structure.
Definition at line 108 of file imu_disco.c.
References Imu::accel, Imu::accel_unscaled, ImuDisco::ak, ak8963_event(), Ak8963::data, Mpu60x0_I2c::data_accel, Mpu60x0_I2c::data_available, Ak8963::data_available, Mpu60x0_I2c::data_rates, get_sys_time_usec(), Imu::gyro, Imu::gyro_unscaled, imu, IMU_BOARD_ID, imu_disco, imu_scale_accel(), imu_scale_gyro(), imu_scale_mag(), Imu::mag, Imu::mag_unscaled, ImuDisco::mpu, mpu60x0_i2c_event(), RATES_ASSIGN, and VECT3_ASSIGN.
imu_disco_init()
void imu_disco_init (void)
Disco IMU initializtion of the MPU-60x0 and HMC58xx.
Definition at line 72 of file imu_disco.c.
References Mpu60x0Config::accel_range, ImuDisco::ak, AK8963_ADDR, ak8963_init(), Mpu60x0_I2c::config, DISCO_ACCEL_RANGE, DISCO_GYRO_RANGE, DISCO_MAG_I2C_DEV, DISCO_MPU_I2C_DEV, Mpu60x0Config::dlpf_cfg, Mpu60x0Config::gyro_range, imu_disco, ImuDisco::mpu, MPU60X0_ADDR, mpu60x0_i2c_init(), and Mpu60x0Config::smplrt_div.
imu_disco_periodic()
void imu_disco_periodic (void)
Handle all the periodic tasks of the Disco IMU components.
Read the MPU60x0 every periodic call and the AKM8963 every 10th call.
Definition at line 89 of file imu_disco.c.
References ImuDisco::ak, AK8963_HZ, ak8963_periodic(), imu_disco, ImuDisco::mpu, and mpu60x0_i2c_periodic().
Variable Documentation
imu_disco
struct ImuDisco imu_disco
Disco IMU data.
Definition at line 67 of file imu_disco.c.
Referenced by imu_disco_event(), imu_disco_init(), and imu_disco_periodic().