Paparazzi UAS: sw/airborne/subsystems/imu/imu_px4fmu_v2.4.h File Reference
imu_px4fmu_v2.4.h File Reference
#include "std.h"
#include "generated/airframe.h"
#include "subsystems/imu.h"
#include "subsystems/imu/imu_px4_defaults.h"
#include "peripherals/l3gd20_spi.h"
#include "peripherals/lsm303d_spi.h"
Data Structures
struct ImuPX4
Macros
#define IMU_PX4_DISABLE_MAG FALSE
Functions
void imu_px4_init (void)
void imu_px4_periodic (void)
void imu_px4_event (void)
Variables
struct ImuPX4 imu_px4
Detailed Description
Driver for pixhawk IMU's. L3GD20H + LSM303D (both on spi)
Definition in file imu_px4fmu_v2.4.h.
Data Structure Documentation
ImuPX4
struct ImuPX4
Definition at line 47 of file imu_px4fmu_v2.4.h.
Data Fields
struct L3gd20_Spi l3g
struct Lsm303d_Spi lsm_acc
struct Lsm303d_Spi lsm_mag
Macro Definition Documentation
IMU_PX4_DISABLE_MAG
#define IMU_PX4_DISABLE_MAG FALSE
Definition at line 43 of file imu_px4fmu_v2.4.h.
Function Documentation
imu_px4_event()
void imu_px4_event (void)
Definition at line 67 of file imu_px4fmu_v2.4.c.
References Imu::accel, Imu::accel_unscaled, Lsm303d_Spi::data_accel, L3gd20_Spi::data_available, Lsm303d_Spi::data_available_acc, Lsm303d_Spi::data_available_mag, Lsm303d_Spi::data_mag, L3gd20_Spi::data_rates, FALSE, get_sys_time_usec(), Imu::gyro, Imu::gyro_unscaled, imu, imu_px4, IMU_PX4_ID, imu_scale_accel(), imu_scale_gyro(), imu_scale_mag(), ImuPX4::l3g, l3gd20_spi_event(), lsm303d_spi_event(), ImuPX4::lsm_acc, ImuPX4::lsm_mag, Imu::mag, Imu::mag_unscaled, Int32Rates::p, Int32Rates::q, Int32Rates::r, and VECT3_COPY.
imu_px4_init()
void imu_px4_init (void)
Definition at line 42 of file imu_px4fmu_v2.4.c.
References imu_px4, ImuPX4::l3g, l3gd20_spi_init(), lsm303d_spi_init(), LSM303D_TARGET_ACC, LSM303D_TARGET_MAG, ImuPX4::lsm_acc, and ImuPX4::lsm_mag.
imu_px4_periodic()
void imu_px4_periodic (void)
Definition at line 55 of file imu_px4fmu_v2.4.c.
References imu_px4, ImuPX4::l3g, l3gd20_spi_periodic(), lsm303d_spi_periodic(), ImuPX4::lsm_acc, and ImuPX4::lsm_mag.
Variable Documentation
imu_px4
struct ImuPX4 imu_px4
Definition at line 40 of file imu_px4fmu_v2.4.c.
Referenced by imu_px4_event(), imu_px4_init(), and imu_px4_periodic().