Paparazzi UAS: sw/airborne/modules/ins/imu_xsens.c File Reference
imu_xsens.c File Reference
#include "imu_xsens.h"
#include "xsens.h"
#include "generated/airframe.h"
#include "mcu_periph/sys_time.h"
#include "subsystems/abi.h"
Functions
static void handle_ins_msg (void)
void imu_xsens_init (void)
void imu_xsens_event (void)
Detailed Description
XSENS to just provide IMU measurements. For use with an external AHRS algorithm.
Definition in file imu_xsens.c.
Function Documentation
handle_ins_msg()
static void handle_ins_msg (void) static
Definition at line 53 of file imu_xsens.c.
References Xsens::accel, Imu::accel, Xsens::accel_available, ACCEL_BFP_OF_REAL, Imu::accel_unscaled, ACCELS_BFP_OF_REAL, FALSE, get_sys_time_usec(), Xsens::gyro, Imu::gyro, Xsens::gyro_available, Imu::gyro_unscaled, imu, imu_scale_accel(), imu_scale_gyro(), imu_scale_mag(), IMU_XSENS_ID, Xsens::mag, Imu::mag, Xsens::mag_available, MAG_BFP_OF_REAL, Imu::mag_unscaled, MAGS_BFP_OF_REAL, FloatRates::p, FloatRates::q, FloatRates::r, RATE_BFP_OF_REAL, RATES_ASSIGN, RATES_BFP_OF_REAL, VECT3_ASSIGN, and xsens.
Referenced by imu_xsens_event().
imu_xsens_event()
void imu_xsens_event (void)
Definition at line 43 of file imu_xsens.c.
References FALSE, handle_ins_msg(), XsensParser::msg_received, parse_xsens_msg(), Xsens::parser, xsens, and xsens_parser_event().
imu_xsens_init()
void imu_xsens_init (void)
Definition at line 38 of file imu_xsens.c.
References xsens_init().