Paparazzi UAS: sw/airborne/boards/hbmini/imu_hbmini.h File Reference
imu_hbmini.h File Reference
#include "std.h"
#include "generated/airframe.h"
#include "subsystems/imu.h"
#include "peripherals/max1168.h"
#include "peripherals/hmc58xx.h"
Data Structures
struct ImuHbmini
Macros
#define IMU_GYRO_P_SIGN -1
#define IMU_GYRO_Q_SIGN 1
#define IMU_GYRO_R_SIGN -1
#define IMU_ACCEL_X_SIGN 1
#define IMU_ACCEL_Y_SIGN -1
#define IMU_ACCEL_Z_SIGN -1
#define IMU_MAG_X_SIGN -1
#define IMU_MAG_Y_SIGN -1
#define IMU_MAG_Z_SIGN -1
Functions
void imu_hbmini_init (void)
void imu_hbmini_periodic (void)
void imu_hbmini_event (void)
void imu_hbmini_downlink_raw (void)
Variables
struct ImuHbmini imu_hbmini
Data Structure Documentation
ImuHbmini
struct ImuHbmini
Definition at line 61 of file imu_hbmini.h.
Data Fields
struct Hmc58xx hmc
Macro Definition Documentation
IMU_ACCEL_X_SIGN
#define IMU_ACCEL_X_SIGN 1
Definition at line 50 of file imu_hbmini.h.
IMU_ACCEL_Y_SIGN
#define IMU_ACCEL_Y_SIGN -1
Definition at line 51 of file imu_hbmini.h.
IMU_ACCEL_Z_SIGN
#define IMU_ACCEL_Z_SIGN -1
Definition at line 52 of file imu_hbmini.h.
IMU_GYRO_P_SIGN
#define IMU_GYRO_P_SIGN -1
Definition at line 45 of file imu_hbmini.h.
IMU_GYRO_Q_SIGN
#define IMU_GYRO_Q_SIGN 1
Definition at line 46 of file imu_hbmini.h.
IMU_GYRO_R_SIGN
#define IMU_GYRO_R_SIGN -1
Definition at line 47 of file imu_hbmini.h.
IMU_MAG_X_SIGN
#define IMU_MAG_X_SIGN -1
Definition at line 55 of file imu_hbmini.h.
IMU_MAG_Y_SIGN
#define IMU_MAG_Y_SIGN -1
Definition at line 56 of file imu_hbmini.h.
IMU_MAG_Z_SIGN
#define IMU_MAG_Z_SIGN -1
Definition at line 57 of file imu_hbmini.h.
Function Documentation
imu_hbmini_downlink_raw()
void imu_hbmini_downlink_raw (void)
Definition at line 84 of file imu_hbmini.c.
References Imu::accel_unscaled, DefaultChannel, DefaultDevice, Imu::gyro_unscaled, imu, Imu::mag_unscaled, Int32Rates::p, Int32Rates::q, Int32Rates::r, Int32Vect3::x, Int32Vect3::y, and Int32Vect3::z.
imu_hbmini_event()
void imu_hbmini_event (void)
Definition at line 93 of file imu_hbmini.c.
References Imu::accel, Imu::accel_unscaled, Hmc58xx::data, Hmc58xx::data_available, get_sys_time_usec(), Imu::gyro, Imu::gyro_unscaled, ImuHbmini::hmc, hmc58xx_event(), imu, IMU_ACCEL_X_CHAN, IMU_ACCEL_Y_CHAN, IMU_ACCEL_Z_CHAN, IMU_BOARD_ID, IMU_GYRO_P_CHAN, IMU_GYRO_Q_CHAN, IMU_GYRO_R_CHAN, imu_hbmini, IMU_MAG_X_CHAN, IMU_MAG_Y_CHAN, IMU_MAG_Z_CHAN, imu_scale_accel(), imu_scale_gyro(), imu_scale_mag(), Imu::mag, Imu::mag_unscaled, MAX1168_DATA_AVAILABLE, max1168_event(), MAX1168_IDLE, max1168_status, max1168_values, Int32Rates::p, Int32Rates::q, Int32Rates::r, Int32Vect3::x, Int32Vect3::y, and Int32Vect3::z.
imu_hbmini_init()
void imu_hbmini_init (void)
Definition at line 63 of file imu_hbmini.c.
References ImuHbmini::hmc, HMC58XX_ADDR, hmc58xx_init(), imu_hbmini, and max1168_init().
imu_hbmini_periodic()
void imu_hbmini_periodic (void)
Definition at line 72 of file imu_hbmini.c.
References ImuHbmini::hmc, hmc58xx_periodic(), imu_hbmini, and Max1168Periodic.
Variable Documentation
imu_hbmini
struct ImuHbmini imu_hbmini
Definition at line 61 of file imu_hbmini.c.
Referenced by imu_hbmini_event(), imu_hbmini_init(), and imu_hbmini_periodic().