Paparazzi UAS: sw/airborne/boards/apogee/imu_apogee.c File Reference
imu_apogee.c File Reference
#include <math.h>
#include "boards/apogee/imu_apogee.h"
#include "mcu_periph/i2c.h"
#include "led.h"
#include "subsystems/abi.h"
#include "mcu_periph/uart.h"
#include "pprzlink/messages.h"
#include "subsystems/datalink/downlink.h"
Macros
#define IMU_APOGEE_CHAN_X 0
#define IMU_APOGEE_CHAN_Y 1
#define IMU_APOGEE_CHAN_Z 2
#define APOGEE_LOWPASS_FILTER MPU60X0_DLPF_42HZ
#define APOGEE_SMPLRT_DIV 9
Functions
bool configure_baro_slave (Mpu60x0ConfigSet mpu_set, void *mpu)
void imu_apogee_init (void)
void imu_apogee_periodic (void)
void imu_apogee_downlink_raw (void)
void imu_apogee_event (void)
Variables
struct ImuApogee imu_apogee
Detailed Description
Driver for the IMU on the Apogee board.
Invensense MPU-6050
Definition in file imu_apogee.c.
Macro Definition Documentation
APOGEE_LOWPASS_FILTER
#define APOGEE_LOWPASS_FILTER MPU60X0_DLPF_42HZ
Definition at line 52 of file imu_apogee.c.
APOGEE_SMPLRT_DIV
#define APOGEE_SMPLRT_DIV 9
Definition at line 53 of file imu_apogee.c.
IMU_APOGEE_CHAN_X
#define IMU_APOGEE_CHAN_X 0
Definition at line 42 of file imu_apogee.c.
IMU_APOGEE_CHAN_Y
#define IMU_APOGEE_CHAN_Y 1
Definition at line 45 of file imu_apogee.c.
IMU_APOGEE_CHAN_Z
#define IMU_APOGEE_CHAN_Z 2
Definition at line 48 of file imu_apogee.c.
Function Documentation
configure_baro_slave()
bool configure_baro_slave (Mpu60x0ConfigSet mpu_set, void * mpu)
Definition at line 89 of file imu_apogee.c.
Referenced by imu_apogee_init().
imu_apogee_downlink_raw()
void imu_apogee_downlink_raw (void)
Definition at line 129 of file imu_apogee.c.
References Imu::accel_unscaled, DefaultChannel, DefaultDevice, Imu::gyro_unscaled, imu, Int32Rates::p, Int32Rates::q, Int32Rates::r, Int32Vect3::x, Int32Vect3::y, and Int32Vect3::z.
imu_apogee_event()
void imu_apogee_event (void)
Definition at line 138 of file imu_apogee.c.
References Imu::accel, Imu::accel_unscaled, ak8975_event(), Mpu60x0_I2c::data_accel, Mpu60x0_I2c::data_available, Mpu60x0_I2c::data_rates, get_sys_time_usec(), Imu::gyro, Imu::gyro_unscaled, imu, imu_apogee, IMU_APOGEE_CHAN_X, IMU_APOGEE_CHAN_Y, IMU_APOGEE_CHAN_Z, IMU_BOARD_ID, imu_scale_accel(), imu_scale_gyro(), imu_scale_mag(), Imu::mag, Imu::mag_unscaled, ImuApogee::mpu, mpu60x0_i2c_event(), RATES_COPY, and VECT3_COPY.
imu_apogee_init()
void imu_apogee_init (void)
Definition at line 94 of file imu_apogee.c.
References Mpu60x0Config::accel_range, AK8975_I2C_SLV_ADDR, ak8975_init(), APOGEE_ACCEL_RANGE, APOGEE_GYRO_RANGE, APOGEE_LOWPASS_FILTER, APOGEE_SMPLRT_DIV, Mpu60x0_I2c::config, Mpu60x0I2cSlave::configure, configure_baro_slave(), Mpu60x0Config::dlpf_cfg, Mpu60x0Config::gyro_range, Mpu60x0Config::i2c_bypass, imu_apogee, ImuApogee::mpu, MPU60X0_ADDR_ALT, mpu60x0_i2c_init(), Mpu60x0Config::nb_slaves, Mpu60x0Config::slaves, and Mpu60x0Config::smplrt_div.
imu_apogee_periodic()
void imu_apogee_periodic (void)
Definition at line 116 of file imu_apogee.c.
References ak8975_periodic(), imu_apogee, ImuApogee::mpu, and mpu60x0_i2c_periodic().
Variable Documentation
imu_apogee
struct ImuApogee imu_apogee
Definition at line 85 of file imu_apogee.c.
Referenced by baro_periodic(), imu_apogee_event(), imu_apogee_init(), and imu_apogee_periodic().