Paparazzi UAS: sw/airborne/boards/krooz/imu_krooz_memsic.h File Reference
imu_krooz_memsic.h File Reference
#include "std.h"
#include "generated/airframe.h"
#include "subsystems/imu.h"
#include "peripherals/mpu60x0_i2c.h"
#include "peripherals/hmc58xx.h"
#include "mcu_periph/spi.h"
Data Structures
struct ImuKrooz
Macros
#define KROOZ_GYRO_RANGE MPU60X0_GYRO_RANGE_250
#define IMU_GYRO_P_SENS MPU60X0_GYRO_SENS[KROOZ_GYRO_RANGE]
#define IMU_GYRO_P_SENS_NUM MPU60X0_GYRO_SENS_FRAC[KROOZ_GYRO_RANGE][0]
#define IMU_GYRO_P_SENS_DEN MPU60X0_GYRO_SENS_FRAC[KROOZ_GYRO_RANGE][1]
#define IMU_GYRO_Q_SENS MPU60X0_GYRO_SENS[KROOZ_GYRO_RANGE]
#define IMU_GYRO_Q_SENS_NUM MPU60X0_GYRO_SENS_FRAC[KROOZ_GYRO_RANGE][0]
#define IMU_GYRO_Q_SENS_DEN MPU60X0_GYRO_SENS_FRAC[KROOZ_GYRO_RANGE][1]
#define IMU_GYRO_R_SENS MPU60X0_GYRO_SENS[KROOZ_GYRO_RANGE]
#define IMU_GYRO_R_SENS_NUM MPU60X0_GYRO_SENS_FRAC[KROOZ_GYRO_RANGE][0]
#define IMU_GYRO_R_SENS_DEN MPU60X0_GYRO_SENS_FRAC[KROOZ_GYRO_RANGE][1]
#define IMU_ACCEL_X_SENS 0.9197
default accel sensitivy using 16 bit AD7689 adc MXR9500 with 1.5g has 21845 LSB/g sens = 9.81 [m/s^2] / 21845 [LSB/g] * 2^INT32_ACCEL_FRAC = 0.6131
#define IMU_ACCEL_X_SENS_NUM 9197
#define IMU_ACCEL_X_SENS_DEN 10000
#define IMU_ACCEL_Y_SENS 0.9197
#define IMU_ACCEL_Y_SENS_NUM 9197
#define IMU_ACCEL_Y_SENS_DEN 10000
#define IMU_ACCEL_Z_SENS 0.9197
#define IMU_ACCEL_Z_SENS_NUM 9197
#define IMU_ACCEL_Z_SENS_DEN 10000
#define IMU_ACCEL_X_NEUTRAL 32768
#define IMU_ACCEL_Y_NEUTRAL 32768
#define IMU_ACCEL_Z_NEUTRAL 32768
#define IMU_KROOZ_ACCEL_AVG_FILTER 15
Functions
void imu_krooz_init (void)
void imu_krooz_periodic (void)
void imu_krooz_event (void)
void imu_krooz_downlink_raw (void)
Variables
struct ImuKrooz imu_krooz
Detailed Description
Driver for the IMU on the KroozSD Big Rotorcraft Edition board.
Invensense MPU-6050 Memsic MXR9500 with AD7689 Honeywell HMC-5883
Definition in file imu_krooz_memsic.h.
Data Structure Documentation
ImuKrooz
struct ImuKrooz
Definition at line 80 of file imu_krooz.h.
Data Fields
struct Int32Vect3 accel_filtered
struct Int32Vect3 accel_sum
volatile uint8_t ad7689_spi_rx_buffer[2]
volatile uint8_t ad7689_spi_tx_buffer[2]
struct spi_transaction ad7689_trans
struct Hmc58xx hmc
volatile bool hmc_eoc
volatile uint8_t meas_nb
struct Uint8Vect3 meas_nb_acc
struct Mpu60x0_I2c mpu
volatile bool mpu_eoc
struct Int32Rates rates_sum
int32_t temperature
Macro Definition Documentation
IMU_ACCEL_X_NEUTRAL
#define IMU_ACCEL_X_NEUTRAL 32768
Definition at line 78 of file imu_krooz_memsic.h.
IMU_ACCEL_X_SENS
#define IMU_ACCEL_X_SENS 0.9197
default accel sensitivy using 16 bit AD7689 adc MXR9500 with 1.5g has 21845 LSB/g sens = 9.81 [m/s^2] / 21845 [LSB/g] * 2^INT32_ACCEL_FRAC = 0.6131
Definition at line 67 of file imu_krooz_memsic.h.
IMU_ACCEL_X_SENS_DEN
#define IMU_ACCEL_X_SENS_DEN 10000
Definition at line 69 of file imu_krooz_memsic.h.
IMU_ACCEL_X_SENS_NUM
#define IMU_ACCEL_X_SENS_NUM 9197
Definition at line 68 of file imu_krooz_memsic.h.
IMU_ACCEL_Y_NEUTRAL
#define IMU_ACCEL_Y_NEUTRAL 32768
Definition at line 79 of file imu_krooz_memsic.h.
IMU_ACCEL_Y_SENS
#define IMU_ACCEL_Y_SENS 0.9197
Definition at line 70 of file imu_krooz_memsic.h.
IMU_ACCEL_Y_SENS_DEN
#define IMU_ACCEL_Y_SENS_DEN 10000
Definition at line 72 of file imu_krooz_memsic.h.
IMU_ACCEL_Y_SENS_NUM
#define IMU_ACCEL_Y_SENS_NUM 9197
Definition at line 71 of file imu_krooz_memsic.h.
IMU_ACCEL_Z_NEUTRAL
#define IMU_ACCEL_Z_NEUTRAL 32768
Definition at line 80 of file imu_krooz_memsic.h.
IMU_ACCEL_Z_SENS
#define IMU_ACCEL_Z_SENS 0.9197
Definition at line 73 of file imu_krooz_memsic.h.
IMU_ACCEL_Z_SENS_DEN
#define IMU_ACCEL_Z_SENS_DEN 10000
Definition at line 75 of file imu_krooz_memsic.h.
IMU_ACCEL_Z_SENS_NUM
#define IMU_ACCEL_Z_SENS_NUM 9197
Definition at line 74 of file imu_krooz_memsic.h.
IMU_GYRO_P_SENS
#define IMU_GYRO_P_SENS MPU60X0_GYRO_SENS[KROOZ_GYRO_RANGE]
Definition at line 49 of file imu_krooz_memsic.h.
IMU_GYRO_P_SENS_DEN
#define IMU_GYRO_P_SENS_DEN MPU60X0_GYRO_SENS_FRAC[KROOZ_GYRO_RANGE][1]
Definition at line 51 of file imu_krooz_memsic.h.
IMU_GYRO_P_SENS_NUM
#define IMU_GYRO_P_SENS_NUM MPU60X0_GYRO_SENS_FRAC[KROOZ_GYRO_RANGE][0]
Definition at line 50 of file imu_krooz_memsic.h.
IMU_GYRO_Q_SENS
#define IMU_GYRO_Q_SENS MPU60X0_GYRO_SENS[KROOZ_GYRO_RANGE]
Definition at line 52 of file imu_krooz_memsic.h.
IMU_GYRO_Q_SENS_DEN
#define IMU_GYRO_Q_SENS_DEN MPU60X0_GYRO_SENS_FRAC[KROOZ_GYRO_RANGE][1]
Definition at line 54 of file imu_krooz_memsic.h.
IMU_GYRO_Q_SENS_NUM
#define IMU_GYRO_Q_SENS_NUM MPU60X0_GYRO_SENS_FRAC[KROOZ_GYRO_RANGE][0]
Definition at line 53 of file imu_krooz_memsic.h.
IMU_GYRO_R_SENS
#define IMU_GYRO_R_SENS MPU60X0_GYRO_SENS[KROOZ_GYRO_RANGE]
Definition at line 55 of file imu_krooz_memsic.h.
IMU_GYRO_R_SENS_DEN
#define IMU_GYRO_R_SENS_DEN MPU60X0_GYRO_SENS_FRAC[KROOZ_GYRO_RANGE][1]
Definition at line 57 of file imu_krooz_memsic.h.
IMU_GYRO_R_SENS_NUM
#define IMU_GYRO_R_SENS_NUM MPU60X0_GYRO_SENS_FRAC[KROOZ_GYRO_RANGE][0]
Definition at line 56 of file imu_krooz_memsic.h.
IMU_KROOZ_ACCEL_AVG_FILTER
#define IMU_KROOZ_ACCEL_AVG_FILTER 15
Definition at line 84 of file imu_krooz_memsic.h.
KROOZ_GYRO_RANGE
#define KROOZ_GYRO_RANGE MPU60X0_GYRO_RANGE_250
Definition at line 44 of file imu_krooz_memsic.h.
Function Documentation
imu_krooz_downlink_raw()
void imu_krooz_downlink_raw (void)
Definition at line 130 of file imu_krooz.c.
References Imu::accel_unscaled, DefaultChannel, DefaultDevice, Imu::gyro_unscaled, imu, Int32Rates::p, Int32Rates::q, Int32Rates::r, Int32Vect3::x, Int32Vect3::y, and Int32Vect3::z.
imu_krooz_event()
void imu_krooz_event (void)
Definition at line 139 of file imu_krooz.c.
References ImuKrooz::accel_sum, ad7689_event_timer, ImuKrooz::ad7689_trans, axis_cnt, axis_nb, Hmc58xx::data, Mpu60x0_I2c::data_accel, Mpu60x0_I2c::data_available, Hmc58xx::data_available, Mpu60x0_I2c::data_rates, get_sys_time_usec(), ImuKrooz::hmc, hmc58xx_event(), hmc58xx_read(), ImuKrooz::hmc_eoc, imu, IMU_BOARD_ID, imu_krooz, imu_scale_mag(), spi_transaction::input_buf, Imu::mag, Imu::mag_unscaled, ImuKrooz::meas_nb, ImuKrooz::meas_nb_acc, median_mag, ImuKrooz::mpu, mpu60x0_i2c_event(), mpu60x0_i2c_read(), ImuKrooz::mpu_eoc, spi_transaction::output_buf, RATES_ADD, ImuKrooz::rates_sum, spi_submit(), SPITransDone, SPITransSuccess, spi_transaction::status, SysTimeTimer, SysTimeTimerStart, ImuKrooz::temperature, UpdateMedianFilterVect3Int, VECT3_ADD, VECT3_ASSIGN, Uint8Vect3::x, Int32Vect3::x, Uint8Vect3::y, Int32Vect3::y, Uint8Vect3::z, and Int32Vect3::z.
imu_krooz_init()
void imu_krooz_init (void)
Definition at line 61 of file imu_krooz.c.
References Mpu60x0Config::accel_range, ImuKrooz::accel_sum, ImuKrooz::ad7689_spi_rx_buffer, ImuKrooz::ad7689_spi_tx_buffer, ImuKrooz::ad7689_trans, spi_transaction::after_cb, axis_cnt, axis_nb, spi_transaction::before_cb, spi_transaction::bitorder, spi_transaction::cdiv, Mpu60x0_I2c::config, spi_transaction::cpha, spi_transaction::cpol, Mpu60x0Config::dlpf_cfg, Mpu60x0Config::drdy_int_enable, spi_transaction::dss, Mpu60x0Config::gyro_range, ImuKrooz::hmc, HMC58XX_ADDR, hmc58xx_init(), ImuKrooz::hmc_eoc, imu_krooz, imu_krooz_sd_arch_init(), InitMedianFilterVect3Int, spi_transaction::input_buf, spi_transaction::input_length, KROOZ_ACCEL_RANGE, KROOZ_GYRO_RANGE, KROOZ_LOWPASS_FILTER, KROOZ_SMPLRT_DIV, ImuKrooz::meas_nb, MEDIAN_DEFAULT_SIZE, median_mag, ImuKrooz::mpu, MPU60X0_ADDR, mpu60x0_i2c_init(), ImuKrooz::mpu_eoc, spi_transaction::output_buf, spi_transaction::output_length, RATES_ASSIGN, ImuKrooz::rates_sum, spi_transaction::select, spi_transaction::slave_idx, Mpu60x0Config::smplrt_div, SPICphaEdge1, SPICpolIdleLow, SPIDiv16, SPIDss8bit, SPIMSBFirst, SPISelectUnselect, and VECT3_ASSIGN.
imu_krooz_periodic()
void imu_krooz_periodic (void)
Definition at line 91 of file imu_krooz.c.
References Imu::accel, ImuKrooz::accel_filtered, ImuKrooz::accel_sum, Imu::accel_unscaled, axis_nb, Mpu60x0_I2c::config, get_sys_time_usec(), Imu::gyro, Imu::gyro_unscaled, ImuKrooz::hmc, hmc58xx_start_configure(), imu, IMU_BOARD_ID, imu_krooz, IMU_KROOZ_ACCEL_AVG_FILTER, imu_scale_accel(), imu_scale_gyro(), Hmc58xx::initialized, Mpu60x0Config::initialized, INT_VECT3_ZERO, ImuKrooz::meas_nb, ImuKrooz::meas_nb_acc, ImuKrooz::mpu, mpu60x0_i2c_start_configure(), Int32Rates::p, Int32Rates::q, Int32Rates::r, RATES_ASSIGN, ImuKrooz::rates_sum, UpdateMedianFilterVect3Int, VECT3_ADD, VECT3_ASSIGN, VECT3_COPY, VECT3_SDIV, VECT3_SMUL, Uint8Vect3::x, Int32Vect3::x, Uint8Vect3::y, Int32Vect3::y, Uint8Vect3::z, and Int32Vect3::z.
Variable Documentation
imu_krooz
struct ImuKrooz imu_krooz
Definition at line 54 of file imu_krooz.c.
Referenced by exti9_5_isr(), imu_krooz_event(), imu_krooz_init(), and imu_krooz_periodic().