Paparazzi UAS: sw/airborne/subsystems/imu/imu_mpu6000_hmc5883.h File Reference
imu_mpu6000_hmc5883.h File Reference
#include "std.h"
#include "generated/airframe.h"
#include "subsystems/imu.h"
#include "peripherals/mpu60x0_spi.h"
#include "peripherals/hmc58xx.h"
Data Structures
struct ImuMpu6000Hmc5883
Macros
#define IMU_MPU_GYRO_RANGE MPU60X0_GYRO_RANGE_2000
#define IMU_MPU_ACCEL_RANGE MPU60X0_ACCEL_RANGE_16G
#define IMU_GYRO_P_SENS MPU60X0_GYRO_SENS[IMU_MPU_GYRO_RANGE]
#define IMU_GYRO_P_SENS_NUM MPU60X0_GYRO_SENS_FRAC[IMU_MPU_GYRO_RANGE][0]
#define IMU_GYRO_P_SENS_DEN MPU60X0_GYRO_SENS_FRAC[IMU_MPU_GYRO_RANGE][1]
#define IMU_GYRO_Q_SENS MPU60X0_GYRO_SENS[IMU_MPU_GYRO_RANGE]
#define IMU_GYRO_Q_SENS_NUM MPU60X0_GYRO_SENS_FRAC[IMU_MPU_GYRO_RANGE][0]
#define IMU_GYRO_Q_SENS_DEN MPU60X0_GYRO_SENS_FRAC[IMU_MPU_GYRO_RANGE][1]
#define IMU_GYRO_R_SENS MPU60X0_GYRO_SENS[IMU_MPU_GYRO_RANGE]
#define IMU_GYRO_R_SENS_NUM MPU60X0_GYRO_SENS_FRAC[IMU_MPU_GYRO_RANGE][0]
#define IMU_GYRO_R_SENS_DEN MPU60X0_GYRO_SENS_FRAC[IMU_MPU_GYRO_RANGE][1]
#define IMU_ACCEL_X_SENS MPU60X0_ACCEL_SENS[IMU_MPU_ACCEL_RANGE]
#define IMU_ACCEL_X_SENS_NUM MPU60X0_ACCEL_SENS_FRAC[IMU_MPU_ACCEL_RANGE][0]
#define IMU_ACCEL_X_SENS_DEN MPU60X0_ACCEL_SENS_FRAC[IMU_MPU_ACCEL_RANGE][1]
#define IMU_ACCEL_Y_SENS MPU60X0_ACCEL_SENS[IMU_MPU_ACCEL_RANGE]
#define IMU_ACCEL_Y_SENS_NUM MPU60X0_ACCEL_SENS_FRAC[IMU_MPU_ACCEL_RANGE][0]
#define IMU_ACCEL_Y_SENS_DEN MPU60X0_ACCEL_SENS_FRAC[IMU_MPU_ACCEL_RANGE][1]
#define IMU_ACCEL_Z_SENS MPU60X0_ACCEL_SENS[IMU_MPU_ACCEL_RANGE]
#define IMU_ACCEL_Z_SENS_NUM MPU60X0_ACCEL_SENS_FRAC[IMU_MPU_ACCEL_RANGE][0]
#define IMU_ACCEL_Z_SENS_DEN MPU60X0_ACCEL_SENS_FRAC[IMU_MPU_ACCEL_RANGE][1]
Functions
void imu_mpu_hmc_init (void)
void imu_mpu_hmc_periodic (void)
void imu_mpu_hmc_event (void)
Variables
struct ImuMpu6000Hmc5883 imu_mpu_hmc
Detailed Description
Driver for IMU with MPU6000 via SPI and HMC5883 via I2c. E.g. for Aspirin 2.1
Definition in file imu_mpu6000_hmc5883.h.
Data Structure Documentation
ImuMpu6000Hmc5883
struct ImuMpu6000Hmc5883
Definition at line 73 of file imu_mpu6000_hmc5883.h.
Data Fields
struct Hmc58xx hmc
struct Mpu60x0_Spi mpu
Macro Definition Documentation
IMU_ACCEL_X_SENS
#define IMU_ACCEL_X_SENS MPU60X0_ACCEL_SENS[IMU_MPU_ACCEL_RANGE]
Definition at line 61 of file imu_mpu6000_hmc5883.h.
IMU_ACCEL_X_SENS_DEN
#define IMU_ACCEL_X_SENS_DEN MPU60X0_ACCEL_SENS_FRAC[IMU_MPU_ACCEL_RANGE][1]
Definition at line 63 of file imu_mpu6000_hmc5883.h.
IMU_ACCEL_X_SENS_NUM
#define IMU_ACCEL_X_SENS_NUM MPU60X0_ACCEL_SENS_FRAC[IMU_MPU_ACCEL_RANGE][0]
Definition at line 62 of file imu_mpu6000_hmc5883.h.
IMU_ACCEL_Y_SENS
#define IMU_ACCEL_Y_SENS MPU60X0_ACCEL_SENS[IMU_MPU_ACCEL_RANGE]
Definition at line 64 of file imu_mpu6000_hmc5883.h.
IMU_ACCEL_Y_SENS_DEN
#define IMU_ACCEL_Y_SENS_DEN MPU60X0_ACCEL_SENS_FRAC[IMU_MPU_ACCEL_RANGE][1]
Definition at line 66 of file imu_mpu6000_hmc5883.h.
IMU_ACCEL_Y_SENS_NUM
#define IMU_ACCEL_Y_SENS_NUM MPU60X0_ACCEL_SENS_FRAC[IMU_MPU_ACCEL_RANGE][0]
Definition at line 65 of file imu_mpu6000_hmc5883.h.
IMU_ACCEL_Z_SENS
#define IMU_ACCEL_Z_SENS MPU60X0_ACCEL_SENS[IMU_MPU_ACCEL_RANGE]
Definition at line 67 of file imu_mpu6000_hmc5883.h.
IMU_ACCEL_Z_SENS_DEN
#define IMU_ACCEL_Z_SENS_DEN MPU60X0_ACCEL_SENS_FRAC[IMU_MPU_ACCEL_RANGE][1]
Definition at line 69 of file imu_mpu6000_hmc5883.h.
IMU_ACCEL_Z_SENS_NUM
#define IMU_ACCEL_Z_SENS_NUM MPU60X0_ACCEL_SENS_FRAC[IMU_MPU_ACCEL_RANGE][0]
Definition at line 68 of file imu_mpu6000_hmc5883.h.
IMU_GYRO_P_SENS
#define IMU_GYRO_P_SENS MPU60X0_GYRO_SENS[IMU_MPU_GYRO_RANGE]
Definition at line 48 of file imu_mpu6000_hmc5883.h.
IMU_GYRO_P_SENS_DEN
#define IMU_GYRO_P_SENS_DEN MPU60X0_GYRO_SENS_FRAC[IMU_MPU_GYRO_RANGE][1]
Definition at line 50 of file imu_mpu6000_hmc5883.h.
IMU_GYRO_P_SENS_NUM
#define IMU_GYRO_P_SENS_NUM MPU60X0_GYRO_SENS_FRAC[IMU_MPU_GYRO_RANGE][0]
Definition at line 49 of file imu_mpu6000_hmc5883.h.
IMU_GYRO_Q_SENS
#define IMU_GYRO_Q_SENS MPU60X0_GYRO_SENS[IMU_MPU_GYRO_RANGE]
Definition at line 51 of file imu_mpu6000_hmc5883.h.
IMU_GYRO_Q_SENS_DEN
#define IMU_GYRO_Q_SENS_DEN MPU60X0_GYRO_SENS_FRAC[IMU_MPU_GYRO_RANGE][1]
Definition at line 53 of file imu_mpu6000_hmc5883.h.
IMU_GYRO_Q_SENS_NUM
#define IMU_GYRO_Q_SENS_NUM MPU60X0_GYRO_SENS_FRAC[IMU_MPU_GYRO_RANGE][0]
Definition at line 52 of file imu_mpu6000_hmc5883.h.
IMU_GYRO_R_SENS
#define IMU_GYRO_R_SENS MPU60X0_GYRO_SENS[IMU_MPU_GYRO_RANGE]
Definition at line 54 of file imu_mpu6000_hmc5883.h.
IMU_GYRO_R_SENS_DEN
#define IMU_GYRO_R_SENS_DEN MPU60X0_GYRO_SENS_FRAC[IMU_MPU_GYRO_RANGE][1]
Definition at line 56 of file imu_mpu6000_hmc5883.h.
IMU_GYRO_R_SENS_NUM
#define IMU_GYRO_R_SENS_NUM MPU60X0_GYRO_SENS_FRAC[IMU_MPU_GYRO_RANGE][0]
Definition at line 55 of file imu_mpu6000_hmc5883.h.
IMU_MPU_ACCEL_RANGE
#define IMU_MPU_ACCEL_RANGE MPU60X0_ACCEL_RANGE_16G
Definition at line 43 of file imu_mpu6000_hmc5883.h.
IMU_MPU_GYRO_RANGE
#define IMU_MPU_GYRO_RANGE MPU60X0_GYRO_RANGE_2000
Definition at line 39 of file imu_mpu6000_hmc5883.h.
Function Documentation
imu_mpu_hmc_event()
void imu_mpu_hmc_event (void)
Definition at line 146 of file imu_mpu6000_hmc5883.c.
References Imu::accel, Imu::accel_unscaled, Hmc58xx::data, Mpu60x0_Spi::data_accel, Mpu60x0_Spi::data_available, Hmc58xx::data_available, Mpu60x0_Spi::data_rates, get_sys_time_usec(), Imu::gyro, Imu::gyro_unscaled, ImuMpu6000Hmc5883::hmc, hmc58xx_event(), imu, IMU_HMC_CHAN_X, IMU_HMC_CHAN_Y, IMU_HMC_CHAN_Z, IMU_HMC_X_SIGN, IMU_HMC_Y_SIGN, IMU_HMC_Z_SIGN, IMU_MPU6000_HMC_ID, IMU_MPU_CHAN_X, IMU_MPU_CHAN_Y, IMU_MPU_CHAN_Z, imu_mpu_hmc, IMU_MPU_X_SIGN, IMU_MPU_Y_SIGN, IMU_MPU_Z_SIGN, imu_scale_accel(), imu_scale_gyro(), imu_scale_mag(), Imu::mag, Imu::mag_unscaled, ImuMpu6000Hmc5883::mpu, mpu60x0_spi_event(), RATES_COPY, VECT3_COPY, Int32Vect3::x, Int32Vect3::y, and Int32Vect3::z.
imu_mpu_hmc_init()
void imu_mpu_hmc_init (void)
Definition at line 122 of file imu_mpu6000_hmc5883.c.
References Mpu60x0Config::accel_range, Mpu60x0_Spi::config, Mpu60x0Config::dlpf_cfg, Mpu60x0Config::gyro_range, ImuMpu6000Hmc5883::hmc, HMC58XX_ADDR, hmc58xx_init(), IMU_MPU_ACCEL_RANGE, IMU_MPU_GYRO_RANGE, imu_mpu_hmc, IMU_MPU_LOWPASS_FILTER, IMU_MPU_SMPLRT_DIV, ImuMpu6000Hmc5883::mpu, mpu60x0_spi_init(), and Mpu60x0Config::smplrt_div.
imu_mpu_hmc_periodic()
void imu_mpu_hmc_periodic (void)
Definition at line 136 of file imu_mpu6000_hmc5883.c.
References ImuMpu6000Hmc5883::hmc, hmc58xx_periodic(), imu_mpu_hmc, ImuMpu6000Hmc5883::mpu, and mpu60x0_spi_periodic().
Variable Documentation
imu_mpu_hmc
struct ImuMpu6000Hmc5883 imu_mpu_hmc
Definition at line 120 of file imu_mpu6000_hmc5883.c.
Referenced by imu_mpu_hmc_event(), imu_mpu_hmc_init(), and imu_mpu_hmc_periodic().