Paparazzi UAS: sw/airborne/subsystems/imu/imu_drotek_10dof_v2.h File Reference
imu_drotek_10dof_v2.h File Reference
#include "std.h"
#include "generated/airframe.h"
#include "subsystems/imu.h"
#include "peripherals/mpu60x0_i2c.h"
#include "peripherals/hmc58xx.h"
Data Structures
struct ImuDrotek2
Macros
#define DROTEK_2_GYRO_RANGE MPU60X0_GYRO_RANGE_1000
#define DROTEK_2_ACCEL_RANGE MPU60X0_ACCEL_RANGE_8G
#define IMU_GYRO_P_SENS MPU60X0_GYRO_SENS[DROTEK_2_GYRO_RANGE]
#define IMU_GYRO_P_SENS_NUM MPU60X0_GYRO_SENS_FRAC[DROTEK_2_GYRO_RANGE][0]
#define IMU_GYRO_P_SENS_DEN MPU60X0_GYRO_SENS_FRAC[DROTEK_2_GYRO_RANGE][1]
#define IMU_GYRO_Q_SENS MPU60X0_GYRO_SENS[DROTEK_2_GYRO_RANGE]
#define IMU_GYRO_Q_SENS_NUM MPU60X0_GYRO_SENS_FRAC[DROTEK_2_GYRO_RANGE][0]
#define IMU_GYRO_Q_SENS_DEN MPU60X0_GYRO_SENS_FRAC[DROTEK_2_GYRO_RANGE][1]
#define IMU_GYRO_R_SENS MPU60X0_GYRO_SENS[DROTEK_2_GYRO_RANGE]
#define IMU_GYRO_R_SENS_NUM MPU60X0_GYRO_SENS_FRAC[DROTEK_2_GYRO_RANGE][0]
#define IMU_GYRO_R_SENS_DEN MPU60X0_GYRO_SENS_FRAC[DROTEK_2_GYRO_RANGE][1]
#define IMU_ACCEL_X_SENS MPU60X0_ACCEL_SENS[DROTEK_2_ACCEL_RANGE]
#define IMU_ACCEL_X_SENS_NUM MPU60X0_ACCEL_SENS_FRAC[DROTEK_2_ACCEL_RANGE][0]
#define IMU_ACCEL_X_SENS_DEN MPU60X0_ACCEL_SENS_FRAC[DROTEK_2_ACCEL_RANGE][1]
#define IMU_ACCEL_Y_SENS MPU60X0_ACCEL_SENS[DROTEK_2_ACCEL_RANGE]
#define IMU_ACCEL_Y_SENS_NUM MPU60X0_ACCEL_SENS_FRAC[DROTEK_2_ACCEL_RANGE][0]
#define IMU_ACCEL_Y_SENS_DEN MPU60X0_ACCEL_SENS_FRAC[DROTEK_2_ACCEL_RANGE][1]
#define IMU_ACCEL_Z_SENS MPU60X0_ACCEL_SENS[DROTEK_2_ACCEL_RANGE]
#define IMU_ACCEL_Z_SENS_NUM MPU60X0_ACCEL_SENS_FRAC[DROTEK_2_ACCEL_RANGE][0]
#define IMU_ACCEL_Z_SENS_DEN MPU60X0_ACCEL_SENS_FRAC[DROTEK_2_ACCEL_RANGE][1]
Functions
void imu_drotek2_init (void)
void imu_drotek2_periodic (void)
void imu_drotek2_event (void)
bool imu_drotek2_configure_mag_slave (Mpu60x0ConfigSet mpu_set, void *mpu)
callback function to configure hmc5883 mag
Variables
struct ImuDrotek2 imu_drotek2
Detailed Description
Driver for the Drotek 10DOF V2 IMU. MPU6050 + HMC5883 + MS5611
Definition in file imu_drotek_10dof_v2.h.
Data Structure Documentation
ImuDrotek2
struct ImuDrotek2
Definition at line 75 of file imu_drotek_10dof_v2.h.
Data Fields
struct Hmc58xx hmc
struct Mpu60x0_I2c mpu
Macro Definition Documentation
DROTEK_2_ACCEL_RANGE
#define DROTEK_2_ACCEL_RANGE MPU60X0_ACCEL_RANGE_8G
Definition at line 44 of file imu_drotek_10dof_v2.h.
DROTEK_2_GYRO_RANGE
#define DROTEK_2_GYRO_RANGE MPU60X0_GYRO_RANGE_1000
Definition at line 40 of file imu_drotek_10dof_v2.h.
IMU_ACCEL_X_SENS
#define IMU_ACCEL_X_SENS MPU60X0_ACCEL_SENS[DROTEK_2_ACCEL_RANGE]
Definition at line 62 of file imu_drotek_10dof_v2.h.
IMU_ACCEL_X_SENS_DEN
#define IMU_ACCEL_X_SENS_DEN MPU60X0_ACCEL_SENS_FRAC[DROTEK_2_ACCEL_RANGE][1]
Definition at line 64 of file imu_drotek_10dof_v2.h.
IMU_ACCEL_X_SENS_NUM
#define IMU_ACCEL_X_SENS_NUM MPU60X0_ACCEL_SENS_FRAC[DROTEK_2_ACCEL_RANGE][0]
Definition at line 63 of file imu_drotek_10dof_v2.h.
IMU_ACCEL_Y_SENS
#define IMU_ACCEL_Y_SENS MPU60X0_ACCEL_SENS[DROTEK_2_ACCEL_RANGE]
Definition at line 65 of file imu_drotek_10dof_v2.h.
IMU_ACCEL_Y_SENS_DEN
#define IMU_ACCEL_Y_SENS_DEN MPU60X0_ACCEL_SENS_FRAC[DROTEK_2_ACCEL_RANGE][1]
Definition at line 67 of file imu_drotek_10dof_v2.h.
IMU_ACCEL_Y_SENS_NUM
#define IMU_ACCEL_Y_SENS_NUM MPU60X0_ACCEL_SENS_FRAC[DROTEK_2_ACCEL_RANGE][0]
Definition at line 66 of file imu_drotek_10dof_v2.h.
IMU_ACCEL_Z_SENS
#define IMU_ACCEL_Z_SENS MPU60X0_ACCEL_SENS[DROTEK_2_ACCEL_RANGE]
Definition at line 68 of file imu_drotek_10dof_v2.h.
IMU_ACCEL_Z_SENS_DEN
#define IMU_ACCEL_Z_SENS_DEN MPU60X0_ACCEL_SENS_FRAC[DROTEK_2_ACCEL_RANGE][1]
Definition at line 70 of file imu_drotek_10dof_v2.h.
IMU_ACCEL_Z_SENS_NUM
#define IMU_ACCEL_Z_SENS_NUM MPU60X0_ACCEL_SENS_FRAC[DROTEK_2_ACCEL_RANGE][0]
Definition at line 69 of file imu_drotek_10dof_v2.h.
IMU_GYRO_P_SENS
#define IMU_GYRO_P_SENS MPU60X0_GYRO_SENS[DROTEK_2_GYRO_RANGE]
Definition at line 49 of file imu_drotek_10dof_v2.h.
IMU_GYRO_P_SENS_DEN
#define IMU_GYRO_P_SENS_DEN MPU60X0_GYRO_SENS_FRAC[DROTEK_2_GYRO_RANGE][1]
Definition at line 51 of file imu_drotek_10dof_v2.h.
IMU_GYRO_P_SENS_NUM
#define IMU_GYRO_P_SENS_NUM MPU60X0_GYRO_SENS_FRAC[DROTEK_2_GYRO_RANGE][0]
Definition at line 50 of file imu_drotek_10dof_v2.h.
IMU_GYRO_Q_SENS
#define IMU_GYRO_Q_SENS MPU60X0_GYRO_SENS[DROTEK_2_GYRO_RANGE]
Definition at line 52 of file imu_drotek_10dof_v2.h.
IMU_GYRO_Q_SENS_DEN
#define IMU_GYRO_Q_SENS_DEN MPU60X0_GYRO_SENS_FRAC[DROTEK_2_GYRO_RANGE][1]
Definition at line 54 of file imu_drotek_10dof_v2.h.
IMU_GYRO_Q_SENS_NUM
#define IMU_GYRO_Q_SENS_NUM MPU60X0_GYRO_SENS_FRAC[DROTEK_2_GYRO_RANGE][0]
Definition at line 53 of file imu_drotek_10dof_v2.h.
IMU_GYRO_R_SENS
#define IMU_GYRO_R_SENS MPU60X0_GYRO_SENS[DROTEK_2_GYRO_RANGE]
Definition at line 55 of file imu_drotek_10dof_v2.h.
IMU_GYRO_R_SENS_DEN
#define IMU_GYRO_R_SENS_DEN MPU60X0_GYRO_SENS_FRAC[DROTEK_2_GYRO_RANGE][1]
Definition at line 57 of file imu_drotek_10dof_v2.h.
IMU_GYRO_R_SENS_NUM
#define IMU_GYRO_R_SENS_NUM MPU60X0_GYRO_SENS_FRAC[DROTEK_2_GYRO_RANGE][0]
Definition at line 56 of file imu_drotek_10dof_v2.h.
Function Documentation
imu_drotek2_configure_mag_slave()
bool imu_drotek2_configure_mag_slave (Mpu60x0ConfigSet mpu_set, void * mpu)
callback function to configure hmc5883 mag
Returns
TRUE if mag configuration finished
Definition at line 158 of file imu_drotek_10dof_v2.c.
References ImuDrotek2::hmc, hmc58xx_start_configure(), imu_drotek2, and Hmc58xx::initialized.
Referenced by imu_drotek2_init().
imu_drotek2_event()
void imu_drotek2_event (void)
Definition at line 110 of file imu_drotek_10dof_v2.c.
References Imu::accel, Imu::accel_unscaled, Hmc58xx::data, Mpu60x0_I2c::data_accel, Mpu60x0_I2c::data_available, Hmc58xx::data_available, Mpu60x0_I2c::data_rates, get_sys_time_usec(), Imu::gyro, Imu::gyro_unscaled, ImuDrotek2::hmc, hmc58xx_event(), imu, imu_drotek2, IMU_DROTEK_ID, imu_scale_accel(), imu_scale_gyro(), imu_scale_mag(), Imu::mag, Imu::mag_unscaled, ImuDrotek2::mpu, mpu60x0_i2c_event(), Int32Rates::p, Int32Rates::q, Int32Rates::r, RATES_COPY, VECT3_COPY, Int32Vect3::x, Int32Vect3::y, and Int32Vect3::z.
imu_drotek2_init()
void imu_drotek2_init (void)
Definition at line 75 of file imu_drotek_10dof_v2.c.
References Mpu60x0Config::accel_range, Mpu60x0_I2c::config, Mpu60x0I2cSlave::configure, Mpu60x0Config::dlpf_cfg, DROTEK_2_ACCEL_RANGE, DROTEK_2_GYRO_RANGE, DROTEK_2_HMC_I2C_ADDR, DROTEK_2_MPU_I2C_ADDR, Mpu60x0Config::gyro_range, ImuDrotek2::hmc, hmc58xx_init(), Mpu60x0Config::i2c_bypass, imu_drotek2, imu_drotek2_configure_mag_slave(), ImuDrotek2::mpu, mpu60x0_i2c_init(), Mpu60x0Config::nb_slaves, Mpu60x0Config::slaves, and Mpu60x0Config::smplrt_div.
imu_drotek2_periodic()
void imu_drotek2_periodic (void)
Definition at line 99 of file imu_drotek_10dof_v2.c.
References Mpu60x0_I2c::config, ImuDrotek2::hmc, hmc58xx_read(), imu_drotek2, Mpu60x0Config::initialized, ImuDrotek2::mpu, and mpu60x0_i2c_periodic().
Variable Documentation
imu_drotek2
struct ImuDrotek2 imu_drotek2
Definition at line 73 of file imu_drotek_10dof_v2.c.
Referenced by imu_drotek2_configure_mag_slave(), imu_drotek2_event(), imu_drotek2_init(), and imu_drotek2_periodic().