Paparazzi UAS: sw/airborne/boards/navgo/imu_navgo.h File Reference
imu_navgo.h File Reference
#include "std.h"
#include "generated/airframe.h"
#include "subsystems/imu.h"
#include "peripherals/itg3200.h"
#include "peripherals/adxl345_i2c.h"
#include "peripherals/hmc58xx.h"
Data Structures
struct ImuNavgo
Macros
#define IMU_GYRO_P_SIGN 1
#define IMU_GYRO_Q_SIGN 1
#define IMU_GYRO_R_SIGN 1
#define IMU_ACCEL_X_SIGN 1
#define IMU_ACCEL_Y_SIGN 1
#define IMU_ACCEL_Z_SIGN 1
#define IMU_MAG_X_SIGN 1
#define IMU_MAG_Y_SIGN 1
#define IMU_MAG_Z_SIGN 1
Functions
void imu_navgo_init (void)
void imu_navgo_periodic (void)
void imu_navgo_event (void)
void imu_navgo_downlink_raw (void)
Variables
struct ImuNavgo imu_navgo
Detailed Description
Interface for the IMU on the NavGo board.
Gyroscope: Invensense ITG-3200
Accelerometer: Analog Devices ADXL345
Magnetometer: Honeywell HMC5883L
Interface for the IMU on the Umarim board.
Gyroscope: Invensense ITG-3200
Accelerometer: Analog Devices ADXL345
Definition in file imu_navgo.h.
Data Structure Documentation
ImuNavgo
struct ImuNavgo
Definition at line 62 of file imu_navgo.h.
Data Fields
struct Adxl345_I2c adxl
struct Hmc58xx hmc
struct Itg3200 itg
Macro Definition Documentation
IMU_ACCEL_X_SIGN
#define IMU_ACCEL_X_SIGN 1
Definition at line 51 of file imu_navgo.h.
IMU_ACCEL_Y_SIGN
#define IMU_ACCEL_Y_SIGN 1
Definition at line 52 of file imu_navgo.h.
IMU_ACCEL_Z_SIGN
#define IMU_ACCEL_Z_SIGN 1
Definition at line 53 of file imu_navgo.h.
IMU_GYRO_P_SIGN
#define IMU_GYRO_P_SIGN 1
Definition at line 46 of file imu_navgo.h.
IMU_GYRO_Q_SIGN
#define IMU_GYRO_Q_SIGN 1
Definition at line 47 of file imu_navgo.h.
IMU_GYRO_R_SIGN
#define IMU_GYRO_R_SIGN 1
Definition at line 48 of file imu_navgo.h.
IMU_MAG_X_SIGN
#define IMU_MAG_X_SIGN 1
Definition at line 56 of file imu_navgo.h.
IMU_MAG_Y_SIGN
#define IMU_MAG_Y_SIGN 1
Definition at line 57 of file imu_navgo.h.
IMU_MAG_Z_SIGN
#define IMU_MAG_Z_SIGN 1
Definition at line 58 of file imu_navgo.h.
Function Documentation
imu_navgo_downlink_raw()
void imu_navgo_downlink_raw (void)
Definition at line 111 of file imu_navgo.c.
References Imu::accel_unscaled, DefaultChannel, DefaultDevice, Imu::gyro_unscaled, imu, Imu::mag_unscaled, Int32Rates::p, Int32Rates::q, Int32Rates::r, Int32Vect3::x, Int32Vect3::y, and Int32Vect3::z.
imu_navgo_event()
void imu_navgo_event (void)
Definition at line 120 of file imu_navgo.c.
References Imu::accel, Imu::accel_unscaled, ImuNavgo::adxl, adxl345_i2c_event(), Adxl345_I2c::data, Hmc58xx::data, Itg3200::data, Adxl345_I2c::data_available, Hmc58xx::data_available, Itg3200::data_available, get_sys_time_usec(), Imu::gyro, Imu::gyro_unscaled, ImuNavgo::hmc, hmc58xx_event(), imu, IMU_BOARD_ID, imu_navgo, imu_scale_accel(), imu_scale_gyro(), imu_scale_mag(), ImuNavgo::itg, itg3200_event(), Imu::mag, Imu::mag_unscaled, median_mag, RATES_ASSIGN, UpdateMedianFilterRatesInt, UpdateMedianFilterVect3Int, VECT3_ASSIGN, and VECT3_COPY.
imu_navgo_init()
void imu_navgo_init (void)
Definition at line 66 of file imu_navgo.c.
References ImuNavgo::adxl, ADXL345_ADDR_ALT, adxl345_i2c_init(), Adxl345_I2c::config, Itg3200::config, Itg3200Config::dlpf_cfg, ImuNavgo::hmc, HMC58XX_ADDR, hmc58xx_init(), imu_navgo, InitMedianFilterRatesInt, InitMedianFilterVect3Int, ImuNavgo::itg, ITG3200_ADDR_ALT, itg3200_init(), MEDIAN_DEFAULT_SIZE, median_mag, NAVGO_ACCEL_RATE, NAVGO_GYRO_LOWPASS, NAVGO_GYRO_SMPLRT_DIV, Adxl345Config::rate, and Itg3200Config::smplrt_div.
imu_navgo_periodic()
void imu_navgo_periodic (void)
Definition at line 93 of file imu_navgo.c.
References ImuNavgo::adxl, adxl345_i2c_periodic(), ImuNavgo::hmc, hmc58xx_periodic(), imu_navgo, ImuNavgo::itg, itg3200_periodic(), and NAVGO_ACCEL_RATE.
Variable Documentation
imu_navgo
struct ImuNavgo imu_navgo
Definition at line 64 of file imu_navgo.c.
Referenced by imu_navgo_event(), imu_navgo_init(), and imu_navgo_periodic().