Paparazzi UAS: sw/airborne/subsystems/ins.h File Reference
ins.h File Reference
#include "std.h"
#include "math/pprz_geodetic_int.h"
#include "math/pprz_algebra_float.h"
#include "state.h"
Functions
void ins_reset_local_origin (void)
INS local origin reset.
void ins_reset_altitude_ref (void)
INS altitude reference reset.
void ins_reset_utm_zone (struct UtmCoor_f *utm)
INS utm zone reset.
void ins_init_origin_i_from_flightplan (struct LtpDef_i *ltp_def)
initialize the local origin (ltp_def in fixed point) from flight plan position
Detailed Description
Integrated Navigation System interface.
Definition in file ins.h.
Function Documentation
ins_init_origin_i_from_flightplan()
void ins_init_origin_i_from_flightplan (struct LtpDef_i * ltp_def)
initialize the local origin (ltp_def in fixed point) from flight plan position
Definition at line 39 of file ins.c.
References LlaCoor_i::alt, LtpDef_i::hmsl, LlaCoor_i::lat, LlaCoor_i::lon, ltp_def, ltp_def_from_lla_i(), and stateSetLocalOrigin_i().
Referenced by ins_int_init(), ins_module_wrapper_init(), and ins_vectornav_init().
ins_reset_altitude_ref()
void ins_reset_altitude_ref (void)
INS altitude reference reset.
Reset only vertical reference to the current altitude. Does nothing if not implemented by specific INS algorithm.
Definition at line 649 of file ins_mekf_wind_wrapper.c.
References LlaCoor_i::alt, UtmCoor_f::alt, gps, GpsFixValid, GpsState::hmsl, LtpDef_i::hmsl, ins_altf, ins_gp, ins_int, LlaCoor_i::lat, LtpDef_i::lla, GpsState::lla_pos, LlaCoor_i::lon, ltp_def, InsInt::ltp_def, InsGpsPassthrough::ltp_def, ltp_def_from_lla_i(), State::ned_origin_i, InsAltFloat::reset_alt_ref, state, stateSetLocalOrigin_i(), stateSetLocalUtmOrigin_f(), State::utm_origin_f, and InsInt::vf_reset.
Referenced by nav_reset_alt().
ins_reset_local_origin()
void ins_reset_local_origin (void)
INS local origin reset.
Reset horizontal and vertical reference to the current position. Does nothing if not implemented by specific INS algorithm.
INS local origin reset.
Definition at line 633 of file ins_mekf_wind_wrapper.c.
References LlaCoor_i::alt, GpsState::ecef_pos, GpsState::fix, gps, InsModuleInt::gps, GPS_FIX_3D, GpsFixValid, InsInt::hf_realign, GpsState::hmsl, LtpDef_i::hmsl, ins_altf, ins_gp, ins_int, ins_mekf_wind_wrapper_Reset, ins_module, ins_module_reset_local_origin(), LtpDef_i::lla, GpsState::lla_pos, ltp_def, InsModuleInt::ltp_def, InsInt::ltp_def, InsGpsPassthrough::ltp_def, ltp_def_from_ecef_i(), InsInt::ltp_initialized, InsModuleInt::ltp_initialized, InsGpsPassthrough::ltp_initialized, InsAltFloat::origin_initialized, InsAltFloat::reset_alt_ref, stateSetLocalOrigin_i(), stateSetLocalUtmOrigin_f(), utm_float_from_gps(), and InsInt::vf_reset.
Referenced by gps_cb(), ins_alt_float_update_gps(), ins_int_update_gps(), and nav_reset_reference().
ins_reset_utm_zone()
void ins_reset_utm_zone (struct UtmCoor_f * utm)
INS utm zone reset.
Reset UTM zone according the the actual position. Only used with fixedwing firmware. Can be overwritte by specifc INS implementation.
Parameters
utm initial utm zone, returns the corrected utm position
Definition at line 68 of file ins.c.
References gps, GPS_VALID_POS_UTM_BIT, lla_of_utm_f(), stateSetLocalUtmOrigin_f(), utm_of_lla_f(), GpsState::utm_pos, GpsState::valid_fields, UtmCoor_f::zone, and UtmCoor_i::zone.
Referenced by nav_reset_utm_zone().