Paparazzi UAS: sw/airborne/subsystems/ins.c File Reference
ins.c File Reference
#include "subsystems/ins.h"
#include "subsystems/gps.h"
#include "state.h"
#include "generated/flight_plan.h"
Functions
void ins_init_origin_i_from_flightplan (struct LtpDef_i *ltp_def)
initialize the local origin (ltp_def in fixed point) from flight plan position
void WEAK ins_reset_local_origin (void)
INS local origin reset.
void WEAK ins_reset_altitude_ref (void)
INS altitude reference reset.
void WEAK ins_reset_utm_zone (struct UtmCoor_f *utm)
INS utm zone reset.
Detailed Description
Integrated Navigation System interface.
Definition in file ins.c.
Function Documentation
ins_init_origin_i_from_flightplan()
void ins_init_origin_i_from_flightplan (struct LtpDef_i * ltp_def)
initialize the local origin (ltp_def in fixed point) from flight plan position
Definition at line 39 of file ins.c.
References LlaCoor_i::alt, LtpDef_i::hmsl, LlaCoor_i::lat, LlaCoor_i::lon, ltp_def, ltp_def_from_lla_i(), and stateSetLocalOrigin_i().
Referenced by ins_int_init(), ins_module_wrapper_init(), and ins_vectornav_init().
ins_reset_altitude_ref()
void WEAK ins_reset_altitude_ref (void)
INS altitude reference reset.
Reset only vertical reference to the current altitude. Does nothing if not implemented by specific INS algorithm.
Definition at line 65 of file ins.c.
References LlaCoor_i::alt, UtmCoor_f::alt, gps, GpsState::hmsl, LtpDef_i::hmsl, LlaCoor_i::lat, LtpDef_i::lla, GpsState::lla_pos, LlaCoor_i::lon, ltp_def, ltp_def_from_lla_i(), State::ned_origin_i, state, stateSetLocalOrigin_i(), stateSetLocalUtmOrigin_f(), and State::utm_origin_f.
ins_reset_local_origin()
void WEAK ins_reset_local_origin (void)
INS local origin reset.
Reset horizontal and vertical reference to the current position. Does nothing if not implemented by specific INS algorithm.
INS local origin reset.
Definition at line 55 of file ins.c.
References GpsState::ecef_pos, gps, GpsState::hmsl, LtpDef_i::hmsl, ins_mekf_wind_wrapper_Reset, ltp_def, ltp_def_from_ecef_i(), stateSetLocalOrigin_i(), stateSetLocalUtmOrigin_f(), and utm_float_from_gps().
ins_reset_utm_zone()
void WEAK ins_reset_utm_zone (struct UtmCoor_f * utm)
INS utm zone reset.
Reset UTM zone according the the actual position. Only used with fixedwing firmware. Can be overwritte by specifc INS implementation.
Parameters
utm initial utm zone, returns the corrected utm position
Definition at line 68 of file ins.c.
References gps, GPS_VALID_POS_UTM_BIT, lla_of_utm_f(), stateSetLocalUtmOrigin_f(), utm_of_lla_f(), GpsState::utm_pos, GpsState::valid_fields, UtmCoor_f::zone, and UtmCoor_i::zone.
Referenced by nav_reset_utm_zone().