Paparazzi UAS: sw/airborne/subsystems/ins/ins_gps_passthrough_utm.c File Reference
ins_gps_passthrough_utm.c File Reference
#include "subsystems/ins/ins_gps_passthrough.h"
#include "subsystems/ins.h"
#include <inttypes.h>
#include <math.h>
#include "state.h"
#include "subsystems/gps.h"
#include "firmwares/fixedwing/nav.h"
#include "subsystems/abi.h"
Macros
#define INS_PT_GPS_ID GPS_MULTI_ID
ABI binding for gps data.
Functions
static void gps_cb (uint8_t sender_id, uint32_t stamp, struct GpsState *gps_s)
void ins_gps_passthrough_init (void)
void ins_reset_local_origin (void)
INS local origin reset.
void ins_reset_altitude_ref (void)
INS altitude reference reset.
Variables
static abi_event gps_ev
Detailed Description
Simply passes GPS UTM position and velocity through to the state interface. For fixedwing firmware since it sets UTM pos only.
Definition in file ins_gps_passthrough_utm.c.
Macro Definition Documentation
INS_PT_GPS_ID
#define INS_PT_GPS_ID GPS_MULTI_ID
ABI binding for gps data.
Used for GPS ABI messages.
Definition at line 45 of file ins_gps_passthrough_utm.c.
Function Documentation
gps_cb()
static void gps_cb (uint8_t sender_id, uint32_t stamp, struct GpsState * gps_s) static
Definition at line 50 of file ins_gps_passthrough_utm.c.
References nav_utm_zone0, stateSetPositionUtm_f(), stateSetSpeedNed_f(), utm_float_from_gps(), and NedCoor_f::x.
Referenced by ins_gps_passthrough_init().
ins_gps_passthrough_init()
void ins_gps_passthrough_init (void)
Definition at line 69 of file ins_gps_passthrough_utm.c.
References accel_cb(), accel_ev, LlaCoor_i::alt, body_to_imu_cb(), body_to_imu_ev, DefaultPeriodic, ecef_of_lla_i(), gps_cb(), gps_ev, LtpDef_i::hmsl, ins_gp, INS_PT_GPS_ID, INS_PT_IMU_ID, INT32_VECT3_ZERO, LlaCoor_i::lat, LlaCoor_i::lon, InsGpsPassthrough::ltp_accel, InsGpsPassthrough::ltp_def, ltp_def_from_ecef_i(), InsGpsPassthrough::ltp_initialized, InsGpsPassthrough::ltp_pos, InsGpsPassthrough::ltp_speed, nav_utm_east0, nav_utm_north0, nav_utm_zone0, register_periodic_telemetry(), send_ins(), send_ins_ref(), send_ins_z(), stateSetLocalOrigin_i(), stateSetLocalUtmOrigin_f(), and stateSetPositionUtm_f().
ins_reset_altitude_ref()
void ins_reset_altitude_ref (void)
INS altitude reference reset.
Reset only vertical reference to the current altitude. Does nothing if not implemented by specific INS algorithm.
Definition at line 86 of file ins_gps_passthrough_utm.c.
References UtmCoor_f::alt, gps, GpsState::hmsl, state, stateSetLocalUtmOrigin_f(), and State::utm_origin_f.
ins_reset_local_origin()
void ins_reset_local_origin (void)
INS local origin reset.
Reset horizontal and vertical reference to the current position. Does nothing if not implemented by specific INS algorithm.
INS local origin reset.
Definition at line 78 of file ins_gps_passthrough_utm.c.
References gps, stateSetLocalUtmOrigin_f(), and utm_float_from_gps().
Variable Documentation
gps_ev
abi_event gps_ev static
Definition at line 48 of file ins_gps_passthrough_utm.c.
Referenced by ins_gps_passthrough_init().