Paparazzi UAS: sw/airborne/subsystems/intermcu/intermcu_ap.h File Reference
intermcu_ap.h File Reference
Rotorcraft Inter-MCU on the autopilot.
#include "subsystems/intermcu.h"
#include "generated/airframe.h"
#include "subsystems/electrical.h"
Data Structures
struct fbw_status_t
Macros
#define RADIO_THROTTLE 0
#define RADIO_ROLL 1
#define RADIO_PITCH 2
#define RADIO_YAW 3
#define RADIO_MODE 4
#define RADIO_KILL_SWITCH 5
#define RADIO_AUX1 5
#define RADIO_AUX2 6
#define RADIO_AUX3 7
#define RADIO_CONTROL_NB_CHANNEL 8
Functions
void intermcu_set_actuators (pprz_t *command_values, uint8_t ap_mode)
void RadioControlEvent (void(*frame_handler)(void))
void intermcu_send_spektrum_bind (void)
void intermcu_set_enabled (bool value)
Detailed Description
Rotorcraft Inter-MCU on the autopilot.
Definition in file intermcu_ap.h.
Data Structure Documentation
fbw_status_t
struct fbw_status_t
Definition at line 52 of file intermcu_ap.h.
Data Fields
struct Electrical electrical
uint8_t frame_rate
uint8_t mode
uint8_t rc_status
Macro Definition Documentation
RADIO_AUX1
#define RADIO_AUX1 5
Definition at line 46 of file intermcu_ap.h.
RADIO_AUX2
#define RADIO_AUX2 6
Definition at line 47 of file intermcu_ap.h.
RADIO_AUX3
#define RADIO_AUX3 7
Definition at line 48 of file intermcu_ap.h.
RADIO_CONTROL_NB_CHANNEL
#define RADIO_CONTROL_NB_CHANNEL 8
Definition at line 49 of file intermcu_ap.h.
RADIO_KILL_SWITCH
#define RADIO_KILL_SWITCH 5
Definition at line 45 of file intermcu_ap.h.
RADIO_MODE
#define RADIO_MODE 4
Definition at line 44 of file intermcu_ap.h.
RADIO_PITCH
#define RADIO_PITCH 2
Definition at line 42 of file intermcu_ap.h.
RADIO_ROLL
#define RADIO_ROLL 1
Definition at line 41 of file intermcu_ap.h.
RADIO_THROTTLE
#define RADIO_THROTTLE 0
Definition at line 40 of file intermcu_ap.h.
RADIO_YAW
#define RADIO_YAW 3
Definition at line 43 of file intermcu_ap.h.
Function Documentation
intermcu_send_spektrum_bind()
void intermcu_send_spektrum_bind (void)
Definition at line 129 of file intermcu_ap.c.
References intermcu_t::device, intermcu_t::enabled, intermcu, INTERMCU_AP, and intermcu_t::transport.
Referenced by spektrum_soft_bind_click().
intermcu_set_actuators()
void intermcu_set_actuators (pprz_t * command_values, uint8_t ap_mode)
Definition at line 111 of file intermcu_ap.c.
References autopilot_get_motors_on(), intermcu_t::cmd_status, intermcu_t::device, intermcu_t::enabled, intermcu, INTERMCU_AP, INTERMCU_CMD_MOTORS_ON, INTERMCU_SET_CMD_STATUS, and intermcu_t::transport.
Referenced by main_periodic().
intermcu_set_enabled()
void intermcu_set_enabled (bool value)
Definition at line 105 of file intermcu_ap.c.
References intermcu_t::enabled, and intermcu.
Referenced by px4flash_event().
RadioControlEvent()
void RadioControlEvent (void(*)(void) frame_handler)
Definition at line 231 of file intermcu_ap.c.
References intermcu_t::device, intermcu_t::enabled, imcu_msg_buf, intermcu, intermcu_parse_msg(), intermcu_t::msg_available, and intermcu_t::transport.