Paparazzi UAS: sw/airborne/peripherals/ist8310.c File Reference
ist8310.c File Reference
#include "peripherals/ist8310.h"
#include "std.h"
Macros
#define Int16FromBuf(_buf, _idx) ((int16_t)(_buf[_idx] | (_buf[_idx+1] << 8)))
Functions
void ist8310_init (struct IST8310 *ist, struct i2c_periph *i2c_p, uint8_t addr)
Initialize IST8310 struct.
void ist8310_configure (struct IST8310 *ist)
void ist8310_read (struct IST8310 *ist)
void ist8310_event (struct IST8310 *ist)
Detailed Description
Driver for the Isentek IST8310 magnetometer.
Definition in file ist8310.c.
Macro Definition Documentation
Int16FromBuf
#define Int16FromBuf (_buf, _idx) ((int16_t)(_buf[_idx] | (_buf[_idx+1] << 8)))
Definition at line 110 of file ist8310.c.
Function Documentation
ist8310_configure()
void ist8310_configure (struct IST8310 * ist)
Definition at line 46 of file ist8310.c.
References i2c_transaction::buf, IST8310::i2c_p, IST8310::i2c_trans, i2c_transmit(), I2CTransDone, I2CTransFailed, I2CTransSuccess, IST8310::init_status, IST8310::initialized, IST8310_CNTL1_ODR_SINGLE, IST8310_CNTL3_SAMPAVG_16, IST8310_CNTL4_SRPD, IST8310_REG_CNTL1, IST8310_REG_CNTL3, IST8310_REG_CNTL4, IST_CONF_CNTL1, IST_CONF_CNTL3, IST_CONF_CNTL4, IST_CONF_UNINIT, i2c_transaction::slave_addr, and i2c_transaction::status.
Referenced by ist8310_periodic().
ist8310_event()
void ist8310_event (struct IST8310 * ist)
Definition at line 111 of file ist8310.c.
References i2c_transaction::buf, IST8310::data, IST8310::data_available, IST8310::i2c_p, IST8310::i2c_trans, i2c_transceive(), I2CTransDone, I2CTransFailed, I2CTransSuccess, IST8310::initialized, Int16FromBuf, IST8310_REG_DATA_XL, IST_STATUS_IDLE, IST_STATUS_READ, i2c_transaction::slave_addr, IST8310::status, and i2c_transaction::status.
Referenced by mag_ist8310_module_event().
ist8310_init()
void ist8310_init (struct IST8310 * ist, struct i2c_periph * i2c_p, uint8_t addr)
Initialize IST8310 struct.
Definition at line 34 of file ist8310.c.
References IST8310::data_available, IST8310::i2c_p, IST8310::i2c_trans, I2CTransDone, IST8310::init_status, IST8310::initialized, IST_CONF_UNINIT, i2c_transaction::slave_addr, and i2c_transaction::status.
Referenced by mag_ist8310_module_init().
ist8310_read()
void ist8310_read (struct IST8310 * ist)
Definition at line 98 of file ist8310.c.
References i2c_transaction::buf, IST8310::i2c_p, IST8310::i2c_trans, i2c_transceive(), IST8310_CNTL1_ODR_SINGLE, IST8310_REG_CNTL1, IST_STATUS_IDLE, i2c_transaction::slave_addr, and IST8310::status.
Referenced by ist8310_periodic().