Paparazzi UAS: sw/airborne/arch/lpc21/modules/display/lcd_dogm_hw.h File Reference
lcd_dogm_hw.h File Reference
#include <stdbool.h>
#include "std.h"
#include "mcu_periph/spi.h"
#include "led.h"
Macros
#define LCDDOGM_SS_PORT 0
#define LCDDOGM_SS_PIN 20
#define LCDDOGM_RS_PORT 0
#define LCDDOGM_RS_PIN 16
#define LCDDOGM_IO__(port, reg) IO ## port ## reg
#define LCDDOGM_IO_(port, reg) LCDDOGM_IO__(port, reg)
#define LCDDOGM_SS_IOCLR LCDDOGM_IO_(LCDDOGM_SS_PORT, CLR)
#define LCDDOGM_SS_IODIR LCDDOGM_IO_(LCDDOGM_SS_PORT, DIR)
#define LCDDOGM_SS_IOSET LCDDOGM_IO_(LCDDOGM_SS_PORT, SET)
#define LCDDOGM_RS_IOCLR LCDDOGM_IO_(LCDDOGM_RS_PORT, CLR)
#define LCDDOGM_RS_IODIR LCDDOGM_IO_(LCDDOGM_RS_PORT, DIR)
#define LCDDOGM_RS_IOSET LCDDOGM_IO_(LCDDOGM_RS_PORT, SET)
#define lcddogmSelect()
#define lcddogmUnselect()
#define lcddogmCmdMode()
#define lcddogmDataMode()
Functions
void lcd_spi_tx (uint8_t data)
void lcd_dogm_init_hw (void)
Macro Definition Documentation
LCDDOGM_IO_
#define LCDDOGM_IO_ (port, reg) LCDDOGM_IO__(port, reg)
Definition at line 17 of file lcd_dogm_hw.h.
LCDDOGM_IO__
#define LCDDOGM_IO__ (port, reg) IO ## port ## reg
Definition at line 16 of file lcd_dogm_hw.h.
LCDDOGM_RS_IOCLR
#define LCDDOGM_RS_IOCLR LCDDOGM_IO_(LCDDOGM_RS_PORT, CLR)
Definition at line 23 of file lcd_dogm_hw.h.
LCDDOGM_RS_IODIR
#define LCDDOGM_RS_IODIR LCDDOGM_IO_(LCDDOGM_RS_PORT, DIR)
Definition at line 24 of file lcd_dogm_hw.h.
LCDDOGM_RS_IOSET
#define LCDDOGM_RS_IOSET LCDDOGM_IO_(LCDDOGM_RS_PORT, SET)
Definition at line 25 of file lcd_dogm_hw.h.
LCDDOGM_RS_PIN
#define LCDDOGM_RS_PIN 16
Definition at line 14 of file lcd_dogm_hw.h.
LCDDOGM_RS_PORT
#define LCDDOGM_RS_PORT 0
Definition at line 13 of file lcd_dogm_hw.h.
LCDDOGM_SS_IOCLR
#define LCDDOGM_SS_IOCLR LCDDOGM_IO_(LCDDOGM_SS_PORT, CLR)
Definition at line 19 of file lcd_dogm_hw.h.
LCDDOGM_SS_IODIR
#define LCDDOGM_SS_IODIR LCDDOGM_IO_(LCDDOGM_SS_PORT, DIR)
Definition at line 20 of file lcd_dogm_hw.h.
LCDDOGM_SS_IOSET
#define LCDDOGM_SS_IOSET LCDDOGM_IO_(LCDDOGM_SS_PORT, SET)
Definition at line 21 of file lcd_dogm_hw.h.
LCDDOGM_SS_PIN
#define LCDDOGM_SS_PIN 20
Definition at line 11 of file lcd_dogm_hw.h.
LCDDOGM_SS_PORT
#define LCDDOGM_SS_PORT 0
Definition at line 10 of file lcd_dogm_hw.h.
lcddogmCmdMode
#define lcddogmCmdMode ()
Value:
    {  \
    SetBit(LCDDOGM_RS_IOCLR, LCDDOGM_RS_PIN); \
  }
Definition at line 35 of file lcd_dogm_hw.h.
lcddogmDataMode
#define lcddogmDataMode ()
Value:
    { \
    SetBit(LCDDOGM_RS_IOSET, LCDDOGM_RS_PIN); \
  }
Definition at line 39 of file lcd_dogm_hw.h.
lcddogmSelect
#define lcddogmSelect ()
Value:
    { \
    SetBit(LCDDOGM_SS_IOCLR, LCDDOGM_SS_PIN); \
  }
Definition at line 27 of file lcd_dogm_hw.h.
lcddogmUnselect
#define lcddogmUnselect ()
Value:
    { \
    SetBit(LCDDOGM_SS_IOSET, LCDDOGM_SS_PIN); \
  }
Definition at line 31 of file lcd_dogm_hw.h.
Function Documentation
lcd_dogm_init_hw()
void lcd_dogm_init_hw (void)
Definition at line 65 of file lcd_dogm_hw.c.
References _VIC_CNTL, LCDDOGM_RS_IODIR, LCDDOGM_RS_PIN, LCDDOGM_SS_IODIR, LCDDOGM_SS_PIN, lcddogmUnselect, PINSEL1, PINSEL1_MOSI, PINSEL1_SCK, SPI1_ISR(), SPI1_VIC_SLOT, SSP_CPHA, SSP_CPOL, SSP_DSS, SSP_FRF, SSP_LBM, SSP_MS, SSP_SCR, SSP_SOD, SSPCPSR, SSPCPSR_VAL, SSPCR0, SSPCR1, VIC_BIT, VIC_ENABLE, VIC_SPI1, VICIntEnable, and VICIntSelect.
Referenced by lcd_dogm_init().
lcd_spi_tx()
void lcd_spi_tx (uint8_t data)
Definition at line 57 of file lcd_dogm_hw.c.
References SpiClearRti(), SpiEnable, SpiEnableRti(), and SSPDR.
Referenced by lcd_cmd(), and lcd_data().