Paparazzi UAS: sw/airborne/arch/linux/mcu_periph/sys_time_arch.h File Reference
sys_time_arch.h File Reference
#include "std.h"
#include <unistd.h>
Functions
uint32_t get_sys_time_usec (void)
Get the time in microseconds since startup.
uint32_t get_sys_time_msec (void)
Get the time in milliseconds since startup.
static void sys_time_usleep (uint32_t us)
static unsigned int sys_time_elapsed_us (struct timespec *prev, struct timespec *now)
elapsed time in microsecs between two timespecs
Detailed Description
linux timing functions
Definition in file sys_time_arch.h.
Function Documentation
get_sys_time_msec()
uint32_t get_sys_time_msec (void)
Get the time in milliseconds since startup.
Returns
milliseconds since startup as uint32_t
Definition at line 78 of file sys_time_arch.c.
References msec_of_sys_time_ticks(), sys_time::nb_sec, sys_time::nb_sec_rem, sys_time::nb_tick, and startup_time.
Referenced by ak8975_event(), ak8975_read(), bf_millis(), collective_tracking_control(), dc_ctrl_parrot_mykonos_command(), dc_ctrl_parrot_mykonos_periodic(), distributed_circular(), gps_piksi_event(), gvf_control_2D(), gvf_parametric_control_2D(), gvf_parametric_control_3D(), hackhd_command(), hackhd_periodic(), init_random(), mavlink_send_attitude(), mavlink_send_attitude_quaternion(), mavlink_send_global_position_int(), mavlink_send_highres_imu(), mavlink_send_local_position_ned(), mavlink_send_rc_channels(), mavlink_send_set_mode(), mavlink_send_system_time(), parseThetaTable(), periodic_2Hz_openlog(), sbp_pos_ecef_callback(), sbus_common_decode_event(), send_bluegiga(), send_circle(), send_circle_parametric(), send_downlink(), send_gvf(), send_gvf_parametric(), send_segment(), spb_heartbeat_callback(), spektrum_init_sat(), spektrum_uart_check(), tunnel_event(), and wind_estimator_periodic().
get_sys_time_usec()
uint32_t get_sys_time_usec (void)
Get the time in microseconds since startup.
WARNING: overflows after 71min34seconds!
Returns
current system time as uint32_t
WARNING: overflows after 70min!
Returns
microseconds since startup as uint32_t
Definition at line 68 of file sys_time_arch.c.
References sys_time::nb_sec, sys_time::nb_sec_rem, sys_time::nb_tick, startup_time, and usec_of_sys_time_ticks().
Referenced by ahrs_aligner_run(), ahrs_gx3_publish_imu(), ahrs_vectornav_event(), apogee_baro_event(), ardrone_baro_event(), baro_amsys_read_event(), baro_bmp280_event(), baro_bmp3_event(), baro_bmp_event(), baro_ets_read_event(), baro_event(), baro_hca_read_event(), baro_mpl3115_read_event(), baro_MS5534A_event(), baro_ms5611_event(), baro_periodic(), baro_scp_event(), baro_sim_periodic(), bf_micros(), bmp_baro_event(), decode_optical_flow_msg(), gps_cb(), gps_feed_value(), gps_mtk_msg(), gps_piksi_publish(), gps_sim_hitl_event(), gps_sim_publish(), gps_sirf_msg(), gps_skytraq_msg(), gps_ubx_msg(), gps_udp_parse(), handle_ins_msg(), hott_periodic_event(), imu_analog_periodic(), imu_apogee_event(), imu_aspirin2_event(), imu_aspirin_event(), imu_aspirin_i2c_event(), imu_b2_event(), imu_bebop_event(), imu_bmi088_event(), imu_disco_event(), imu_drotek2_event(), imu_gl1_event(), imu_hbmini_event(), imu_krooz_event(), imu_krooz_periodic(), imu_mpu9250_event(), imu_mpu_hmc_event(), imu_mpu_i2c_event(), imu_mpu_spi_event(), imu_navgo_event(), imu_navstik_event(), imu_nps_event(), imu_ppzuav_event(), imu_px4_event(), imu_px4fmu_event(), imu_swing_event(), imu_um6_publish(), imu_umarim_event(), ins_alt_float_update_baro(), ins_alt_float_update_gps(), intermcu_parse_msg(), laser_range_array_parse_msg(), lidar_lite_periodic(), lidar_sf11_periodic(), lisa_l_baro_event(), mag_hmc58xx_module_event(), mag_ist8310_module_event(), mag_lis3mdl_module_event(), mag_pitot_parse_msg(), main(), mateksys3901l0x_parse(), mavlink_send_gps_raw_int(), meteo_stick_event(), navdata_publish_imu(), navdata_update(), navgo_baro_event(), nmea_gps_msg(), nps_autopilot_run_step(), opticflow_module_run(), opticflow_pmw3901_event(), parse_gps_datalink(), parse_gps_datalink_local(), parse_gps_datalink_small(), pose_periodic(), pprzlog_tp_init(), px4flow_i2c_frame_cb(), range_msg_callback(), readRegister_nonblocking(), send_filter_status(), sonar_adc_read(), sonar_bebop_read(), sonar_pwm_read(), sonar_vl53l1x_publish(), stereocam_parse_msg(), superbitrf_event(), superbitrf_receive_packet_cb(), teraranger_event(), tfmini_i2c_periodic(), tfmini_parse(), umarim_baro_event(), v4l2_capture_thread(), and video_thread_function().
sys_time_elapsed_us()
static unsigned int sys_time_elapsed_us (struct timespec * prev, struct timespec * now) inline static
elapsed time in microsecs between two timespecs
Definition at line 53 of file sys_time_arch.h.
sys_time_usleep()
static void sys_time_usleep (uint32_t us) inline static
Definition at line 47 of file sys_time_arch.h.