Paparazzi UAS: sw/airborne/arch/lpc21/mcu_arch.c File Reference
mcu_arch.c File Reference
LPC21 architecture
lpc21 arch dependant microcontroller initialisation functions.
#include "mcu.h"
#include <inttypes.h>
#include <BOARD_CONFIG>
#include "LPC21xx.h"
Functions
void reset (void)
void mcu_arch_init (void)
Detailed Description
lpc21 arch dependant microcontroller initialisation functions.
Definition in file mcu_arch.c.
Function Documentation
mcu_arch_init()
void mcu_arch_init (void)
Definition at line 40 of file mcu_arch.c.
References MAMCR, MAMCR_FULL, MAMTIM, MAMTIM_CYCLES, MEMMAP, MEMMAP_FLASH, PLLCFG, PLLCFG_MSEL, PLLCFG_PSEL, PLLCON, PLLCON_PLLC, PLLCON_PLLE, PLLFEED, PLLSTAT, PLLSTAT_LOCK, reset(), VICDefVectAddr, VICIntEnClear, VICIntSelect, VPBDIV, and VPBDIV_VALUE.
reset()
void reset (void)
Referenced by mcu_arch_init(), and rxSpiCheckBindRequested().