Paparazzi UAS: sw/airborne/modules/sensors/mag_pitot_uart.h File Reference
mag_pitot_uart.h File Reference
#include "std.h"
#include "generated/airframe.h"
#include "pprzlink/pprz_transport.h"
#include "math/pprz_orientation_conversion.h"
Data Structures
struct mag_pitot_t
Macros
#define IMU_TO_MAG_PHI 0
#define IMU_TO_MAG_THETA 0
#define IMU_TO_MAG_PSI 0
Functions
void mag_pitot_init (void)
void mag_pitot_event (void)
Detailed Description
Author
C. De Wagter Remotely located magnetometer and pitot tube over uart (RS232) communication
Definition in file mag_pitot_uart.h.
Data Structure Documentation
mag_pitot_t
struct mag_pitot_t
Definition at line 43 of file mag_pitot_uart.h.
Data Fields
struct link_device * device The device which is uses for communication.
struct OrientationReps imu_to_mag IMU to magneto translation.
bool msg_available If we received a message.
struct pprz_transport transport The transport layer (PPRZ)
Macro Definition Documentation
IMU_TO_MAG_PHI
#define IMU_TO_MAG_PHI 0
Definition at line 37 of file mag_pitot_uart.h.
IMU_TO_MAG_PSI
#define IMU_TO_MAG_PSI 0
Definition at line 39 of file mag_pitot_uart.h.
IMU_TO_MAG_THETA
#define IMU_TO_MAG_THETA 0
Definition at line 38 of file mag_pitot_uart.h.
Function Documentation
mag_pitot_event()
void mag_pitot_event (void)
Definition at line 128 of file mag_pitot_uart.c.
References mag_pitot_t::device, mag_pitot, mag_pitot_parse_msg(), mp_msg_buf, mag_pitot_t::msg_available, and mag_pitot_t::transport.
mag_pitot_init()
void mag_pitot_init (void)
Definition at line 55 of file mag_pitot_uart.c.
References DefaultPeriodic, mag_pitot_t::imu_to_mag, IMU_TO_MAG_PHI, IMU_TO_MAG_PSI, IMU_TO_MAG_THETA, mag_pitot, mag_pitot_raw_downlink(), orientationSetEulers_f(), register_periodic_telemetry(), and mag_pitot_t::transport.