Paparazzi UAS: sw/airborne/arch/lpc21/modules/sensors/mag_micromag_fw_hw.c File Reference
mag_micromag_fw_hw.c File Reference
#include "led.h"
#include "modules/sensors/mag_micromag_fw_hw.h"
#include "modules/sensors/mag_micromag_fw.h"
Macros
#define SPI1_VIC_SLOT 7
Functions
static void SSP_ISR (void)
static void EXTINT_ISR (void)
void micromag_hw_init (void)
Variables
volatile uint8_t micromag_cur_axe
Macro Definition Documentation
SPI1_VIC_SLOT
#define SPI1_VIC_SLOT 7
Definition at line 21 of file mag_micromag_fw_hw.c.
Function Documentation
EXTINT_ISR()
void EXTINT_ISR (void) static
Definition at line 34 of file mag_micromag_fw_hw.c.
References EXTINT, ISR_ENTRY, ISR_EXIT, micromag_status, MM_GOT_EOC, and VICVectAddr.
Referenced by micromag_hw_init().
micromag_hw_init()
void micromag_hw_init (void)
Definition at line 48 of file mag_micromag_fw_hw.c.
References _VIC_ADDR, _VIC_CNTL, EXTINT, EXTINT_ISR(), EXTMODE, EXTPOLAR, MmReset, MmUnselect, PINSEL1, SPI1_VIC_SLOT, SSP_ISR(), SSP_PINSEL1_MISO, SSP_PINSEL1_MOSI, SSP_PINSEL1_SCK, SSPCPSR, SSPCR0, SSPCR0_VAL, SSPCR1, SSPCR1_VAL, VIC_BIT, VIC_ENABLE, VIC_SPI1, VICIntEnable, and VICIntSelect.
Referenced by micromag_init().
SSP_ISR()
static void SSP_ISR (void) static
Definition at line 24 of file mag_micromag_fw_hw.c.
References ISR_ENTRY, ISR_EXIT, MmOnSpiIt, and VICVectAddr.
Referenced by micromag_hw_init().
Variable Documentation
micromag_cur_axe
volatile uint8_t micromag_cur_axe
Definition at line 13 of file mag_micromag_fw_hw.c.