Paparazzi UAS: sw/airborne/firmwares/tutorial/main_demo4.c File Reference
main_demo4.c File Reference
#include "std.h"
#include "mcu.h"
#include "mcu_periph/sys_time.h"
#include "led.h"
#include "mcu_periph/uart.h"
#include "pprzlink/messages.h"
#include "subsystems/datalink/downlink.h"
Functions
static void main_init (void)
static void main_periodic_task (void)
int main (void)
Function Documentation
main()
int main (void)
Definition at line 13 of file main_demo4.c.
References main_init(), main_periodic_task(), and sys_time_check_and_ack_timer().
main_init()
static void main_init (void) inline static
Definition at line 24 of file main_demo4.c.
References mcu_init(), mcu_int_enable, and sys_time_register_timer().
Referenced by main().
main_periodic_task()
static void main_periodic_task (void) inline static
Definition at line 32 of file main_demo4.c.
References LED_TOGGLE, and sys_time::nb_sec.
Referenced by main().