Paparazzi UAS: sw/airborne/peripherals/max1168.h File Reference
max1168.h File Reference
#include "std.h"
#include "peripherals/max1168_arch.h"
Macros
#define MAX1168_NB_CHAN 8
#define MAX1168_SLAVE_IDX SPI_SLAVE0
#define MAX1168_SPI_DEV spi1
#define MAX1168_CONF_CHANNEL 0x7
Configure control register.
#define MAX1168_CONF_SCAN 0x1
#define MAX1168_CONF_REF 0x0
#define MAX1168_CONF_CLOCK 0x1
#define MAX1168_CONF_CR ((MAX1168_CONF_CHANNEL<<5)|(MAX1168_CONF_SCAN<<3)|(MAX1168_CONF_REF<<1)|(MAX1168_CONF_CLOCK))
#define MAX1168_IDLE 0
#define MAX1168_SENDING_REQ 1
#define MAX1168_GOT_EOC 2
#define MAX1168_READING_RES 3
#define MAX1168_DATA_AVAILABLE 4
#define Max1168Periodic()
Functions
void max1168_init (void)
void max1168_read (void)
void max1168_event (void)
void max1168_arch_init (void)
Variables
volatile uint8_t max1168_status
uint16_t max1168_values [MAX1168_NB_CHAN]
Macro Definition Documentation
MAX1168_CONF_CHANNEL
#define MAX1168_CONF_CHANNEL 0x7
Configure control register.
Definition at line 41 of file max1168.h.
MAX1168_CONF_CLOCK
#define MAX1168_CONF_CLOCK 0x1
Definition at line 50 of file max1168.h.
MAX1168_CONF_CR
#define MAX1168_CONF_CR ((MAX1168_CONF_CHANNEL<<5)|(MAX1168_CONF_SCAN<<3)|(MAX1168_CONF_REF<<1)|(MAX1168_CONF_CLOCK))
Definition at line 53 of file max1168.h.
MAX1168_CONF_REF
#define MAX1168_CONF_REF 0x0
Definition at line 47 of file max1168.h.
MAX1168_CONF_SCAN
#define MAX1168_CONF_SCAN 0x1
Definition at line 44 of file max1168.h.
MAX1168_DATA_AVAILABLE
#define MAX1168_DATA_AVAILABLE 4
Definition at line 63 of file max1168.h.
MAX1168_GOT_EOC
#define MAX1168_GOT_EOC 2
Definition at line 61 of file max1168.h.
MAX1168_IDLE
#define MAX1168_IDLE 0
Definition at line 59 of file max1168.h.
MAX1168_NB_CHAN
#define MAX1168_NB_CHAN 8
Definition at line 28 of file max1168.h.
MAX1168_READING_RES
#define MAX1168_READING_RES 3
Definition at line 62 of file max1168.h.
MAX1168_SENDING_REQ
#define MAX1168_SENDING_REQ 1
Definition at line 60 of file max1168.h.
MAX1168_SLAVE_IDX
#define MAX1168_SLAVE_IDX SPI_SLAVE0
Definition at line 31 of file max1168.h.
MAX1168_SPI_DEV
#define MAX1168_SPI_DEV spi1
Definition at line 35 of file max1168.h.
Max1168Periodic
#define Max1168Periodic ()
Value:
    {             \
    if (max1168_status == MAX1168_IDLE) { \
      max1168_read();                     \
    }                                     \
  }
Definition at line 68 of file max1168.h.
Function Documentation
max1168_arch_init()
void max1168_arch_init (void)
Definition at line 31 of file max1168_arch.c.
References _VIC_ADDR, _VIC_CNTL, EXTINT, EXTINT0_ISR(), EXTMODE, EXTPOLAR, GPIO2, GPIOB, MAX1168_EOC_EINT, MAX1168_EOC_PINSEL, MAX1168_EOC_PINSEL_BIT, MAX1168_EOC_PINSEL_VAL, MAX1168_EOC_VIC_IT, VIC_BIT, VIC_ENABLE, VICIntEnable, and VICIntSelect.
Referenced by max1168_init().
max1168_event()
void max1168_event (void)
Definition at line 101 of file max1168.c.
References MAX1168_DATA_AVAILABLE, MAX1168_GOT_EOC, MAX1168_IDLE, max1168_read_trans, MAX1168_READING_RES, max1168_req_trans, MAX1168_SLAVE_IDX, MAX1168_SPI_DEV, max1168_status, spi_resume(), spi_slave_unselect(), SPITransDone, SPITransFailed, SPITransSuccess, and spi_transaction::status.
Referenced by imu_b2_event(), and imu_hbmini_event().
max1168_init()
void max1168_init (void)
Definition at line 40 of file max1168.c.
References spi_transaction::after_cb, spi_transaction::bitorder, spi_transaction::cdiv, spi_transaction::cpha, spi_transaction::cpol, spi_transaction::dss, spi_transaction::input_buf, spi_transaction::input_length, max1168_arch_init(), MAX1168_CONF_CR, max1168_conv_req, MAX1168_IDLE, max1168_lock_cb(), MAX1168_NB_CHAN, max1168_read_trans, max1168_req_trans, MAX1168_SLAVE_IDX, max1168_status, max1168_values, spi_transaction::output_buf, spi_transaction::output_length, spi_transaction::select, spi_transaction::slave_idx, SPICphaEdge1, SPICpolIdleLow, SPIDiv64, SPIDss16bit, SPIMSBFirst, SPISelect, SPITransDone, SPIUnselect, and spi_transaction::status.
Referenced by imu_b2_init(), and imu_hbmini_init().
max1168_read()
void max1168_read (void)
Definition at line 26 of file max1168_arch.c.
References max1168_read_trans, max1168_req_trans, MAX1168_SENDING_REQ, MAX1168_SPI_DEV, max1168_status, and spi_submit().
Variable Documentation
max1168_status
volatile uint8_t max1168_status
Definition at line 27 of file max1168.c.
Referenced by exti2_isr(), EXTINT0_ISR(), imu_b2_event(), imu_hbmini_event(), max1168_event(), max1168_init(), and max1168_read().
max1168_values
uint16_t max1168_values[MAX1168_NB_CHAN]
Definition at line 28 of file max1168.c.
Referenced by imu_b2_event(), imu_hbmini_event(), and max1168_init().