Paparazzi UAS: sw/airborne/peripherals/max1168.c File Reference
max1168.c File Reference
#include "peripherals/max1168.h"
#include "mcu_periph/spi.h"
#include "led.h"
Functions
void max1168_lock_cb (struct spi_transaction *t)
void max1168_init (void)
void max1168_read (void)
void max1168_event (void)
Variables
volatile uint8_t max1168_status
uint16_t max1168_values [MAX1168_NB_CHAN]
struct spi_transaction max1168_req_trans
struct spi_transaction max1168_read_trans
uint16_t max1168_conv_req
Function Documentation
max1168_event()
void max1168_event (void)
Definition at line 101 of file max1168.c.
References MAX1168_DATA_AVAILABLE, MAX1168_GOT_EOC, MAX1168_IDLE, max1168_read_trans, MAX1168_READING_RES, max1168_req_trans, MAX1168_SLAVE_IDX, MAX1168_SPI_DEV, max1168_status, spi_resume(), spi_slave_unselect(), SPITransDone, SPITransFailed, SPITransSuccess, and spi_transaction::status.
Referenced by imu_b2_event(), and imu_hbmini_event().
max1168_init()
void max1168_init (void)
Definition at line 40 of file max1168.c.
References spi_transaction::after_cb, spi_transaction::bitorder, spi_transaction::cdiv, spi_transaction::cpha, spi_transaction::cpol, spi_transaction::dss, spi_transaction::input_buf, spi_transaction::input_length, max1168_arch_init(), MAX1168_CONF_CR, max1168_conv_req, MAX1168_IDLE, max1168_lock_cb(), MAX1168_NB_CHAN, max1168_read_trans, max1168_req_trans, MAX1168_SLAVE_IDX, max1168_status, max1168_values, spi_transaction::output_buf, spi_transaction::output_length, spi_transaction::select, spi_transaction::slave_idx, SPICphaEdge1, SPICpolIdleLow, SPIDiv64, SPIDss16bit, SPIMSBFirst, SPISelect, SPITransDone, SPIUnselect, and spi_transaction::status.
Referenced by imu_b2_init(), and imu_hbmini_init().
max1168_lock_cb()
void max1168_lock_cb (struct spi_transaction * t)
Definition at line 134 of file max1168.c.
References MAX1168_SLAVE_IDX, MAX1168_SPI_DEV, and spi_lock().
Referenced by max1168_init().
max1168_read()
void max1168_read (void)
Definition at line 87 of file max1168.c.
References max1168_read_trans, max1168_req_trans, MAX1168_SENDING_REQ, MAX1168_SPI_DEV, max1168_status, and spi_submit().
Variable Documentation
max1168_conv_req
uint16_t max1168_conv_req
Definition at line 33 of file max1168.c.
Referenced by max1168_init().
max1168_read_trans
struct spi_transaction max1168_read_trans
Definition at line 31 of file max1168.c.
Referenced by max1168_event(), max1168_init(), and max1168_read().
max1168_req_trans
struct spi_transaction max1168_req_trans
Definition at line 30 of file max1168.c.
Referenced by max1168_event(), max1168_init(), and max1168_read().
max1168_status
volatile uint8_t max1168_status
Definition at line 27 of file max1168.c.
Referenced by exti2_isr(), EXTINT0_ISR(), imu_b2_event(), imu_hbmini_event(), max1168_event(), max1168_init(), and max1168_read().
max1168_values
uint16_t max1168_values[MAX1168_NB_CHAN]
Definition at line 28 of file max1168.c.
Referenced by imu_b2_event(), imu_hbmini_event(), and max1168_init().