Paparazzi UAS: sw/airborne/arch/lpc21/modules/adcs/max11040_hw.c File Reference
max11040_hw.c File Reference
#include "armVIC.h"
#include "max11040_hw.h"
#include "adcs/max11040.h"
Macros
#define SPI1_VIC_SLOT 7
Functions
static void SSP_ISR (void)
static void EXTINT_ISR (void)
void max11040_hw_init (void)
Variables
volatile uint8_t num_irqs = 0
Macro Definition Documentation
SPI1_VIC_SLOT
#define SPI1_VIC_SLOT 7
Definition at line 46 of file max11040_hw.c.
Function Documentation
EXTINT_ISR()
void EXTINT_ISR (void) static
Definition at line 232 of file max11040_hw.c.
References EXTINT, IO0DIR, ISR_ENTRY, ISR_EXIT, max11040_buf_in, max11040_count, MAX11040_DATA2, max11040_status, max11040_timestamp, MaxmSelect, num_irqs, PINSEL1, SSP_Send, and VICVectAddr.
Referenced by max11040_hw_init().
max11040_hw_init()
void max11040_hw_init (void)
Definition at line 271 of file max11040_hw.c.
References _VIC_ADDR, _VIC_CNTL, EXTINT, EXTINT_ISR(), EXTMODE, EXTPOLAR, MAXM_NB_ADCS, PINSEL1, SPI1_VIC_SLOT, SSP_ClearRti, SSP_Enable, SSP_EnableRti, SSP_ISR(), SSP_PINSEL1_MISO, SSP_PINSEL1_MOSI, SSP_PINSEL1_SCK, SSP_PINSEL1_SSEL, SSP_Send, SSPCPSR, SSPCR0, SSPCR0_VAL, SSPCR1, SSPCR1_VAL, VIC_BIT, VIC_ENABLE, VIC_SPI1, VICIntEnable, and VICIntSelect.
Referenced by max11040_init().
SSP_ISR()
static void SSP_ISR (void) static
Definition at line 49 of file max11040_hw.c.
References foo, ISR_ENTRY, ISR_EXIT, max11040_buf_in, max11040_buf_out, MAX11040_BUF_SIZE, MAX11040_CONF, max11040_count, MAX11040_DATA, max11040_data, MAX11040_DATA2, MAX11040_DATA_AVAILABLE, MAX11040_INSTANT, MAX11040_RATE, MAX11040_RESET, max11040_status, max11040_values, MAXM_NB_ADCS, MAXM_NB_CHAN, MaxmUnselect, SSP_ClearRti, SSP_ClearRxi, SSP_Send, SSPDR, and VICVectAddr.
Referenced by max11040_hw_init().
Variable Documentation
num_irqs
volatile uint8_t num_irqs = 0
Definition at line 38 of file max11040_hw.c.
Referenced by EXTINT_ISR().