Paparazzi UAS: sw/airborne/modules/datalink/missionlib/mission_manager.h File Reference
mission_manager.h File Reference
Common functions used within the mission library, blocks and waypoints cannot be send simultaneously (which should not matter)
#include <mavlink/mavlink_types.h>
Data Structures
struct mavlink_mission_mgr
Macros
#define MAVLINK_TIMEOUT 15
Typedefs
typedef struct mavlink_mission_mgr mavlink_mission_mgr
Enumerations
enum MAVLINK_MISSION_MGR_STATES { STATE_IDLE = 0, STATE_SEND_LIST, STATE_SEND_ITEM, STATE_WAYPOINT_WRITE_TRANSACTION }
State machine.
Functions
void mavlink_mission_init (mavlink_mission_mgr *mgr)
void mavlink_mission_message_handler (const mavlink_message_t *msg)
void mavlink_mission_periodic (void)
update current block and send if changed
void mavlink_send_mission_ack (void)
void mavlink_mission_set_timer (void)
void mavlink_mission_cancel_timer (void)
Variables
mavlink_mission_mgr mission_mgr
Detailed Description
Common functions used within the mission library, blocks and waypoints cannot be send simultaneously (which should not matter)
Definition in file mission_manager.h.
Data Structure Documentation
mavlink_mission_mgr
struct mavlink_mission_mgr
Definition at line 46 of file mission_manager.h.
Data Fields
uint8_t current_block
uint8_t rem_compid
uint8_t rem_sysid
uint16_t seq
enum MAVLINK_MISSION_MGR_STATES state
int timer_id
Macro Definition Documentation
MAVLINK_TIMEOUT
#define MAVLINK_TIMEOUT 15
Definition at line 35 of file mission_manager.h.
Typedef Documentation
mavlink_mission_mgr
typedef struct mavlink_mission_mgr mavlink_mission_mgr
Definition at line 55 of file mission_manager.h.
Enumeration Type Documentation
MAVLINK_MISSION_MGR_STATES
enum MAVLINK_MISSION_MGR_STATES
State machine.
Enumerator
STATE_IDLE
STATE_SEND_LIST
STATE_SEND_ITEM
STATE_WAYPOINT_WRITE_TRANSACTION
Definition at line 39 of file mission_manager.h.
Function Documentation
mavlink_mission_cancel_timer()
void mavlink_mission_cancel_timer (void)
Definition at line 67 of file mission_manager.c.
References mission_mgr, sys_time_cancel_timer(), and mavlink_mission_mgr::timer_id.
Referenced by mavlink_block_message_handler(), mavlink_mission_message_handler(), mavlink_mission_periodic(), and mavlink_wp_message_handler().
mavlink_mission_init()
void mavlink_mission_init (mavlink_mission_mgr * mgr)
Definition at line 51 of file mission_manager.c.
References mavlink_mission_mgr::seq, and mavlink_mission_mgr::timer_id.
Referenced by mavlink_init().
mavlink_mission_message_handler()
void mavlink_mission_message_handler (const mavlink_message_t * msg)
Definition at line 75 of file mission_manager.c.
References mavlink_block_message_handler(), MAVLINK_DEBUG, mavlink_mission_cancel_timer(), mavlink_wp_message_handler(), mission_mgr, msg, mavlink_mission_mgr::state, and STATE_IDLE.
Referenced by mavlink_event().
mavlink_mission_periodic()
void mavlink_mission_periodic (void)
update current block and send if changed
Definition at line 90 of file mission_manager.c.
References mavlink_mission_mgr::current_block, MAVLINK_DEBUG, mavlink_mission_cancel_timer(), MAVLinkSendMessage, mission_mgr, nav_block, mavlink_mission_mgr::seq, mavlink_mission_mgr::state, STATE_IDLE, sys_time_check_and_ack_timer(), and mavlink_mission_mgr::timer_id.
Referenced by mavlink_periodic().
mavlink_mission_set_timer()
void mavlink_mission_set_timer (void)
Definition at line 57 of file mission_manager.c.
References MAVLINK_TIMEOUT, mission_mgr, sys_time_register_timer(), sys_time_update_timer(), and mavlink_mission_mgr::timer_id.
Referenced by mavlink_block_message_handler(), and mavlink_wp_message_handler().
mavlink_send_mission_ack()
void mavlink_send_mission_ack (void)
Definition at line 107 of file mission_manager.c.
References MAVLINK_DEBUG, MAVLinkSendMessage, mission_mgr, mavlink_mission_mgr::rem_compid, and mavlink_mission_mgr::rem_sysid.
Variable Documentation
mission_mgr
mavlink_mission_mgr mission_mgr
Definition at line 73 of file mavlink.c.
Referenced by mavlink_block_message_handler(), mavlink_init(), mavlink_mission_cancel_timer(), mavlink_mission_message_handler(), mavlink_mission_periodic(), mavlink_mission_set_timer(), mavlink_send_block(), mavlink_send_block_count(), mavlink_send_mission_ack(), and mavlink_wp_message_handler().