Paparazzi UAS: sw/airborne/modules/datalink/missionlib/mission_manager.c File Reference
mission_manager.c File Reference
Common functions used within the mission library.
#include "modules/datalink/missionlib/mission_manager.h"
#include "modules/datalink/mavlink.h"
#include "modules/datalink/missionlib/blocks.h"
#include "modules/datalink/missionlib/waypoints.h"
#include "mavlink/paparazzi/mavlink.h"
#include "firmwares/rotorcraft/navigation.h"
#include "generated/flight_plan.h"
#include "mcu_periph/sys_time.h"
Functions
void mavlink_mission_init (mavlink_mission_mgr *mgr)
void mavlink_mission_set_timer (void)
void mavlink_mission_cancel_timer (void)
void mavlink_mission_message_handler (const mavlink_message_t *msg)
void mavlink_mission_periodic (void)
update current block and send if changed
void mavlink_send_mission_ack (void)
Detailed Description
Common functions used within the mission library.
Definition in file mission_manager.c.
Function Documentation
mavlink_mission_cancel_timer()
void mavlink_mission_cancel_timer (void)
Definition at line 67 of file mission_manager.c.
References mission_mgr, sys_time_cancel_timer(), and mavlink_mission_mgr::timer_id.
Referenced by mavlink_block_message_handler(), mavlink_mission_message_handler(), mavlink_mission_periodic(), and mavlink_wp_message_handler().
mavlink_mission_init()
void mavlink_mission_init (mavlink_mission_mgr * mgr)
Definition at line 51 of file mission_manager.c.
References mavlink_mission_mgr::seq, and mavlink_mission_mgr::timer_id.
Referenced by mavlink_init().
mavlink_mission_message_handler()
void mavlink_mission_message_handler (const mavlink_message_t * msg)
Definition at line 75 of file mission_manager.c.
References mavlink_block_message_handler(), MAVLINK_DEBUG, mavlink_mission_cancel_timer(), mavlink_wp_message_handler(), mission_mgr, msg, mavlink_mission_mgr::state, and STATE_IDLE.
Referenced by mavlink_event().
mavlink_mission_periodic()
void mavlink_mission_periodic (void)
update current block and send if changed
Definition at line 90 of file mission_manager.c.
References mavlink_mission_mgr::current_block, MAVLINK_DEBUG, mavlink_mission_cancel_timer(), MAVLinkSendMessage, mission_mgr, nav_block, mavlink_mission_mgr::seq, mavlink_mission_mgr::state, STATE_IDLE, sys_time_check_and_ack_timer(), and mavlink_mission_mgr::timer_id.
Referenced by mavlink_periodic().
mavlink_mission_set_timer()
void mavlink_mission_set_timer (void)
Definition at line 57 of file mission_manager.c.
References MAVLINK_TIMEOUT, mission_mgr, sys_time_register_timer(), sys_time_update_timer(), and mavlink_mission_mgr::timer_id.
Referenced by mavlink_block_message_handler(), and mavlink_wp_message_handler().
mavlink_send_mission_ack()
void mavlink_send_mission_ack (void)
Definition at line 107 of file mission_manager.c.
References MAVLINK_DEBUG, MAVLinkSendMessage, mission_mgr, mavlink_mission_mgr::rem_compid, and mavlink_mission_mgr::rem_sysid.