Paparazzi UAS: sw/airborne/modules/hott/hott.h File Reference
hott.h File Reference
#include "generated/airframe.h"
#include "std.h"
Functions
void hott_init (void)
void hott_periodic (void)
void hott_event (void)
Detailed Description
Graupner HOTT telemetry control module.
Definition in file hott.h.
Function Documentation
hott_event()
void hott_event (void)
Definition at line 291 of file hott.c.
References hott_event_timer, hott_periodic_event(), SysTimeTimer, and SysTimeTimerStart.
hott_init()
void hott_init (void)
Definition at line 123 of file hott.c.
References hott_msgs_init().
hott_periodic()
void hott_periodic (void)
Definition at line 129 of file hott.c.
References HOTT_TELEMETRY_EAM_SENSOR_ID, HOTT_TELEMETRY_GAM_SENSOR_ID, HOTT_TELEMETRY_GPS_SENSOR_ID, hott_telemetry_sendig_msgs_id, HOTT_TELEMETRY_VARIO_SENSOR_ID, hott_update_eam_msg(), hott_update_gam_msg(), and TRUE.