Paparazzi UAS: sw/airborne/modules/nav/nav_gls.h File Reference
nav_gls.h File Reference
gps landing system
#include "std.h"
#include "paparazzi.h"
Functions
bool gls_start (uint8_t _af, uint8_t _sd, uint8_t _tod, uint8_t _td)
bool gls_run (uint8_t _af, uint8_t _sd, uint8_t _tod, uint8_t _td)
Detailed Description
gps landing system
Definition in file nav_gls.h.
Function Documentation
gls_run()
bool gls_run (uint8_t _af, uint8_t _sd, uint8_t _tod, uint8_t _td)
Definition at line 159 of file nav_gls.c.
References app_angle, app_distance_af_sd, app_intercept_rate, gs_on_final, init, Max, NavSegment, NavVerticalAltitudeMode, NavVerticalAutoThrottleMode, sd_intercept, sd_tod_x, sd_tod_y, stateGetHorizontalSpeedNorm_f(), stateGetPositionEnu_f(), target_speed, v_ctl_auto_airspeed_setpoint, WaypointAlt, WaypointX, WaypointY, EnuCoor_f::x, and EnuCoor_f::y.
gls_start()
bool gls_start (uint8_t _af, uint8_t _sd, uint8_t _tod, uint8_t _td)
Definition at line 135 of file nav_gls.c.
References app_angle, APP_ANGLE, app_distance_af_sd, APP_DISTANCE_AF_SD, app_intercept_rate, APP_INTERCEPT_RATE, APP_TARGET_SPEED, gls_compute_TOD(), init, and target_speed.