Paparazzi UAS: sw/airborne/modules/nav/nav_launcher.h File Reference
nav_launcher.h File Reference
Pneumatic launcher system See video of the system: https://www.youtube.com/watch?v=qc1uwH-8Dbw Launcher. A pneumatic launching system.
#include "std.h"
#include "paparazzi.h"
Functions
void nav_launcher_setup (void)
bool nav_launcher_run (void)
Detailed Description
Pneumatic launcher system See video of the system: https://www.youtube.com/watch?v=qc1uwH-8Dbw Launcher. A pneumatic launching system.
Phase 1: Zero Roll, Takeoff Pitch, Full Throttle(once you enter the block!)
Phase 2: After detecting lauch (ground speed) and travelling enough distance from the launch point follow launch line -> Auto roll, Takeoff pitch, Full Throttle
Phase 3: If the aircraft is above a specific alt, greater than a specific speed or too far away, circle up with takeoff circle radius, until you reach desired takeoff altitude
An example section to be added into your airframe configuration:
<section name="LAUNCHER" prefix="LAUNCHER_TAKEOFF_"> <define name="PITCH" value="0.23" unit="rad"> <define name="HEIGH" value="70" unit="m"> <define name="MIN_SPEED_CIRCLE" value="8" unit="m/s"> <define name="DISTANCE" value="30" unit="m"> <define name="MIN_SPEED_LINE" value="5" unit="m/s"> </section>
Definition in file nav_launcher.h.
Function Documentation
nav_launcher_run()
bool nav_launcher_run (void)
Definition at line 125 of file nav_launcher.c.
References CLaunch_Status, FALSE, L_CircleUp, L_Finished, L_Line_Nav, L_Pitch_Nav, launch_alt, launch_circle, launch_circle_alt, launch_line_x, launch_line_y, launch_x, launch_y, LAUNCHER_TAKEOFF_CIRCLE_RADIUS, LAUNCHER_TAKEOFF_DISTANCE, LAUNCHER_TAKEOFF_HEIGHT_THRESHOLD, LAUNCHER_TAKEOFF_MAX_CIRCLE_DISTANCE, LAUNCHER_TAKEOFF_MIN_SPEED_CIRCLE, LAUNCHER_TAKEOFF_MIN_SPEED_LINE, LAUNCHER_TAKEOFF_PITCH, MAX_PPRZ, nav_circle_XY(), nav_route_xy(), NavAttitude, NavVerticalAltitudeMode, NavVerticalAutoThrottleMode, NavVerticalThrottleMode, stateGetHorizontalSpeedNorm_f(), stateGetPositionEnu_f(), stateGetPositionUtm_f(), TRUE, EnuCoor_f::x, Point2D::x, EnuCoor_f::y, and Point2D::y.
nav_launcher_setup()
void nav_launcher_setup (void)
Definition at line 111 of file nav_launcher.c.
References UtmCoor_f::alt, CLaunch_Status, L_Pitch_Nav, launch_alt, launch_circle_alt, launch_pitch, launch_time, launch_x, launch_y, LAUNCHER_TAKEOFF_CIRCLE_ALT, LAUNCHER_TAKEOFF_HEIGHT, stateGetNedToBodyEulers_f(), stateGetPositionEnu_f(), stateGetPositionUtm_f(), FloatEulers::theta, EnuCoor_f::x, and EnuCoor_f::y.