Paparazzi UAS: sw/airborne/subsystems/navigation/nav_survey_rectangle.h File Reference
nav_survey_rectangle.h File Reference
#include "firmwares/fixedwing/nav.h"
Macros
#define NavSurveyRectangleInit(_wp1, _wp2, _grid, _orientation) nav_survey_rectangle_init(_wp1, _wp2, _grid, _orientation)
#define NavSurveyRectangle(_wp1, _wp2) nav_survey_rectangle(_wp1, _wp2)
Enumerations
enum survey_orientation_t { NS, WE, NS, WE }
Functions
void nav_survey_rectangle_init (uint8_t wp1, uint8_t wp2, float grid, survey_orientation_t so)
void nav_survey_rectangle (uint8_t wp1, uint8_t wp2)
Variables
float nav_survey_sweep
Macro Definition Documentation
NavSurveyRectangle
#define NavSurveyRectangle (_wp1, _wp2) nav_survey_rectangle(_wp1, _wp2)
Definition at line 42 of file nav_survey_rectangle.h.
NavSurveyRectangleInit
#define NavSurveyRectangleInit (_wp1, _wp2, _grid, _orientation) nav_survey_rectangle_init(_wp1, _wp2, _grid, _orientation)
Definition at line 41 of file nav_survey_rectangle.h.
Enumeration Type Documentation
survey_orientation_t
enum survey_orientation_t
Enumerator
NS
WE
NS
WE
Definition at line 35 of file nav_survey_rectangle.h.
Function Documentation
nav_survey_rectangle()
void nav_survey_rectangle (uint8_t wp1, uint8_t wp2)
Do half a circle around WP 0
Do half a circle around WP 0
Definition at line 92 of file nav_survey_rectangle.c.
References LINE_START_FUNCTION, LINE_STOP_FUNCTION, Max, Min, nav_in_circle, nav_in_segment, nav_route_xy(), nav_survey_active, nav_survey_east, nav_survey_north, nav_survey_shift, nav_survey_south, nav_survey_sweep, nav_survey_west, NavCircleWaypoint, NavCourseCloseTo, NavVerticalAltitudeMode, NavVerticalAutoThrottleMode, NS, stateGetPositionEnu_f(), survey_from, survey_orientation, survey_to, survey_uturn, SurveyGoingEast, SurveyGoingNorth, SurveyGoingSouth, SurveyGoingWest, WaypointAlt, waypoints, WaypointX, WaypointY, point::x, and point::y.
nav_survey_rectangle_init()
void nav_survey_rectangle_init (uint8_t wp1, uint8_t wp2, float grid, survey_orientation_t so)
Definition at line 55 of file nav_survey_rectangle.c.
References LINE_START_FUNCTION, Max, Min, nav_survey_east, nav_survey_north, nav_survey_shift, nav_survey_south, nav_survey_sweep, nav_survey_west, NS, stateGetHorizontalSpeedDir_f(), stateGetPositionEnu_f(), survey_from, survey_orientation, survey_to, survey_uturn, WaypointX, WaypointY, point::x, and point::y.
Variable Documentation
nav_survey_sweep
float nav_survey_sweep
Definition at line 33 of file nav_survey_rectangle.c.
Referenced by nav_survey_rectangle(), and nav_survey_rectangle_init().