Paparazzi UAS: sw/airborne/modules/nav/nav_vertical_raster.c File Reference
nav_vertical_raster.c File Reference
#include "modules/nav/nav_vertical_raster.h"
#include "firmwares/fixedwing/nav.h"
#include "state.h"
#include "autopilot.h"
#include "generated/flight_plan.h"
Enumerations
enum line_status {
LR12, LQC21, LTC2, LQC22,
LR21, LQC12, LTC1, LQC11,
LR12, LQC21, LTC2, LQC22,
LR21, LQC12, LTC1, LQC11
}
Copy of nav line.
Functions
void nav_vertical_raster_setup (void)
bool nav_vertical_raster_run (uint8_t l1, uint8_t l2, float radius, float AltSweep)
Variables
static enum line_status line_status
Detailed Description
from OSAM advanced navigation routines
Definition in file nav_vertical_raster.c.
Enumeration Type Documentation
line_status
enum line_status
Copy of nav line.
The only difference is it changes altitude every sweep, but doesn't come out of circle until it reaches altitude.
Enumerator
LR12
LQC21
LTC2
LQC22
LR21
LQC12
LTC1
LQC11
LR12
LQC21
LTC2
LQC22
LR21
LQC12
LTC1
LQC11
Definition at line 40 of file nav_vertical_raster.c.
Function Documentation
nav_vertical_raster_run()
bool nav_vertical_raster_run (uint8_t l1, uint8_t l2, float radius, float AltSweep)
Definition at line 48 of file nav_vertical_raster.c.
References point::a, CARROT, LQC11, LQC12, LQC21, LQC22, LR12, LR21, LTC1, LTC2, nav_circle_XY(), nav_init_stage(), NavApproachingFrom, NavQdrCloseTo, NavSegment, NavVerticalAltitudeMode, NavVerticalAutoThrottleMode, stateGetPositionUtm_f(), WaypointAlt, waypoints, WaypointX, WaypointY, point::x, and point::y.
nav_vertical_raster_setup()
void nav_vertical_raster_setup (void)
Definition at line 43 of file nav_vertical_raster.c.
References LR12.
Variable Documentation
line_status
enum line_status line_status static
Definition at line 41 of file nav_vertical_raster.c.