Paparazzi UAS: sw/airborne/modules/nav/nav_spiral.c File Reference
nav_spiral.c File Reference
#include "modules/nav/nav_spiral.h"
#include "firmwares/fixedwing/nav.h"
#include "state.h"
#include "autopilot.h"
#include "generated/flight_plan.h"
Macros
#define NAV_SPIRAL_MIN_CIRCLE_RADIUS 60
Functions
void nav_spiral_setup (uint8_t center_wp, uint8_t edge_wp, float radius_start, float radius_inc, float segments)
bool nav_spiral_run (void)
Variables
struct NavSpiral nav_spiral
Detailed Description
Fixedwing navigation in a spiral/helix.
creating a helix:
start radius to end radius, increasing after reaching alphamax
Alphamax is calculated from given segments
IMPORTANT: numer of segments has to be larger than 2!
Definition in file nav_spiral.c.
Macro Definition Documentation
NAV_SPIRAL_MIN_CIRCLE_RADIUS
#define NAV_SPIRAL_MIN_CIRCLE_RADIUS 60
Definition at line 45 of file nav_spiral.c.
Function Documentation
nav_spiral_run()
bool nav_spiral_run (void)
Definition at line 86 of file nav_spiral.c.
References NavSpiral::alpha_limit, UtmCoor_f::alt, NavSpiral::center, dc_cam_angle, dc_cam_tracing, dc_Circle, dc_send_command(), DC_SHOOT, dc_stop(), NavSpiral::dist_from_center, float_vect2_norm(), FLOAT_VECT3_NORM, NavSpiral::fly_from, NavSpiral::last_circle, nav_approaching_xy(), nav_circle_XY(), nav_route_xy(), nav_spiral, NavVerticalAltitudeMode, NavVerticalAutoThrottleMode, pos_diff, NavSpiral::radius, NavSpiral::radius_increment, NavSpiral::radius_start, NavSpiral::segments, SpiralCircle, SpiralInc, SpiralOutside, SpiralStartCircle, stateGetPositionEnu_f(), stateGetPositionUtm_f(), NavSpiral::status, NavSpiral::trans_current, VECT2_COPY, VECT2_DIFF, FloatVect2::x, FloatVect3::x, FloatVect2::y, FloatVect3::y, and FloatVect3::z.
nav_spiral_setup()
void nav_spiral_setup (uint8_t center_wp, uint8_t edge_wp, float radius_start, float radius_inc, float segments)
Definition at line 50 of file nav_spiral.c.
References point::a, NavSpiral::alpha_limit, UtmCoor_f::alt, NavSpiral::center, NavSpiral::dist_from_center, float_vect2_norm(), FLOAT_VECT3_NORM, NavSpiral::fly_from, nav_spiral, NAV_SPIRAL_MIN_CIRCLE_RADIUS, NavSpiral::radius, NavSpiral::radius_increment, NavSpiral::radius_min, NavSpiral::radius_start, NavSpiral::segments, SpiralOutside, stateGetPositionEnu_f(), stateGetPositionUtm_f(), NavSpiral::status, NavSpiral::trans_current, VECT2_COPY, VECT2_DIFF, waypoints, FloatVect2::x, EnuCoor_f::x, FloatVect2::y, EnuCoor_f::y, and FloatVect3::z.
Variable Documentation
nav_spiral
struct NavSpiral nav_spiral
Definition at line 48 of file nav_spiral.c.
Referenced by nav_spiral_run(), and nav_spiral_setup().