Paparazzi UAS: sw/airborne/modules/nav/nav_catapult.c File Reference
nav_catapult.c File Reference
#include "modules/nav/nav_catapult.h"
#include "state.h"
#include "generated/airframe.h"
#include "firmwares/fixedwing/nav.h"
#include "autopilot.h"
#include "firmwares/fixedwing/stabilization/stabilization_attitude.h"
#include "mcu_periph/uart.h"
#include "pprzlink/messages.h"
#include "subsystems/datalink/downlink.h"
Macros
#define NAV_CATAPULT_ACCELERATION_THRESHOLD 1.5
#define NAV_CATAPULT_ACCELERATION_DETECTION 5
#define NAV_CATAPULT_MOTOR_DELAY 0.75
#define NAV_CATAPULT_HEADING_DELAY 3.0
#define NAV_CATAPULT_INITIAL_PITCH RadOfDeg(10)
#define NAV_CATAPULT_INITIAL_THROTTLE 1.0
#define NAV_CATAPULT_CLIMB_DISTANCE 300.
#define NAV_CATAPULT_TIMEOUT 30.
Functions
void nav_catapult_init (void)
void nav_catapult_highrate_module (void)
bool nav_catapult_run (uint8_t _climb)
Variables
struct nav_catapult_struct nav_catapult
Macro Definition Documentation
NAV_CATAPULT_ACCELERATION_DETECTION
#define NAV_CATAPULT_ACCELERATION_DETECTION 5
Definition at line 56 of file nav_catapult.c.
NAV_CATAPULT_ACCELERATION_THRESHOLD
#define NAV_CATAPULT_ACCELERATION_THRESHOLD 1.5
Definition at line 52 of file nav_catapult.c.
NAV_CATAPULT_CLIMB_DISTANCE
#define NAV_CATAPULT_CLIMB_DISTANCE 300.
Definition at line 76 of file nav_catapult.c.
NAV_CATAPULT_HEADING_DELAY
#define NAV_CATAPULT_HEADING_DELAY 3.0
Definition at line 64 of file nav_catapult.c.
NAV_CATAPULT_INITIAL_PITCH
#define NAV_CATAPULT_INITIAL_PITCH RadOfDeg(10)
Definition at line 68 of file nav_catapult.c.
NAV_CATAPULT_INITIAL_THROTTLE
#define NAV_CATAPULT_INITIAL_THROTTLE 1.0
Definition at line 72 of file nav_catapult.c.
NAV_CATAPULT_MOTOR_DELAY
#define NAV_CATAPULT_MOTOR_DELAY 0.75
Definition at line 60 of file nav_catapult.c.
NAV_CATAPULT_TIMEOUT
#define NAV_CATAPULT_TIMEOUT 30.
Definition at line 80 of file nav_catapult.c.
Function Documentation
nav_catapult_highrate_module()
void nav_catapult_highrate_module (void)
Definition at line 102 of file nav_catapult.c.
References nav_catapult_struct::accel_threshold, autopilot, float_rmat_transp_vmult(), nav_catapult_struct::initial_throttle, pprz_autopilot::launch, MAX_PPRZ, nav_catapult_struct::motor_delay, nav_catapult, NAV_CATAPULT_ACCELERATION_DETECTION, NAV_CATAPULT_ARMED, NAV_CATAPULT_MOTOR_ON, NAV_CATAPULT_TIMEOUT, NAV_CATAPULT_UNINIT, NAV_CATAPULT_WAIT_ACCEL, NavVerticalThrottleMode, stateGetAccelNed_f(), stateGetNedToBodyRMat_f(), nav_catapult_struct::status, nav_catapult_struct::timer, and FloatVect3::x.
nav_catapult_init()
void nav_catapult_init (void)
Definition at line 86 of file nav_catapult.c.
References nav_catapult_struct::accel_threshold, nav_catapult_struct::heading_delay, nav_catapult_struct::initial_pitch, nav_catapult_struct::initial_throttle, nav_catapult_struct::motor_delay, nav_catapult, NAV_CATAPULT_ACCELERATION_THRESHOLD, NAV_CATAPULT_HEADING_DELAY, NAV_CATAPULT_INITIAL_PITCH, NAV_CATAPULT_INITIAL_THROTTLE, NAV_CATAPULT_MOTOR_DELAY, NAV_CATAPULT_UNINIT, nav_catapult_struct::status, and nav_catapult_struct::timer.
nav_catapult_run()
bool nav_catapult_run (uint8_t _climb)
Definition at line 159 of file nav_catapult.c.
References UtmCoor_f::alt, DownlinkSendWpNr(), f, nav_catapult_struct::heading_delay, nav_catapult_struct::initial_pitch, nav_catapult_struct::initial_throttle, MAX_PPRZ, nav_approaching_xy(), nav_catapult, NAV_CATAPULT_ARMED, NAV_CATAPULT_CLIMB_DISTANCE, NAV_CATAPULT_DISARM, NAV_CATAPULT_MOTOR_CLIMB, NAV_CATAPULT_MOTOR_ON, NAV_CATAPULT_UNINIT, NAV_CATAPULT_WAIT_ACCEL, NavAttitude, NavGotoWaypoint, NavVerticalAltitudeMode, NavVerticalAutoThrottleMode, NavVerticalThrottleMode, nav_catapult_struct::pos, stateGetPositionEnu_f(), stateGetPositionUtm_f(), nav_catapult_struct::status, nav_catapult_struct::timer, WaypointAlt, WaypointX, WaypointY, FloatVect3::x, EnuCoor_f::x, FloatVect3::y, EnuCoor_f::y, and FloatVect3::z.
Variable Documentation
nav_catapult
struct nav_catapult_struct nav_catapult
Definition at line 83 of file nav_catapult.c.
Referenced by nav_catapult_highrate_module(), nav_catapult_init(), and nav_catapult_run().