Paparazzi UAS: sw/simulator/nps/nps_ivy.c File Reference
nps_ivy.c File Reference
#include "nps_ivy.h"
#include <stdlib.h>
#include <stdio.h>
#include <sys/types.h>
#include <unistd.h>
#include <Ivy/ivy.h>
#include <Ivy/ivyloop.h>
#include <pthread.h>
#include "generated/airframe.h"
#include "math/pprz_algebra_float.h"
#include "math/pprz_algebra_double.h"
#include "nps_main.h"
#include "nps_autopilot.h"
#include "nps_fdm.h"
#include "nps_sensors.h"
#include "nps_atmosphere.h"
#include "generated/settings.h"
#include "pprzlink/dl_protocol.h"
#include "subsystems/datalink/downlink.h"
#include "subsystems/gps.h"
#include <NPS_SENSORS_PARAMS>
Functions
static void on_WORLD_ENV (IvyClientPtr app, void *user_data, int argc, char *argv[])
static void on_DL_SETTING (IvyClientPtr app, void *user_data, int argc, char *argv[])
void * ivy_main_loop (void *data)
int find_launch_index (void)
void nps_ivy_init (char *ivy_bus)
void nps_ivy_send_WORLD_ENV_REQ (void)
void nps_ivy_display (struct NpsFdm *fdm_data, struct NpsSensors *sensors_data)
Variables
pthread_t th_ivy_main
static MsgRcvPtr ivyPtr = NULL
static int seq = 1
static int ap_launch_index
Function Documentation
find_launch_index()
int find_launch_index (void)
Definition at line 155 of file nps_ivy.c.
References idx.
Referenced by nps_ivy_init().
ivy_main_loop()
void * ivy_main_loop (void * data)
Definition at line 52 of file nps_ivy.c.
Referenced by nps_ivy_init().
nps_ivy_display()
void nps_ivy_display (struct NpsFdm * fdm_data, struct NpsSensors * sensors_data)
Definition at line 205 of file nps_ivy.c.
References NpsSensors::accel, NpsFdm::agl, LlaCoor_d::alt, NpsSensorGyro::bias_initial, NpsSensorGyro::bias_random_walk_value, NpsFdm::body_ecef_rotvel, double_quat_vmult(), NpsSensors::gyro, NpsFdm::hmsl, LlaCoor_d::lat, NpsFdm::lla_pos_geoc, NpsFdm::lla_pos_geod, NpsFdm::lla_pos_pprz, LlaCoor_d::lon, NpsFdm::ltp_h, NpsFdm::ltp_to_body_eulers, NpsFdm::ltp_to_body_quat, NpsFdm::ltpprz_ecef_accel, NpsFdm::ltpprz_ecef_vel, NpsFdm::ltpprz_pos, NpsSensorAccel::neutral, nps_ivy_send_world_env, nps_ivy_send_WORLD_ENV_REQ(), DoubleRates::p, DoubleEulers::phi, DoubleEulers::psi, DoubleRates::q, DoubleRates::r, RATE_FLOAT_OF_BFP, DoubleEulers::theta, NpsSensorAccel::value, NpsFdm::wind, DoubleVect3::x, NedCoor_d::x, DoubleVect3::y, NedCoor_d::y, DoubleVect3::z, and NedCoor_d::z.
Referenced by nps_main_display().
nps_ivy_init()
void nps_ivy_init (char * ivy_bus)
Definition at line 59 of file nps_ivy.c.
References ap_launch_index, find_launch_index(), ivy_main_loop(), nps_ivy_send_world_env, on_DL_SETTING(), on_WORLD_ENV(), and th_ivy_main.
Referenced by nps_main_display().
nps_ivy_send_WORLD_ENV_REQ()
void nps_ivy_send_WORLD_ENV_REQ (void)
Definition at line 125 of file nps_ivy.c.
References fdm, NpsFdm::hmsl, ivyPtr, LlaCoor_d::lat, NpsFdm::lla_pos_pprz, LlaCoor_d::lon, NpsFdm::ltpprz_pos, nps_ivy_send_world_env, on_WORLD_ENV(), seq, NedCoor_d::x, NedCoor_d::y, and NedCoor_d::z.
Referenced by nps_ivy_display().
on_DL_SETTING()
static void on_DL_SETTING (IvyClientPtr app, void * user_data, int argc, char * argv[]) static
Definition at line 170 of file nps_ivy.c.
References ap_launch_index, DefaultChannel, DefaultDevice, and nps_update_launch_from_dl().
Referenced by nps_ivy_init().
on_WORLD_ENV()
static void on_WORLD_ENV (IvyClientPtr app, void * user_data, int argc, char * argv[]) static
Definition at line 95 of file nps_ivy.c.
References gps_has_fix, nps_atmosphere_set_wind_ned(), nps_set_time_factor(), FloatVect3::x, FloatVect3::y, and FloatVect3::z.
Referenced by nps_ivy_init(), and nps_ivy_send_WORLD_ENV_REQ().
Variable Documentation
ap_launch_index
int ap_launch_index static
Definition at line 34 of file nps_ivy.c.
Referenced by nps_ivy_init(), and on_DL_SETTING().
ivyPtr
MsgRcvPtr ivyPtr = NULL static
Definition at line 32 of file nps_ivy.c.
Referenced by nps_ivy_send_WORLD_ENV_REQ().
seq
int seq = 1 static
Definition at line 33 of file nps_ivy.c.
Referenced by escape_process(), mavlink_send_block(), mavlink_send_wp(), and nps_ivy_send_WORLD_ENV_REQ().
th_ivy_main
pthread_t th_ivy_main
Definition at line 31 of file nps_ivy.c.
Referenced by nps_ivy_init().