Paparazzi UAS: sw/simulator/nps/nps_sensor_mag.h File Reference
nps_sensor_mag.h File Reference
#include "math/pprz_algebra.h"
#include "math/pprz_algebra_double.h"
#include "math/pprz_algebra_float.h"
#include "std.h"
Data Structures
struct NpsSensorMag
Functions
void nps_sensor_mag_init (struct NpsSensorMag *mag, double time)
void nps_sensor_mag_run_step (struct NpsSensorMag *mag, double time, struct DoubleRMat *body_to_imu)
Data Structure Documentation
NpsSensorMag
struct NpsSensorMag
Definition at line 9 of file nps_sensor_mag.h.
Data Fields
bool data_available
struct DoubleRMat imu_to_sensor_rmat
int max
int min
struct DoubleVect3 neutral
double next_update
struct DoubleVect3 noise_std_dev
struct DoubleMat33 sensitivity
struct DoubleVect3 value
Function Documentation
nps_sensor_mag_init()
void nps_sensor_mag_init (struct NpsSensorMag * mag, double time)
Definition at line 8 of file nps_sensor_mag.c.
References NpsSensorMag::data_available, double_rmat_of_eulers(), FALSE, FLOAT_MAT33_DIAG, NpsSensorMag::imu_to_sensor_rmat, NpsSensorMag::max, NpsSensorMag::min, NpsSensorMag::neutral, NpsSensorMag::next_update, NpsSensorMag::noise_std_dev, NpsSensorMag::sensitivity, NpsSensorMag::value, and VECT3_ASSIGN.
Referenced by nps_sensors_init().
nps_sensor_mag_run_step()
void nps_sensor_mag_run_step (struct NpsSensorMag * mag, double time, struct DoubleRMat * body_to_imu)
Definition at line 26 of file nps_sensor_mag.c.
References body_to_imu, NpsSensorMag::data_available, double_quat_vmult(), DOUBLE_VECT3_ROUND, fdm, NpsSensorMag::imu_to_sensor_rmat, NpsFdm::ltp_h, NpsFdm::ltp_to_body_quat, MAT33_VECT3_MUL, NpsSensorMag::max, NpsSensorMag::min, NpsSensorMag::neutral, NpsSensorMag::next_update, NpsSensorMag::sensitivity, TRUE, NpsSensorMag::value, VECT3_ADD, and VECT3_BOUND_CUBE.
Referenced by nps_sensors_run_step().