Paparazzi UAS: sw/simulator/nps/nps_sensor_sideslip.h File Reference
nps_sensor_sideslip.h File Reference
#include "math/pprz_algebra.h"
#include "math/pprz_algebra_double.h"
#include "math/pprz_algebra_float.h"
#include "std.h"
Data Structures
struct NpsSensorSideSlip
Functions
void nps_sensor_sideslip_init (struct NpsSensorSideSlip *sideslip, double time)
void nps_sensor_sideslip_run_step (struct NpsSensorSideSlip *sideslip, double time)
Detailed Description
Simulated Angle Of Attack of the Wind for NPS simulator.
Definition in file nps_sensor_sideslip.h.
Data Structure Documentation
NpsSensorSideSlip
struct NpsSensorSideSlip
Definition at line 36 of file nps_sensor_sideslip.h.
Data Fields
bool data_available
double next_update
double noise_std_dev noise standard deviation
double offset offset in meters/second
double value sideslip reading in radian
Function Documentation
nps_sensor_sideslip_init()
void nps_sensor_sideslip_init (struct NpsSensorSideSlip * sideslip, double time)
Definition at line 53 of file nps_sensor_sideslip.c.
References NpsSensorSideSlip::data_available, FALSE, NpsSensorSideSlip::next_update, NpsSensorSideSlip::noise_std_dev, NPS_SIDESLIP_NOISE_STD_DEV, NPS_SIDESLIP_OFFSET, NpsSensorSideSlip::offset, and NpsSensorSideSlip::value.
Referenced by nps_sensors_init().
nps_sensor_sideslip_run_step()
void nps_sensor_sideslip_run_step (struct NpsSensorSideSlip * sideslip, double time)
Definition at line 63 of file nps_sensor_sideslip.c.
References NpsSensorSideSlip::data_available, fdm, get_gaussian_noise(), NpsSensorSideSlip::next_update, NpsSensorSideSlip::noise_std_dev, NPS_SIDESLIP_DT, NpsSensorSideSlip::offset, NpsFdm::sideslip, TRUE, and NpsSensorSideSlip::value.
Referenced by nps_sensors_run_step().