Paparazzi UAS: sw/simulator/nps/nps_sensor_sonar.h File Reference
nps_sensor_sonar.h File Reference
#include "math/pprz_algebra.h"
#include "math/pprz_algebra_double.h"
#include "math/pprz_algebra_float.h"
#include "std.h"
Data Structures
struct NpsSensorSonar
Functions
void nps_sensor_sonar_init (struct NpsSensorSonar *sonar, double time)
void nps_sensor_sonar_run_step (struct NpsSensorSonar *sonar, double time)
Detailed Description
Simulated sonar for NPS simulator.
Definition in file nps_sensor_sonar.h.
Data Structure Documentation
NpsSensorSonar
struct NpsSensorSonar
Definition at line 37 of file nps_sensor_sonar.h.
Data Fields
bool data_available
double next_update
double noise_std_dev noise standard deviation
double offset offset in meters
double value sonar reading in meters
Function Documentation
nps_sensor_sonar_init()
void nps_sensor_sonar_init (struct NpsSensorSonar * sonar, double time)
Definition at line 53 of file nps_sensor_sonar.c.
References FALSE, NPS_SONAR_NOISE_STD_DEV, NPS_SONAR_OFFSET, and sonar.
Referenced by nps_sensors_init().
nps_sensor_sonar_run_step()
void nps_sensor_sonar_run_step (struct NpsSensorSonar * sonar, double time)
Definition at line 63 of file nps_sensor_sonar.c.
References NpsFdm::agl, fdm, get_gaussian_noise(), NPS_SONAR_DT, sonar, and TRUE.
Referenced by nps_sensors_run_step().