Paparazzi UAS: sw/simulator/nps/nps_flightgear.h File Reference
nps_flightgear.h File Reference
Functions
void nps_flightgear_init (const char *host, unsigned int port, unsigned int port_in, unsigned int time_offset)
void nps_flightgear_send (void)
Send FlightGear GUI packet For visualization of airplane position and attitude only start fgfs with –native-gui=socket...
void nps_flightgear_send_fdm (void)
Send FlightGear FDM packet For visualization with moving surfaces (elevator, propeller etc).
Function Documentation
nps_flightgear_init()
void nps_flightgear_init (const char * host, unsigned int port, unsigned int port_in, unsigned int time_offset)
Definition at line 52 of file nps_flightgear.c.
References flightgear, nps_flightgear_receive(), and th_fg_rx.
Referenced by nps_flight_gear_loop().
nps_flightgear_send()
void nps_flightgear_send (void)
Send FlightGear GUI packet For visualization of airplane position and attitude only start fgfs with –native-gui=socket...
option
This is the default option
Definition at line 179 of file nps_flightgear.c.
References FGNetGUI::agl, LlaCoor_d::alt, FGNetGUI::altitude, FGNetGUI::climb_rate, FGNetGUI::course_deviation_deg, FGNetGUI::cur_time, FGNetGUI::dist_nm, fdm, FG_NET_GUI_VERSION, flightgear, FGNetGUI::fuel_quantity, FGNetGUI::ground_elev, FGNetGUI::gs_deviation_deg, FGNetGUI::in_range, LlaCoor_d::lat, FGNetGUI::latitude, NpsFdm::lla_pos, LlaCoor_d::lon, FGNetGUI::longitude, NpsFdm::ltp_to_body_eulers, FGNetGUI::nav_radial, FGNetGUI::num_tanks, FGNetGUI::padding1, DoubleEulers::phi, FGNetGUI::phi, DoubleEulers::psi, FGNetGUI::psi, DoubleEulers::theta, FGNetGUI::theta, NpsFdm::time, FGNetGUI::tuned_freq, FGNetGUI::vcas, FGNetGUI::version, and FGNetGUI::warp.
Referenced by nps_flight_gear_loop().
nps_flightgear_send_fdm()
void nps_flightgear_send_fdm (void)
Send FlightGear FDM packet For visualization with moving surfaces (elevator, propeller etc).
start fgfs with –native-fdm=socket... option
Definition at line 115 of file nps_flightgear.c.
References NpsFdm::agl, FGNetFDM::agl, LlaCoor_d::alt, FGNetFDM::altitude, FGNetFDM::climb_rate, FGNetFDM::cur_time, NpsFdm::elevator, FGNetFDM::elevator, NpsFdm::eng_state, FGNetFDM::eng_state, fdm, FG_NET_FDM_MAX_ENGINES, FG_NET_FDM_VERSION, NpsFdm::flap, flightgear, FGNetFDM::fuel_quantity, htond(), htonf(), LlaCoor_d::lat, FGNetFDM::latitude, NpsFdm::left_aileron, FGNetFDM::left_aileron, FGNetFDM::left_flap, NpsFdm::lla_pos, LlaCoor_d::lon, FGNetFDM::longitude, NpsFdm::ltp_to_body_eulers, NpsFdm::num_engines, FGNetFDM::num_engines, FGNetFDM::num_tanks, DoubleEulers::phi, FGNetFDM::phi, DoubleEulers::psi, FGNetFDM::psi, NpsFdm::right_aileron, FGNetFDM::right_aileron, FGNetFDM::right_flap, NpsFdm::rpm, FGNetFDM::rpm, NpsFdm::rudder, FGNetFDM::rudder, DoubleEulers::theta, FGNetFDM::theta, NpsFdm::time, FGNetFDM::vcas, FGNetFDM::version, and FGNetFDM::warp.
Referenced by nps_flight_gear_loop().