Paparazzi UAS: sw/airborne/peripherals/mcp355x.h File Reference
mcp355x.h File Reference
#include "std.h"
Functions
void mcp355x_init (void)
void mcp355x_read (void)
void mcp355x_event (void)
Variables
bool mcp355x_data_available
int32_t mcp355x_data
Function Documentation
mcp355x_event()
void mcp355x_event (void)
Definition at line 60 of file mcp355x.c.
References spi_transaction::input_buf, mcp355x_data, mcp355x_data_available, mcp355x_spi_trans, SPITransDone, SPITransFailed, SPITransSuccess, and spi_transaction::status.
Referenced by navgo_baro_event().
mcp355x_init()
void mcp355x_init (void)
Definition at line 36 of file mcp355x.c.
References spi_transaction::bitorder, spi_transaction::cdiv, spi_transaction::cpha, spi_transaction::cpol, spi_transaction::dss, spi_transaction::input_buf, spi_transaction::input_length, mcp355x_data, mcp355x_data_available, mcp355x_spi_trans, mcp355x_val, spi_transaction::output_buf, spi_transaction::output_length, spi_transaction::select, spi_transaction::slave_idx, SPI_SLAVE0, SPICphaEdge1, SPICpolIdleLow, SPIDiv64, SPIDss8bit, SPIMSBFirst, and SPISelect.
Referenced by baro_init().
mcp355x_read()
void mcp355x_read (void)
Definition at line 55 of file mcp355x.c.
References mcp355x_spi_trans, spi1, and spi_submit().
Referenced by baro_periodic().
Variable Documentation
mcp355x_data
int32_t mcp355x_data
Definition at line 31 of file mcp355x.c.
Referenced by mcp355x_event(), mcp355x_init(), and navgo_baro_event().
mcp355x_data_available
bool mcp355x_data_available
Definition at line 30 of file mcp355x.c.
Referenced by mcp355x_event(), mcp355x_init(), and navgo_baro_event().