Paparazzi UAS: sw/airborne/modules/px4_flash/px4_flash.h File Reference
px4_flash.h File Reference
Functions
void px4flash_init (void)
void px4flash_event (void)
Detailed Description
Author
Kevin van Hecke Enables to flashes the px4 FBW and AP through the original px4 bootloader. Assumes the flash port on the Pixhawk is configured as the usb.
Definition in file px4_flash.h.
Function Documentation
px4flash_event()
void px4flash_event (void)
Definition at line 79 of file px4_flash.c.
References b, B115200, B230400, IOPacket::count_code, IOPacket::crc, crc_packet(), FALSE, FLASH_PORT, intermcu_set_enabled(), IOPacket::offset, p, IOPacket::page, PKT_CODE_SUCCESS, PROTO_EOC, PROTO_GET_SYNC, PROTO_INSYNC, PX4IO_P_SETUP_REBOOT_BL, PX4IO_PAGE_SETUP, PX4IO_REBOOT_BL_MAGIC, px4ioRebootTimeout, IOPacket::regs, setToBootloaderMode, state, sys_time_cancel_timer(), sys_time_check_and_ack_timer(), sys_time_register_timer(), sys_time_usleep(), target, TRUE, and uart_periph_set_baudrate().
px4flash_init()
void px4flash_init (void)
Definition at line 70 of file px4_flash.c.
References px4ioRebootTimeout, setToBootloaderMode, and sys_time_register_timer().