Paparazzi UAS: sw/airborne/modules/relative_localization_filter/relative_localization_filter.h File Reference
relative_localization_filter.h File Reference
Functions
void relative_localization_filter_init (void)
void relative_localization_filter_periodic (void)
Detailed Description
Author
Mario Coppola Relative Localization Filter for collision avoidance between drones
Definition in file relative_localization_filter.h.
Function Documentation
relative_localization_filter_init()
void relative_localization_filter_init (void)
Definition at line 128 of file relative_localization_filter.c.
References DefaultPeriodic, id_array, int32_vect_set_value(), number_filters, pprzmsg_cnt, range_communication_event, range_msg_callback(), register_periodic_telemetry(), RELATIVE_LOCALIZATION_N_UAVS, send_relative_localization_data(), and UWB_COMM_ID.
relative_localization_filter_periodic()
void relative_localization_filter_periodic (void)
Definition at line 139 of file relative_localization_filter.c.
References ekf_rl, f, id_array, number_filters, RELATIVE_LOCALIZATION_ID, and mesonh.mesonh_atmosphere::X.