Paparazzi UAS: sw/airborne/mcu_periph/rng.h File Reference
rng.h File Reference
arch independent Random Number Generator API
#include <inttypes.h>
#include "std.h"
Functions
void rng_init (void)
void rng_deinit (void)
bool rng_get (uint32_t *rand_nr)
uint32_t rng_wait_and_get (void)
Detailed Description
arch independent Random Number Generator API
Definition in file rng.h.
Function Documentation
rng_deinit()
void rng_deinit (void)
Definition at line 82 of file rng_arch.c.
References TRNGStop().
rng_get()
bool rng_get (uint32_t * rand_nr)
Definition at line 89 of file rng_arch.c.
References fd, last, TRNGClearErrors(), and TRNGGenerate().
Referenced by rng_wait_and_get().
rng_init()
void rng_init (void)
Definition at line 77 of file rng_arch.c.
References last, rng_wait_and_get(), and TRNGStart().
Referenced by mcu_init().
rng_wait_and_get()
uint32_t rng_wait_and_get (void)
Definition at line 104 of file rng_arch.c.
References last, rng_get(), and TRNGGenerate().
Referenced by gec_generate_ephemeral_keys(), and rng_init().