Paparazzi UAS: sw/airborne/firmwares/rotorcraft/main_ap.c File Reference
main_ap.c File Reference
#include <inttypes.h>
#include "mcu.h"
#include "mcu_periph/sys_time.h"
#include "led.h"
#include "subsystems/datalink/telemetry.h"
#include "subsystems/datalink/datalink.h"
#include "subsystems/datalink/downlink.h"
#include "subsystems/settings.h"
#include "subsystems/commands.h"
#include "subsystems/actuators.h"
#include "subsystems/imu.h"
#include "subsystems/gps.h"
#include "subsystems/electrical.h"
#include "autopilot.h"
#include "subsystems/radio_control.h"
#include "subsystems/ahrs.h"
#include "state.h"
#include "firmwares/rotorcraft/main_ap.h"
#include "generated/modules.h"
#include "subsystems/abi.h"
#include "subsystems/navigation/waypoints.h"
Macros
#define MODULES_C
#define ABI_C
#define RC_LOST_MODE AP_MODE_FAILSAFE
mode to enter when RC is lost while using a mode with RC input (not AP_MODE_NAV)
Functions
void main_init (void)
void handle_periodic_tasks (void)
void main_periodic (void)
void telemetry_periodic (void)
void failsafe_check (void)
void main_event (void)
Variables
tid_t main_periodic_tid
id for main_periodic() timer
tid_t modules_tid
id for modules_periodic_task() timer
tid_t failsafe_tid
id for failsafe_check() timer
tid_t radio_control_tid
id for radio_control_periodic_task() timer
tid_t electrical_tid
id for electrical_periodic() timer
tid_t telemetry_tid
id for telemetry_periodic() timer
Detailed Description
Rotorcraft main loop.
Definition in file main_ap.c.
Macro Definition Documentation
ABI_C
#define ABI_C
Definition at line 31 of file main_ap.c.
MODULES_C
#define MODULES_C
Definition at line 29 of file main_ap.c.
RC_LOST_MODE
#define RC_LOST_MODE AP_MODE_FAILSAFE
mode to enter when RC is lost while using a mode with RC input (not AP_MODE_NAV)
Definition at line 291 of file main_ap.c.
Function Documentation
failsafe_check()
void failsafe_check (void)
Definition at line 294 of file main_ap.c.
Referenced by handle_periodic_tasks(), and main_init().
handle_periodic_tasks()
void handle_periodic_tasks (void)
Definition at line 202 of file main_ap.c.
main_event()
void main_event (void) inline
Definition at line 336 of file main_ap.c.
main_init()
void main_init (void) inline
Definition at line 118 of file main_ap.c.
main_periodic()
void main_periodic (void) inline
Definition at line 237 of file main_ap.c.
Referenced by handle_periodic_tasks().
telemetry_periodic()
void telemetry_periodic (void)
Definition at line 270 of file main_ap.c.
Referenced by handle_periodic_tasks().
Variable Documentation
electrical_tid
tid_t electrical_tid
id for electrical_periodic() timer
Definition at line 112 of file main_ap.c.
Referenced by handle_periodic_tasks(), and main_init().
failsafe_tid
tid_t failsafe_tid
id for failsafe_check() timer
Definition at line 110 of file main_ap.c.
Referenced by handle_periodic_tasks(), and main_init().
main_periodic_tid
tid_t main_periodic_tid
id for main_periodic() timer
Definition at line 108 of file main_ap.c.
Referenced by handle_periodic_tasks(), and main_init().
modules_tid
tid_t modules_tid
id for modules_periodic_task() timer
Definition at line 109 of file main_ap.c.
radio_control_tid
tid_t radio_control_tid
id for radio_control_periodic_task() timer
Definition at line 111 of file main_ap.c.
Referenced by handle_periodic_tasks(), and main_init().
telemetry_tid
tid_t telemetry_tid
id for telemetry_periodic() timer
Definition at line 113 of file main_ap.c.