Paparazzi UAS: sw/airborne/firmwares/rotorcraft/autopilot_generated.c File Reference
autopilot_generated.c File Reference
#include "firmwares/rotorcraft/autopilot_generated.h"
#include "autopilot.h"
#include "autopilot_arming.h"
#include "subsystems/radio_control.h"
#include "subsystems/commands.h"
#include "subsystems/actuators.h"
#include "subsystems/settings.h"
#include "subsystems/datalink/telemetry.h"
#include "generated/settings.h"
Macros
#define AUTOPILOT_CORE_AP_C
Functions
void autopilot_generated_init (void)
void autopilot_generated_periodic (void)
void autopilot_generated_SetModeHandler (float mode)
AP mode setting handler.
void autopilot_generated_set_mode (uint8_t new_autopilot_mode)
void autopilot_generated_set_motors_on (bool motors_on)
void autopilot_generated_on_rc_frame (void)
Detailed Description
Generated autopilot implementation.
Definition in file autopilot_generated.c.
Macro Definition Documentation
AUTOPILOT_CORE_AP_C
#define AUTOPILOT_CORE_AP_C
Definition at line 27 of file autopilot_generated.c.
Function Documentation
autopilot_generated_init()
void autopilot_generated_init (void)
Definition at line 42 of file autopilot_generated.c.
References autopilot, autopilot_arming_init(), and pprz_autopilot::mode.
autopilot_generated_on_rc_frame()
void autopilot_generated_on_rc_frame (void)
Definition at line 104 of file autopilot_generated.c.
References ap_ahrs_is_aligned(), AP_ARMING_STATUS_AHRS_NOT_ALLIGNED, pprz_autopilot::arming_status, autopilot, autopilot_arming_check_motors_on(), pprz_autopilot::kill_throttle, and pprz_autopilot::motors_on.
autopilot_generated_periodic()
void autopilot_generated_periodic (void)
Definition at line 54 of file autopilot_generated.c.
References autopilot, autopilot_in_flight(), pprz_autopilot::detect_ground_once, pprz_autopilot::ground_detected, and pprz_autopilot::mode.
autopilot_generated_set_mode()
void autopilot_generated_set_mode (uint8_t new_autopilot_mode)
Definition at line 81 of file autopilot_generated.c.
References autopilot, and pprz_autopilot::mode.
autopilot_generated_set_motors_on()
void autopilot_generated_set_motors_on (bool motors_on)
Definition at line 89 of file autopilot_generated.c.
References ap_ahrs_is_aligned(), AP_MODE_KILL, autopilot, autopilot_arming_set(), pprz_autopilot::mode, and pprz_autopilot::motors_on.
autopilot_generated_SetModeHandler()
void autopilot_generated_SetModeHandler (float mode)
AP mode setting handler.
FIXME generated something else for this?
Definition at line 75 of file autopilot_generated.c.
References autopilot_generated_set_mode(), and mode.