Paparazzi UAS: sw/airborne/firmwares/rover/main_chibios.c File Reference
main_chibios.c File Reference
#include "mcu_periph/sys_time.h"
#include "mcu.h"
#include <ch.h>
#include "firmwares/rotorcraft/main_ap.h"
Macros
#define THD_WORKING_AREA_MAIN 8192
Functions
static void thd_ap (void *arg)
THD_WORKING_AREA (wa_thd_ap, THD_WORKING_AREA_MAIN)
int main (void)
Main function.
void pprz_terminate_autopilot_threads (void)
Terminate all autopilot threads Wait until proper stop.
Variables
static thread_t * apThdPtr = NULL
Macro Definition Documentation
THD_WORKING_AREA_MAIN
#define THD_WORKING_AREA_MAIN 8192
Definition at line 40 of file main_chibios.c.
Function Documentation
main()
int main (void)
Main function.
Definition at line 54 of file main_chibios.c.
References apThdPtr, main_init(), thd_ap(), and TRUE.
pprz_terminate_autopilot_threads()
void pprz_terminate_autopilot_threads (void)
Terminate all autopilot threads Wait until proper stop.
Definition at line 94 of file main_chibios.c.
References apThdPtr, and fbwThdPtr.
thd_ap()
static void thd_ap (void * arg) static
Definition at line 76 of file main_chibios.c.
References handle_periodic_tasks(), and main_event().
Referenced by main().
THD_WORKING_AREA()
THD_WORKING_AREA (wa_thd_ap , THD_WORKING_AREA_MAIN)
Variable Documentation
apThdPtr
thread_t* apThdPtr = NULL static
Definition at line 49 of file main_chibios.c.
Referenced by main(), and pprz_terminate_autopilot_threads().