Paparazzi UAS: sw/airborne/arch/chibios/mcu_periph/sdio_arch.c File Reference
sdio_arch.c File Reference
#include "std.h"
#include <string.h>
#include <ch.h>
#include <hal.h>
#include "mcu_periph/sdio.h"
#include <stdarg.h>
#include "mcu_periph/gpio.h"
#include <BOARD_CONFIG>
Enumerations
enum { STOP, CONNECT }
Functions
bool sdio_connect (void)
Connect a SD card on SDIO peripheral.
bool sdio_disconnect (void)
Disconnect a SD card on SDIO peripheral.
bool is_card_inserted (void)
Check if a SD card is inserted.
Variables
static enum { ... } cnxState = STOP
Detailed Description
SDIO interface using ChibiOS API for Paparazzi
Definition in file sdio_arch.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
STOP
CONNECT
Definition at line 45 of file sdio_arch.c.
Function Documentation
is_card_inserted()
bool is_card_inserted (void)
Check if a SD card is inserted.
Definition at line 99 of file sdio_arch.c.
sdio_connect()
bool sdio_connect (void)
Connect a SD card on SDIO peripheral.
Definition at line 48 of file sdio_arch.c.
References cnxState, CONNECT, FALSE, mode, SDIO_AF, SDIO_CK_PIN, SDIO_CK_PORT, SDIO_CMD_PIN, SDIO_CMD_PORT, SDIO_D0_PIN, SDIO_D0_PORT, SDIO_D1_PIN, SDIO_D1_PORT, SDIO_D2_PIN, SDIO_D2_PORT, SDIO_D3_PIN, SDIO_D3_PORT, and TRUE.
Referenced by sdLogInit(), and thdUsbStorage().
sdio_disconnect()
bool sdio_disconnect (void)
Disconnect a SD card on SDIO peripheral.
Definition at line 87 of file sdio_arch.c.
References cnxState, FALSE, STOP, and TRUE.
Referenced by sdLogInit().
Variable Documentation
cnxState
enum { ... } cnxState
Referenced by sdio_connect(), and sdio_disconnect().