Paparazzi UAS: sw/airborne/mcu_periph/sdio.h File Reference
sdio.h File Reference
arch independent SDIO API
Functions
bool sdio_connect (void)
Connect a SD card on SDIO peripheral.
bool sdio_disconnect (void)
Disconnect a SD card on SDIO peripheral.
bool is_card_inserted (void)
Check if a SD card is inserted.
Detailed Description
arch independent SDIO API
Definition in file sdio.h.
Function Documentation
is_card_inserted()
bool is_card_inserted (void)
Check if a SD card is inserted.
Definition at line 99 of file sdio_arch.c.
sdio_connect()
bool sdio_connect (void)
Connect a SD card on SDIO peripheral.
Definition at line 48 of file sdio_arch.c.
References cnxState, CONNECT, FALSE, mode, SDIO_AF, SDIO_CK_PIN, SDIO_CK_PORT, SDIO_CMD_PIN, SDIO_CMD_PORT, SDIO_D0_PIN, SDIO_D0_PORT, SDIO_D1_PIN, SDIO_D1_PORT, SDIO_D2_PIN, SDIO_D2_PORT, SDIO_D3_PIN, SDIO_D3_PORT, and TRUE.
Referenced by sdLogInit(), and thdUsbStorage().
sdio_disconnect()
bool sdio_disconnect (void)
Disconnect a SD card on SDIO peripheral.
Definition at line 87 of file sdio_arch.c.
References cnxState, FALSE, STOP, and TRUE.
Referenced by sdLogInit().