Paparazzi UAS: sw/airborne/modules/sensors/trigger_ext.c File Reference
trigger_ext.c File Reference
#include "trigger_ext.h"
#include "modules/sensors/trig_ext_hw.h"
#include "subsystems/gps.h"
#include "mcu_periph/sys_time.h"
#include "mcu_periph/uart.h"
#include "pprzlink/messages.h"
#include "subsystems/datalink/downlink.h"
Functions
void trigger_ext_init (void)
void trigger_ext_periodic (void)
Detailed Description
Measure external trigger pulse at PPM input
This measures a trigger pulse length (e.g. duration of a wind turbine rotation) and sends a message with the info.
Definition in file trigger_ext.c.
Function Documentation
trigger_ext_init()
void trigger_ext_init (void)
Definition at line 41 of file trigger_ext.c.
References T0CCR, trig_ext_init(), TRIG_EXT_PINSEL, TRIG_EXT_PINSEL_BIT, TRIG_EXT_PINSEL_VAL, TRIGGER_CRF, TRIGGER_CRI, TRIGGER_CRR, and trigger_ext_valid.
trigger_ext_periodic()
void trigger_ext_periodic (void)
Definition at line 46 of file trigger_ext.c.
References ac_id, DefaultChannel, DefaultDevice, delta_t0, gps_tow_from_sys_ticks(), msec_of_sys_time_ticks(), trig_ext_valid, trigger_t0, and TRUE.