Paparazzi UAS: sw/airborne/arch/sim/modules/actuators/actuators_dshot_arch.c File Reference
actuators_dshot_arch.c File Reference
#include "modules/actuators/actuators_dshot.h"
Functions
void actuators_dshot_arch_init (void)
Arch dependent init.
void actuators_dshot_arch_commit (void)
Variables
uint16_t actuators_dshot_values [ACTUATORS_DSHOT_NB]
Function Documentation
actuators_dshot_arch_commit()
void actuators_dshot_arch_commit (void)
Definition at line 34 of file actuators_dshot_arch.c.
References actuators_dshot_values, DSHOT_SERVO_0, DSHOT_SERVO_0_CHANNEL, DSHOT_SERVO_0_DRIVER, DSHOT_SERVO_1, DSHOT_SERVO_10, DSHOT_SERVO_10_CHANNEL, DSHOT_SERVO_10_DRIVER, DSHOT_SERVO_1_CHANNEL, DSHOT_SERVO_1_DRIVER, DSHOT_SERVO_2, DSHOT_SERVO_2_CHANNEL, DSHOT_SERVO_2_DRIVER, DSHOT_SERVO_3, DSHOT_SERVO_3_CHANNEL, DSHOT_SERVO_3_DRIVER, DSHOT_SERVO_4, DSHOT_SERVO_4_CHANNEL, DSHOT_SERVO_4_DRIVER, DSHOT_SERVO_5, DSHOT_SERVO_5_CHANNEL, DSHOT_SERVO_5_DRIVER, DSHOT_SERVO_7, DSHOT_SERVO_7_CHANNEL, DSHOT_SERVO_7_DRIVER, DSHOT_SERVO_8, DSHOT_SERVO_8_CHANNEL, DSHOT_SERVO_8_DRIVER, DSHOT_SERVO_9, DSHOT_SERVO_9_CHANNEL, DSHOT_SERVO_9_DRIVER, dshotSendFrame(), and dshotSetThrottle().
actuators_dshot_arch_init()
void actuators_dshot_arch_init (void)
Arch dependent init.
Definition at line 32 of file actuators_dshot_arch.c.
References DSHOT_SERVO_0_AF, DSHOT_SERVO_0_GPIO, DSHOT_SERVO_0_PIN, DSHOT_SERVO_10_AF, DSHOT_SERVO_10_GPIO, DSHOT_SERVO_10_PIN, DSHOT_SERVO_1_AF, DSHOT_SERVO_1_GPIO, DSHOT_SERVO_1_PIN, DSHOT_SERVO_2_AF, DSHOT_SERVO_2_GPIO, DSHOT_SERVO_2_PIN, DSHOT_SERVO_3_AF, DSHOT_SERVO_3_GPIO, DSHOT_SERVO_3_PIN, DSHOT_SERVO_4_AF, DSHOT_SERVO_4_GPIO, DSHOT_SERVO_4_PIN, DSHOT_SERVO_5_AF, DSHOT_SERVO_5_GPIO, DSHOT_SERVO_5_PIN, DSHOT_SERVO_7_AF, DSHOT_SERVO_7_GPIO, DSHOT_SERVO_7_PIN, DSHOT_SERVO_8_AF, DSHOT_SERVO_8_GPIO, DSHOT_SERVO_8_PIN, DSHOT_SERVO_9_AF, DSHOT_SERVO_9_GPIO, DSHOT_SERVO_9_PIN, dshotStart(), and gpio_setup_pin_af().
Variable Documentation
actuators_dshot_values
uint16_t actuators_dshot_values[ACTUATORS_DSHOT_NB]
Definition at line 30 of file actuators_dshot_arch.c.