Paparazzi UAS: sw/airborne/arch/sim/mcu_periph/uart_arch.c File Reference
uart_arch.c File Reference
#include <BOARD_CONFIG>
#include "mcu_periph/uart.h"
#include <stdint.h>
#include <unistd.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include "serial_port.h"
#include "rt_priority.h"
#include <pthread.h>
#include <sys/select.h>
Macros
#define UART_THREAD_PRIO 11
#define TRACE(fmt, args...)
Functions
static void uart_receive_handler (struct uart_periph *periph)
static void * uart_thread (void *data)
void uart_arch_init (void)
static void uart_periph_open (struct uart_periph *periph, uint32_t baud)
void uart_periph_set_baudrate (struct uart_periph *periph, uint32_t baud)
Set baudrate.
void uart_periph_set_bits_stop_parity (struct uart_periph *periph, uint8_t bits, uint8_t stop, uint8_t parity)
Set parity and stop bits.
void uart_put_byte (struct uart_periph *periph, long fd, uint8_t data)
Uart transmit implementation.
uint8_t uart_getch (struct uart_periph *p)
int uart_char_available (struct uart_periph *p)
Check UART for available chars in receive buffer.
Variables
static pthread_mutex_t uart_mutex = PTHREAD_MUTEX_INITIALIZER
Macro Definition Documentation
TRACE
#define TRACE (fmt, args...)
Definition at line 52 of file uart_arch.c.
UART_THREAD_PRIO
#define UART_THREAD_PRIO 11
Definition at line 44 of file uart_arch.c.
Function Documentation
uart_arch_init()
void uart_arch_init (void)
Definition at line 54 of file uart_arch.c.
References uart_mutex, and uart_thread().
uart_char_available()
int uart_char_available (struct uart_periph * p)
Check UART for available chars in receive buffer.
Returns
number of chars in the buffer
Definition at line 323 of file uart_arch.c.
References p, uart_mutex, and UART_RX_BUFFER_SIZE.
uart_getch()
uint8_t uart_getch (struct uart_periph * p)
Definition at line 314 of file uart_arch.c.
References p, uart_mutex, and UART_RX_BUFFER_SIZE.
uart_periph_open()
static void uart_periph_open (struct uart_periph * periph, uint32_t baud) static
Definition at line 219 of file uart_arch.c.
References uart_periph::baudrate, uart_periph::dev, uart_periph::reg_addr, serial_port_close(), serial_port_free(), serial_port_new(), serial_port_open_raw(), and TRACE.
Referenced by uart_periph_set_baudrate().
uart_periph_set_baudrate()
void uart_periph_set_baudrate (struct uart_periph * periph, uint32_t baud)
Set baudrate.
Definition at line 246 of file uart_arch.c.
References uart_periph::baudrate, uart_periph::reg_addr, serial_port_set_baudrate(), and uart_periph_open().
uart_periph_set_bits_stop_parity()
void uart_periph_set_bits_stop_parity (struct uart_periph * periph, uint8_t bits, uint8_t stop, uint8_t parity)
Set parity and stop bits.
Definition at line 262 of file uart_arch.c.
References uart_periph::reg_addr, and serial_port_set_bits_stop_parity().
uart_put_byte()
void uart_put_byte (struct uart_periph * periph, long fd, uint8_t data)
Uart transmit implementation.
Definition at line 272 of file uart_arch.c.
References SerialPort::fd, uart_periph::reg_addr, and TRACE.
uart_receive_handler()
static void uart_receive_handler (struct uart_periph * periph) static
Definition at line 290 of file uart_arch.c.
References c(), fd, SerialPort::fd, uart_periph::reg_addr, uart_periph::rx_buf, uart_periph::rx_extract_idx, uart_periph::rx_insert_idx, TRACE, uart_mutex, and UART_RX_BUFFER_SIZE.
Referenced by uart_thread().
uart_thread()
static void * uart_thread (void * data) static
Definition at line 68 of file uart_arch.c.
References fd, get_rt_prio(), uart_receive_handler(), and UART_THREAD_PRIO.
Referenced by uart_arch_init().
Variable Documentation
uart_mutex
pthread_mutex_t uart_mutex = PTHREAD_MUTEX_INITIALIZER static
Definition at line 49 of file uart_arch.c.
Referenced by uart_arch_init(), uart_char_available(), uart_getch(), and uart_receive_handler().