Paparazzi UAS: sw/airborne/arch/sim/sim_gps.c File Reference
sim_gps.c File Reference
#include <assert.h>
#include <math.h>
#include <inttypes.h>
#include "generated/airframe.h"
#include "generated/flight_plan.h"
#include "subsystems/gps/gps_sim.h"
#include "math/pprz_geodetic_float.h"
#include "math/pprz_geodetic_int.h"
#include "subsystems/navigation/common_nav.h"
#include <caml/mlvalues.h>
Functions
value sim_use_gps_pos (value x, value y, value z, value c, value a, value s, value cl, value t, value m, value lat, value lon)
From airborne/autopilot/.
value sim_use_gps_pos_bytecode (value *a, int argn)
void ubxsend_cfg_rst (uint16_t a, uint8_t b)
Function Documentation
sim_use_gps_pos()
value sim_use_gps_pos (value x, value y, value z, value c, value a, value s, value cl, value t, value m, value lat, value lon)
From airborne/autopilot/.
Space vehicle info simulation
Definition at line 20 of file sim_gps.c.
References LlaCoor_f::alt, UtmCoor_i::alt, SVinfo::azim, c(), SVinfo::cno, GpsState::course, UtmCoor_i::east, SVinfo::elev, GpsState::fix, SVinfo::flags, gps, gps_sim_publish(), GPS_VALID_COURSE_BIT, GPS_VALID_HMSL_BIT, GPS_VALID_POS_LLA_BIT, GPS_VALID_POS_UTM_BIT, GPS_VALID_VEL_NED_BIT, GpsState::gspeed, GpsState::hmsl, LlaCoor_f::lat, LLA_BFP_OF_REAL, GpsState::lla_pos, LlaCoor_f::lon, GpsState::nb_channels, GpsState::ned_vel, UtmCoor_i::north, GpsState::num_sv, GpsState::pacc, GpsState::pdop, SVinfo::qi, s, GpsState::sacc, SVinfo::svid, GpsState::svinfos, GpsState::tow, GpsState::utm_pos, GpsState::valid_fields, GpsState::week, NedCoor_i::x, NedCoor_i::y, NedCoor_i::z, and UtmCoor_i::zone.
Referenced by sim_use_gps_pos_bytecode().
sim_use_gps_pos_bytecode()
value sim_use_gps_pos_bytecode (value * a, int argn)
Definition at line 72 of file sim_gps.c.
References sim_use_gps_pos().
ubxsend_cfg_rst()
void ubxsend_cfg_rst (uint16_t a, uint8_t b)
Definition at line 78 of file sim_gps.c.