Paparazzi UAS: sw/airborne/firmwares/rotorcraft/stabilization/stabilization_attitude_quat_indi.c File Reference
stabilization_attitude_quat_indi.c File Reference
MAVLab Delft University of Technology This control algorithm is Incremental Nonlinear Dynamic Inversion (INDI)
#include "firmwares/rotorcraft/stabilization/stabilization_attitude.h"
Functions
void stabilization_attitude_init (void)
stabilization_attitude_init
void stabilization_attitude_enter (void)
void stabilization_attitude_set_failsafe_setpoint (void)
void stabilization_attitude_set_rpy_setpoint_i (struct Int32Eulers *rpy)
void stabilization_attitude_set_earth_cmd_i (struct Int32Vect2 *cmd, int32_t heading)
void stabilization_attitude_run (bool in_flight)
void stabilization_attitude_read_rc (bool in_flight, bool in_carefree, bool coordinated_turn)
Detailed Description
MAVLab Delft University of Technology This control algorithm is Incremental Nonlinear Dynamic Inversion (INDI)
MAVLab Delft University of Technology This control algorithm is Incremental Nonlinear Dynamic Inversion (INDI)
This is an implementation of the publication in the journal of Control Guidance and Dynamics: Adaptive Incremental Nonlinear Dynamic Inversion for Attitude Control of Micro Aerial Vehicles
This is an implementation of the publication in the journal of Control Guidance and Dynamics: Adaptive Incremental Nonlinear Dynamic Inversion for Attitude Control of Micro Aerial Vehicles http://arc.aiaa.org/doi/pdf/10.2514/1.G001490
Definition in file stabilization_attitude_quat_indi.c.
Function Documentation
stabilization_attitude_enter()
void stabilization_attitude_enter (void)
Definition at line 43 of file stabilization_attitude_quat_indi.c.
References stabilization_indi_enter().
stabilization_attitude_init()
void stabilization_attitude_init (void)
stabilization_attitude_init
Initialize the heli indi attitude controller.
Definition at line 35 of file stabilization_attitude_quat_indi.c.
References stabilization_indi_init().
stabilization_attitude_read_rc()
void stabilization_attitude_read_rc (bool in_flight, bool in_carefree, bool coordinated_turn)
Definition at line 68 of file stabilization_attitude_quat_indi.c.
References stabilization_indi_read_rc().
stabilization_attitude_run()
void stabilization_attitude_run (bool in_flight)
Definition at line 63 of file stabilization_attitude_quat_indi.c.
References stab_att_sp_quat, and stabilization_indi_attitude_run().
stabilization_attitude_set_earth_cmd_i()
void stabilization_attitude_set_earth_cmd_i (struct Int32Vect2 * cmd, int32_t heading)
Definition at line 58 of file stabilization_attitude_quat_indi.c.
References heading, and stabilization_indi_set_earth_cmd_i().
stabilization_attitude_set_failsafe_setpoint()
void stabilization_attitude_set_failsafe_setpoint (void)
Definition at line 48 of file stabilization_attitude_quat_indi.c.
References stabilization_indi_set_failsafe_setpoint().
stabilization_attitude_set_rpy_setpoint_i()
void stabilization_attitude_set_rpy_setpoint_i (struct Int32Eulers * rpy)
Definition at line 53 of file stabilization_attitude_quat_indi.c.
References stabilization_indi_set_rpy_setpoint_i().