Paparazzi UAS: sw/airborne/firmwares/rotorcraft/stabilization/stabilization_attitude_quat_transformations.c File Reference
stabilization_attitude_quat_transformations.c File Reference
#include "stabilization_attitude_quat_transformations.h"
Functions
void quat_from_rpy_cmd_i (struct Int32Quat *quat, struct Int32Eulers *rpy)
void quat_from_rpy_cmd_f (struct FloatQuat *quat, struct FloatEulers *rpy)
void quat_from_earth_cmd_i (struct Int32Quat *quat, struct Int32Vect2 *cmd, int32_t heading)
void quat_from_earth_cmd_f (struct FloatQuat *quat, struct FloatVect2 *cmd, float heading)
Detailed Description
Quaternion transformation functions.
Definition in file stabilization_attitude_quat_transformations.c.
Function Documentation
quat_from_earth_cmd_f()
void quat_from_earth_cmd_f (struct FloatQuat * quat, struct FloatVect2 * cmd, float heading)
Todo:
optimize yaw angle calculation
Definition at line 63 of file stabilization_attitude_quat_transformations.c.
References b, float_quat_comp(), float_quat_normalize(), float_quat_of_orientation_vect(), float_quat_wrap_shortest(), float_rmat_of_quat(), FLOAT_VECT3_NORM, heading, FloatRMat::m, QUAT_ASSIGN, VECT3_ASSIGN, VECT3_CROSS_PRODUCT, VECT3_DOT_PRODUCT, FloatVect2::x, FloatVect3::x, FloatVect2::y, FloatVect3::y, and FloatVect3::z.
Referenced by quat_from_earth_cmd_i(), and stabilization_attitude_set_earth_cmd_i().
quat_from_earth_cmd_i()
void quat_from_earth_cmd_i (struct Int32Quat * quat, struct Int32Vect2 * cmd, int32_t heading)
Definition at line 48 of file stabilization_attitude_quat_transformations.c.
References ANGLE_FLOAT_OF_BFP, heading, QUAT_BFP_OF_REAL, quat_from_earth_cmd_f(), FloatVect2::x, Int32Vect2::x, FloatVect2::y, and Int32Vect2::y.
Referenced by stabilization_attitude_set_earth_cmd_i(), and stabilization_indi_set_earth_cmd_i().
quat_from_rpy_cmd_f()
void quat_from_rpy_cmd_f (struct FloatQuat * quat, struct FloatEulers * rpy)
Definition at line 37 of file stabilization_attitude_quat_transformations.c.
References float_quat_of_orientation_vect(), FloatEulers::phi, FloatEulers::psi, and FloatEulers::theta.
Referenced by quat_from_rpy_cmd_i().
quat_from_rpy_cmd_i()
void quat_from_rpy_cmd_i (struct Int32Quat * quat, struct Int32Eulers * rpy)
Definition at line 28 of file stabilization_attitude_quat_transformations.c.
References EULERS_FLOAT_OF_BFP, QUAT_BFP_OF_REAL, and quat_from_rpy_cmd_f().