Paparazzi UAS: sw/airborne/modules/stereocam/droplet/stereocam_droplet.c File Reference
stereocam_droplet.c File Reference
#include "modules/stereocam/droplet/stereocam_droplet.h"
#include "generated/flight_plan.h"
#include "firmwares/rotorcraft/navigation.h"
#include "mcu_periph/uart.h"
#include "pprzlink/messages.h"
#include "subsystems/datalink/downlink.h"
#include "led.h"
Data Structures
struct AvoidNavigationStruct
Macros
#define STEREO_PORT (&((STEREO_UART).device))
#define StereoGetch() STEREO_PORT ->get_byte(STEREO_PORT->periph)
#define StereoSend1(c) STEREO_PORT->put_byte(STEREO_PORT->periph, 0, c)
#define StereoUartSend1(c) StereoSend1(c)
#define StereoSend(_dat, _len) { for (uint8_t i = 0; i< (_len); i++) StereoSend1(_dat[i]); };
#define StereoUartSetBaudrate(_b) uart_periph_set_baudrate(STEREO_PORT, _b);
#define StereoChAvailable() (xdev->char_available(xdev->periph))
#define DOWNLINK_DEVICE DOWNLINK_AP_DEVICE
Functions
static void stereo_parse (uint8_t c)
void stereocam_droplet_init (void)
void stereocam_droplet_periodic (void)
Variables
struct link_device * xdev = STEREO_PORT
struct AvoidNavigationStruct avoid_navigation_data
global VIDEO state
Detailed Description
Author
C. DW
Definition in file stereocam_droplet.c.
Data Structure Documentation
AvoidNavigationStruct
struct AvoidNavigationStruct
Definition at line 69 of file stereocam_droplet.c.
Data Fields
uint8_t mode 0 = straight, 1 = right, 2 = left, ...
0 = nothing, 1 = climb, 2 = sideways, ...
uint8_t stereo_bin[8]
uint8_t timeout
Macro Definition Documentation
DOWNLINK_DEVICE
#define DOWNLINK_DEVICE DOWNLINK_AP_DEVICE
Definition at line 57 of file stereocam_droplet.c.
STEREO_PORT
#define STEREO_PORT (&((STEREO_UART).device))
Definition at line 40 of file stereocam_droplet.c.
StereoChAvailable
#define StereoChAvailable () (xdev->char_available(xdev->periph))
Definition at line 48 of file stereocam_droplet.c.
StereoGetch
#define StereoGetch () STEREO_PORT ->get_byte(STEREO_PORT->periph)
Definition at line 43 of file stereocam_droplet.c.
StereoSend
#define StereoSend (_dat, _len) { for (uint8_t i = 0; i< (_len); i++) StereoSend1(_dat[i]); };
Definition at line 46 of file stereocam_droplet.c.
StereoSend1
#define StereoSend1 (c) STEREO_PORT->put_byte(STEREO_PORT->periph, 0, c)
Definition at line 44 of file stereocam_droplet.c.
StereoUartSend1
#define StereoUartSend1 (c) StereoSend1(c)
Definition at line 45 of file stereocam_droplet.c.
StereoUartSetBaudrate
#define StereoUartSetBaudrate (_b) uart_periph_set_baudrate(STEREO_PORT, _b);
Definition at line 47 of file stereocam_droplet.c.
Function Documentation
stereo_parse()
static void stereo_parse (uint8_t c) static
Definition at line 84 of file stereocam_droplet.c.
References avoid_navigation_data, c(), AvoidNavigationStruct::stereo_bin, and AvoidNavigationStruct::timeout.
Referenced by stereocam_droplet_periodic().
stereocam_droplet_init()
void stereocam_droplet_init (void)
Definition at line 92 of file stereocam_droplet.c.
References avoid_navigation_data, AvoidNavigationStruct::mode, and AvoidNavigationStruct::timeout.
stereocam_droplet_periodic()
void stereocam_droplet_periodic (void)
Definition at line 98 of file stereocam_droplet.c.
References ANGLE_FLOAT_OF_BFP, avoid_navigation_data, DefaultChannel, DefaultDevice, heading, LED_OFF, LED_ON, nav_heading, nav_set_heading_rad(), NavSetWaypointHere, obstacle_detected, AvoidNavigationStruct::stereo_bin, stereo_parse(), StereoChAvailable, StereoGetch, AvoidNavigationStruct::timeout, waypoint_get_alt(), waypoint_get_x(), waypoint_get_y(), waypoint_set_enu(), EnuCoor_f::x, EnuCoor_f::y, and EnuCoor_f::z.
Variable Documentation
avoid_navigation_data
struct AvoidNavigationStruct avoid_navigation_data
global VIDEO state
Definition at line 75 of file stereocam_droplet.c.
Referenced by stereo_avoid_init(), stereo_avoid_run(), stereo_parse(), stereocam_droplet_init(), and stereocam_droplet_periodic().
xdev
struct link_device* xdev = STEREO_PORT
Definition at line 41 of file stereocam_droplet.c.