Paparazzi UAS: sw/airborne/modules/stereocam/droplet/stereocam_droplet.h File Reference
stereocam_droplet.h File Reference
Functions
void stereocam_droplet_init (void)
void stereocam_droplet_periodic (void)
Detailed Description
Author
C. DW
Definition in file stereocam_droplet.h.
Function Documentation
stereocam_droplet_init()
void stereocam_droplet_init (void)
Definition at line 92 of file stereocam_droplet.c.
References avoid_navigation_data, AvoidNavigationStruct::mode, and AvoidNavigationStruct::timeout.
stereocam_droplet_periodic()
void stereocam_droplet_periodic (void)
Definition at line 98 of file stereocam_droplet.c.
References ANGLE_FLOAT_OF_BFP, avoid_navigation_data, DefaultChannel, DefaultDevice, heading, LED_OFF, LED_ON, nav_heading, nav_set_heading_rad(), NavSetWaypointHere, obstacle_detected, AvoidNavigationStruct::stereo_bin, stereo_parse(), StereoChAvailable, StereoGetch, AvoidNavigationStruct::timeout, waypoint_get_alt(), waypoint_get_x(), waypoint_get_y(), waypoint_set_enu(), EnuCoor_f::x, EnuCoor_f::y, and EnuCoor_f::z.