Paparazzi UAS: sw/airborne/arch/stm32/mcu_arch.h File Reference
mcu_arch.h File Reference
stm32 arch dependant microcontroller initialisation functions.
#include "std.h"
#include <BOARD_CONFIG>
Macros
#define MyByteSwap16(in, out)
#define mcu_int_enable() {}
#define mcu_int_disable() {}
Functions
void mcu_arch_init (void)
uint32_t timer_get_frequency (uint32_t timer_peripheral)
Get Timer clock frequency (before prescaling) Only valid if using the internal clock for the timer.
Detailed Description
stm32 arch dependant microcontroller initialisation functions.
Definition in file mcu_arch.h.
Macro Definition Documentation
mcu_int_disable
#define mcu_int_disable () {}
Definition at line 55 of file mcu_arch.h.
mcu_int_enable
#define mcu_int_enable () {}
Definition at line 54 of file mcu_arch.h.
MyByteSwap16
#define MyByteSwap16 (in, out)
Value:
    {                 \
    asm volatile (                              \
        "rev16        %0, %1\n\t"     \
        : "=r" (out)                  \
        : "r"(in)                     \
                 );                            \
  }
Definition at line 46 of file mcu_arch.h.
Function Documentation
mcu_arch_init()
void mcu_arch_init (void)
Definition at line 109 of file mcu_arch.c.
References MAMCR, MAMCR_FULL, MAMTIM, MAMTIM_CYCLES, MEMMAP, MEMMAP_FLASH, PLLCFG, PLLCFG_MSEL, PLLCFG_PSEL, PLLCON, PLLCON_PLLC, PLLCON_PLLE, PLLFEED, PLLSTAT, PLLSTAT_LOCK, PRINT_CONFIG_MSG(), reset(), SCB, VICDefVectAddr, VICIntEnClear, VICIntSelect, VPBDIV, and VPBDIV_VALUE.
Referenced by mcu_init().
timer_get_frequency()
uint32_t timer_get_frequency (uint32_t timer_peripheral)
Get Timer clock frequency (before prescaling) Only valid if using the internal clock for the timer.
Currently implemented for STM32F1x and STM32F405xx/407xx STM32F415xx/417xx. Not valid for STM32F42xxx and STM32F43xxx.
Parameters
[in] timer_peripheral Unsigned int32. Timer register address base
Returns
Unsigned int32. Timer base frequency
Definition at line 311 of file mcu_arch.c.
Referenced by adc_init_rcc(), ppm_arch_init(), pwm_input_set_timer(), and set_servo_timer().