Paparazzi UAS: sw/airborne/arch/stm32/peripherals/ms2100_arch.c File Reference
ms2100_arch.c File Reference
#include "peripherals/ms2100.h"
#include "mcu_periph/sys_time.h"
#include <libopencm3/stm32/rcc.h>
#include <libopencm3/stm32/gpio.h>
#include <libopencm3/stm32/exti.h>
#include <libopencm3/cm3/nvic.h>
Functions
void ms2100_arch_init (void)
void ms2100_reset_cb (struct spi_transaction *t)
Reset callback.
void exti9_5_isr (void)
Detailed Description
STM32 specific functions for the ms2100 magnetic sensor from PNI.
Definition in file ms2100_arch.c.
Function Documentation
exti9_5_isr()
void exti9_5_isr (void)
Definition at line 81 of file ms2100_arch.c.
References ms2100, MS2100_GOT_EOC, and Ms2100::status.
ms2100_arch_init()
void ms2100_arch_init (void)
Definition at line 40 of file ms2100_arch.c.
References _VIC_ADDR, _VIC_CNTL, EXTINT, EXTINT_ISR(), EXTMODE, EXTPOLAR, GPIO13, GPIO5, gpio_set(), GPIOB, GPIOC, MS2100_DRDY_EINT, MS2100_DRDY_PINSEL, MS2100_DRDY_PINSEL_BIT, MS2100_DRDY_PINSEL_VAL, MS2100_DRDY_VIC_IT, MS2100_RESET_IODIR, MS2100_RESET_PIN, Ms2100Reset, VIC_BIT, VIC_ENABLE, VICIntEnable, and VICIntSelect.
ms2100_reset_cb()
void ms2100_reset_cb (struct spi_transaction * t)
Reset callback.
called before spi transaction and after slave select
Definition at line 63 of file ms2100_arch.c.
References cpu_ticks_of_nsec(), Ms2100Reset, Ms2100Set, and T0TC.