Paparazzi UAS: sw/airborne/arch/stm32/mcu_periph/pwm_input_arch.c File Reference
pwm_input_arch.c File Reference
STM32 architecture
#include "mcu_periph/pwm_input.h"
#include <BOARD_CONFIG>
#include "generated/airframe.h"
#include <libopencm3/stm32/rcc.h>
#include <libopencm3/stm32/gpio.h>
#include <libopencm3/stm32/timer.h>
#include <libopencm3/cm3/nvic.h>
#include "mcu_periph/sys_time.h"
#include "mcu_periph/gpio.h"
#include "mcu_arch.h"
Macros
#define ONE_MHZ_CLK 1000000
#define PWM_INPUT_IRQ_PRIO 2
Functions
static void pwm_input_set_timer (uint32_t tim, uint32_t ticks_per_usec)
void pwm_input_init (void)
Detailed Description
handling of smt32 PWM input using a timer with capture.
Definition in file pwm_input_arch.c.
Macro Definition Documentation
ONE_MHZ_CLK
#define ONE_MHZ_CLK 1000000
Definition at line 44 of file pwm_input_arch.c.
PWM_INPUT_IRQ_PRIO
#define PWM_INPUT_IRQ_PRIO 2
Definition at line 48 of file pwm_input_arch.c.
Function Documentation
pwm_input_init()
void pwm_input_init (void)
Configure timers
timer clock enable
base configuration
enable counter
Definition at line 61 of file pwm_input_arch.c.
References FALSE, gpio_setup_pin_af(), PWM_INPUT1_CC_IE, PWM_INPUT1_CHANNEL_DUTY, PWM_INPUT1_CHANNEL_PERIOD, PWM_INPUT1_GPIO_AF, PWM_INPUT1_GPIO_PIN, PWM_INPUT1_GPIO_PORT, PWM_INPUT1_IRQ, PWM_INPUT1_IRQ2, PWM_INPUT1_SLAVE_TRIG, PWM_INPUT1_TIMER, PWM_INPUT1_TIMER_INPUT, PWM_INPUT2_CC_IE, PWM_INPUT2_CHANNEL_DUTY, PWM_INPUT2_CHANNEL_PERIOD, PWM_INPUT2_GPIO_AF, PWM_INPUT2_GPIO_PIN, PWM_INPUT2_GPIO_PORT, PWM_INPUT2_IRQ, PWM_INPUT2_SLAVE_TRIG, PWM_INPUT2_TIMER, PWM_INPUT2_TIMER_INPUT, pwm_input_duty_tics, pwm_input_duty_valid, PWM_INPUT_IRQ_PRIO, PWM_INPUT_NB, pwm_input_period_tics, pwm_input_period_valid, and pwm_input_set_timer().
pwm_input_set_timer()
static void pwm_input_set_timer (uint32_t tim, uint32_t ticks_per_usec) inline static
Definition at line 51 of file pwm_input_arch.c.
References ONE_MHZ_CLK, and timer_get_frequency().
Referenced by pwm_input_init().