Paparazzi UAS: sw/airborne/subsystems/radio_control/rc_datalink.c File Reference
rc_datalink.c File Reference
#include "subsystems/radio_control/rc_datalink.h"
#include "subsystems/radio_control.h"
Functions
void radio_control_impl_init (void)
void parse_rc_3ch_datalink (uint8_t throttle_mode, int8_t roll, int8_t pitch)
Decode datalink message to get rc values with RC_3CH message Mode and throttle are merge in the same byte.
void parse_rc_4ch_datalink (uint8_t mode, uint8_t throttle, int8_t roll, int8_t pitch, int8_t yaw)
Decode datalink message to get rc values with RC_4CH message.
static void rc_datalink_normalize (int8_t *in, int16_t *out)
Normalize rc_dl_values to radio values.
void radio_control_impl_event (void(*_received_frame_handler)(void))
RC event function with handler callback.
Variables
int8_t rc_dl_values [RC_DL_NB_CHANNEL]
volatile bool rc_dl_frame_available
Function Documentation
parse_rc_3ch_datalink()
void parse_rc_3ch_datalink (uint8_t throttle_mode, int8_t roll, int8_t pitch)
Decode datalink message to get rc values with RC_3CH message Mode and throttle are merge in the same byte.
Definition at line 40 of file rc_datalink.c.
References mode, RADIO_MODE, RADIO_PITCH, RADIO_ROLL, RADIO_THROTTLE, RADIO_YAW, rc_dl_frame_available, and rc_dl_values.
Referenced by dl_parse_msg().
parse_rc_4ch_datalink()
void parse_rc_4ch_datalink (uint8_t mode, uint8_t throttle, int8_t roll, int8_t pitch, int8_t yaw)
Decode datalink message to get rc values with RC_4CH message.
Definition at line 56 of file rc_datalink.c.
References mode, RADIO_MODE, RADIO_PITCH, RADIO_ROLL, RADIO_THROTTLE, RADIO_YAW, rc_dl_frame_available, and rc_dl_values.
Referenced by dl_parse_msg(), and mavlink_common_message_handler().
radio_control_impl_event()
void radio_control_impl_event (void(*)(void) _received_frame_handler)
RC event function with handler callback.
PPM frames are normalized using the IIR filter.
Definition at line 89 of file rc_datalink.c.
References RadioControl::frame_cpt, radio_control, RadioControl::radio_ok_cpt, rc_datalink_normalize(), rc_dl_frame_available, rc_dl_values, RC_OK, RadioControl::status, RadioControl::time_since_last_frame, and RadioControl::values.
radio_control_impl_init()
void radio_control_impl_init (void)
Definition at line 34 of file rc_datalink.c.
References rc_dl_frame_available.
rc_datalink_normalize()
static void rc_datalink_normalize (int8_t * in, int16_t * out) static
Normalize rc_dl_values to radio values.
Definition at line 75 of file rc_datalink.c.
References MAX_PPRZ, MIN_PPRZ, RADIO_MODE, RADIO_PITCH, RADIO_ROLL, RADIO_THROTTLE, and RADIO_YAW.
Referenced by radio_control_impl_event().
Variable Documentation
rc_dl_frame_available
volatile bool rc_dl_frame_available
Definition at line 31 of file rc_datalink.c.
Referenced by parse_rc_3ch_datalink(), parse_rc_4ch_datalink(), radio_control_impl_event(), and radio_control_impl_init().
rc_dl_values
int8_t rc_dl_values[RC_DL_NB_CHANNEL]
Definition at line 30 of file rc_datalink.c.
Referenced by parse_rc_3ch_datalink(), parse_rc_4ch_datalink(), and radio_control_impl_event().