Paparazzi UAS: sw/airborne/subsystems/sensors/infrared_adc.h File Reference
infrared_adc.h File Reference
#include "std.h"
#include "subsystems/sensors/infrared.h"
Functions
void infrared_adc_init (void)
Initialisation of ir.
void infrared_adc_update (void)
Update ir_roll and ir_pitch from ADCs or from simulator message in HITL and SITL modes.
Variables
struct Infrared_raw ir_adc
Function Documentation
infrared_adc_init()
void infrared_adc_init (void)
Initialisation of ir.
Initialize adc_buf_channel
Definition at line 71 of file infrared_adc.c.
References adc_buf_channel(), ADC_CHANNEL_IR_NB_SAMPLES, buf_ir1, buf_ir2, infrared_struct_init(), Infrared_raw::ir3, and ir_adc.
Referenced by infrared_init().
infrared_adc_update()
void infrared_adc_update (void)
Update ir_roll and ir_pitch from ADCs or from simulator message in HITL and SITL modes.
Definition at line 92 of file infrared_adc.c.
References adc_buf::av_nb_sample, buf_ir1, buf_ir2, Infrared_raw::ir1, Infrared_raw::ir2, Infrared_raw::ir3, ir_adc, adc_buf::sum, and UpdateIRValue.
Referenced by infrared_update().
Variable Documentation
ir_adc
struct Infrared_raw ir_adc
Definition at line 52 of file infrared_adc.c.
Referenced by infrared_adc_init(), and infrared_adc_update().