Paparazzi UAS: sw/airborne/subsystems/radio_control/superbitrf_rc.c File Reference
superbitrf_rc.c File Reference
#include "superbitrf_rc.h"
#include "subsystems/radio_control.h"
Functions
void radio_control_impl_init (void)
Initialization.
static void superbitrf_rc_normalize (int16_t *in, int16_t *out, uint8_t count)
normalize superbitrf rc_values to radio values
void radio_control_impl_event (void(*_received_frame_handler)(void))
RC event function with handler callback.
Detailed Description
DSM2 and DSMX radio control implementation for the cyrf6936 2.4GHz radio chip trough SPI
Definition in file superbitrf_rc.c.
Function Documentation
radio_control_impl_event()
void radio_control_impl_event (void(*)(void) _received_frame_handler)
RC event function with handler callback.
PPM frames are normalized using the IIR filter.
Definition at line 52 of file superbitrf_rc.c.
References SuperbitRF::cyrf6936, cyrf6936_event(), RadioControl::frame_cpt, frsky_raw, SuperbitRF::num_channels, radio_control, RADIO_CONTROL_NB_CHANNEL, RadioControl::radio_ok_cpt, SuperbitRF::rc_frame_available, RC_OK, SuperbitRF::rc_values, rxRuntimeConfig_s::rcFrameStatusFn, rxRuntimeConfig_s::rcProcessFrameFn, rxRuntimeConfig_s::rcReadRawFn, RX_FRAME_COMPLETE, rxRuntimeConfig, RadioControl::status, superbitrf, superbitrf_event(), superbitrf_rc_normalize(), RadioControl::time_since_last_frame, and RadioControl::values.
radio_control_impl_init()
void radio_control_impl_init (void)
Initialization.
Main Radio initialization.
Definition at line 32 of file superbitrf_rc.c.
References spektrum_available, and superbitrf_init().
superbitrf_rc_normalize()
static void superbitrf_rc_normalize (int16_t * in, int16_t * out, uint8_t count) static
normalize superbitrf rc_values to radio values
Definition at line 38 of file superbitrf_rc.c.
References MAX_PPRZ, MIN_PPRZ, and RADIO_THROTTLE.
Referenced by radio_control_impl_event().