Paparazzi UAS: sw/airborne/boards/swing/baro_board.c File Reference
baro_board.c File Reference
#include "subsystems/sensors/baro.h"
#include "subsystems/abi.h"
#include "baro_board.h"
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <fcntl.h>
#include <unistd.h>
#include <pthread.h>
#include <linux/input.h>
Functions
static void * baro_read (void *data)
Check baro thread TODO something better ?
void baro_init (void)
void baro_periodic (void)
void baro_event (void)
Variables
static bool baro_swing_available
static int32_t baro_swing_raw
static pthread_mutex_t baro_swing_mutex = PTHREAD_MUTEX_INITIALIZER
Detailed Description
Paparazzi Swing Baro Sensor implementation. Sensor is LPS22HB (I2C) from ST but is accessed through sysfs interface
Definition in file baro_board.c.
Function Documentation
baro_event()
void baro_event (void)
Definition at line 91 of file baro_board.c.
References BARO_BOARD_SENDER_ID, baro_swing_available, baro_swing_mutex, baro_swing_raw, bb_ms5611, bb_ms5611_filt, Ms5611Data::d1, Ms5611Data::d2, Ms5611_I2c::data, Ms5611_I2c::data_available, DefaultChannel, DefaultDevice, fbaroms, get_sys_time_usec(), LED_TOGGLE, ms5611_i2c_event(), sys_time::nb_sec, Ms5611Data::pressure, Ms5611Data::temperature, and update_median_filter_f().
baro_init()
void baro_init (void)
Definition at line 74 of file baro_board.c.
References baro_read(), baro_swing_available, and baro_swing_raw.
baro_periodic()
void baro_periodic (void)
Definition at line 88 of file baro_board.c.
baro_read()
static void* baro_read (void * data) static
Check baro thread TODO something better ?
Definition at line 46 of file baro_board.c.
References baro_swing_available, baro_swing_mutex, baro_swing_raw, ev, and TRUE.
Referenced by baro_init().
Variable Documentation
baro_swing_available
bool baro_swing_available static
Definition at line 38 of file baro_board.c.
Referenced by baro_event(), baro_init(), and baro_read().
baro_swing_mutex
pthread_mutex_t baro_swing_mutex = PTHREAD_MUTEX_INITIALIZER static
Definition at line 40 of file baro_board.c.
Referenced by baro_event(), and baro_read().
baro_swing_raw
int32_t baro_swing_raw static
Definition at line 39 of file baro_board.c.
Referenced by baro_event(), baro_init(), and baro_read().