Paparazzi UAS: sw/airborne/modules/telemetry/telemetry_intermcu_ap.c File Reference
telemetry_intermcu_ap.c File Reference
Telemetry through InterMCU.
#include "telemetry_intermcu.h"
#include "telemetry_intermcu_ap.h"
#include "subsystems/intermcu.h"
#include "pprzlink/intermcu_msg.h"
#include "pprzlink/short_transport.h"
#include "generated/periodic_telemetry.h"
#include "subsystems/datalink/telemetry.h"
#include "subsystems/datalink/datalink.h"
Macros
#define PERIODIC_C_INTERMCU
Functions
static int telemetry_intermcu_check_free_space (struct telemetry_intermcu_t *p, long *fd, uint16_t len)
static void telemetry_intermcu_put_byte (struct telemetry_intermcu_t *p, long fd, uint8_t data)
static void telemetry_intermcu_put_buffer (struct telemetry_intermcu_t *p, long fd, uint8_t *data, uint16_t len)
static void telemetry_intermcu_send_message (struct telemetry_intermcu_t *p, long fd)
void telemetry_intermcu_init (void)
void telemetry_intermcu_periodic (void)
void telemetry_intermcu_event (void)
void telemetry_intermcu_on_msg (uint8_t *msg, uint8_t size)
Variables
struct telemetry_intermcu_t telemetry_intermcu
Detailed Description
Telemetry through InterMCU.
Definition in file telemetry_intermcu_ap.c.
Macro Definition Documentation
PERIODIC_C_INTERMCU
#define PERIODIC_C_INTERMCU
Definition at line 27 of file telemetry_intermcu_ap.c.
Function Documentation
telemetry_intermcu_check_free_space()
static int telemetry_intermcu_check_free_space (struct telemetry_intermcu_t * p, long * fd, uint16_t len) static
Definition at line 79 of file telemetry_intermcu_ap.c.
References p, and TELEMERTY_INTERMCU_MSG_SIZE.
Referenced by telemetry_intermcu_init().
telemetry_intermcu_event()
void telemetry_intermcu_event (void)
Definition at line 67 of file telemetry_intermcu_ap.c.
telemetry_intermcu_init()
void telemetry_intermcu_init (void)
Definition at line 47 of file telemetry_intermcu_ap.c.
References telemetry_intermcu_t::dev, telemetry_intermcu, telemetry_intermcu_check_free_space(), telemetry_intermcu_put_buffer(), telemetry_intermcu_put_byte(), telemetry_intermcu_send_message(), and telemetry_intermcu_t::trans.
telemetry_intermcu_on_msg()
void telemetry_intermcu_on_msg (uint8_t * msg, uint8_t size)
Definition at line 72 of file telemetry_intermcu_ap.c.
References datalink_nb_msgs, datalink_time, telemetry_intermcu_t::dev, dl_parse_msg(), msg, telemetry_intermcu, and telemetry_intermcu_t::trans.
telemetry_intermcu_periodic()
void telemetry_intermcu_periodic (void)
Definition at line 61 of file telemetry_intermcu_ap.c.
References DefaultPeriodic, telemetry_intermcu_t::dev, telemetry_intermcu, and telemetry_intermcu_t::trans.
telemetry_intermcu_put_buffer()
static void telemetry_intermcu_put_buffer (struct telemetry_intermcu_t * p, long fd, uint8_t * data, uint16_t len) static
Definition at line 93 of file telemetry_intermcu_ap.c.
References p.
Referenced by telemetry_intermcu_init().
telemetry_intermcu_put_byte()
static void telemetry_intermcu_put_byte (struct telemetry_intermcu_t * p, long fd, uint8_t data) static
Definition at line 85 of file telemetry_intermcu_ap.c.
References p, and TELEMERTY_INTERMCU_MSG_SIZE.
Referenced by telemetry_intermcu_init().
telemetry_intermcu_send_message()
static void telemetry_intermcu_send_message (struct telemetry_intermcu_t * p, long fd) static
Definition at line 101 of file telemetry_intermcu_ap.c.
References intermcu_t::device, intermcu, INTERMCU_AP, p, and intermcu_t::transport.
Referenced by telemetry_intermcu_init().
Variable Documentation
telemetry_intermcu
struct telemetry_intermcu_t telemetry_intermcu
Definition at line 38 of file telemetry_intermcu_ap.c.
Referenced by telemetry_intermcu_init(), telemetry_intermcu_on_msg(), and telemetry_intermcu_periodic().