Paparazzi UAS: sw/airborne/arch/stm32/TIM_usage_list.txt File Reference
sw/airborne/arch/stm32/TIM_usage_list.txt File Reference
Functions
timer subsystem type (config options) --------------------------------------------(advanced timers using RCC_APB1) TIM1 adc(if USE_AD_TIM1) radio_control/ppm(if USE_PPM_TIM1
timer subsystem PPM input on SERVO6 pin actuators pwm (if PWM_USE_TIM1) TIM8 radio_control/ppm(if USE_PPM_TIM8)(non-advanced timers using RCC_APB2) TIM2 adc(if USE_AD_TIM2
timer subsystem PPM input on SERVO6 pin actuators default radio_control ppm (if USE_PPM_TIM2, PPM input on UART1_RX pin) actuators/pwm(if PWM_USE_TIM2) TIM3 actuators/pwm(if PWM_USE_TIM3
Function Documentation
ppm()
timer subsystem PPM input on SERVO6 pin actuators default radio_control ppm (if USE_PPM_TIM2, PPM input on UART1_RX pin)
pwm()
timer subsystem PPM input on SERVO6 pin actuators pwm (if PWM_USE_TIM1)
Referenced by pwm_sysfs_enable(), pwm_sysfs_init(), pwm_sysfs_set_duty(), and pwm_sysfs_set_period().
type()
timer subsystem type (config options)
Referenced by ekf_range_update_speed(), getDescriptor(), image_create(), mission_get_registered(), mission_register(), mtostk_get_calibrated_value(), nps_radio_control_init(), spektrum_parser(), stereocam_parse_msg(), v4l2_start_capture(), and v4l2_stop_capture().