Paparazzi UAS: sw/airborne/modules/loggers/sdlog_chibios/usb_msd.c File Reference
usb_msd.c File Reference
#include "modules/loggers/sdlog_chibios/usb_msd.h"
#include "mcu_periph/ram_arch.h"
Data Structures
struct PACK_STRUCT_STRUCT
Response to a READ_CAPACITY_10 SCSI command.
struct PACK_STRUCT_STRUCT
Response to a READ_CAPACITY_10 SCSI command.
Macros
#define MSD_REQ_RESET 0xFF
#define MSD_GET_MAX_LUN 0xFE
#define MSD_CBW_SIGNATURE 0x43425355
#define MSD_CSW_SIGNATURE 0x53425355
#define MSD_SETUP_WORD(setup, index) (uint16_t)(((uint16_t)setup[index + 1] << 8) | (setup[index] & 0x00FF))
#define MSD_SETUP_VALUE(setup) MSD_SETUP_WORD(setup, 2)
#define MSD_SETUP_INDEX(setup) MSD_SETUP_WORD(setup, 4)
#define MSD_SETUP_LENGTH(setup) MSD_SETUP_WORD(setup, 6)
#define MSD_COMMAND_PASSED 0x00
#define MSD_COMMAND_FAILED 0x01
#define MSD_COMMAND_PHASE_ERROR 0x02
#define SCSI_CMD_TEST_UNIT_READY 0x00
#define SCSI_CMD_REQUEST_SENSE 0x03
#define SCSI_CMD_FORMAT_UNIT 0x04
#define SCSI_CMD_INQUIRY 0x12
#define SCSI_CMD_MODE_SENSE_6 0x1A
#define SCSI_CMD_START_STOP_UNIT 0x1B
#define SCSI_CMD_SEND_DIAGNOSTIC 0x1D
#define SCSI_CMD_PREVENT_ALLOW_MEDIUM_REMOVAL 0x1E
#define SCSI_CMD_READ_FORMAT_CAPACITIES 0x23
#define SCSI_CMD_READ_CAPACITY_10 0x25
#define SCSI_CMD_READ_10 0x28
#define SCSI_CMD_WRITE_10 0x2A
#define SCSI_CMD_VERIFY_10 0x2F
#define SCSI_SENSE_KEY_GOOD 0x00
#define SCSI_SENSE_KEY_RECOVERED_ERROR 0x01
#define SCSI_SENSE_KEY_NOT_READY 0x02
#define SCSI_SENSE_KEY_MEDIUM_ERROR 0x03
#define SCSI_SENSE_KEY_HARDWARE_ERROR 0x04
#define SCSI_SENSE_KEY_ILLEGAL_REQUEST 0x05
#define SCSI_SENSE_KEY_UNIT_ATTENTION 0x06
#define SCSI_SENSE_KEY_DATA_PROTECT 0x07
#define SCSI_SENSE_KEY_BLANK_CHECK 0x08
#define SCSI_SENSE_KEY_VENDOR_SPECIFIC 0x09
#define SCSI_SENSE_KEY_COPY_ABORTED 0x0A
#define SCSI_SENSE_KEY_ABORTED_COMMAND 0x0B
#define SCSI_SENSE_KEY_VOLUME_OVERFLOW 0x0D
#define SCSI_SENSE_KEY_MISCOMPARE 0x0E
#define SCSI_ASENSE_NO_ADDITIONAL_INFORMATION 0x00
#define SCSI_ASENSE_WRITE_FAULT 0x03
#define SCSI_ASENSE_LOGICAL_UNIT_NOT_READY 0x04
#define SCSI_ASENSE_READ_ERROR 0x11
#define SCSI_ASENSE_INVALID_COMMAND 0x20
#define SCSI_ASENSE_LOGICAL_BLOCK_ADDRESS_OUT_OF_RANGE 0x21
#define SCSI_ASENSE_INVALID_FIELD_IN_CDB 0x24
#define SCSI_ASENSE_WRITE_PROTECTED 0x27
#define SCSI_ASENSE_NOT_READY_TO_READY_CHANGE 0x28
#define SCSI_ASENSE_FORMAT_ERROR 0x31
#define SCSI_ASENSE_MEDIUM_NOT_PRESENT 0x3A
#define SCSI_ASENSEQ_NO_QUALIFIER 0x00
#define SCSI_ASENSEQ_FORMAT_COMMAND_FAILED 0x01
#define SCSI_ASENSEQ_INITIALIZING_COMMAND_REQUIRED 0x02
#define SCSI_ASENSEQ_OPERATION_IN_PROGRESS 0x07
Typedefs
typedef uint32_t DWORD
typedef uint16_t WORD
Functions
static THD_WORKING_AREA (mass_storage_thread_wa, 1024)
static void mass_storage_thread (void *arg)
Mass storage thread that processes commands.
void debug_snd_evt_i (eventmask_t evt)
void debug_snd_evt_inl (eventmask_t evt)
void debug_snd_evt_nl (eventmask_t evt)
static uint8_t IN_DMA_SECTION_CLEAR (rw_buf[2][512])
Read-write buffers (TODO: need a way of specifying the size of this)
static DWORD swap_uint32 (const DWORD val)
Byte-swap a 32 bits unsigned integer.
static WORD swap_uint16 (const WORD val)
Byte-swap a 16 bits unsigned integer.
static void msd_handle_end_point_notification (USBDriver *usbp, usbep_t ep)
Called when data can be read or written on the endpoint – wakes the thread up.
void msdConfigureHookI (USBMassStorageDriver *msdp)
USB device configured handler.
bool msdRequestsHook (USBDriver *usbp)
Default requests hook.
static void msd_wait_for_isr (USBMassStorageDriver *msdp)
Wait until the end-point interrupt handler has been called.
static void msd_start_transmit (USBMassStorageDriver *msdp, const uint8_t *buffer, size_t size)
Starts sending data.
static void msd_start_receive (USBMassStorageDriver *msdp, uint8_t *buffer, size_t size)
Starts receiving data.
static void msd_scsi_set_sense (USBMassStorageDriver *msdp, uint8_t key, uint8_t acode, uint8_t aqual)
Changes the SCSI sense information.
bool msd_scsi_process_inquiry (USBMassStorageDriver *msdp)
Processes an INQUIRY SCSI command.
bool msd_scsi_process_request_sense (USBMassStorageDriver *msdp)
Processes a REQUEST_SENSE SCSI command.
bool msd_scsi_process_read_capacity_10 (USBMassStorageDriver *msdp)
Processes a READ_CAPACITY_10 SCSI command.
bool msd_scsi_process_send_diagnostic (USBMassStorageDriver *msdp)
Processes a SEND_DIAGNOSTIC SCSI command.
bool msd_scsi_process_start_read_write_10 (USBMassStorageDriver *msdp)
Processes a READ_WRITE_10 SCSI command.
bool msd_scsi_process_start_stop_unit (USBMassStorageDriver *msdp)
Processes a START_STOP_UNIT SCSI command.
bool msd_scsi_process_mode_sense_6 (USBMassStorageDriver *msdp)
Processes a MODE_SENSE_6 SCSI command.
bool msd_scsi_process_read_format_capacities (USBMassStorageDriver *msdp)
Processes a READ_FORMAT_CAPACITIES SCSI command.
bool msd_scsi_process_test_unit_ready (USBMassStorageDriver *msdp)
Processes a TEST_UNIT_READY SCSI command.
bool msd_wait_for_command_block (USBMassStorageDriver *msdp)
Waits for a new command block.
bool msd_read_command_block (USBMassStorageDriver *msdp)
Reads a newly received command block.
void msdInit (USBMassStorageDriver *msdp)
Initializse a USB mass storage driver.
void msdStart (USBMassStorageDriver *msdp, const USBMassStorageConfig *config)
Starts a USB mass storage driver.
void msdStop (USBMassStorageDriver *msdp)
Stops a USB mass storage driver.
static void usbEvent (USBDriver *usbp, usbevent_t event)
static const USBDescriptor * getDescriptor (USBDriver *usbp, uint8_t type, uint8_t index, uint16_t lang)
void deinit_msd_driver (void)
void init_msd_driver (void *dbgThreadPtr, USBMassStorageConfig *msdConfig)
void msd_register_evt_connected (event_listener_t *elp, eventmask_t mask)
register connected event source in local event mask
void msd_register_evt_ejected (event_listener_t *elp, eventmask_t mask)
register ejected event source in local event mask
Variables
static USBMassStorageDriver UMSD
thread_t * dbg_printer = NULL
static USBInEndpointState ep1_in_state
IN end-point 1 state.
static USBOutEndpointState ep1_out_state
OUT end-point 1 state.
static const USBEndpointConfig ep_data_config
End-point 1 initialization structure.
static const uint8_t deviceDescriptorData []
static const USBDescriptor deviceDescriptor
static const uint8_t configurationDescriptorData []
static const USBDescriptor configurationDescriptor
static const uint8_t languageDescriptorData []
static const USBDescriptor languageDescriptor
static const uint8_t vendorDescriptorData []
static const USBDescriptor vendorDescriptor
static const uint8_t productDescriptorData []
static const USBDescriptor productDescriptor
static const uint8_t serialNumberDescriptorData []
static const USBDescriptor serialNumberDescriptor
static const USBConfig usbConfig
Data Structure Documentation
PACK_STRUCT_STRUCT
struct PACK_STRUCT_STRUCT
Response to a READ_CAPACITY_10 SCSI command.
structure holding the data to reply to an INQUIRY SCSI command
Structure holding sense data (status/error information)
Command Status Wrapper structure.
Command Block Wrapper structure.
Response to a READ_FORMAT_CAPACITIES SCSI command.
Definition at line 113 of file usb_msd.c.
Data Fields
uint8_t additional_length
uint32_t block_count
uint32_t block_size
uint8_t bqueetc
uint8_t byte[18]
uint8_t capacity_list_length
uint8_t cmdque
uint32_t data_len
uint32_t data_residue
uint32_t desc_and_block_length
uint8_t flags
uint32_t last_block_addr
uint8_t lun
uint8_t peripheral
uint8_t product_id[16]
uint8_t product_rev[4]
uint8_t removable
uint8_t reserved[3]
uint8_t response_data_format
uint8_t sccstp
uint8_t scsi_cmd_data[16]
uint8_t scsi_cmd_len
uint32_t signature
uint8_t status
uint32_t tag
uint8_t vendor_id[8]
uint8_t version
PACK_STRUCT_STRUCT
struct PACK_STRUCT_STRUCT
Response to a READ_CAPACITY_10 SCSI command.
structure holding the data to reply to an INQUIRY SCSI command
Structure holding sense data (status/error information)
Command Status Wrapper structure.
Command Block Wrapper structure.
Response to a READ_FORMAT_CAPACITIES SCSI command.
Definition at line 113 of file usb_msd.c.
Data Fields
uint8_t additional_length
uint32_t block_count
uint32_t block_size
uint8_t bqueetc
uint8_t byte[18]
uint8_t capacity_list_length
uint8_t cmdque
uint32_t data_len
uint32_t data_residue
uint32_t desc_and_block_length
uint8_t flags
uint32_t last_block_addr
uint8_t lun
uint8_t peripheral
uint8_t product_id[16]
uint8_t product_rev[4]
uint8_t removable
uint8_t reserved[3]
uint8_t response_data_format
uint8_t sccstp
uint8_t scsi_cmd_data[16]
uint8_t scsi_cmd_len
uint32_t signature
uint8_t status
uint32_t tag
uint8_t vendor_id[8]
uint8_t version
Macro Definition Documentation
MSD_CBW_SIGNATURE
#define MSD_CBW_SIGNATURE 0x43425355
Definition at line 39 of file usb_msd.c.
MSD_COMMAND_FAILED
#define MSD_COMMAND_FAILED 0x01
Definition at line 50 of file usb_msd.c.
MSD_COMMAND_PASSED
#define MSD_COMMAND_PASSED 0x00
Definition at line 49 of file usb_msd.c.
MSD_COMMAND_PHASE_ERROR
#define MSD_COMMAND_PHASE_ERROR 0x02
Definition at line 51 of file usb_msd.c.
MSD_CSW_SIGNATURE
#define MSD_CSW_SIGNATURE 0x53425355
Definition at line 40 of file usb_msd.c.
MSD_GET_MAX_LUN
#define MSD_GET_MAX_LUN 0xFE
Definition at line 36 of file usb_msd.c.
MSD_REQ_RESET
#define MSD_REQ_RESET 0xFF
Definition at line 35 of file usb_msd.c.
MSD_SETUP_INDEX
#define MSD_SETUP_INDEX (setup) MSD_SETUP_WORD(setup, 4)
Definition at line 45 of file usb_msd.c.
MSD_SETUP_LENGTH
#define MSD_SETUP_LENGTH (setup) MSD_SETUP_WORD(setup, 6)
Definition at line 46 of file usb_msd.c.
MSD_SETUP_VALUE
#define MSD_SETUP_VALUE (setup) MSD_SETUP_WORD(setup, 2)
Definition at line 44 of file usb_msd.c.
MSD_SETUP_WORD
#define MSD_SETUP_WORD (setup, index) (uint16_t)(((uint16_t)setup[index + 1] << 8) | (setup[index] & 0x00FF))
Definition at line 43 of file usb_msd.c.
SCSI_ASENSE_FORMAT_ERROR
#define SCSI_ASENSE_FORMAT_ERROR 0x31
Definition at line 93 of file usb_msd.c.
SCSI_ASENSE_INVALID_COMMAND
#define SCSI_ASENSE_INVALID_COMMAND 0x20
Definition at line 88 of file usb_msd.c.
SCSI_ASENSE_INVALID_FIELD_IN_CDB
#define SCSI_ASENSE_INVALID_FIELD_IN_CDB 0x24
Definition at line 90 of file usb_msd.c.
SCSI_ASENSE_LOGICAL_BLOCK_ADDRESS_OUT_OF_RANGE
#define SCSI_ASENSE_LOGICAL_BLOCK_ADDRESS_OUT_OF_RANGE 0x21
Definition at line 89 of file usb_msd.c.
SCSI_ASENSE_LOGICAL_UNIT_NOT_READY
#define SCSI_ASENSE_LOGICAL_UNIT_NOT_READY 0x04
Definition at line 86 of file usb_msd.c.
SCSI_ASENSE_MEDIUM_NOT_PRESENT
#define SCSI_ASENSE_MEDIUM_NOT_PRESENT 0x3A
Definition at line 94 of file usb_msd.c.
SCSI_ASENSE_NO_ADDITIONAL_INFORMATION
#define SCSI_ASENSE_NO_ADDITIONAL_INFORMATION 0x00
Definition at line 84 of file usb_msd.c.
SCSI_ASENSE_NOT_READY_TO_READY_CHANGE
#define SCSI_ASENSE_NOT_READY_TO_READY_CHANGE 0x28
Definition at line 92 of file usb_msd.c.
SCSI_ASENSE_READ_ERROR
#define SCSI_ASENSE_READ_ERROR 0x11
Definition at line 87 of file usb_msd.c.
SCSI_ASENSE_WRITE_FAULT
#define SCSI_ASENSE_WRITE_FAULT 0x03
Definition at line 85 of file usb_msd.c.
SCSI_ASENSE_WRITE_PROTECTED
#define SCSI_ASENSE_WRITE_PROTECTED 0x27
Definition at line 91 of file usb_msd.c.
SCSI_ASENSEQ_FORMAT_COMMAND_FAILED
#define SCSI_ASENSEQ_FORMAT_COMMAND_FAILED 0x01
Definition at line 97 of file usb_msd.c.
SCSI_ASENSEQ_INITIALIZING_COMMAND_REQUIRED
#define SCSI_ASENSEQ_INITIALIZING_COMMAND_REQUIRED 0x02
Definition at line 98 of file usb_msd.c.
SCSI_ASENSEQ_NO_QUALIFIER
#define SCSI_ASENSEQ_NO_QUALIFIER 0x00
Definition at line 96 of file usb_msd.c.
SCSI_ASENSEQ_OPERATION_IN_PROGRESS
#define SCSI_ASENSEQ_OPERATION_IN_PROGRESS 0x07
Definition at line 99 of file usb_msd.c.
SCSI_CMD_FORMAT_UNIT
#define SCSI_CMD_FORMAT_UNIT 0x04
Definition at line 56 of file usb_msd.c.
SCSI_CMD_INQUIRY
#define SCSI_CMD_INQUIRY 0x12
Definition at line 57 of file usb_msd.c.
SCSI_CMD_MODE_SENSE_6
#define SCSI_CMD_MODE_SENSE_6 0x1A
Definition at line 58 of file usb_msd.c.
SCSI_CMD_PREVENT_ALLOW_MEDIUM_REMOVAL
#define SCSI_CMD_PREVENT_ALLOW_MEDIUM_REMOVAL 0x1E
Definition at line 61 of file usb_msd.c.
SCSI_CMD_READ_10
#define SCSI_CMD_READ_10 0x28
Definition at line 64 of file usb_msd.c.
SCSI_CMD_READ_CAPACITY_10
#define SCSI_CMD_READ_CAPACITY_10 0x25
Definition at line 63 of file usb_msd.c.
SCSI_CMD_READ_FORMAT_CAPACITIES
#define SCSI_CMD_READ_FORMAT_CAPACITIES 0x23
Definition at line 62 of file usb_msd.c.
SCSI_CMD_REQUEST_SENSE
#define SCSI_CMD_REQUEST_SENSE 0x03
Definition at line 55 of file usb_msd.c.
SCSI_CMD_SEND_DIAGNOSTIC
#define SCSI_CMD_SEND_DIAGNOSTIC 0x1D
Definition at line 60 of file usb_msd.c.
SCSI_CMD_START_STOP_UNIT
#define SCSI_CMD_START_STOP_UNIT 0x1B
Definition at line 59 of file usb_msd.c.
SCSI_CMD_TEST_UNIT_READY
#define SCSI_CMD_TEST_UNIT_READY 0x00
Definition at line 54 of file usb_msd.c.
SCSI_CMD_VERIFY_10
#define SCSI_CMD_VERIFY_10 0x2F
Definition at line 66 of file usb_msd.c.
SCSI_CMD_WRITE_10
#define SCSI_CMD_WRITE_10 0x2A
Definition at line 65 of file usb_msd.c.
SCSI_SENSE_KEY_ABORTED_COMMAND
#define SCSI_SENSE_KEY_ABORTED_COMMAND 0x0B
Definition at line 80 of file usb_msd.c.
SCSI_SENSE_KEY_BLANK_CHECK
#define SCSI_SENSE_KEY_BLANK_CHECK 0x08
Definition at line 77 of file usb_msd.c.
SCSI_SENSE_KEY_COPY_ABORTED
#define SCSI_SENSE_KEY_COPY_ABORTED 0x0A
Definition at line 79 of file usb_msd.c.
SCSI_SENSE_KEY_DATA_PROTECT
#define SCSI_SENSE_KEY_DATA_PROTECT 0x07
Definition at line 76 of file usb_msd.c.
SCSI_SENSE_KEY_GOOD
#define SCSI_SENSE_KEY_GOOD 0x00
Definition at line 69 of file usb_msd.c.
SCSI_SENSE_KEY_HARDWARE_ERROR
#define SCSI_SENSE_KEY_HARDWARE_ERROR 0x04
Definition at line 73 of file usb_msd.c.
SCSI_SENSE_KEY_ILLEGAL_REQUEST
#define SCSI_SENSE_KEY_ILLEGAL_REQUEST 0x05
Definition at line 74 of file usb_msd.c.
SCSI_SENSE_KEY_MEDIUM_ERROR
#define SCSI_SENSE_KEY_MEDIUM_ERROR 0x03
Definition at line 72 of file usb_msd.c.
SCSI_SENSE_KEY_MISCOMPARE
#define SCSI_SENSE_KEY_MISCOMPARE 0x0E
Definition at line 82 of file usb_msd.c.
SCSI_SENSE_KEY_NOT_READY
#define SCSI_SENSE_KEY_NOT_READY 0x02
Definition at line 71 of file usb_msd.c.
SCSI_SENSE_KEY_RECOVERED_ERROR
#define SCSI_SENSE_KEY_RECOVERED_ERROR 0x01
Definition at line 70 of file usb_msd.c.
SCSI_SENSE_KEY_UNIT_ATTENTION
#define SCSI_SENSE_KEY_UNIT_ATTENTION 0x06
Definition at line 75 of file usb_msd.c.
SCSI_SENSE_KEY_VENDOR_SPECIFIC
#define SCSI_SENSE_KEY_VENDOR_SPECIFIC 0x09
Definition at line 78 of file usb_msd.c.
SCSI_SENSE_KEY_VOLUME_OVERFLOW
#define SCSI_SENSE_KEY_VOLUME_OVERFLOW 0x0D
Definition at line 81 of file usb_msd.c.
Typedef Documentation
DWORD
typedef uint32_t DWORD
Definition at line 133 of file usb_msd.c.
WORD
typedef uint16_t WORD
Definition at line 133 of file usb_msd.c.
Function Documentation
debug_snd_evt_i()
void debug_snd_evt_i (eventmask_t evt)
Definition at line 921 of file usb_msd.c.
References dbg_printer.
Referenced by msdInit(), msdRequestsHook(), and usbEvent().
debug_snd_evt_inl()
void debug_snd_evt_inl (eventmask_t evt)
Definition at line 930 of file usb_msd.c.
References dbg_printer.
Referenced by msd_wait_for_isr(), and msdConfigureHookI().
debug_snd_evt_nl()
void debug_snd_evt_nl (eventmask_t evt)
Definition at line 937 of file usb_msd.c.
References dbg_printer.
Referenced by msd_scsi_process_inquiry(), msd_scsi_process_mode_sense_6(), msd_scsi_process_read_capacity_10(), msd_scsi_process_read_format_capacities(), msd_scsi_process_start_read_write_10(), msd_scsi_process_test_unit_ready(), and msd_wait_for_command_block().
deinit_msd_driver()
void deinit_msd_driver (void)
Definition at line 1121 of file usb_msd.c.
References msdStop(), and UMSD.
Referenced by thdUsbStorage().
getDescriptor()
static const USBDescriptor* getDescriptor (USBDriver * usbp, uint8_t type, uint8_t index, uint16_t lang) static
Definition at line 1087 of file usb_msd.c.
References configurationDescriptor, deviceDescriptor, languageDescriptor, productDescriptor, serialNumberDescriptor, type(), and vendorDescriptor.
IN_DMA_SECTION_CLEAR()
static uint8_t IN_DMA_SECTION_CLEAR (rw_buf [2][512]) static
Read-write buffers (TODO: need a way of specifying the size of this)
init_msd_driver()
void init_msd_driver (void * dbgThreadPtr, USBMassStorageConfig * msdConfig)
Definition at line 1126 of file usb_msd.c.
References dbg_printer, msdConfig, msdInit(), msdStart(), UMSD, usbConfig, and USBD.
Referenced by thdUsbStorage().
mass_storage_thread()
static void mass_storage_thread (void * arg) static
Mass storage thread that processes commands.
Definition at line 1156 of file usb_msd.c.
References USBMassStorageDriver::bsem, USBMassStorageDriver::config, ep_data_config, MSD_BOT_RESET, MSD_EJECTED, MSD_IDLE, MSD_READ_COMMAND_BLOCK, msd_read_command_block(), msd_scsi_set_sense(), msd_wait_for_command_block(), msd_wait_for_isr(), USBMassStorageDriver::reconfigured_or_reset_event, SCSI_ASENSE_NO_ADDITIONAL_INFORMATION, SCSI_ASENSEQ_NO_QUALIFIER, SCSI_SENSE_KEY_GOOD, USBMassStorageDriver::state, USB_MS_DATA_EP, and USBMassStorageConfig::usbp.
Referenced by msdStart().
msd_handle_end_point_notification()
static void msd_handle_end_point_notification (USBDriver * usbp, usbep_t ep) static
Called when data can be read or written on the endpoint – wakes the thread up.
Definition at line 298 of file usb_msd.c.
References SEM_RELEASED.
msd_read_command_block()
bool msd_read_command_block (USBMassStorageDriver * msdp)
Reads a newly received command block.
Definition at line 669 of file usb_msd.c.
References USBMassStorageDriver::bot_reset, USBMassStorageConfig::bulk_ep, USBMassStorageDriver::cbw, USBMassStorageDriver::config, USBMassStorageDriver::csw, MSD_CBW_SIGNATURE, MSD_COMMAND_FAILED, MSD_COMMAND_PASSED, MSD_CSW_SIGNATURE, MSD_IDLE, msd_scsi_process_inquiry(), msd_scsi_process_mode_sense_6(), msd_scsi_process_read_capacity_10(), msd_scsi_process_read_format_capacities(), msd_scsi_process_request_sense(), msd_scsi_process_send_diagnostic(), msd_scsi_process_start_read_write_10(), msd_scsi_process_start_stop_unit(), msd_scsi_process_test_unit_ready(), msd_scsi_set_sense(), msd_start_transmit(), msd_wait_for_isr(), USBMassStorageDriver::result, USBMassStorageConfig::rw_activity_callback, SCSI_ASENSE_INVALID_COMMAND, SCSI_ASENSE_INVALID_FIELD_IN_CDB, SCSI_ASENSE_NO_ADDITIONAL_INFORMATION, SCSI_ASENSEQ_NO_QUALIFIER, SCSI_CMD_FORMAT_UNIT, SCSI_CMD_INQUIRY, SCSI_CMD_MODE_SENSE_6, SCSI_CMD_PREVENT_ALLOW_MEDIUM_REMOVAL, SCSI_CMD_READ_10, SCSI_CMD_READ_CAPACITY_10, SCSI_CMD_READ_FORMAT_CAPACITIES, SCSI_CMD_REQUEST_SENSE, SCSI_CMD_SEND_DIAGNOSTIC, SCSI_CMD_START_STOP_UNIT, SCSI_CMD_TEST_UNIT_READY, SCSI_CMD_VERIFY_10, SCSI_CMD_WRITE_10, SCSI_SENSE_KEY_GOOD, SCSI_SENSE_KEY_ILLEGAL_REQUEST, USBMassStorageDriver::state, and USBMassStorageConfig::usbp.
Referenced by mass_storage_thread().
msd_register_evt_connected()
void msd_register_evt_connected (event_listener_t * elp, eventmask_t mask)
register connected event source in local event mask
This function is a stub to chEvtRegisterMask
Definition at line 1142 of file usb_msd.c.
References USBMassStorageDriver::evt_connected, and UMSD.
Referenced by thdUsbStorage().
msd_register_evt_ejected()
void msd_register_evt_ejected (event_listener_t * elp, eventmask_t mask)
register ejected event source in local event mask
This function is a stub to chEvtRegisterMask ejected event is a logical event : when host unmount the filesystem, not a physical event (event is not sent in case of unplugged usb wire)
Definition at line 1147 of file usb_msd.c.
References USBMassStorageDriver::evt_ejected, and UMSD.
msd_scsi_process_inquiry()
bool msd_scsi_process_inquiry (USBMassStorageDriver * msdp)
Processes an INQUIRY SCSI command.
Definition at line 349 of file usb_msd.c.
References USBMassStorageDriver::cbw, debug_snd_evt_nl(), EVT_SCSI_PROC_INQ, USBMassStorageDriver::inquiry, msd_scsi_set_sense(), msd_start_transmit(), USBMassStorageDriver::result, SCSI_ASENSE_INVALID_FIELD_IN_CDB, SCSI_ASENSEQ_NO_QUALIFIER, and SCSI_SENSE_KEY_ILLEGAL_REQUEST.
Referenced by msd_read_command_block().
msd_scsi_process_mode_sense_6()
bool msd_scsi_process_mode_sense_6 (USBMassStorageDriver * msdp)
Processes a MODE_SENSE_6 SCSI command.
Definition at line 588 of file usb_msd.c.
References debug_snd_evt_nl(), EVT_SCSI_REQ_SENSE6, msd_start_transmit(), and USBMassStorageDriver::result.
Referenced by msd_read_command_block().
msd_scsi_process_read_capacity_10()
bool msd_scsi_process_read_capacity_10 (USBMassStorageDriver * msdp)
Processes a READ_CAPACITY_10 SCSI command.
Definition at line 407 of file usb_msd.c.
References USBMassStorageDriver::block_dev_info, debug_snd_evt_nl(), EVT_SCSI_REQ_READ_CAP10, msd_start_transmit(), USBMassStorageDriver::result, and swap_uint32().
Referenced by msd_read_command_block().
msd_scsi_process_read_format_capacities()
bool msd_scsi_process_read_format_capacities (USBMassStorageDriver * msdp)
Processes a READ_FORMAT_CAPACITIES SCSI command.
Definition at line 608 of file usb_msd.c.
References USBMassStorageDriver::block_dev_info, debug_snd_evt_nl(), EVT_SCSI_REQ_READ_FMT_CAP, msd_start_transmit(), USBMassStorageDriver::result, and swap_uint32().
Referenced by msd_read_command_block().
msd_scsi_process_request_sense()
bool msd_scsi_process_request_sense (USBMassStorageDriver * msdp)
Processes a REQUEST_SENSE SCSI command.
Definition at line 391 of file usb_msd.c.
References msd_start_transmit(), msd_wait_for_isr(), USBMassStorageDriver::result, and USBMassStorageDriver::sense.
Referenced by msd_read_command_block().
msd_scsi_process_send_diagnostic()
bool msd_scsi_process_send_diagnostic (USBMassStorageDriver * msdp)
Processes a SEND_DIAGNOSTIC SCSI command.
Definition at line 425 of file usb_msd.c.
References USBMassStorageDriver::cbw, msd_scsi_set_sense(), USBMassStorageDriver::result, SCSI_ASENSE_INVALID_FIELD_IN_CDB, SCSI_ASENSEQ_NO_QUALIFIER, and SCSI_SENSE_KEY_ILLEGAL_REQUEST.
Referenced by msd_read_command_block().
msd_scsi_process_start_read_write_10()
bool msd_scsi_process_start_read_write_10 (USBMassStorageDriver * msdp)
Processes a READ_WRITE_10 SCSI command.
Definition at line 449 of file usb_msd.c.
References USBMassStorageConfig::bbdp, USBMassStorageDriver::block_dev_info, USBMassStorageDriver::cbw, USBMassStorageDriver::config, debug_snd_evt_nl(), EVT_SCSI_REQ_SENSE10, msd_scsi_set_sense(), msd_start_receive(), msd_start_transmit(), msd_wait_for_isr(), USBMassStorageDriver::result, SCSI_ASENSE_LOGICAL_BLOCK_ADDRESS_OUT_OF_RANGE, SCSI_ASENSE_READ_ERROR, SCSI_ASENSE_WRITE_FAULT, SCSI_ASENSE_WRITE_PROTECTED, SCSI_ASENSEQ_NO_QUALIFIER, SCSI_CMD_WRITE_10, SCSI_SENSE_KEY_DATA_PROTECT, SCSI_SENSE_KEY_ILLEGAL_REQUEST, SCSI_SENSE_KEY_MEDIUM_ERROR, swap_uint16(), and swap_uint32().
Referenced by msd_read_command_block().
msd_scsi_process_start_stop_unit()
bool msd_scsi_process_start_stop_unit (USBMassStorageDriver * msdp)
Processes a START_STOP_UNIT SCSI command.
Definition at line 570 of file usb_msd.c.
References USBMassStorageDriver::cbw, USBMassStorageDriver::evt_ejected, MSD_EJECTED, USBMassStorageDriver::result, and USBMassStorageDriver::state.
Referenced by msd_read_command_block().
msd_scsi_process_test_unit_ready()
bool msd_scsi_process_test_unit_ready (USBMassStorageDriver * msdp)
Processes a TEST_UNIT_READY SCSI command.
Definition at line 627 of file usb_msd.c.
References USBMassStorageConfig::bbdp, USBMassStorageDriver::config, debug_snd_evt_nl(), EVT_SCSI_REQ_TEST_UNIT_READY, msd_scsi_set_sense(), USBMassStorageDriver::result, SCSI_ASENSE_MEDIUM_NOT_PRESENT, SCSI_ASENSE_NO_ADDITIONAL_INFORMATION, SCSI_ASENSEQ_NO_QUALIFIER, SCSI_SENSE_KEY_NOT_READY, and SCSI_SENSE_KEY_RECOVERED_ERROR.
Referenced by msd_read_command_block().
msd_scsi_set_sense()
static void msd_scsi_set_sense (USBMassStorageDriver * msdp, uint8_t key, uint8_t acode, uint8_t aqual) inline static
Changes the SCSI sense information.
Definition at line 339 of file usb_msd.c.
References USBMassStorageDriver::sense.
Referenced by mass_storage_thread(), msd_read_command_block(), msd_scsi_process_inquiry(), msd_scsi_process_send_diagnostic(), msd_scsi_process_start_read_write_10(), and msd_scsi_process_test_unit_ready().
msd_start_receive()
static void msd_start_receive (USBMassStorageDriver * msdp, uint8_t * buffer, size_t size) static
Starts receiving data.
Definition at line 325 of file usb_msd.c.
References USBMassStorageDriver::bot_reset, USBMassStorageConfig::bulk_ep, USBMassStorageDriver::config, and USBMassStorageConfig::usbp.
Referenced by msd_scsi_process_start_read_write_10(), and msd_wait_for_command_block().
msd_start_transmit()
static void msd_start_transmit (USBMassStorageDriver * msdp, const uint8_t * buffer, size_t size) static
Starts sending data.
Definition at line 311 of file usb_msd.c.
References USBMassStorageDriver::bot_reset, USBMassStorageConfig::bulk_ep, USBMassStorageDriver::config, and USBMassStorageConfig::usbp.
Referenced by msd_read_command_block(), msd_scsi_process_inquiry(), msd_scsi_process_mode_sense_6(), msd_scsi_process_read_capacity_10(), msd_scsi_process_read_format_capacities(), msd_scsi_process_request_sense(), and msd_scsi_process_start_read_write_10().
msd_wait_for_command_block()
bool msd_wait_for_command_block (USBMassStorageDriver * msdp)
Waits for a new command block.
Definition at line 654 of file usb_msd.c.
References USBMassStorageDriver::cbw, debug_snd_evt_nl(), EVT_WAIT_FOR_COMMAND_BLOCK, MSD_READ_COMMAND_BLOCK, msd_start_receive(), and USBMassStorageDriver::state.
Referenced by mass_storage_thread().
msd_wait_for_isr()
static void msd_wait_for_isr (USBMassStorageDriver * msdp) static
Wait until the end-point interrupt handler has been called.
Definition at line 285 of file usb_msd.c.
References USBMassStorageDriver::bsem, debug_snd_evt_inl(), EVT_SEM_TAKEN, and SEM_TAKEN.
Referenced by mass_storage_thread(), msd_read_command_block(), msd_scsi_process_request_sense(), and msd_scsi_process_start_read_write_10().
msdConfigureHookI()
void msdConfigureHookI (USBMassStorageDriver * msdp)
USB device configured handler.
Parameters
[in] msdp pointer to the USBMassStorageDriver object
@iclass
Definition at line 188 of file usb_msd.c.
References USBMassStorageDriver::bsem, USBMassStorageConfig::bulk_ep, USBMassStorageDriver::config, debug_snd_evt_inl(), ep_data_config, USBMassStorageDriver::evt_connected, EVT_SEM_RELEASED, SEM_RELEASED, and USBMassStorageConfig::usbp.
Referenced by usbEvent().
msdInit()
void msdInit (USBMassStorageDriver * msdp)
Initializse a USB mass storage driver.
Initializes a USB mass storage driver.
Definition at line 815 of file usb_msd.c.
References USBMassStorageDriver::bot_reset, USBMassStorageDriver::bsem, USBMassStorageDriver::config, debug_snd_evt_i(), USBMassStorageDriver::evt_connected, USBMassStorageDriver::evt_ejected, EVT_SEM_TAKEN, USBMassStorageDriver::inquiry, MSD_IDLE, USBMassStorageDriver::reconfigured_or_reset_event, USBMassStorageDriver::sense, USBMassStorageDriver::state, and USBMassStorageDriver::thread.
Referenced by init_msd_driver().
msdRequestsHook()
bool msdRequestsHook (USBDriver * usbp)
Default requests hook.
Parameters
[in] usbp pointer to the USBDriver object
Returns
The hook status.
Return values
true Message handled internally.
false Message not handled.
Definition at line 205 of file usb_msd.c.
References USBMassStorageDriver::bot_reset, USBMassStorageDriver::bsem, USBMassStorageConfig::bulk_ep, USBMassStorageDriver::config, debug_snd_evt_i(), EVT_BOT_RESET, MSD_BOT_RESET, MSD_GET_MAX_LUN, MSD_REQ_RESET, MSD_SETUP_INDEX, MSD_SETUP_LENGTH, MSD_SETUP_VALUE, USBMassStorageDriver::state, UMSD, and USBMassStorageConfig::usbp.
msdStart()
void msdStart (USBMassStorageDriver * msdp, const USBMassStorageConfig * config)
Starts a USB mass storage driver.
This function is sufficient to have USB mass storage running, it internally runs a thread that handles USB requests and transfers. The block device must be connected but no file system must be mounted, everything is handled by the host system.
Definition at line 855 of file usb_msd.c.
References USBMassStorageDriver::block_dev_info, config, USBMassStorageDriver::config, USBMassStorageDriver::inquiry, mass_storage_thread(), MSD_IDLE, USBMassStorageConfig::short_product_id, USBMassStorageConfig::short_product_version, USBMassStorageConfig::short_vendor_id, USBMassStorageDriver::state, and USBMassStorageDriver::thread.
Referenced by init_msd_driver().
msdStop()
void msdStop (USBMassStorageDriver * msdp)
Stops a USB mass storage driver.
This function waits for current tasks to be finished, if any, and then stops the mass storage thread.
Definition at line 900 of file usb_msd.c.
References USBMassStorageDriver::bsem, USBMassStorageConfig::bulk_ep, USBMassStorageDriver::config, USBMassStorageDriver::thread, and USBMassStorageConfig::usbp.
Referenced by deinit_msd_driver().
swap_uint16()
static WORD swap_uint16 (const WORD val) inline static
Byte-swap a 16 bits unsigned integer.
Definition at line 149 of file usb_msd.c.
References val.
Referenced by msd_scsi_process_start_read_write_10().
swap_uint32()
static DWORD swap_uint32 (const DWORD val) inline static
Byte-swap a 32 bits unsigned integer.
Definition at line 140 of file usb_msd.c.
References val.
Referenced by msd_scsi_process_read_capacity_10(), msd_scsi_process_read_format_capacities(), and msd_scsi_process_start_read_write_10().
THD_WORKING_AREA()
static THD_WORKING_AREA (mass_storage_thread_wa , 1024) static
usbEvent()
static void usbEvent (USBDriver * usbp, usbevent_t event) static
Definition at line 945 of file usb_msd.c.
References debug_snd_evt_i(), EVT_USB_RESET, msdConfigureHookI(), USBMassStorageDriver::reconfigured_or_reset_event, and UMSD.
Variable Documentation
configurationDescriptor
const USBDescriptor configurationDescriptor static
Initial value:
= {
  sizeof(configurationDescriptorData),
  configurationDescriptorData
}
Definition at line 1036 of file usb_msd.c.
Referenced by getDescriptor().
configurationDescriptorData
const uint8_t configurationDescriptorData[] static
Definition at line 994 of file usb_msd.c.
dbg_printer
thread_t* dbg_printer = NULL
Definition at line 109 of file usb_msd.c.
Referenced by debug_snd_evt_i(), debug_snd_evt_inl(), debug_snd_evt_nl(), and init_msd_driver().
deviceDescriptor
const USBDescriptor deviceDescriptor static
Initial value:
= {
  sizeof(deviceDescriptorData),
  deviceDescriptorData
}
Definition at line 988 of file usb_msd.c.
Referenced by getDescriptor().
deviceDescriptorData
const uint8_t deviceDescriptorData[] static
Initial value:
= {
  USB_DESC_DEVICE
  (
    0x0200,
    0x00,
    0x00,
    0x00,
    64,
    0x0483,
    0xBABE,
    0x0100,
    1,
    2,
    3,
    1
  )
}
Definition at line 971 of file usb_msd.c.
ep1_in_state
USBInEndpointState ep1_in_state static
IN end-point 1 state.
Definition at line 158 of file usb_msd.c.
ep1_out_state
USBOutEndpointState ep1_out_state static
OUT end-point 1 state.
Definition at line 163 of file usb_msd.c.
ep_data_config
const USBEndpointConfig ep_data_config static
Initial value:
= {
  USB_EP_MODE_TYPE_BULK,
  NULL,
  msd_handle_end_point_notification,
  msd_handle_end_point_notification,
  64,
  64,
  &ep1_in_state,
  &ep1_out_state,
  1,
  NULL
}
End-point 1 initialization structure.
Definition at line 168 of file usb_msd.c.
Referenced by mass_storage_thread(), and msdConfigureHookI().
languageDescriptor
const USBDescriptor languageDescriptor static
Initial value:
= {
  sizeof(languageDescriptorData),
  languageDescriptorData
}
Definition at line 1047 of file usb_msd.c.
Referenced by getDescriptor().
languageDescriptorData
const uint8_t languageDescriptorData[] static
Initial value:
= {
  USB_DESC_BYTE(4),
  USB_DESC_BYTE(USB_DESCRIPTOR_STRING),
  USB_DESC_WORD(0x0409)
}
Definition at line 1042 of file usb_msd.c.
productDescriptor
const USBDescriptor productDescriptor static
Initial value:
= {
  sizeof(productDescriptorData),
  productDescriptorData
}
Definition at line 1069 of file usb_msd.c.
Referenced by getDescriptor().
productDescriptorData
const uint8_t productDescriptorData[] static
Initial value:
= {
  USB_DESC_BYTE(24),
  USB_DESC_BYTE(USB_DESCRIPTOR_STRING),
  'M', 0, 'S', 0, 'D', 0, ' ', 0, 'E', 0, 'x', 0, 'a', 0, 'm', 0, 'p', 0, 'l', 0, 'e', 0
}
Definition at line 1064 of file usb_msd.c.
serialNumberDescriptor
const USBDescriptor serialNumberDescriptor static
Initial value:
= {
  sizeof(serialNumberDescriptorData),
  serialNumberDescriptorData
}
Definition at line 1080 of file usb_msd.c.
Referenced by getDescriptor().
serialNumberDescriptorData
const uint8_t serialNumberDescriptorData[] static
Initial value:
= {
  USB_DESC_BYTE(26),
  USB_DESC_BYTE(USB_DESCRIPTOR_STRING),
  '0', 0, '1', 0, '4', 0, '2', 0, '3', 0, '0', 0, 'F', 0, 'K', 0, '0', 0, '0', 0, '0', 0, '1', 0
}
Definition at line 1075 of file usb_msd.c.
UMSD
USBMassStorageDriver UMSD static
Definition at line 33 of file usb_msd.c.
Referenced by deinit_msd_driver(), init_msd_driver(), msd_register_evt_connected(), msd_register_evt_ejected(), msdRequestsHook(), and usbEvent().
usbConfig
const USBConfig usbConfig static
Initial value:
= {
  usbEvent,
  getDescriptor,
  msdRequestsHook,
  0
}
Definition at line 1112 of file usb_msd.c.
Referenced by init_msd_driver().
vendorDescriptor
const USBDescriptor vendorDescriptor static
Initial value:
= {
  sizeof(vendorDescriptorData),
  vendorDescriptorData
}
Definition at line 1058 of file usb_msd.c.
Referenced by getDescriptor().
vendorDescriptorData
const uint8_t vendorDescriptorData[] static
Initial value:
= {
  USB_DESC_BYTE(22),
  USB_DESC_BYTE(USB_DESCRIPTOR_STRING),
  'S', 0, 'T', 0, 'M', 0, 'i', 0, 'c', 0, 'r', 0, 'o', 0, 'M', 0, 'S', 0, 'D', 0
}
Definition at line 1053 of file usb_msd.c.