Paparazzi UAS: sw/airborne/modules/com/usb_serial_stm32_example1.c File Reference
usb_serial_stm32_example1.c File Reference
#include "modules/com/usb_serial_stm32.h"
#include <string.h>
Functions
void send_command (void)
void cmd_execute (void)
Execute command from user use strncmp.
void init_usb_serial (void)
Init module, call VCOM_init() from here.
void usb_serial_parse_packet (int data)
Parse data from buffer Note that the function receives int, not char Because we want to be able to catch -1 in case no more data were available.
static void ReadUsbBuffer (void)
Helper function.
void event_usb_serial (void)
Call VCOM_poll() from module event function.
Variables
char cmd_buf [64]
uint8_t cmd_idx
bool cmd_avail
uint8_t prompt = '$'
Detailed Description
USB_SERIAL_STM32 example 1 - a template for a console to autopilot
Definition in file usb_serial_stm32_example1.c.
Function Documentation
cmd_execute()
void cmd_execute (void)
Execute command from user use strncmp.
Definition at line 93 of file usb_serial_stm32_example1.c.
References cmd_buf, cmd_idx, prompt, VCOM_putchar(), and VCOM_send_message().
Referenced by event_usb_serial().
event_usb_serial()
void event_usb_serial (void)
Call VCOM_poll() from module event function.
Definition at line 126 of file usb_serial_stm32_example1.c.
References cmd_avail, cmd_execute(), ReadUsbBuffer(), VCOM_check_available(), and VCOM_event().
init_usb_serial()
void init_usb_serial (void)
Init module, call VCOM_init() from here.
Definition at line 44 of file usb_serial_stm32_example1.c.
References cmd_avail, cmd_idx, and VCOM_init().
ReadUsbBuffer()
static void ReadUsbBuffer (void) inline static
Helper function.
Definition at line 82 of file usb_serial_stm32_example1.c.
References cmd_avail, usb_serial_parse_packet(), VCOM_check_available(), and VCOM_getchar().
Referenced by event_usb_serial().
send_command()
void send_command (void)
usb_serial_parse_packet()
void usb_serial_parse_packet (int data)
Parse data from buffer Note that the function receives int, not char Because we want to be able to catch -1 in case no more data were available.
Definition at line 58 of file usb_serial_stm32_example1.c.
References c(), cmd_avail, cmd_buf, cmd_idx, prompt, VCOM_putchar(), and VCOM_send_message().
Referenced by ReadUsbBuffer().
Variable Documentation
cmd_avail
bool cmd_avail
Definition at line 38 of file usb_serial_stm32_example1.c.
Referenced by event_usb_serial(), init_usb_serial(), ReadUsbBuffer(), and usb_serial_parse_packet().
cmd_buf
char cmd_buf[64]
Definition at line 36 of file usb_serial_stm32_example1.c.
Referenced by cmd_execute(), nps_ap_data_loop(), and usb_serial_parse_packet().
cmd_idx
uint8_t cmd_idx
Definition at line 37 of file usb_serial_stm32_example1.c.
Referenced by cmd_execute(), init_usb_serial(), and usb_serial_parse_packet().
prompt
uint8_t prompt = '$'
Definition at line 39 of file usb_serial_stm32_example1.c.
Referenced by cmd_execute(), and usb_serial_parse_packet().