Paparazzi UAS: sw/airborne/modules/vehicle_interface/vi.c File Reference
vi.c File Reference
#include "vehicle_interface/vi.h"
#include "subsystems/imu.h"
#include "subsystems/ahrs.h"
#include "subsystems/gps.h"
#include "generated/airframe.h"
Macros
#define VI_TIMEOUT 100
Functions
void vi_init (void)
void vi_periodic (void)
void vi_set_enabled (bool enabled)
void vi_update_info (void)
Variables
struct VehicleInterface vi
Macro Definition Documentation
VI_TIMEOUT
#define VI_TIMEOUT 100
Definition at line 33 of file vi.c.
Function Documentation
vi_init()
void vi_init (void)
Definition at line 36 of file vi.c.
References VehicleInterface::enabled, GUIDANCE_H_MODE_ATTITUDE, GUIDANCE_V_MODE_CLIMB, Vi_command::h_mode, Vi_command::h_sp, VehicleInterface::input, INT_EULERS_ZERO, VehicleInterface::last_msg, VehicleInterface::timeouted, Vi_command::v_mode, Vi_command::v_sp, vi, vi_impl_init(), and VI_TIMEOUT.
vi_periodic()
void vi_periodic (void)
Definition at line 51 of file vi.c.
References GUIDANCE_H_MODE_ATTITUDE, GUIDANCE_V_MODE_CLIMB, Vi_command::h_mode, Vi_command::h_sp, VehicleInterface::input, INT_EULERS_ZERO, VehicleInterface::last_msg, VehicleInterface::timeouted, Vi_command::v_mode, Vi_command::v_sp, vi, vi_impl_periodic(), and VI_TIMEOUT.
vi_set_enabled()
void vi_set_enabled (bool enabled)
Definition at line 67 of file vi.c.
References VehicleInterface::enabled, and vi_impl_set_enabled().
vi_update_info()
void vi_update_info (void)
Definition at line 73 of file vi.c.
Variable Documentation
vi
struct VehicleInterface vi
Definition at line 30 of file vi.c.
Referenced by float_quat_vmul_right(), vi_init(), vi_periodic(), and vi_update_wp().