Paparazzi UAS: sw/airborne/modules/vehicle_interface/vi.h File Reference
vi.h File Reference
#include "std.h"
#include "math/pprz_algebra_int.h"
#include "autopilot.h"
#include "firmwares/rotorcraft/stabilization.h"
#include "firmwares/rotorcraft/guidance.h"
#include "firmwares/rotorcraft/navigation.h"
Data Structures
struct Vi_imu_info
struct Vi_gps_info
struct Vi_ahrs_info
struct Vi_info
struct Vi_command
struct VehicleInterface
union Vi_command.h_sp
union Vi_command.v_sp
Macros
#define vi_SetEnabled(_val)
Functions
void vi_init (void)
void vi_set_enabled (bool enabled)
void vi_periodic (void)
void vi_update_info (void)
void vi_notify_imu_available (void)
void vi_notify_mag_available (void)
void vi_notify_gps_available (void)
void vi_notify_baro_abs_available (void)
void vi_impl_init (void)
void vi_impl_periodic (void)
void vi_impl_set_enabled (bool enabled)
Variables
struct VehicleInterface vi
Data Structure Documentation
Vi_imu_info
struct Vi_imu_info
Definition at line 36 of file vi.h.
Data Fields
struct Int16Vect3 accel
struct Int16Vect3 gyro
struct Int16Vect3 mag
Vi_gps_info
struct Vi_gps_info
Definition at line 42 of file vi.h.
Data Fields
uint8_t fix
uint8_t num_sv
int32_t pacc
struct Int32Vect3 pos
struct Int16Vect3 speed
Vi_ahrs_info
struct Vi_ahrs_info
Definition at line 50 of file vi.h.
Data Fields
struct Int16Eulers euler
struct Int16Eulers rate
Vi_info
struct Vi_info
Definition at line 55 of file vi.h.
Data Fields
struct Vi_ahrs_info ahrs
struct Vi_gps_info gps
struct Vi_imu_info imu
Vi_command
struct Vi_command
Definition at line 61 of file vi.h.
Data Fields
uint8_t h_mode
union Vi_command h_sp
uint8_t v_mode
union Vi_command v_sp
VehicleInterface
struct VehicleInterface
Definition at line 77 of file vi.h.
Data Fields
uint8_t available_sensors
bool enabled
struct Vi_info info
struct Vi_command input
uint8_t last_msg
bool timeouted
Vi_command.h_sp
union Vi_command.h_sp
Definition at line 62 of file vi.h.
Data Fields
struct Int32Eulers attitude
struct Int32Vect3 pos
struct Int32Vect3 rate
struct Int32Vect3 speed
Vi_command.v_sp
union Vi_command.v_sp
Definition at line 68 of file vi.h.
Data Fields
int32_t climb
int32_t direct
int32_t height
Macro Definition Documentation
vi_SetEnabled
#define vi_SetEnabled (_val)
Value:
    {     \
    vi.enabled = _val;        \
    vi_set_enabled(_val);     \
  }
Definition at line 104 of file vi.h.
Function Documentation
vi_impl_init()
void vi_impl_init (void)
Definition at line 24 of file vi_datalink.c.
Referenced by vi_init().
vi_impl_periodic()
void vi_impl_periodic (void)
Definition at line 28 of file vi_datalink.c.
Referenced by vi_periodic().
vi_impl_set_enabled()
void vi_impl_set_enabled (bool enabled)
Definition at line 32 of file vi_datalink.c.
Referenced by vi_set_enabled().
vi_init()
void vi_init (void)
Definition at line 36 of file vi.c.
References VehicleInterface::enabled, GUIDANCE_H_MODE_ATTITUDE, GUIDANCE_V_MODE_CLIMB, Vi_command::h_mode, Vi_command::h_sp, VehicleInterface::input, INT_EULERS_ZERO, VehicleInterface::last_msg, VehicleInterface::timeouted, Vi_command::v_mode, Vi_command::v_sp, vi, vi_impl_init(), and VI_TIMEOUT.
vi_notify_baro_abs_available()
void vi_notify_baro_abs_available (void)
vi_notify_gps_available()
void vi_notify_gps_available (void)
vi_notify_imu_available()
void vi_notify_imu_available (void)
vi_notify_mag_available()
void vi_notify_mag_available (void)
vi_periodic()
void vi_periodic (void)
Definition at line 51 of file vi.c.
References GUIDANCE_H_MODE_ATTITUDE, GUIDANCE_V_MODE_CLIMB, Vi_command::h_mode, Vi_command::h_sp, VehicleInterface::input, INT_EULERS_ZERO, VehicleInterface::last_msg, VehicleInterface::timeouted, Vi_command::v_mode, Vi_command::v_sp, vi, vi_impl_periodic(), and VI_TIMEOUT.
vi_set_enabled()
void vi_set_enabled (bool enabled)
Definition at line 67 of file vi.c.
References VehicleInterface::enabled, and vi_impl_set_enabled().
vi_update_info()
void vi_update_info (void)
Definition at line 73 of file vi.c.
Variable Documentation
vi
struct VehicleInterface vi
Definition at line 30 of file vi.c.
Referenced by float_quat_vmul_right(), vi_init(), vi_periodic(), and vi_update_wp().