Paparazzi UAS: sw/airborne/modules/vehicle_interface/vi_datalink.c File Reference
vi_datalink.c File Reference
#include "modules/vehicle_interface/vi_datalink.h"
Macros
#define ViMaxHSpeed ((int16_t)SPEED_BFP_OF_REAL(VI_MAX_H_SPEED))
#define ViMaxVSpeed ((int16_t)SPEED_BFP_OF_REAL(VI_MAX_V_SPEED))
#define ViMaxHeadingRate ((int16_t)RATE_BFP_OF_REAL(VI_MAX_HEADING_RATE))
Functions
void vi_impl_init (void)
void vi_impl_periodic (void)
void vi_impl_set_enabled (bool enabled)
void vi_update_wp (uint8_t wp_id)
Variables
struct Int16Vect3 wp_speed_max = { ViMaxHSpeed, ViMaxHSpeed, ViMaxVSpeed }
Macro Definition Documentation
ViMaxHeadingRate
#define ViMaxHeadingRate ((int16_t)RATE_BFP_OF_REAL(VI_MAX_HEADING_RATE))
Definition at line 38 of file vi_datalink.c.
ViMaxHSpeed
#define ViMaxHSpeed ((int16_t)SPEED_BFP_OF_REAL(VI_MAX_H_SPEED))
Definition at line 36 of file vi_datalink.c.
ViMaxVSpeed
#define ViMaxVSpeed ((int16_t)SPEED_BFP_OF_REAL(VI_MAX_V_SPEED))
Definition at line 37 of file vi_datalink.c.
Function Documentation
vi_impl_init()
void vi_impl_init (void)
Definition at line 24 of file vi_datalink.c.
Referenced by vi_init().
vi_impl_periodic()
void vi_impl_periodic (void)
Definition at line 28 of file vi_datalink.c.
Referenced by vi_periodic().
vi_impl_set_enabled()
void vi_impl_set_enabled (bool enabled)
Definition at line 32 of file vi_datalink.c.
Referenced by vi_set_enabled().
vi_update_wp()
void vi_update_wp (uint8_t wp_id)
Definition at line 42 of file vi_datalink.c.
References Vi_command::h_sp, VehicleInterface::input, navigation_update_wp_from_speed(), Vi_command::v_sp, VECT3_BOUND_BOX, vi, ViMaxHeadingRate, ViMaxHSpeed, ViMaxVSpeed, wp_speed_max, Int16Vect3::x, Int16Vect3::y, and Int16Vect3::z.
Variable Documentation
wp_speed_max
struct Int16Vect3 wp_speed_max = { ViMaxHSpeed, ViMaxHSpeed, ViMaxVSpeed }
Definition at line 40 of file vi_datalink.c.
Referenced by vi_update_wp().