Paparazzi UAS: sw/airborne/arch/lpc21/vic_slots.txt File Reference
sw/airborne/arch/lpc21/vic_slots.txt File Reference
Functions
VIC slots used for the LPC2148 define name slot (default) used for ------------------------------------------------------------------ TIMER0_VIC_SLOT 1 system timer AD0_VIC_SLOT 2 adc_arch if USE_AD0 PWM_VIC_SLOT 3 PWM_ISR in servos_4015 AD1_VIC_SLOT 4 adc_arch if USE_AD1 UART0_VIC_SLOT 5 uart_arch
VIC slots used for the LPC2148 define name e g gps UART1_VIC_SLOT e g modem SPI1_VIC_SLOT SPI1 in mcu_periph spi_arch c or spi_slave_hs_arch c (and some others not using the SPI peripheral yet..) I2C0_VIC_SLOT 8 mcu_periph/i2c_arch.c I2C1_VIC_SLOT 9 mcu_periph/i2c_arch.c USB_VIC_SLOT 10 usb
Variables
VIC slots used for the LPC2148 define name e g gps UART1_VIC_SLOT uart_arch
VIC slots used for the LPC2148 define name e g gps UART1_VIC_SLOT e g modem SPI1_VIC_SLOT SPI1 in mcu_periph spi_arch c or spi_slave_hs_arch e g telemetry_transparent_usb no defaults
VIC slots used for the LPC2148 define name e g gps UART1_VIC_SLOT e g modem SPI1_VIC_SLOT SPI1 in mcu_periph spi_arch c or spi_slave_hs_arch e g telemetry_transparent_usb no explicitly set in subsystems
VIC slots used for the LPC2148 define name e g gps UART1_VIC_SLOT e g modem SPI1_VIC_SLOT SPI1 in mcu_periph spi_arch c or spi_slave_hs_arch e g telemetry_transparent_usb no explicitly set in imu_b2_v1
VIC slots used for the LPC2148 define name e g gps UART1_VIC_SLOT e g modem SPI1_VIC_SLOT SPI1 in mcu_periph spi_arch c or spi_slave_hs_arch e g telemetry_transparent_usb no explicitly set in imu_b2_v1 MS2100_DRDY_VIC_SLOT ms2100 mag in imu_b2_v1 in modules
VIC slots used for the LPC2148 define name e g gps UART1_VIC_SLOT e g modem SPI1_VIC_SLOT SPI1 in mcu_periph spi_arch c or spi_slave_hs_arch e g telemetry_transparent_usb no explicitly set in imu_b2_v1 MS2100_DRDY_VIC_SLOT ms2100 mag in imu_b2_v1 in no define EXTINT in max3100 module these seem to be outdated
Function Documentation
c()
VIC slots used for the LPC2148 define name e g gps UART1_VIC_SLOT e g modem SPI1_VIC_SLOT SPI1 in mcu_periph spi_arch c or spi_slave_hs_arch c (and some others not using the SPI peripheral yet..)
Referenced by _chvsnprintf(), act_fast(), adxl345_data_format(), adxl345_set_default_config(), airspeed_otf_parse(), airspeed_uadc_parse(), ascii_to_osd_c(), autopilot_parse(), bef(), bmi088_set_default_config(), calc_ntc(), calculate_edge_displacement(), coloryuv_opencv_to_yuv422(), compute_ground_speed(), cv_blob_locator_func(), detect_escape(), dev_getch(), DictionaryTrainingYUV(), DistributionExtraction(), dw1000_arduino_parse(), esc32_compute_ck(), esc32_get_float(), esc32_put_char(), esc32_put_float(), esc32_put_short(), fifo_put(), float_mat_col(), float_mat_exp(), float_quat_derivative_lagrange(), frsky_x_serial_put_byte(), frSkyXSetRcData(), frSkyXTelemetrySendByte(), get_comm_signature(), get_msg(), gps_mtk_parse(), gps_skytraq_parse(), gps_ubx_parse(), gsm_parse(), gx3_packet_parse(), handle_raw(), handle_raw_other(), handle_uart_rx(), hmc58xx_set_default_config(), hott_check_serial_data(), humid_sht_uart_parse(), indexn(), initialise(), inputbuf_init(), intermcu_parse(), InterMcuEvent(), invariant_model(), itg3200_set_default_config(), jevois_mavlink_event(), jevois_parse(), l3g4200_set_default_config(), l3gd20_set_default_config(), lis302dl_set_default_config(), lla_of_ecef_d(), lla_of_ecef_f(), lps25h_set_default_config(), lsm303d_set_default_config(), lsm303dlhc_acc_set_default_config(), lsm303dlhc_mag_set_default_config(), lsm6_set_default_config(), main(), modem_parse(), mpu60x0_set_default_config(), mpu9250_set_default_config(), nav_survey_ComputeProjectionOnLine(), nmea_parse_char(), nps_main_parse_options(), opticflow_pmw3901_publish(), parse_data(), parse_esc32(), parse_mavlink(), parse_mora(), pprz_polyfit_float(), print_hex(), print_hex16(), print_hex32(), push_gps_to_vision(), qr(), qr_e(), read_into_buffer(), set_comm_from_transaction(), set_default_comm_config(), sim_use_gps_pos(), sirf_parse_char(), smartPortDataReceive(), SpiRead(), SpiSend(), stabilization_attitude_init(), stabilization_attitude_run(), stereo_parse(), syslink_parse_char(), syslink_put_buffer(), THD_FUNCTION(), uart_receive_handler(), UM6_packet_parse(), update_LUT(), update_rc_channel(), usb_serial_parse_packet(), uyvy_opencv_to_yuv_opencv(), VCOM_getchar(), VCOM_peekchar(), VCOM_putchar(), vn200_parse(), w5100_read_buffer(), xsens_parser_func(), and yuv_opencv_to_yuv422().
slot()
VIC slots used for the LPC2148 define name slot (default)
Variable Documentation
defaults
VIC slots used for the LPC2148 define name e g gps UART1_VIC_SLOT e g modem SPI1_VIC_SLOT SPI1 in mcu_periph spi_arch c or spi_slave_hs_arch e g telemetry_transparent_usb no defaults
Definition at line 17 of file vic_slots.txt.
imu_b2_v1
VIC slots used for the LPC2148 define name e g gps UART1_VIC_SLOT e g modem SPI1_VIC_SLOT SPI1 in mcu_periph spi_arch c or spi_slave_hs_arch e g telemetry_transparent_usb no explicitly set in imu_b2_v1
Definition at line 18 of file vic_slots.txt.
modules
VIC slots used for the LPC2148 define name e g gps UART1_VIC_SLOT e g modem SPI1_VIC_SLOT SPI1 in mcu_periph spi_arch c or spi_slave_hs_arch e g telemetry_transparent_usb no explicitly set in imu_b2_v1 MS2100_DRDY_VIC_SLOT ms2100 mag in imu_b2_v1 in modules
Definition at line 22 of file vic_slots.txt.
outdated
VIC slots used for the LPC2148 define name e g gps UART1_VIC_SLOT e g modem SPI1_VIC_SLOT SPI1 in mcu_periph spi_arch c or spi_slave_hs_arch e g telemetry_transparent_usb no explicitly set in imu_b2_v1 MS2100_DRDY_VIC_SLOT ms2100 mag in imu_b2_v1 in no define EXTINT in max3100 module these seem to be outdated
Definition at line 24 of file vic_slots.txt.
subsystems
VIC slots used for the LPC2148 define name e g gps UART1_VIC_SLOT e g modem SPI1_VIC_SLOT SPI1 in mcu_periph spi_arch c or spi_slave_hs_arch e g telemetry_transparent_usb no explicitly set in subsystems
Definition at line 18 of file vic_slots.txt.
uart_arch
VIC slots used for the LPC2148 define name e g gps UART1_VIC_SLOT uart_arch
Definition at line 10 of file vic_slots.txt.