Paparazzi UAS: sw/airborne/modules/actuators/actuators_uavcan.h File Reference
actuators_uavcan.h File Reference
#include "modules/uavcan/uavcan.h"
#include <BOARD_CONFIG>
Functions
void actuators_uavcan_init (struct uavcan_iface_t *iface)
Initialize an uavcan interface.
void actuators_uavcan_commit (struct uavcan_iface_t *iface, int16_t *values, uint8_t nb)
Commit actuator values to the uavcan interface.
Function Documentation
actuators_uavcan_commit()
void actuators_uavcan_commit (struct uavcan_iface_t * iface, int16_t * values, uint8_t nb)
Commit actuator values to the uavcan interface.
Definition at line 198 of file actuators_uavcan.c.
References offset, uavcan_broadcast(), UAVCAN_EQUIPMENT_ESC_RAWCOMMAND_ID, UAVCAN_EQUIPMENT_ESC_RAWCOMMAND_MAX_SIZE, and UAVCAN_EQUIPMENT_ESC_RAWCOMMAND_SIGNATURE.
actuators_uavcan_init()
void actuators_uavcan_init (struct uavcan_iface_t * iface)
Initialize an uavcan interface.
Definition at line 174 of file actuators_uavcan.c.
References actuators_uavcan_esc_status_cb(), actuators_uavcan_initialized, actuators_uavcan_send_esc(), DefaultPeriodic, esc_status_ev, init_random(), register_periodic_telemetry(), uavcan_bind(), UAVCAN_EQUIPMENT_ESC_STATUS_ID, and UAVCAN_EQUIPMENT_ESC_STATUS_SIGNATURE.