Paparazzi UAS: sw/airborne/modules/ahrs/ahrs_chimu_uart.c File Reference
ahrs_chimu_uart.c File Reference
#include <stdbool.h>
#include "state.h"
#include "modules/gps/gps.h"
#include "modules/ahrs/ahrs.h"
#include "generated/airframe.h"
#include "modules/ins/ins_module.h"
#include "modules/ins/imu_chimu.h"
#include "led.h"
Functions
static bool ahrs_chimu_enable_output (bool enable)
void ahrs_chimu_register (void)
void ahrs_chimu_init (void)
void parse_ins_msg (void)
Variables
CHIMU_PARSER_DATA CHIMU_DATA
INS_FORMAT ins_roll_neutral
INS_FORMAT ins_pitch_neutral
struct AhrsChimu ahrs_chimu
Function Documentation
ahrs_chimu_enable_output()
static bool ahrs_chimu_enable_output (bool enable) static
Definition at line 35 of file ahrs_chimu_uart.c.
References ahrs_chimu, and AhrsChimu::is_enabled.
Referenced by ahrs_chimu_register().
ahrs_chimu_init()
void ahrs_chimu_init (void)
Definition at line 47 of file ahrs_chimu_uart.c.
References ahrs_chimu, CHIMU_BROADCAST, CHIMU_Checksum(), CHIMU_DATA, CHIMU_Init(), CHIMU_STX, ins_pitch_neutral, INS_PITCH_NEUTRAL_DEFAULT, ins_roll_neutral, INS_ROLL_NEUTRAL_DEFAULT, InsSend, InsUartSend1, AhrsChimu::is_aligned, AhrsChimu::is_enabled, MSG00_PING, MSG09_ESTIMATOR, MSG10_UARTSETTINGS, and new_ins_attitude.
Referenced by ahrs_chimu_register().
ahrs_chimu_register()
void ahrs_chimu_register (void)
Definition at line 41 of file ahrs_chimu_uart.c.
References ahrs_chimu_enable_output(), ahrs_chimu_init(), and ahrs_register_impl().
parse_ins_msg()
void parse_ins_msg (void) inline
Definition at line 81 of file ahrs_chimu_uart.c.
References ahrs_chimu, AHRS_COMP_ID_CHIMU, CHIMU_DATA, CHIMU_Msg_3_IMU_Attitude, CHIMU_Parse(), DefaultChannel, DefaultDevice, dev, CHIMU_attitude_data::euler, InsLinkDevice, AhrsChimu::is_aligned, AhrsChimu::is_enabled, LED_TOGGLE, CHIMU_PARSER_DATA::m_attitude, CHIMU_PARSER_DATA::m_attrates, CHIMU_PARSER_DATA::m_MsgID, CHIMU_PARSER_DATA::m_sensor, new_ins_attitude, CHIMU_Euler::phi, CHIMU_Euler::psi, CHIMU_sensor_data::rate, stateSetBodyRates_f(), stateSetNedToBodyEulers_f(), and CHIMU_Euler::theta.
Referenced by ins_event_check_and_handle().
Variable Documentation
ahrs_chimu
struct AhrsChimu ahrs_chimu
Definition at line 33 of file ahrs_chimu_uart.c.
Referenced by ahrs_chimu_enable_output(), ahrs_chimu_init(), and parse_ins_msg().
CHIMU_DATA
CHIMU_PARSER_DATA CHIMU_DATA
Definition at line 28 of file ahrs_chimu_uart.c.
Referenced by ahrs_chimu_init(), and parse_ins_msg().
ins_pitch_neutral
INS_FORMAT ins_pitch_neutral
Definition at line 31 of file ahrs_chimu_uart.c.
Referenced by ahrs_chimu_init().
ins_roll_neutral
INS_FORMAT ins_roll_neutral
Definition at line 30 of file ahrs_chimu_uart.c.
Referenced by ahrs_chimu_init().