Paparazzi UAS: sw/airborne/modules/ahrs/ahrs_float_cmpl_wrapper.h File Reference
ahrs_float_cmpl_wrapper.h File Reference
#include "modules/ahrs/ahrs_float_cmpl.h"
Macros
#define PRIMARY_AHRS ahrs_fc
Functions
void ahrs_fc_register (void)
Detailed Description
Paparazzi specific wrapper to run floating point complementary filter.
Definition in file ahrs_float_cmpl_wrapper.h.
Macro Definition Documentation
PRIMARY_AHRS
#define PRIMARY_AHRS ahrs_fc
Definition at line 33 of file ahrs_float_cmpl_wrapper.h.
Function Documentation
ahrs_fc_register()
void ahrs_fc_register (void)
Definition at line 283 of file ahrs_float_cmpl_wrapper.c.
References ABI_BROADCAST, accel_cb(), accel_ev, ahrs_fc_enable_output(), AHRS_FC_GPS_ID, AHRS_FC_IMU_ID, ahrs_fc_init(), AHRS_FC_MAG_ID, AHRS_FC_OUTPUT_ENABLED, ahrs_fc_output_enabled, ahrs_register_impl(), aligner_cb(), aligner_ev, body_to_imu_cb(), body_to_imu_ev, DefaultPeriodic, geo_mag_cb(), geo_mag_ev, gps_cb(), gps_ev, gyro_cb(), gyro_ev, mag_cb(), mag_ev, register_periodic_telemetry(), send_bias(), send_euler(), send_euler_int(), send_filter_status(), and send_geo_mag().