Paparazzi UAS: sw/airborne/modules/ahrs/ahrs_chimu.h File Reference
ahrs_chimu.h File Reference
#include "modules/ins/ins_module.h"
#include "modules/ahrs/ahrs.h"
Data Structures
struct AhrsChimu
Macros
#define PRIMARY_AHRS ahrs_chimu
Functions
void ahrs_chimu_register (void)
void ahrs_chimu_init (void)
Variables
struct AhrsChimu ahrs_chimu
Data Structure Documentation
AhrsChimu
struct AhrsChimu
Definition at line 32 of file ahrs_chimu.h.
Data Fields
bool is_aligned
bool is_enabled
Macro Definition Documentation
PRIMARY_AHRS
#define PRIMARY_AHRS ahrs_chimu
Definition at line 40 of file ahrs_chimu.h.
Function Documentation
ahrs_chimu_init()
void ahrs_chimu_init (void)
Definition at line 71 of file ahrs_chimu_spi.c.
References ahrs_chimu, CHIMU_BROADCAST, CHIMU_Checksum(), CHIMU_DATA, CHIMU_Init(), CHIMU_STX, ins_pitch_neutral, INS_PITCH_NEUTRAL_DEFAULT, ins_roll_neutral, INS_ROLL_NEUTRAL_DEFAULT, InsSend, InsSend1, InsUartSend1, AhrsChimu::is_aligned, AhrsChimu::is_enabled, MSG00_PING, MSG09_ESTIMATOR, MSG10_UARTSETTINGS, and new_ins_attitude.
Referenced by ahrs_chimu_register().
ahrs_chimu_register()
void ahrs_chimu_register (void)
Definition at line 64 of file ahrs_chimu_spi.c.
References ahrs_chimu_enable_output(), AHRS_CHIMU_GPS_ID, ahrs_chimu_init(), ahrs_register_impl(), gps_cb(), and gps_ev.
Variable Documentation
ahrs_chimu
struct AhrsChimu ahrs_chimu
Definition at line 38 of file ahrs_chimu_spi.c.
Referenced by ahrs_chimu_enable_output(), ahrs_chimu_init(), and parse_ins_msg().