Paparazzi UAS: sw/airborne/modules/ahrs/ahrs_float_invariant_wrapper.h File Reference
ahrs_float_invariant_wrapper.h File Reference
#include "modules/ahrs/ahrs_float_invariant.h"
Macros
#define PRIMARY_AHRS ahrs_float_invariant
Functions
void ahrs_float_invariant_register (void)
Detailed Description
Paparazzi specific wrapper to run INVARIANT ahrs filter.
Definition in file ahrs_float_invariant_wrapper.h.
Macro Definition Documentation
PRIMARY_AHRS
#define PRIMARY_AHRS ahrs_float_invariant
Definition at line 33 of file ahrs_float_invariant_wrapper.h.
Function Documentation
ahrs_float_invariant_register()
void ahrs_float_invariant_register (void)
Definition at line 237 of file ahrs_float_invariant_wrapper.c.
References ABI_BROADCAST, accel_cb(), accel_ev, AHRS_FINV_IMU_ID, AHRS_FINV_MAG_ID, AHRS_FINV_OUTPUT_ENABLED, ahrs_finv_output_enabled, ahrs_float_invariant_enable_output(), ahrs_float_invariant_init(), ahrs_register_impl(), aligner_cb(), aligner_ev, body_to_imu_cb(), body_to_imu_ev, DefaultPeriodic, geo_mag_cb(), geo_mag_ev, gyro_cb(), gyro_ev, mag_cb(), mag_ev, register_periodic_telemetry(), send_att(), send_filter_status(), and send_geo_mag().