Paparazzi UAS: sw/airborne/modules/ahrs/ahrs_float_mlkf_wrapper.h File Reference
ahrs_float_mlkf_wrapper.h File Reference
#include "modules/ahrs/ahrs_float_mlkf.h"
Macros
#define PRIMARY_AHRS ahrs_mlkf
Functions
void ahrs_mlkf_register (void)
Detailed Description
Paparazzi specific wrapper to run MLKF filter.
Definition in file ahrs_float_mlkf_wrapper.h.
Macro Definition Documentation
PRIMARY_AHRS
#define PRIMARY_AHRS ahrs_mlkf
Definition at line 33 of file ahrs_float_mlkf_wrapper.h.
Function Documentation
ahrs_mlkf_register()
void ahrs_mlkf_register (void)
Definition at line 222 of file ahrs_float_mlkf_wrapper.c.
References ABI_BROADCAST, accel_cb(), accel_ev, ahrs_mlkf_enable_output(), AHRS_MLKF_IMU_ID, ahrs_mlkf_init(), AHRS_MLKF_MAG_ID, AHRS_MLKF_OUTPUT_ENABLED, ahrs_mlkf_output_enabled, ahrs_register_impl(), aligner_cb(), aligner_ev, body_to_imu_cb(), body_to_imu_ev, DefaultPeriodic, geo_mag_cb(), geo_mag_ev, gyro_cb(), gyro_ev, mag_cb(), mag_ev, register_periodic_telemetry(), send_bias(), send_euler(), send_filter_status(), and send_geo_mag().