Paparazzi UAS: sw/airborne/modules/ahrs/ahrs_int_cmpl_quat_wrapper.h File Reference
ahrs_int_cmpl_quat_wrapper.h File Reference
#include "modules/ahrs/ahrs_int_cmpl_quat.h"
Macros
#define PRIMARY_AHRS ahrs_icq
Functions
void ahrs_icq_register (void)
Detailed Description
Paparazzi specific wrapper to run floating point complementary filter.
Definition in file ahrs_int_cmpl_quat_wrapper.h.
Macro Definition Documentation
PRIMARY_AHRS
#define PRIMARY_AHRS ahrs_icq
Definition at line 33 of file ahrs_int_cmpl_quat_wrapper.h.
Function Documentation
ahrs_icq_register()
void ahrs_icq_register (void)
Definition at line 271 of file ahrs_int_cmpl_quat_wrapper.c.
References ABI_BROADCAST, accel_cb(), accel_ev, ahrs_icq_enable_output(), AHRS_ICQ_GPS_ID, AHRS_ICQ_IMU_ID, ahrs_icq_init(), AHRS_ICQ_MAG_ID, AHRS_ICQ_OUTPUT_ENABLED, ahrs_icq_output_enabled, ahrs_register_impl(), aligner_cb(), aligner_ev, body_to_imu_cb(), body_to_imu_ev, DefaultPeriodic, geo_mag_cb(), geo_mag_ev, gps_cb(), gps_ev, gyro_cb(), gyro_ev, mag_cb(), mag_ev, register_periodic_telemetry(), send_bias(), send_euler(), send_filter_status(), send_geo_mag(), and send_quat().