Paparazzi UAS: sw/airborne/modules/ahrs/ahrs_madgwick_wrapper.h File Reference
ahrs_madgwick_wrapper.h File Reference
#include "modules/ahrs/ahrs_madgwick.h"
Macros
#define PRIMARY_AHRS ahrs_madgwick
Functions
void ahrs_madgwick_register (void)
Detailed Description
Paparazzi specific wrapper to run Madgwick ahrs filter.
Definition in file ahrs_madgwick_wrapper.h.
Macro Definition Documentation
PRIMARY_AHRS
#define PRIMARY_AHRS ahrs_madgwick
Definition at line 33 of file ahrs_madgwick_wrapper.h.
Function Documentation
ahrs_madgwick_register()
void ahrs_madgwick_register (void)
Definition at line 203 of file ahrs_madgwick_wrapper.c.
References accel_cb(), accel_ev, ahrs_madgwick_enable_output(), AHRS_MADGWICK_IMU_ID, ahrs_madgwick_init(), AHRS_MADGWICK_OUTPUT_ENABLED, ahrs_madgwick_output_enabled, ahrs_register_impl(), aligner_cb(), aligner_ev, body_to_imu_cb(), body_to_imu_ev, DefaultPeriodic, gyro_cb(), gyro_ev, register_periodic_telemetry(), send_att(), and send_filter_status().