Paparazzi UAS: sw/airborne/modules/ahrs/ahrs_float_utils.h File Reference
ahrs_float_utils.h File Reference
#include "math/pprz_algebra_float.h"
#include "modules/ahrs/ahrs_magnetic_field_model.h"
#include "std.h"
Functions
static void ahrs_float_get_euler_from_accel_mag (struct FloatEulers *e, struct FloatVect3 *accel, struct FloatVect3 *mag)
Computer orientation in euler angles from accel and mag This is not working when the IMU is upside-down, then use the quaternion based function.
static void ahrs_float_get_quat_from_accel (struct FloatQuat *q, struct FloatVect3 *accel)
Compute a quaternion representing roll and pitch from an accelerometer measurement.
static void ahrs_float_get_quat_from_accel_mag (struct FloatQuat *q, struct FloatVect3 *accel, struct FloatVect3 *mag)
Detailed Description
Utility functions for floating point AHRS implementations.
Definition in file ahrs_float_utils.h.
Function Documentation
ahrs_float_get_euler_from_accel_mag()
static void ahrs_float_get_euler_from_accel_mag (struct FloatEulers * e, struct FloatVect3 * accel, struct FloatVect3 * mag) inline static
Computer orientation in euler angles from accel and mag This is not working when the IMU is upside-down, then use the quaternion based function.
Definition at line 40 of file ahrs_float_utils.h.
References EULERS_ASSIGN, FloatVect3::x, FloatVect3::y, and FloatVect3::z.
ahrs_float_get_quat_from_accel()
static void ahrs_float_get_quat_from_accel (struct FloatQuat * q, struct FloatVect3 * accel) inline static
Compute a quaternion representing roll and pitch from an accelerometer measurement.
Definition at line 61 of file ahrs_float_utils.h.
References float_quat_normalize(), float_vect3_normalize(), FloatQuat::qi, QUAT_ASSIGN, FloatQuat::qx, FloatQuat::qy, FloatQuat::qz, FloatVect3::x, FloatVect3::y, and FloatVect3::z.
Referenced by ahrs_dcm_align(), ahrs_fc_align(), ahrs_float_get_quat_from_accel_mag(), ahrs_int_get_quat_from_accel(), ahrs_madgwick_align(), and ins_float_invariant_align().
ahrs_float_get_quat_from_accel_mag()
static void ahrs_float_get_quat_from_accel_mag (struct FloatQuat * q, struct FloatVect3 * accel, struct FloatVect3 * mag) inline static
Definition at line 85 of file ahrs_float_utils.h.
References ahrs_float_get_quat_from_accel(), float_quat_comp_norm_shortest(), float_quat_normalize(), float_rmat_of_quat(), float_rmat_transp_vmult(), FloatQuat::qi, QUAT_ASSIGN, FloatQuat::qx, FloatQuat::qy, FloatQuat::qz, SQUARE, FloatVect3::x, and FloatVect3::y.
Referenced by ahrs_dcm_align(), ahrs_fc_align(), ahrs_float_invariant_align(), ahrs_int_get_quat_from_accel_mag(), ahrs_mlkf_align(), aligner_cb(), and ins_float_invariant_align().