Paparazzi UAS: sw/airborne/modules/sensors/baro_ms5611_spi.c File Reference
baro_ms5611_spi.c File Reference
#include "modules/sensors/baro_ms5611_spi.h"
#include "math/pprz_isa.h"
#include "mcu_periph/sys_time.h"
#include "modules/core/abi.h"
#include "mcu_periph/uart.h"
#include "pprzlink/messages.h"
#include "modules/datalink/downlink.h"
Macros
#define MS5611_SPI_DEV spi1
#define MS5611_SLAVE_IDX SPI_SLAVE0
Functions
void baro_ms5611_init (void)
void baro_ms5611_periodic_check (void)
void baro_ms5611_read (void)
trigger new measurement or initialize if needed
void baro_ms5611_event (void)
void baro_ms5611_send_coeff (void)
Variables
struct Ms5611_Spi baro_ms5611
float fbaroms
float ftempms
float baro_ms5611_alt
bool baro_ms5611_alt_valid
bool baro_ms5611_enabled
float baro_ms5611_r
float baro_ms5611_sigma2
Detailed Description
Measurement Specialties (Intersema) MS5611-01BA pressure/temperature sensor interface for SPI.
Definition in file baro_ms5611_spi.c.
Macro Definition Documentation
MS5611_SLAVE_IDX
#define MS5611_SLAVE_IDX SPI_SLAVE0
Definition at line 44 of file baro_ms5611_spi.c.
MS5611_SPI_DEV
#define MS5611_SPI_DEV spi1
Definition at line 40 of file baro_ms5611_spi.c.
Function Documentation
baro_ms5611_event()
void baro_ms5611_event (void)
Definition at line 90 of file baro_ms5611_spi.c.
References baro_ms5611, baro_ms5611_alt, baro_ms5611_alt_valid, BARO_MS5611_SENDER_ID, Ms5611Data::d1, Ms5611Data::d2, Ms5611_I2c::data, Ms5611_Spi::data, Ms5611_I2c::data_available, Ms5611_Spi::data_available, DefaultChannel, DefaultDevice, fbaroms, get_sys_time_usec(), ms5611_i2c_event(), ms5611_spi_event(), pprz_isa_altitude_of_pressure(), Ms5611Data::pressure, Mpl3115::pressure, and Ms5611Data::temperature.
baro_ms5611_init()
void baro_ms5611_init (void)
Definition at line 59 of file baro_ms5611_spi.c.
References baro_ms5611, baro_ms5611_alt_valid, baro_ms5611_enabled, BARO_MS5611_R, baro_ms5611_r, BARO_MS5611_SIGMA2, baro_ms5611_sigma2, FALSE, MS5611_I2C_DEV, ms5611_i2c_init(), MS5611_SLAVE_ADDR, MS5611_SLAVE_IDX, MS5611_SPI_DEV, ms5611_spi_init(), and MS5611_TYPE_MS5607.
baro_ms5611_periodic_check()
void baro_ms5611_periodic_check (void)
Definition at line 70 of file baro_ms5611_spi.c.
References baro_ms5611, baro_ms5611_send_coeff(), ms5611_i2c_periodic_check(), and ms5611_spi_periodic_check().
baro_ms5611_read()
void baro_ms5611_read (void)
trigger new measurement or initialize if needed
Definition at line 83 of file baro_ms5611_spi.c.
References baro_ms5611, ms5611_i2c_read(), ms5611_spi_read(), and sys_time::nb_sec.
baro_ms5611_send_coeff()
void baro_ms5611_send_coeff (void)
Definition at line 115 of file baro_ms5611_spi.c.
References baro_ms5611, Ms5611Data::c, Ms5611_I2c::data, Ms5611_Spi::data, DefaultChannel, DefaultDevice, Ms5611_I2c::initialized, and Ms5611_Spi::initialized.
Referenced by baro_ms5611_periodic_check().
Variable Documentation
baro_ms5611
struct Ms5611_Spi baro_ms5611
Definition at line 48 of file baro_ms5611_spi.c.
Referenced by baro_ms5611_event(), baro_ms5611_init(), baro_ms5611_periodic_check(), baro_ms5611_read(), and baro_ms5611_send_coeff().
baro_ms5611_alt
float baro_ms5611_alt
Definition at line 51 of file baro_ms5611_spi.c.
Referenced by baro_ms5611_event().
baro_ms5611_alt_valid
bool baro_ms5611_alt_valid
Definition at line 52 of file baro_ms5611_spi.c.
Referenced by baro_ms5611_event(), and baro_ms5611_init().
baro_ms5611_enabled
bool baro_ms5611_enabled
Definition at line 53 of file baro_ms5611_spi.c.
Referenced by baro_ms5611_init().
baro_ms5611_r
float baro_ms5611_r
Definition at line 55 of file baro_ms5611_spi.c.
Referenced by baro_ms5611_init().
baro_ms5611_sigma2
float baro_ms5611_sigma2
Definition at line 56 of file baro_ms5611_spi.c.
Referenced by baro_ms5611_init().
fbaroms
float fbaroms
Definition at line 50 of file baro_ms5611_spi.c.
Referenced by baro_ms5611_event().
ftempms
float ftempms
Definition at line 50 of file baro_ms5611_spi.c.