Paparazzi UAS: sw/airborne/modules/ctrl/ctrl_module_innerloop_demo.c File Reference
ctrl_module_innerloop_demo.c File Reference
example empty controller
#include "modules/ctrl/ctrl_module_innerloop_demo.h"
#include "state.h"
#include "modules/radio_control/radio_control.h"
#include "firmwares/rotorcraft/stabilization.h"
Data Structures
struct ctrl_module_demo_struct
Functions
void ctrl_module_init (void)
void ctrl_module_run (bool in_flight)
void guidance_h_module_init (void)
void guidance_h_module_enter (void)
void guidance_h_module_read_rc (void)
void guidance_h_module_run (bool in_flight)
void guidance_v_module_init (void)
void guidance_v_module_enter (void)
void guidance_v_module_run (UNUSED bool in_flight)
Variables
struct ctrl_module_demo_struct ctrl_module_demo
float ctrl_module_demo_pr_ff_gain = 0.2f
float ctrl_module_demo_pr_d_gain = 0.1f
float ctrl_module_demo_y_ff_gain = 0.4f
float ctrl_module_demo_y_d_gain = 0.05f
Detailed Description
example empty controller
Implements an example simple rate controller in a module.
Definition in file ctrl_module_innerloop_demo.c.
Data Structure Documentation
ctrl_module_demo_struct
struct ctrl_module_demo_struct
Definition at line 32 of file ctrl_module_innerloop_demo.c.
Data Fields
struct Int32Eulers cmd
struct Int32Eulers rc_sp
int rc_t
int rc_x
int rc_y
int rc_z
Function Documentation
ctrl_module_init()
void ctrl_module_init (void)
Definition at line 48 of file ctrl_module_innerloop_demo.c.
References ctrl_module_demo, ctrl_module_demo_struct::rc_t, ctrl_module_demo_struct::rc_x, ctrl_module_demo_struct::rc_y, and ctrl_module_demo_struct::rc_z.
Referenced by guidance_h_module_enter(), and guidance_h_module_init().
ctrl_module_run()
void ctrl_module_run (bool in_flight)
Definition at line 57 of file ctrl_module_innerloop_demo.c.
References ctrl_module_demo, ctrl_module_demo_pr_d_gain, ctrl_module_demo_pr_ff_gain, ctrl_module_demo_y_d_gain, ctrl_module_demo_y_ff_gain, Int32Rates::p, Int32Rates::q, Int32Rates::r, ctrl_module_demo_struct::rc_t, ctrl_module_demo_struct::rc_x, ctrl_module_demo_struct::rc_y, ctrl_module_demo_struct::rc_z, stabilization_cmd, and stateGetBodyRates_i().
Referenced by guidance_h_module_run().
guidance_h_module_enter()
void guidance_h_module_enter (void)
Definition at line 85 of file ctrl_module_innerloop_demo.c.
Referenced by guidance_h_mode_changed().
guidance_h_module_init()
void guidance_h_module_init (void)
Definition at line 80 of file ctrl_module_innerloop_demo.c.
Referenced by guidance_h_init().
guidance_h_module_read_rc()
void guidance_h_module_read_rc (void)
Definition at line 90 of file ctrl_module_innerloop_demo.c.
Referenced by guidance_h_read_rc().
guidance_h_module_run()
void guidance_h_module_run (bool in_flight)
Definition at line 99 of file ctrl_module_innerloop_demo.c.
Referenced by guidance_h_run().
guidance_v_module_enter()
void guidance_v_module_enter (void)
Definition at line 111 of file ctrl_module_innerloop_demo.c.
Referenced by guidance_v_mode_changed().
guidance_v_module_init()
void guidance_v_module_init (void)
Definition at line 105 of file ctrl_module_innerloop_demo.c.
Referenced by guidance_v_init().
guidance_v_module_run()
void guidance_v_module_run (UNUSED bool in_flight)
Definition at line 116 of file ctrl_module_innerloop_demo.c.
Referenced by guidance_v_run().
Variable Documentation
ctrl_module_demo
struct ctrl_module_demo_struct ctrl_module_demo
Referenced by ctrl_module_init(), ctrl_module_run(), and guidance_h_module_read_rc().
ctrl_module_demo_pr_d_gain
float ctrl_module_demo_pr_d_gain = 0.1f
Definition at line 41 of file ctrl_module_innerloop_demo.c.
Referenced by ctrl_module_run().
ctrl_module_demo_pr_ff_gain
float ctrl_module_demo_pr_ff_gain = 0.2f
Definition at line 40 of file ctrl_module_innerloop_demo.c.
Referenced by ctrl_module_run().
ctrl_module_demo_y_d_gain
float ctrl_module_demo_y_d_gain = 0.05f
Definition at line 43 of file ctrl_module_innerloop_demo.c.
Referenced by ctrl_module_run().
ctrl_module_demo_y_ff_gain
float ctrl_module_demo_y_ff_gain = 0.4f
Definition at line 42 of file ctrl_module_innerloop_demo.c.
Referenced by ctrl_module_run().