Paparazzi UAS: sw/airborne/modules/ctrl/ctrl_effectiveness_scheduling.c File Reference
ctrl_effectiveness_scheduling.c File Reference
#include "modules/ctrl/ctrl_effectiveness_scheduling.h"
#include "firmwares/rotorcraft/stabilization/stabilization_indi.h"
#include "firmwares/rotorcraft/guidance/guidance_h.h"
#include "generated/airframe.h"
#include "state.h"
#include "modules/radio_control/radio_control.h"
Functions
void ctrl_eff_scheduling_init (void)
Initialises periodic loop;.
void ctrl_eff_scheduling_periodic (void)
Periodic function that interpolates between gain sets depending on the scheduling variable.
void ctrl_eff_scheduling_periodic_a (void)
void ctrl_eff_scheduling_periodic_b (void)
Variables
static float g1g2_forward [INDI_OUTPUTS][INDI_NUM_ACT]
static float g1g2_hover [INDI_OUTPUTS][INDI_NUM_ACT]
static float g2_both [INDI_NUM_ACT] = STABILIZATION_INDI_G2
Detailed Description
Module that interpolates gainsets in flight based on the transition percentage
Definition in file ctrl_effectiveness_scheduling.c.
Function Documentation
ctrl_eff_scheduling_init()
void ctrl_eff_scheduling_init (void)
Initialises periodic loop;.
Definition at line 52 of file ctrl_effectiveness_scheduling.c.
ctrl_eff_scheduling_periodic()
void ctrl_eff_scheduling_periodic (void)
Periodic function that interpolates between gain sets depending on the scheduling variable.
Definition at line 70 of file ctrl_effectiveness_scheduling.c.
ctrl_eff_scheduling_periodic_a()
void ctrl_eff_scheduling_periodic_a (void)
Definition at line 94 of file ctrl_effectiveness_scheduling.c.
References FLOAT_OF_BFP, g1g2, g1g2_forward, g1g2_hover, INT32_PERCENTAGE_FRAC, and transition_percentage.
Referenced by ctrl_eff_scheduling_periodic().
ctrl_eff_scheduling_periodic_b()
void ctrl_eff_scheduling_periodic_b (void)
Definition at line 108 of file ctrl_effectiveness_scheduling.c.
References actuator_state_filt_vect, Indi_gains::att, eulers_zxy, float_eulers_of_quat_zxy(), g1g2, g1g2_hover, indi_gains, FloatRates::q, stateGetAirspeed_f(), stateGetNedToBodyQuat_f(), and FloatEulers::theta.
Referenced by ctrl_eff_scheduling_periodic().
Variable Documentation
g1g2_forward
float g1g2_forward[INDI_OUTPUTS][INDI_NUM_ACT] static
Initial value:
= {FWD_G1_ROLL,
                                                  FWD_G1_PITCH, FWD_G1_YAW, FWD_G1_THRUST
                                                 }
Definition at line 41 of file ctrl_effectiveness_scheduling.c.
Referenced by ctrl_eff_scheduling_init(), and ctrl_eff_scheduling_periodic_a().
g1g2_hover
float g1g2_hover[INDI_OUTPUTS][INDI_NUM_ACT] static
Initial value:
= {STABILIZATION_INDI_G1_ROLL,
                                                STABILIZATION_INDI_G1_PITCH, STABILIZATION_INDI_G1_YAW, STABILIZATION_INDI_G1_THRUST
                                               }
Definition at line 45 of file ctrl_effectiveness_scheduling.c.
Referenced by ctrl_eff_scheduling_init(), ctrl_eff_scheduling_periodic_a(), and ctrl_eff_scheduling_periodic_b().
g2_both
float g2_both[INDI_NUM_ACT] = STABILIZATION_INDI_G2 static
Definition at line 49 of file ctrl_effectiveness_scheduling.c.
Referenced by ctrl_eff_scheduling_init().