Paparazzi UAS: sw/airborne/modules/computer_vision/cv_opencvdemo.c File Reference
cv_opencvdemo.c File Reference
#include "modules/computer_vision/cv.h"
#include "modules/computer_vision/cv_opencvdemo.h"
#include "modules/computer_vision/opencv_example.h"
Macros
#define OPENCVDEMO_FPS 0
Default FPS (zero means run at camera fps)
Functions
struct image_t * opencv_func (struct image_t *img, uint8_t camera_id)
void opencvdemo_init (void)
Detailed Description
Author
C. De Wagter A simple module showing what you can do with opencv on the bebop.
Definition in file cv_opencvdemo.c.
Macro Definition Documentation
OPENCVDEMO_FPS
#define OPENCVDEMO_FPS 0
Default FPS (zero means run at camera fps)
Definition at line 31 of file cv_opencvdemo.c.
Function Documentation
opencv_func()
struct image_t * opencv_func (struct image_t * img, uint8_t camera_id)
Definition at line 37 of file cv_opencvdemo.c.
References image_t::buf, image_t::h, IMAGE_YUV422, opencv_example(), image_t::type, and image_t::w.
Referenced by opencvdemo_init().
opencvdemo_init()
void opencvdemo_init (void)
Definition at line 50 of file cv_opencvdemo.c.
References cv_add_to_device(), opencv_func(), and OPENCVDEMO_FPS.