Paparazzi UAS: sw/airborne/modules/computer_vision/cv_georeference.h File Reference
cv_georeference.h File Reference
#include "std.h"
#include <stdint.h>
Data Structures
struct camera_frame_t
Functions
void georeference_init (void)
void georeference_run (void)
void georeference_project (struct camera_frame_t *tar, int wp)
void georeference_filter (bool kalman, int wp, int length)
Variables
int32_t focus_length
Detailed Description
Author
C. De Wagter Geo-reference computer vision detections
Definition in file cv_georeference.h.
Data Structure Documentation
camera_frame_t
struct camera_frame_t
Definition at line 37 of file cv_georeference.h.
Data Fields
int32_t f Camera Focal length in [px].
int32_t h Frame height [px].
int32_t px Target pixel coordinate (left = 0)
int32_t py Target pixel coordinate (top = 0)
int32_t w Frame width [px].
Function Documentation
georeference_filter()
void georeference_filter (bool kalman, int wp, int length)
Definition at line 119 of file cv_georeference.c.
References DefaultChannel, DefaultDevice, georeference_t::filter, geo, h(), georeference_filter_t::P, georeference_filter_t::v, VECT3_ADD, VECT3_COPY, VECT3_SDIV, VECT3_SMUL, VECT3_SUB, waypoint_set_xy_i(), Int32Vect3::x, georeference_filter_t::x, georeference_t::x_t, and Int32Vect3::y.
Referenced by cv_blob_locator_event(), and georeference_run().
georeference_init()
void georeference_init (void)
Definition at line 180 of file cv_georeference.c.
References georeference_t::filter, focus_length, geo, INT32_VECT3_ZERO, georeference_filter_t::P, georeference_t::target_i, georeference_t::target_l, georeference_filter_t::v, VECT3_ASSIGN, georeference_filter_t::x, and georeference_t::x_t.
Referenced by cv_blob_locator_init(), cv_blob_locator_start(), start_vision(), start_vision_land(), and stop_vision().
georeference_project()
void georeference_project (struct camera_frame_t * tar, int wp)
Definition at line 53 of file cv_georeference.c.
References DefaultChannel, DefaultDevice, camera_frame_t::f, geo, camera_frame_t::h, h(), INT32_MAT33_ZERO, int32_rmat_transp_vmult(), INT32_TRIG_FRAC, INT32_VECT3_LSHIFT, MAT33_ELMT, camera_frame_t::px, camera_frame_t::py, stateGetNedToBodyRMat_i(), stateGetPositionNed_i(), georeference_t::target_i, georeference_t::target_l, VECT3_ASSIGN, camera_frame_t::w, waypoint_set_alt_i(), waypoint_set_xy_i(), NedCoor_i::x, Int32Vect3::x, georeference_t::x_t, NedCoor_i::y, Int32Vect3::y, NedCoor_i::z, and Int32Vect3::z.
Referenced by cv_blob_locator_event(), and georeference_run().
georeference_run()
void georeference_run (void)
Definition at line 155 of file cv_georeference.c.
References FALSE, focus_length, georeference_filter(), georeference_project(), and target.
Variable Documentation
focus_length
int32_t focus_length
Definition at line 153 of file cv_georeference.c.
Referenced by georeference_init(), and georeference_run().