Paparazzi UAS: sw/airborne/modules/digital_cam/dc_ctrl_parrot_mykonos.c File Reference
dc_ctrl_parrot_mykonos.c File Reference
#include "modules/digital_cam/dc_ctrl_parrot_mykonos.h"
#include "generated/modules.h"
#include "generated/airframe.h"
#include "mcu_periph/sys_time.h"
#include "modules/digital_cam/dc.h"
Macros
#define DC_CTRL_PARROT_MYKONOS_RECORD_DELAY 0.05
NOTES: For now only the front cam is used, feel free to extend.
#define DC_CTRL_PARROT_MYKONOS_LOG_DELAY 50
delay in milli-seconds before logging after a shot in ms
#define DC_CTRL_PARROT_MYKONOS_TIMER_OF_DELAY(_delay) ((uint32_t)(_delay * DC_CTRL_PARROT_MYKONOS_PERIODIC_FREQ))
Get timer from delay based on periodic freq from modules.h.
#define DC_CTRL_PARROT_MYKONOS_AUTOSHOOT_DELAY 5.0
autoshoot timer delay based on periodic freq from modules.h
#define DC_CTRL_PARROT_MYKONOS_AUTOSHOOT_TIMER_OF_DELAY(_delay) ((uint32_t)(_delay * DC_CTRL_PARROT_MYKONOS_AUTOSHOOT_FREQ))
Functions
void dc_ctrl_parrot_mykonos_init (void)
void dc_ctrl_parrot_mykonos_periodic (void)
void dc_ctrl_parrot_mykonos_command (enum dc_ctrl_parrot_mykonos_status cmd)
void dc_ctrl_parrot_mykonos_autoshoot (void)
void dc_ctrl_parrot_mykonos_autoshoot_start (void)
Variables
struct Dc_Ctrl_Parrot_Mykonos dc_ctrl_parrot_mykonos
Send report.
Macro Definition Documentation
DC_CTRL_PARROT_MYKONOS_AUTOSHOOT_DELAY
#define DC_CTRL_PARROT_MYKONOS_AUTOSHOOT_DELAY 5.0
autoshoot timer delay based on periodic freq from modules.h
Definition at line 47 of file dc_ctrl_parrot_mykonos.c.
DC_CTRL_PARROT_MYKONOS_AUTOSHOOT_TIMER_OF_DELAY
#define DC_CTRL_PARROT_MYKONOS_AUTOSHOOT_TIMER_OF_DELAY (_delay) ((uint32_t)(_delay * DC_CTRL_PARROT_MYKONOS_AUTOSHOOT_FREQ))
Definition at line 49 of file dc_ctrl_parrot_mykonos.c.
DC_CTRL_PARROT_MYKONOS_LOG_DELAY
#define DC_CTRL_PARROT_MYKONOS_LOG_DELAY 50
delay in milli-seconds before logging after a shot in ms
Definition at line 40 of file dc_ctrl_parrot_mykonos.c.
DC_CTRL_PARROT_MYKONOS_RECORD_DELAY
#define DC_CTRL_PARROT_MYKONOS_RECORD_DELAY 0.05
NOTES: For now only the front cam is used, feel free to extend.
Reason is that bottom_cam is normally in use for mapping or Optic flow and the like. See: https://github.com/Parrot-Developers/disco-opensource/ Time in seconds to start/stop recording or take a picture
Definition at line 37 of file dc_ctrl_parrot_mykonos.c.
DC_CTRL_PARROT_MYKONOS_TIMER_OF_DELAY
#define DC_CTRL_PARROT_MYKONOS_TIMER_OF_DELAY (_delay) ((uint32_t)(_delay * DC_CTRL_PARROT_MYKONOS_PERIODIC_FREQ))
Get timer from delay based on periodic freq from modules.h.
Definition at line 43 of file dc_ctrl_parrot_mykonos.c.
Function Documentation
dc_ctrl_parrot_mykonos_autoshoot()
void dc_ctrl_parrot_mykonos_autoshoot (void)
Definition at line 283 of file dc_ctrl_parrot_mykonos.c.
References Dc_Ctrl_Parrot_Mykonos::autoshoot, dc_ctrl_parrot_mykonos, DC_CTRL_PARROT_MYKONOS_AUTOSHOOT_DELAY, DC_CTRL_PARROT_MYKONOS_AUTOSHOOT_START, DC_CTRL_PARROT_MYKONOS_AUTOSHOOT_TIMER_OF_DELAY, dc_ctrl_parrot_mykonos_command(), DC_CTRL_PARROT_MYKONOS_SHOOT, Dc_Ctrl_Parrot_Mykonos::last_shot_pos, stateGetPositionEnu_f(), Dc_Ctrl_Parrot_Mykonos::status, VECT2_NORM2, FloatVect2::x, EnuCoor_f::x, FloatVect2::y, and EnuCoor_f::y.
dc_ctrl_parrot_mykonos_autoshoot_start()
void dc_ctrl_parrot_mykonos_autoshoot_start (void)
Definition at line 309 of file dc_ctrl_parrot_mykonos.c.
References Dc_Ctrl_Parrot_Mykonos::autoshoot, dc_ctrl_parrot_mykonos, DC_CTRL_PARROT_MYKONOS_AUTOSHOOT_START, and Dc_Ctrl_Parrot_Mykonos::status.
dc_ctrl_parrot_mykonos_command()
void dc_ctrl_parrot_mykonos_command (enum dc_ctrl_parrot_mykonos_status cmd)
Definition at line 209 of file dc_ctrl_parrot_mykonos.c.
References dc_ctrl_parrot_mykonos, DC_CTRL_PARROT_MYKONOS_AUTOSHOOT_START, DC_CTRL_PARROT_MYKONOS_AUTOSHOOT_STOP, DC_CTRL_PARROT_MYKONOS_LOG_DELAY, DC_CTRL_PARROT_MYKONOS_RECORD_DELAY, DC_CTRL_PARROT_MYKONOS_RECORD_START, DC_CTRL_PARROT_MYKONOS_RECORD_STOP, DC_CTRL_PARROT_MYKONOS_SHOOT, DC_CTRL_PARROT_MYKONOS_STREAM_START, DC_CTRL_PARROT_MYKONOS_STREAM_STOP, DC_CTRL_PARROT_MYKONOS_TIMER_OF_DELAY, get_sys_time_msec(), Dc_Ctrl_Parrot_Mykonos::last_shot_pos, Dc_Ctrl_Parrot_Mykonos::log_delay, stateGetPositionEnu_f(), Dc_Ctrl_Parrot_Mykonos::status, and Dc_Ctrl_Parrot_Mykonos::timer.
Referenced by dc_ctrl_parrot_mykonos_autoshoot(), dc_ctrl_parrot_mykonos_init(), and dc_ctrl_parrot_mykonos_periodic().
dc_ctrl_parrot_mykonos_init()
void dc_ctrl_parrot_mykonos_init (void)
Definition at line 117 of file dc_ctrl_parrot_mykonos.c.
References Dc_Ctrl_Parrot_Mykonos::autoshoot, dc_ctrl_parrot_mykonos, dc_ctrl_parrot_mykonos_command(), DC_CTRL_PARROT_MYKONOS_NONE, DC_CTRL_PARROT_MYKONOS_STREAM_START, dc_init(), Dc_Ctrl_Parrot_Mykonos::log_delay, Dc_Ctrl_Parrot_Mykonos::photo_nr, Dc_Ctrl_Parrot_Mykonos::status, and Dc_Ctrl_Parrot_Mykonos::timer.
dc_ctrl_parrot_mykonos_periodic()
void dc_ctrl_parrot_mykonos_periodic (void)
Definition at line 151 of file dc_ctrl_parrot_mykonos.c.
References dc_ctrl_parrot_mykonos, dc_ctrl_parrot_mykonos_command(), DC_CTRL_PARROT_MYKONOS_SHOOT, dc_periodic(), get_sys_time_msec(), Dc_Ctrl_Parrot_Mykonos::log_delay, Dc_Ctrl_Parrot_Mykonos::photo_nr, and Dc_Ctrl_Parrot_Mykonos::timer.
Variable Documentation
dc_ctrl_parrot_mykonos
struct Dc_Ctrl_Parrot_Mykonos dc_ctrl_parrot_mykonos
Send report.
Definition at line 115 of file dc_ctrl_parrot_mykonos.c.
Referenced by dc_ctrl_parrot_mykonos_autoshoot(), dc_ctrl_parrot_mykonos_autoshoot_start(), dc_ctrl_parrot_mykonos_command(), dc_ctrl_parrot_mykonos_init(), and dc_ctrl_parrot_mykonos_periodic().