Paparazzi UAS: sw/airborne/arch/chibios/modules/actuators/esc_dshot.c File Reference
esc_dshot.c File Reference
DSHOT driver based on ChibiOS.
#include "modules/actuators/esc_dshot.h"
#include <stdnoreturn.h>
#include <math.h>
#include <string.h>
Macros
#define DSHOT_SPEED 300
Base freq of DSHOT signal (in kHz) Possible values are: 150, 300, 600.
#define DSHOT_TELEMETRY_BAUD 115200
Baudrate of the serial link used for telemetry data Can depend on the ESC, but only 115k have been used so far.
#define DSHOT_TELEMETRY_TIMEOUT_MS 3
Telemetry timeout in ms.
#define PWM_FREQ (STM32_SYSCLK/2000)
the timer will beat @84Mhz on STM32F4 // TODO check on F7
#define TICKS_PER_PERIOD 1000
Ticks per period that let use any timer: does not care if linked to PCLK1 or PCLK2 tick_per_period will be dynamically calculated after pwm init.
#define DSHOT_FREQ (DSHOT_SPEED*1000)
#define TICK_FREQ (PWM_FREQ * TICKS_PER_PERIOD)
#define DSHOT_PWM_PERIOD (TICK_FREQ/DSHOT_FREQ)
#define DSHOT_BIT0_DUTY (DSHOT_PWM_PERIOD * 373 / 1000)
#define DSHOT_BIT1_DUTY (DSHOT_BIT0_DUTY*2)
#define DCR_DBL ((DSHOT_CHANNELS-1) << 8)
#define DCR_DBA(pwmd) (((uint32_t *) (&pwmd->tim->CCR) - ((uint32_t *) pwmd->tim)))
#define ARRAY_LEN(a) (sizeof(a)/sizeof(a[0]))
#define Min(x, y) (x < y ? x : y)
#define DSHOT_MAX_VALUE ((1<<11)-1)
Functions
static DshotPacket makeDshotPacket (const uint16_t throttle, const bool tlmRequest)
static void setDshotPacketThrottle (DshotPacket *const dp, const uint16_t throttle)
static void setDshotPacketTlm (DshotPacket *const dp, const bool tlmRequest)
static void buildDshotDmaBuffer (DshotPackets *const dsp, DshotDmaBuffer *const dma, const size_t timerWidth)
static uint8_t updateCrc8 (uint8_t crc, uint8_t crc_seed)
static uint8_t calculateCrc8 (const uint8_t *Buf, const uint8_t BufLen)
static noreturn void dshotTlmRec (void *arg)
static size_t getTimerWidth (const PWMDriver *pwmp)
void dshotStart (DSHOTDriver *driver, const DSHOTConfig *config)
Configures and activates the DSHOT peripheral.
void dshotSetThrottle (DSHOTDriver *driver, const uint8_t index, const uint16_t throttle)
prepare throttle order for specified ESC
void dshotSendSpecialCommand (DSHOTDriver *driver, const uint8_t index, const dshot_special_commands_t specmd)
send special order to one of the ESC (BHELIX, KISS, ...)
void dshotSendThrottles (DSHOTDriver *driver, const uint16_t throttles[DSHOT_CHANNELS])
send throttle packed order to all of the ESCs
void dshotSendFrame (DSHOTDriver *driver)
send throttle order
uint32_t dshotGetCrcErrorsCount (DSHOTDriver *driver)
return number of telemetry crc error since dshotStart
const DshotTelemetry * dshotGetTelemetry (const DSHOTDriver *driver, const uint32_t index)
return last received telemetry data
Detailed Description
DSHOT driver based on ChibiOS.
Author
Alexandre Bustico @maintainer Gautier Hattenberger gauti.nosp@m.er.h.nosp@m.atten.nosp@m.berg.nosp@m.er@en.nosp@m.ac.f.nosp@m.r
Definition in file esc_dshot.c.
Macro Definition Documentation
ARRAY_LEN
#define ARRAY_LEN (a) (sizeof(a)/sizeof(a[0]))
Definition at line 84 of file esc_dshot.c.
DCR_DBA
#define DCR_DBA (pwmd) (((uint32_t *) (&pwmd->tim->CCR) - ((uint32_t *) pwmd->tim)))
Definition at line 82 of file esc_dshot.c.
DCR_DBL
#define DCR_DBL ((DSHOT_CHANNELS-1) << 8)
Definition at line 81 of file esc_dshot.c.
DSHOT_BIT0_DUTY
#define DSHOT_BIT0_DUTY (DSHOT_PWM_PERIOD * 373 / 1000)
Definition at line 79 of file esc_dshot.c.
DSHOT_BIT1_DUTY
#define DSHOT_BIT1_DUTY (DSHOT_BIT0_DUTY*2)
Definition at line 80 of file esc_dshot.c.
DSHOT_FREQ
#define DSHOT_FREQ (DSHOT_SPEED*1000)
Definition at line 76 of file esc_dshot.c.
DSHOT_MAX_VALUE
#define DSHOT_MAX_VALUE ((1<<11)-1)
Definition at line 87 of file esc_dshot.c.
DSHOT_PWM_PERIOD
#define DSHOT_PWM_PERIOD (TICK_FREQ/DSHOT_FREQ)
Definition at line 78 of file esc_dshot.c.
DSHOT_SPEED
#define DSHOT_SPEED 300
Base freq of DSHOT signal (in kHz) Possible values are: 150, 300, 600.
Definition at line 48 of file esc_dshot.c.
DSHOT_TELEMETRY_BAUD
#define DSHOT_TELEMETRY_BAUD 115200
Baudrate of the serial link used for telemetry data Can depend on the ESC, but only 115k have been used so far.
Definition at line 55 of file esc_dshot.c.
DSHOT_TELEMETRY_TIMEOUT_MS
#define DSHOT_TELEMETRY_TIMEOUT_MS 3
Telemetry timeout in ms.
Definition at line 61 of file esc_dshot.c.
Min
#define Min (x, y) (x < y ? x : y)
Definition at line 85 of file esc_dshot.c.
PWM_FREQ
#define PWM_FREQ (STM32_SYSCLK/2000)
the timer will beat @84Mhz on STM32F4 // TODO check on F7
Definition at line 65 of file esc_dshot.c.
TICK_FREQ
#define TICK_FREQ (PWM_FREQ * TICKS_PER_PERIOD)
Definition at line 77 of file esc_dshot.c.
TICKS_PER_PERIOD
#define TICKS_PER_PERIOD 1000
Ticks per period that let use any timer: does not care if linked to PCLK1 or PCLK2 tick_per_period will be dynamically calculated after pwm init.
Definition at line 73 of file esc_dshot.c.
Function Documentation
buildDshotDmaBuffer()
static void buildDshotDmaBuffer (DshotPackets *const dsp, DshotDmaBuffer *const dma, const size_t timerWidth) static
Definition at line 385 of file esc_dshot.c.
References DshotPackets::dp, DSHOT_BIT0_DUTY, DSHOT_BIT1_DUTY, DSHOT_BIT_WIDTHS, DSHOT_CHANNELS, DSHOT_PRE_FRAME_SILENT_SYNC_BITS, DshotPacket::rawFrame, and DshotDmaBuffer::widths16.
Referenced by dshotSendFrame().
calculateCrc8()
static uint8_t calculateCrc8 (const uint8_t * Buf, const uint8_t BufLen) static
Definition at line 427 of file esc_dshot.c.
References crc, and updateCrc8().
Referenced by dshotTlmRec().
dshotGetCrcErrorsCount()
uint32_t dshotGetCrcErrorsCount (DSHOTDriver * driver)
return number of telemetry crc error since dshotStart
Parameters
[in] driver pointer to the DSHOTDriver object
Returns
number of CRC errors @api
Definition at line 329 of file esc_dshot.c.
References DSHOTDriver::crc_errors.
dshotGetTelemetry()
const DshotTelemetry* dshotGetTelemetry (const DSHOTDriver * driver, const uint32_t index)
return last received telemetry data
Parameters
[in] driver pointer to the DSHOTDriver object
[in] index channel : [0..3] or [0..1] depending on driver used
Returns
pointer on a telemetry structure @api
Definition at line 342 of file esc_dshot.c.
References DSHOTDriver::dshotMotors, and DshotPackets::dt.
dshotSendFrame()
void dshotSendFrame (DSHOTDriver * driver)
send throttle order
Parameters
[in] driver pointer to the DSHOTDriver object
Note
dshotSetXXX api should be called prior to this function @api
Definition at line 302 of file esc_dshot.c.
References buildDshotDmaBuffer(), DSHOTDriver::config, DshotPackets::currentTlmQry, DSHOTConfig::dma_buf, DMA_READY, DSHOTDriver::dmap, dmaStartTransfert(), DshotPackets::dp, DSHOT_CHANNELS, DSHOT_DMA_BUFFER_SIZE, DSHOTDriver::dshotMotors, getTimerWidth(), DSHOTDriver::mb, DshotPackets::onGoingQry, DSHOTConfig::pwmp, setDshotPacketTlm(), DMADriver::state, and DSHOTConfig::tlm_sd.
Referenced by actuators_dshot_arch_commit(), dshotSendSpecialCommand(), and dshotSendThrottles().
dshotSendSpecialCommand()
void dshotSendSpecialCommand (DSHOTDriver * driver, const uint8_t index, const dshot_special_commands_t specmd)
send special order to one of the ESC (BHELIX, KISS, ...)
Parameters
[in] driver pointer to the DSHOTDriver object
[in] index channel : [0..3] or [0..1] depending on driver used
[in] specmd special commands, see enum @api
Definition at line 239 of file esc_dshot.c.
References DSHOTDriver::config, DshotPackets::dp, DSHOT_ALL_MOTORS, DSHOT_CHANNELS, DSHOT_CMD_3D_MODE_OFF, DSHOT_CMD_3D_MODE_ON, DSHOT_CMD_AUDIO_STREAM_MODE_ON_OFF, DSHOT_CMD_MAX, DSHOT_CMD_SAVE_SETTINGS, DSHOT_CMD_SETTINGS_REQUEST, DSHOT_CMD_SILENT_MODE_ON_OFF, DSHOT_CMD_SPIN_DIRECTION_1, DSHOT_CMD_SPIN_DIRECTION_2, DSHOTDriver::dshotMotors, dshotSendFrame(), setDshotPacketThrottle(), setDshotPacketTlm(), and DSHOTConfig::tlm_sd.
dshotSendThrottles()
void dshotSendThrottles (DSHOTDriver * driver, const uint16_t throttles[DSHOT_CHANNELS])
send throttle packed order to all of the ESCs
Parameters
[in] driver pointer to the DSHOTDriver object
[in] throttle[DSHOT_CHANNELS] [48 .. 2047]
Note
dshotSendFrame is called by this function
telemetry bit is set in turn for each ESC of the ESCs @api
Definition at line 286 of file esc_dshot.c.
References DshotPackets::dp, DSHOT_CHANNELS, DSHOTDriver::dshotMotors, dshotSendFrame(), and setDshotPacketThrottle().
dshotSetThrottle()
void dshotSetThrottle (DSHOTDriver * driver, const uint8_t index, const uint16_t throttle)
prepare throttle order for specified ESC
Parameters
[in] driver pointer to the DSHOTDriver object
[in] index channel : [0..3] or [0..1] depending on driver used
[in] throttle [48 .. 2047]
Note
dshotSendFrame has to be called after using this function
see also dshotSendThrottles @api
Definition at line 210 of file esc_dshot.c.
References DshotPackets::dp, DSHOT_ALL_MOTORS, DSHOT_CHANNEL_FIRST_INDEX, DSHOT_CHANNELS, DSHOT_CMD_MAX, DSHOT_MAX_VALUE, DSHOTDriver::dshotMotors, Min, and setDshotPacketThrottle().
Referenced by actuators_dshot_arch_commit().
dshotStart()
void dshotStart (DSHOTDriver * driver, const DSHOTConfig * config)
Configures and activates the DSHOT peripheral.
Parameters
[in] driver pointer to the DSHOTDriver object
[in] config pointer to the DSHOTConfig object. @api
Definition at line 122 of file esc_dshot.c.
References DSHOTDriver::_mbBuf, ARRAY_LEN, config, DSHOTDriver::config, DSHOTDriver::crc_errors, DshotPackets::currentTlmQry, DCR_DBA, DCR_DBL, DSHOTDriver::dma_conf, DMA_DIR_M2P, dmaObjectInit(), DSHOTDriver::dmap, dmaStart(), DshotPackets::dp, DSHOT_CHANNELS, DSHOT_PWM_PERIOD, DSHOT_TELEMETRY_BAUD, DSHOTDriver::dshotMotors, dshotTlmRec(), getTimerWidth(), makeDshotPacket(), DSHOTDriver::mb, DshotPackets::onGoingQry, DSHOTDriver::pwm_conf, DSHOTConfig::pwmp, DMAConfig::stream, TICK_FREQ, TICKS_PER_PERIOD, and DSHOTConfig::tlm_sd.
Referenced by actuators_dshot_arch_init().
dshotTlmRec()
static noreturn void dshotTlmRec (void * arg) static
Definition at line 462 of file esc_dshot.c.
References calculateCrc8(), DSHOTDriver::config, DshotTelemetry::crc8, DSHOTDriver::crc_errors, DSHOT_TELEMETRY_TIMEOUT_MS, DSHOTDriver::dshotMotors, DshotPackets::dt, idx, DSHOTDriver::mb, DshotPackets::onGoingQry, and DSHOTConfig::tlm_sd.
Referenced by dshotStart().
getTimerWidth()
static size_t getTimerWidth (const PWMDriver * pwmp) static
Definition at line 438 of file esc_dshot.c.
References STM32_PWM_USE_TIM2.
Referenced by dshotSendFrame(), and dshotStart().
makeDshotPacket()
static DshotPacket makeDshotPacket (const uint16_t throttle, const bool tlmRequest) static
Definition at line 357 of file esc_dshot.c.
References crc.
Referenced by dshotStart().
setDshotPacketThrottle()
static void setDshotPacketThrottle (DshotPacket *const dp, const uint16_t throttle) inline static
Definition at line 374 of file esc_dshot.c.
Referenced by dshotSendSpecialCommand(), dshotSendThrottles(), and dshotSetThrottle().
setDshotPacketTlm()
static void setDshotPacketTlm (DshotPacket *const dp, const bool tlmRequest) inline static
Definition at line 380 of file esc_dshot.c.
Referenced by dshotSendFrame(), and dshotSendSpecialCommand().
updateCrc8()
static uint8_t updateCrc8 (uint8_t crc, uint8_t crc_seed) inline static
Definition at line 415 of file esc_dshot.c.
References crc.
Referenced by calculateCrc8().