Paparazzi UAS: sw/airborne/firmwares/fixedwing/main_fbw.c File Reference
main_fbw.c File Reference
#include "firmwares/fixedwing/main_fbw.h"
#include "generated/airframe.h"
#include "mcu.h"
#include "mcu_periph/sys_time.h"
#include "modules/core/commands.h"
#include "modules/actuators/actuators.h"
#include "modules/energy/electrical.h"
#include "modules/radio_control/radio_control.h"
#include "autopilot.h"
#include "paparazzi.h"
#include "mcu_periph/i2c.h"
#include "mcu_periph/uart.h"
#include "modules/datalink/telemetry.h"
#include "modules/intermcu/inter_mcu.h"
#include "modules/intermcu/link_mcu.h"
Functions
void radio_lost_mode (void)
Defines behavior when the RC is lost, default goes to AUTO.
static void handle_rc_frame (void)
void radio_control_event (void)
void radio_control_periodic_handle (void)
void fbw_datalink_periodic_handle (void)
void fbw_datalink_event_handle (void)
void update_actuators (void)
void inter_mcu_periodic_handle (void)
void inter_mcu_event_handle (void)
static void send_commands (struct transport_tx *trans, struct link_device *dev)
static void send_fbw_status (struct transport_tx *trans, struct link_device *dev)
static void send_rc (struct transport_tx *trans, struct link_device *dev)
void periodic_telemetry_handle (void)
void init_fbw (void)
void event_task_fbw (void)
void periodic_task_fbw (void)
void handle_periodic_tasks_fbw (void)
Variables
uint8_t fbw_mode
pprz_t command_roll_trim
Trim commands for roll, pitch and yaw.
pprz_t command_pitch_trim
pprz_t command_yaw_trim
volatile uint8_t fbw_new_actuators = 0
uint8_t ap_has_been_ok = false
tid_t fbw_periodic_tid
id for periodic_task_fbw() timer
tid_t electrical_tid
id for electrical_periodic() timer
Detailed Description
FBW (FlyByWire) process
This process is responsible for decoding radio control, generating actuators signals either from the radio control or from the commands provided by the AP (autopilot) process. It also performs a telemetry task and a low level monitoring (for parameters like the supply)
Definition in file main_fbw.c.
Function Documentation
event_task_fbw()
void event_task_fbw (void)
Definition at line 417 of file main_fbw.c.
References fbw_datalink_event_handle(), inter_mcu_event_handle(), mcu_event(), and radio_control_event().
Referenced by sim_periodic_task().
fbw_datalink_event_handle()
void fbw_datalink_event_handle (void)
Definition at line 150 of file main_fbw.c.
Referenced by event_task_fbw().
fbw_datalink_periodic_handle()
void fbw_datalink_periodic_handle (void)
Definition at line 149 of file main_fbw.c.
Referenced by periodic_task_fbw().
handle_periodic_tasks_fbw()
void handle_periodic_tasks_fbw (void)
Definition at line 441 of file main_fbw.c.
References electrical_periodic(), electrical_tid, fbw_periodic_tid, periodic_task_fbw(), and sys_time_check_and_ack_timer().
handle_rc_frame()
static void handle_rc_frame (void) inline static
Definition at line 112 of file main_fbw.c.
References commands, fbw_mode, FBW_MODE_MANUAL, FBW_MODE_OF_PPRZ, fbw_new_actuators, radio_control, RADIO_MODE, and RadioControl::values.
Referenced by radio_control_event().
init_fbw()
void init_fbw (void)
Definition at line 362 of file main_fbw.c.
References commands_failsafe, DefaultPeriodic, electrical_init(), electrical_tid, fbw_mode, FBW_MODE_FAILSAFE, fbw_new_actuators, fbw_periodic_tid, link_mcu_init(), mcu_init(), radio_control_init(), register_periodic_telemetry(), send_actuators(), send_commands(), send_fbw_status(), send_rc(), SetCommands, and sys_time_register_timer().
Referenced by sim_init().
inter_mcu_event_handle()
void inter_mcu_event_handle (void)
Definition at line 314 of file main_fbw.c.
Referenced by event_task_fbw().
inter_mcu_periodic_handle()
void inter_mcu_periodic_handle (void)
Definition at line 313 of file main_fbw.c.
Referenced by periodic_task_fbw().
periodic_task_fbw()
void periodic_task_fbw (void)
Definition at line 430 of file main_fbw.c.
References fbw_datalink_periodic_handle(), inter_mcu_periodic_handle(), periodic_telemetry_handle(), and radio_control_periodic_handle().
Referenced by handle_periodic_tasks_fbw().
periodic_telemetry_handle()
void periodic_telemetry_handle (void)
Definition at line 352 of file main_fbw.c.
References DefaultChannel, DefaultDevice, and DefaultPeriodic.
Referenced by periodic_task_fbw().
radio_control_event()
void radio_control_event (void)
Definition at line 121 of file main_fbw.c.
References handle_rc_frame(), and RadioControlEvent.
Referenced by event_task_fbw().
radio_control_periodic_handle()
void radio_control_periodic_handle (void)
Definition at line 126 of file main_fbw.c.
References fbw_mode, FBW_MODE_MANUAL, radio_control, radio_control_periodic_task(), radio_lost_mode(), RC_REALLY_LOST, and RadioControl::status.
Referenced by periodic_task_fbw().
radio_lost_mode()
void radio_lost_mode (void)
Defines behavior when the RC is lost, default goes to AUTO.
Definition at line 88 of file main_fbw.c.
References fbw_mode, and FBW_MODE_AUTO.
Referenced by radio_control_periodic_handle().
send_commands()
static void send_commands (struct transport_tx * trans, struct link_device * dev) static
Definition at line 319 of file main_fbw.c.
References commands, and dev.
Referenced by init_fbw().
send_fbw_status()
static void send_fbw_status (struct transport_tx * trans, struct link_device * dev) static
Definition at line 325 of file main_fbw.c.
References Electrical::current, dev, electrical, fbw_mode, RadioControl::frame_rate, radio_control, RadioControl::status, and Electrical::vsupply.
Referenced by init_fbw(), and link_mcu_init().
send_rc()
static void send_rc (struct transport_tx * trans, struct link_device * dev) static
Definition at line 331 of file main_fbw.c.
References dev, radio_control, RADIO_CONTROL_NB_CHANNEL, and RadioControl::values.
Referenced by init_fbw().
update_actuators()
void update_actuators (void)
Definition at line 180 of file main_fbw.c.
Variable Documentation
ap_has_been_ok
uint8_t ap_has_been_ok = false
Definition at line 74 of file main_fbw.c.
command_pitch_trim
pprz_t command_pitch_trim
Definition at line 69 of file main_fbw.c.
command_roll_trim
pprz_t command_roll_trim
Trim commands for roll, pitch and yaw.
These are updated from the trim commands in ap_state via inter_mcu
Definition at line 68 of file main_fbw.c.
command_yaw_trim
pprz_t command_yaw_trim
Definition at line 70 of file main_fbw.c.
electrical_tid
tid_t electrical_tid
id for electrical_periodic() timer
Definition at line 77 of file main_fbw.c.
Referenced by handle_periodic_tasks(), handle_periodic_tasks_fbw(), init_fbw(), and main_init().
fbw_mode
uint8_t fbw_mode
Definition at line 63 of file main_fbw.c.
Referenced by fbw_on_ap_command(), fbw_on_rc_frame(), fbw_safety_check(), handle_rc_frame(), init_fbw(), intermcu_on_rc_frame(), main_init(), main_periodic(), radio_control_periodic_handle(), radio_lost_mode(), send_fbw_status(), and telemetry_periodic().
fbw_new_actuators
volatile uint8_t fbw_new_actuators = 0
Definition at line 72 of file main_fbw.c.
Referenced by handle_rc_frame(), and init_fbw().
fbw_periodic_tid
tid_t fbw_periodic_tid
id for periodic_task_fbw() timer
Definition at line 76 of file main_fbw.c.
Referenced by handle_periodic_tasks_fbw(), and init_fbw().