Paparazzi UAS: sw/airborne/modules/gps/gps_ubx.h File Reference
gps_ubx.h File Reference
UBX protocol specific code.
#include "modules/gps/gps.h"
#include "mcu_periph/uart.h"
#include "pprzlink/pprzlink_device.h"
Data Structures
struct GpsUbx
Macros
#define PRIMARY_GPS GPS_UBX
#define gps_ubx_periodic_check() gps_periodic_check(&gps_ubx.state)
#define GPS_UBX_NB_CHANNELS 40
#define GPS_UBX_MAX_PAYLOAD 512
#define CFG_RST_Reset_Hardware 0x00
#define CFG_RST_Reset_Controlled 0x01
#define CFG_RST_Reset_Controlled_GPS_only 0x02
#define CFG_RST_Reset_Controlled_GPS_stop 0x08
#define CFG_RST_Reset_Controlled_GPS_start 0x09
#define CFG_RST_BBR_Hotstart 0x0000
#define CFG_RST_BBR_Warmstart 0x0001
#define CFG_RST_BBR_Coldstart 0xffff
#define gps_ubx_Reset(_val)
Functions
void gps_ubx_init (void)
void gps_ubx_event (void)
void ubx_header (struct link_device *dev, uint8_t nav_id, uint8_t msg_id, uint16_t len)
void ubx_trailer (struct link_device *dev)
void ubx_send_bytes (struct link_device *dev, uint8_t len, uint8_t *bytes)
void ubx_send_cfg_rst (struct link_device *dev, uint16_t bbr, uint8_t reset_mode)
void gps_ubx_read_message (void)
void gps_ubx_parse (uint8_t c)
void gps_ubx_msg (void)
Variables
struct GpsUbx gps_ubx
Detailed Description
UBX protocol specific code.
Definition in file gps_ubx.h.
Data Structure Documentation
GpsUbx
struct GpsUbx
Definition at line 54 of file gps_ubx.h.
Data Fields
uint8_t ck_a
uint8_t ck_b
uint8_t error_cnt
uint8_t error_last
uint16_t len
bool msg_available
uint8_t msg_buf[GPS_UBX_MAX_PAYLOAD]
uint8_t msg_class
uint8_t msg_id
uint16_t msg_idx
uint8_t send_ck_a
uint8_t send_ck_b
uint8_t sol_flags
struct GpsState state
uint8_t status
uint8_t status_flags
Macro Definition Documentation
CFG_RST_BBR_Coldstart
#define CFG_RST_BBR_Coldstart 0xffff
Definition at line 123 of file gps_ubx.h.
CFG_RST_BBR_Hotstart
#define CFG_RST_BBR_Hotstart 0x0000
Definition at line 121 of file gps_ubx.h.
CFG_RST_BBR_Warmstart
#define CFG_RST_BBR_Warmstart 0x0001
Definition at line 122 of file gps_ubx.h.
CFG_RST_Reset_Controlled
#define CFG_RST_Reset_Controlled 0x01
Definition at line 116 of file gps_ubx.h.
CFG_RST_Reset_Controlled_GPS_only
#define CFG_RST_Reset_Controlled_GPS_only 0x02
Definition at line 117 of file gps_ubx.h.
CFG_RST_Reset_Controlled_GPS_start
#define CFG_RST_Reset_Controlled_GPS_start 0x09
Definition at line 119 of file gps_ubx.h.
CFG_RST_Reset_Controlled_GPS_stop
#define CFG_RST_Reset_Controlled_GPS_stop 0x08
Definition at line 118 of file gps_ubx.h.
CFG_RST_Reset_Hardware
#define CFG_RST_Reset_Hardware 0x00
Definition at line 115 of file gps_ubx.h.
GPS_UBX_MAX_PAYLOAD
#define GPS_UBX_MAX_PAYLOAD 512
Definition at line 53 of file gps_ubx.h.
GPS_UBX_NB_CHANNELS
#define GPS_UBX_NB_CHANNELS 40
Definition at line 51 of file gps_ubx.h.
gps_ubx_periodic_check
#define gps_ubx_periodic_check () gps_periodic_check(&gps_ubx.state)
Definition at line 49 of file gps_ubx.h.
gps_ubx_Reset
#define gps_ubx_Reset (_val)
Value:
    {                               \
    gps_ubx.reset = _val;                                       \
    if (gps_ubx.reset > CFG_RST_BBR_Warmstart)                  \
      gps_ubx.reset = CFG_RST_BBR_Coldstart;                    \
    ubx_send_cfg_rst(&(UBX_GPS_LINK).device, gps_ubx.reset, CFG_RST_Reset_Controlled);   \
  }
Definition at line 125 of file gps_ubx.h.
PRIMARY_GPS
#define PRIMARY_GPS GPS_UBX
Definition at line 43 of file gps_ubx.h.
Function Documentation
gps_ubx_event()
void gps_ubx_event (void)
Definition at line 108 of file gps_ubx.c.
References dev, gps_ubx, gps_ubx_msg(), gps_ubx_parse(), and GpsUbx::msg_available.
gps_ubx_init()
void gps_ubx_init (void)
Definition at line 98 of file gps_ubx.c.
References GpsState::comp_id, GpsUbx::error_cnt, GpsUbx::error_last, gps_ubx, GPS_UBX_ERR_NONE, GPS_UBX_ID, GpsUbx::msg_available, GpsUbx::state, GpsUbx::status, and UNINIT.
gps_ubx_msg()
void gps_ubx_msg (void)
Definition at line 636 of file gps_ubx.c.
References GpsState::fix, get_sys_time_usec(), GPS_FIX_3D, gps_ubx, GPS_UBX_ID, gps_ubx_read_message(), gps_ubx_ucenter_event, GPS_VALID_VEL_NED_BIT, GpsState::last_3dfix_ticks, GpsState::last_3dfix_time, GpsState::last_msg_ticks, GpsState::last_msg_time, LED_ON, LED_TOGGLE, GpsUbx::msg_class, GpsUbx::msg_id, sys_time::nb_sec, sys_time::nb_sec_rem, GpsUbx::state, and GpsState::valid_fields.
Referenced by gps_ubx_event().
gps_ubx_parse()
void gps_ubx_parse (uint8_t c)
Definition at line 505 of file gps_ubx.c.
References GpsUbx::ck_a, GpsUbx::ck_b, GpsUbx::error_cnt, GpsUbx::error_last, GOT_CHECKSUM1, GOT_CLASS, GOT_ID, GOT_LEN1, GOT_LEN2, GOT_PAYLOAD, GOT_SYNC1, GOT_SYNC2, gps_ubx, GPS_UBX_ERR_CHECKSUM, GPS_UBX_ERR_MSG_TOO_LONG, GPS_UBX_ERR_OUT_OF_SYNC, GPS_UBX_ERR_OVERRUN, GPS_UBX_ERR_UNEXPECTED, GPS_UBX_MAX_PAYLOAD, GpsUbx::len, GpsUbx::msg_available, GpsUbx::msg_buf, GpsUbx::msg_class, GpsUbx::msg_id, GpsUbx::msg_idx, pprzLogFile, GpsUbx::status, and UNINIT.
Referenced by gps_ubx_event().
gps_ubx_read_message()
void gps_ubx_read_message (void)
Definition at line 443 of file gps_ubx.c.
References gps_ubx, gps_ubx_parse_nav_posecef(), gps_ubx_parse_nav_posllh(), gps_ubx_parse_nav_posutm(), gps_ubx_parse_nav_pvt(), gps_ubx_parse_nav_relposned(), gps_ubx_parse_nav_sat(), gps_ubx_parse_nav_sol(), gps_ubx_parse_nav_status(), gps_ubx_parse_nav_svinfo(), gps_ubx_parse_nav_velned(), gps_ubx_parse_rxm_raw(), gps_ubx_parse_rxm_rtcm(), gps_ubx_parse_velecef(), GpsUbx::msg_class, and GpsUbx::msg_id.
Referenced by gps_ubx_msg().
ubx_header()
void ubx_header (struct link_device * dev, uint8_t nav_id, uint8_t msg_id, uint16_t len)
Definition at line 596 of file gps_ubx.c.
References dev, gps_ubx, GpsUbx::send_ck_a, GpsUbx::send_ck_b, and ubx_send_1byte().
ubx_send_bytes()
void ubx_send_bytes (struct link_device * dev, uint8_t len, uint8_t * bytes)
Definition at line 615 of file gps_ubx.c.
References dev, and ubx_send_1byte().
ubx_send_cfg_rst()
void ubx_send_cfg_rst (struct link_device * dev, uint16_t bbr, uint8_t reset_mode)
Definition at line 623 of file gps_ubx.c.
References dev.
ubx_trailer()
void ubx_trailer (struct link_device * dev)
Definition at line 608 of file gps_ubx.c.
References dev, gps_ubx, GpsUbx::send_ck_a, and GpsUbx::send_ck_b.
Variable Documentation
gps_ubx
struct GpsUbx gps_ubx
Definition at line 75 of file gps_ubx.c.
Referenced by ArduIMU_periodicGPS(), gps_ubx_event(), gps_ubx_init(), gps_ubx_msg(), gps_ubx_parse(), gps_ubx_parse_nav_posecef(), gps_ubx_parse_nav_posllh(), gps_ubx_parse_nav_posutm(), gps_ubx_parse_nav_pvt(), gps_ubx_parse_nav_relposned(), gps_ubx_parse_nav_sat(), gps_ubx_parse_nav_sol(), gps_ubx_parse_nav_status(), gps_ubx_parse_nav_svinfo(), gps_ubx_parse_nav_velned(), gps_ubx_parse_rxm_raw(), gps_ubx_parse_rxm_rtcm(), gps_ubx_parse_velecef(), gps_ubx_read_message(), gps_ubx_ucenter_event(), ubx_header(), ubx_send_1byte(), and ubx_trailer().