Paparazzi UAS: Attitude representations
Attitude representations
State interface
Functions
static bool stateIsAttitudeValid (void)
Test if attitudes are valid.
static void stateSetNedToBodyQuat_i (struct Int32Quat *ned_to_body_quat)
Set vehicle body attitude from quaternion (int).
static void stateSetNedToBodyRMat_i (struct Int32RMat *ned_to_body_rmat)
Set vehicle body attitude from rotation matrix (int).
static void stateSetNedToBodyEulers_i (struct Int32Eulers *ned_to_body_eulers)
Set vehicle body attitude from euler angles (int).
static void stateSetNedToBodyQuat_f (struct FloatQuat *ned_to_body_quat)
Set vehicle body attitude from quaternion (float).
static void stateSetNedToBodyRMat_f (struct FloatRMat *ned_to_body_rmat)
Set vehicle body attitude from rotation matrix (float).
static void stateSetNedToBodyEulers_f (struct FloatEulers *ned_to_body_eulers)
Set vehicle body attitude from euler angles (float).
static struct Int32Quat * stateGetNedToBodyQuat_i (void)
Get vehicle body attitude quaternion (int).
static struct Int32RMat * stateGetNedToBodyRMat_i (void)
Get vehicle body attitude rotation matrix (int).
static struct Int32Eulers * stateGetNedToBodyEulers_i (void)
Get vehicle body attitude euler angles (int).
static struct FloatQuat * stateGetNedToBodyQuat_f (void)
Get vehicle body attitude quaternion (float).
static struct FloatRMat * stateGetNedToBodyRMat_f (void)
Get vehicle body attitude rotation matrix (float).
static struct FloatEulers * stateGetNedToBodyEulers_f (void)
Get vehicle body attitude euler angles (float).
Detailed Description
Function Documentation
stateGetNedToBodyEulers_f()
static struct FloatEulers* stateGetNedToBodyEulers_f (void) inline static
Get vehicle body attitude euler angles (float).
Definition at line 1143 of file state.h.
References State::ned_to_body_orientation, orientationGetEulers_f(), and state.
Referenced by autopilot_guided_goto_body_relative(), autopilot_guided_goto_ned_relative(), autopilot_guided_update(), calculate_new_heading(), calculateForwards(), calibrate_coeff(), cam_target(), CN_calculate_target(), CN_escape_velocity(), CN_potential_heading(), CN_potential_velocity(), CN_vector_escape_velocity(), CN_vector_velocity(), collective_tracking_control(), ctrl_eff_scheduling_periodic(), dc_circle(), dc_info(), dc_periodic(), dc_send_shot_position(), decode_optical_flow_msg(), draw_osd(), dw1000_reset_heading_ref(), file_logger_write_row(), get_world_position_from_image_points(), guidance_h_hover_enter(), guidance_h_nav_enter(), guidance_h_set_guided_body_vel(), guidance_indi_calcG(), guidance_indi_enter(), guidance_indi_run(), gvf_control_2D(), gvf_parametric_low_level_control_2D(), gvf_parametric_low_level_control_3D(), h_ctl_course_loop(), h_ctl_pitch_loop(), h_ctl_roll_loop(), imu_SetBodyToImuCurrent(), increase_nav_heading(), lidar_lite_periodic(), lidar_sf11_periodic(), logger_uart_periodic(), main_periodic_task(), mateksys3901l0x_parse(), mavlink_send_attitude(), mavlink_send_global_position_int(), mavlink_send_highres_imu(), mavlink_send_vfr_hud(), mf_daq_send_state(), nav_launcher_setup(), nav_set_heading_current(), OA_update(), object_tracking_run(), orange_avoider_guided_periodic(), parse_mf_daq_msg(), pose_periodic(), px4flow_i2c_frame_cb(), rover_guidance_enter(), rover_guidance_run(), rover_holo_guidance_enter(), rover_holo_guidance_run(), send_att(), send_attitude(), send_ctl_a(), send_dragspeed(), send_tune_roll(), sonar_bebop_read(), sonar_pwm_read(), stabilization_attitude_get_heading_f(), stabilization_attitude_read_rc_setpoint_eulers_f(), stabilization_attitude_read_rc_setpoint_quat_earth_bound_f(), stabilization_attitude_read_rc_setpoint_quat_f(), stabilization_attitude_reset_care_free_heading(), stabilization_attitude_run(), stabilization_attitude_set_earth_cmd_i(), stabilization_attitude_set_failsafe_setpoint(), state2stereocam(), stereo_avoid_run(), takeoff_detect_periodic(), tfmini_i2c_periodic(), tfmini_parse(), v_ctl_climb_loop(), and wind_estimator_periodic().
stateGetNedToBodyEulers_i()
static struct Int32Eulers* stateGetNedToBodyEulers_i (void) inline static
Get vehicle body attitude euler angles (int).
Definition at line 1125 of file state.h.
References State::ned_to_body_orientation, orientationGetEulers_i(), and state.
Referenced by computeOptiTrack(), dc_send_command(), guidance_flip_run(), guidance_h_module_enter(), guidance_h_nav_enter(), nav_set_heading_current(), OA_update(), read_rc_setpoint_speed_i(), rotorcraft_cam_periodic(), send_att(), send_euler(), send_fp(), send_tune_hover(), stabilization_attitude_enter(), stabilization_attitude_get_heading_i(), stabilization_attitude_read_rc_setpoint_eulers(), stabilization_attitude_run(), stabilization_attitude_set_earth_cmd_i(), stabilization_attitude_set_failsafe_setpoint(), and stabilization_indi_set_earth_cmd_i().
stateGetNedToBodyQuat_f()
static struct FloatQuat* stateGetNedToBodyQuat_f (void) inline static
Get vehicle body attitude quaternion (float).
Definition at line 1131 of file state.h.
References State::ned_to_body_orientation, orientationGetQuat_f(), and state.
Referenced by ctrl_eff_scheduling_periodic_b(), guidance_indi_run(), jevois_send_state(), mag_calib_ukf_run(), mavlink_send_attitude_quaternion(), send_fp(), send_windtunnel_meas(), stabilization_attitude_enter(), stabilization_attitude_run(), stabilization_indi_attitude_run(), vel_est_cb(), and wind_estimator_periodic().
stateGetNedToBodyQuat_i()
static struct Int32Quat* stateGetNedToBodyQuat_i (void) inline static
Get vehicle body attitude quaternion (int).
Definition at line 1113 of file state.h.
References State::ned_to_body_orientation, orientationGetQuat_i(), and state.
Referenced by ins_int_update_gps(), send_ahrs_ref_quat(), send_quat(), stabilization_attitude_enter(), and stabilization_attitude_run().
stateGetNedToBodyRMat_f()
static struct FloatRMat* stateGetNedToBodyRMat_f (void) inline static
Get vehicle body attitude rotation matrix (float).
Definition at line 1137 of file state.h.
References State::ned_to_body_orientation, orientationGetRMat_f(), and state.
Referenced by detection_cb(), nav_catapult_highrate_module(), process_data(), unwrap_LUT(), wind_estimation_quadrotor_periodic(), and wind_estimator_periodic().
stateGetNedToBodyRMat_i()
static struct Int32RMat* stateGetNedToBodyRMat_i (void) inline static
Get vehicle body attitude rotation matrix (int).
Definition at line 1119 of file state.h.
References State::ned_to_body_orientation, orientationGetRMat_i(), and state.
Referenced by accel_cb(), georeference_project(), get_vertical_thrust_coeff(), hff_propagate(), ins_int_propagate(), ins_module_propagate(), and stabilization_attitude_run().
stateIsAttitudeValid()
static bool stateIsAttitudeValid (void) inline static
Test if attitudes are valid.
Definition at line 1067 of file state.h.
References State::ned_to_body_orientation, orienationCheckValid(), and state.
Referenced by ap_ahrs_is_aligned(), imu_SetBodyToImuCurrent(), and mavlink_send_heartbeat().
stateSetNedToBodyEulers_f()
static void stateSetNedToBodyEulers_f (struct FloatEulers * ned_to_body_eulers) inline static
Set vehicle body attitude from euler angles (float).
Definition at line 1105 of file state.h.
References State::ned_to_body_orientation, orientationSetEulers_f(), and state.
Referenced by ArduIMU_event(), ArduIMU_periodic(), gx3_packet_read_message(), IMU_Daten_verarbeiten(), parse_ins_msg(), update_ahrs_from_sim(), update_state_interface(), and vn100_event_task().
stateSetNedToBodyEulers_i()
static void stateSetNedToBodyEulers_i (struct Int32Eulers * ned_to_body_eulers) inline static
Set vehicle body attitude from euler angles (int).
Definition at line 1087 of file state.h.
References State::ned_to_body_orientation, orientationSetEulers_i(), and state.
stateSetNedToBodyQuat_f()
static void stateSetNedToBodyQuat_f (struct FloatQuat * ned_to_body_quat) inline static
Set vehicle body attitude from quaternion (float).
Definition at line 1093 of file state.h.
References State::ned_to_body_orientation, orientationSetQuat_f(), and state.
Referenced by ahrs_vectornav_propagate(), compute_body_orientation_and_rates(), ins_ekf2_publish_attitude(), ins_float_invariant_align(), ins_float_invariant_propagate(), set_body_state_from_quat(), set_state_from_ins(), and sim_overwrite_ahrs().
stateSetNedToBodyQuat_i()
static void stateSetNedToBodyQuat_i (struct Int32Quat * ned_to_body_quat) inline static
Set vehicle body attitude from quaternion (int).
Definition at line 1075 of file state.h.
References State::ned_to_body_orientation, orientationSetQuat_i(), and state.
Referenced by set_body_state_from_quat().
stateSetNedToBodyRMat_f()
static void stateSetNedToBodyRMat_f (struct FloatRMat * ned_to_body_rmat) inline static
Set vehicle body attitude from rotation matrix (float).
Definition at line 1099 of file state.h.
References State::ned_to_body_orientation, orientationSetRMat_f(), and state.
Referenced by gx3_packet_read_message(), ins_vectornav_propagate(), and set_body_orientation_and_rates().
stateSetNedToBodyRMat_i()
static void stateSetNedToBodyRMat_i (struct Int32RMat * ned_to_body_rmat) inline static
Set vehicle body attitude from rotation matrix (int).
Definition at line 1081 of file state.h.
References State::ned_to_body_orientation, orientationSetRMat_i(), and state.