Paparazzi UAS: sw/airborne/modules/guidance/gvf_parametric/gvf_parametric_low_level_control.c File Reference
gvf_parametric_low_level_control.c File Reference
#include "autopilot.h"
#include "gvf_parametric_low_level_control.h"
#include "gvf_parametric.h"
Functions
void gvf_parametric_low_level_control_2D (float heading_rate)
void gvf_parametric_low_level_control_3D (float heading_rate, float climbing_rate)
Detailed Description
Firmware dependent file for the guiding vector field algorithm for 2D and 3D parametric trajectories.
Definition in file gvf_parametric_low_level_control.c.
Function Documentation
gvf_parametric_low_level_control_2D()
void gvf_parametric_low_level_control_2D (float heading_rate)
Definition at line 36 of file gvf_parametric_low_level_control.c.
References AP_MODE_AUTO2, autopilot_get_mode(), ground_speed, gvf_parametric_control, GVF_PARAMETRIC_GRAVITY, h_ctl_roll_max_setpoint, h_ctl_roll_setpoint, gvf_parametric_con::k_roll, lateral_mode, LATERAL_MODE_ROLL, stateGetHorizontalSpeedNorm_f(), stateGetNedToBodyEulers_f(), and FloatEulers::theta.
Referenced by gvf_parametric_control_2D().
gvf_parametric_low_level_control_3D()
void gvf_parametric_low_level_control_3D (float heading_rate, float climbing_rate)
Definition at line 55 of file gvf_parametric_low_level_control.c.
References AP_MODE_AUTO2, autopilot_get_mode(), ground_speed, gvf_parametric_control, GVF_PARAMETRIC_GRAVITY, h_ctl_roll_max_setpoint, h_ctl_roll_setpoint, gvf_parametric_con::k_climb, gvf_parametric_con::k_roll, lateral_mode, LATERAL_MODE_ROLL, stateGetHorizontalSpeedNorm_f(), stateGetNedToBodyEulers_f(), FloatEulers::theta, v_ctl_climb_setpoint, v_ctl_mode, V_CTL_MODE_AUTO_CLIMB, v_ctl_speed_mode, and V_CTL_SPEED_THROTTLE.
Referenced by gvf_parametric_control_3D().