Paparazzi UAS: sw/airborne/modules/imu/imu_drotek_10dof_v2.c File Reference
imu_drotek_10dof_v2.c File Reference
#include "modules/imu/imu.h"
#include "modules/core/abi.h"
#include "mcu_periph/i2c.h"
Macros
#define DROTEK_2_MPU_I2C_ADDR MPU60X0_ADDR_ALT
#define DROTEK_2_HMC_I2C_ADDR HMC58XX_ADDR
Functions
void imu_drotek2_init (void)
void imu_drotek2_periodic (void)
void imu_drotek2_event (void)
bool imu_drotek2_configure_mag_slave (Mpu60x0ConfigSet mpu_set, void *mpu)
callback function to configure hmc5883 mag
Variables
struct ImuDrotek2 imu_drotek2
Detailed Description
Driver for the Drotek 10DOF V2 IMU. MPU6050 + HMC5883 + MS5611 Reading the baro is not part of the IMU driver.
By default the axes orientation should be as printed on the pcb, meaning z-axis pointing down if ICs are facing down. The orientation can be switched so that the IMU can be mounted ICs facing up by defining IMU_DROTEK_2_ORIENTATION_IC_UP.
Definition in file imu_drotek_10dof_v2.c.
Macro Definition Documentation
DROTEK_2_HMC_I2C_ADDR
#define DROTEK_2_HMC_I2C_ADDR HMC58XX_ADDR
Definition at line 68 of file imu_drotek_10dof_v2.c.
DROTEK_2_MPU_I2C_ADDR
#define DROTEK_2_MPU_I2C_ADDR MPU60X0_ADDR_ALT
Definition at line 63 of file imu_drotek_10dof_v2.c.
Function Documentation
imu_drotek2_configure_mag_slave()
bool imu_drotek2_configure_mag_slave (Mpu60x0ConfigSet mpu_set, void * mpu)
callback function to configure hmc5883 mag
Returns
TRUE if mag configuration finished
Definition at line 158 of file imu_drotek_10dof_v2.c.
References ImuDrotek2::hmc, hmc58xx_start_configure(), imu_drotek2, and Hmc58xx::initialized.
Referenced by imu_drotek2_init().
imu_drotek2_event()
void imu_drotek2_event (void)
Definition at line 110 of file imu_drotek_10dof_v2.c.
References Imu::accel, Imu::accel_unscaled, Hmc58xx::data, Mpu60x0_I2c::data_accel, Mpu60x0_I2c::data_available, Hmc58xx::data_available, Mpu60x0_I2c::data_rates, get_sys_time_usec(), Imu::gyro, Imu::gyro_unscaled, ImuDrotek2::hmc, hmc58xx_event(), imu, imu_drotek2, IMU_DROTEK_ID, imu_scale_accel(), imu_scale_gyro(), imu_scale_mag(), Imu::mag, Imu::mag_unscaled, ImuDrotek2::mpu, mpu60x0_i2c_event(), Int32Rates::p, Int32Rates::q, Int32Rates::r, RATES_COPY, VECT3_COPY, Int32Vect3::x, Int32Vect3::y, and Int32Vect3::z.
imu_drotek2_init()
void imu_drotek2_init (void)
Definition at line 75 of file imu_drotek_10dof_v2.c.
References Mpu60x0Config::accel_range, Mpu60x0_I2c::config, Mpu60x0I2cSlave::configure, Mpu60x0Config::dlpf_cfg, DROTEK_2_ACCEL_RANGE, DROTEK_2_GYRO_RANGE, DROTEK_2_HMC_I2C_ADDR, DROTEK_2_MPU_I2C_ADDR, Mpu60x0Config::gyro_range, ImuDrotek2::hmc, hmc58xx_init(), Mpu60x0Config::i2c_bypass, imu_drotek2, imu_drotek2_configure_mag_slave(), ImuDrotek2::mpu, mpu60x0_i2c_init(), Mpu60x0Config::nb_slaves, Mpu60x0Config::slaves, and Mpu60x0Config::smplrt_div.
imu_drotek2_periodic()
void imu_drotek2_periodic (void)
Definition at line 99 of file imu_drotek_10dof_v2.c.
References Mpu60x0_I2c::config, ImuDrotek2::hmc, hmc58xx_read(), imu_drotek2, Mpu60x0Config::initialized, ImuDrotek2::mpu, and mpu60x0_i2c_periodic().
Variable Documentation
imu_drotek2
struct ImuDrotek2 imu_drotek2
Definition at line 73 of file imu_drotek_10dof_v2.c.
Referenced by imu_drotek2_configure_mag_slave(), imu_drotek2_event(), imu_drotek2_init(), and imu_drotek2_periodic().