Paparazzi UAS: sw/airborne/modules/imu/imu_nps.h File Reference
imu_nps.h File Reference
#include "modules/imu/imu.h"
#include "generated/airframe.h"
Data Structures
struct ImuNps
Macros
#define IMU_GYRO_P_SENS 4.359
we just define some defaults for aspirin v1.5 for now
#define IMU_GYRO_P_SENS_NUM 4359
#define IMU_GYRO_P_SENS_DEN 1000
#define IMU_GYRO_Q_SENS 4.359
#define IMU_GYRO_Q_SENS_NUM 4359
#define IMU_GYRO_Q_SENS_DEN 1000
#define IMU_GYRO_R_SENS 4.359
#define IMU_GYRO_R_SENS_NUM 4359
#define IMU_GYRO_R_SENS_DEN 1000
#define IMU_ACCEL_X_SENS 37.91
we just define some defaults for aspirin v1.5 for now
#define IMU_ACCEL_X_SENS_NUM 3791
#define IMU_ACCEL_X_SENS_DEN 100
#define IMU_ACCEL_Y_SENS 37.91
#define IMU_ACCEL_Y_SENS_NUM 3791
#define IMU_ACCEL_Y_SENS_DEN 100
#define IMU_ACCEL_Z_SENS 39.24
#define IMU_ACCEL_Z_SENS_NUM 3924
#define IMU_ACCEL_Z_SENS_DEN 100
#define IMU_MAG_X_SENS 3.5
#define IMU_MAG_X_SENS_NUM 7
#define IMU_MAG_X_SENS_DEN 2
#define IMU_MAG_Y_SENS 3.5
#define IMU_MAG_Y_SENS_NUM 7
#define IMU_MAG_Y_SENS_DEN 2
#define IMU_MAG_Z_SENS 3.5
#define IMU_MAG_Z_SENS_NUM 7
#define IMU_MAG_Z_SENS_DEN 2
Functions
void imu_feed_gyro_accel (void)
void imu_feed_mag (void)
void imu_nps_init (void)
void imu_nps_event (void)
Variables
struct ImuNps imu_nps
Data Structure Documentation
ImuNps
struct ImuNps
Definition at line 72 of file imu_nps.h.
Data Fields
uint8_t accel_available
uint8_t gyro_available
uint8_t mag_available
Macro Definition Documentation
IMU_ACCEL_X_SENS
#define IMU_ACCEL_X_SENS 37.91
we just define some defaults for aspirin v1.5 for now
Definition at line 47 of file imu_nps.h.
IMU_ACCEL_X_SENS_DEN
#define IMU_ACCEL_X_SENS_DEN 100
Definition at line 49 of file imu_nps.h.
IMU_ACCEL_X_SENS_NUM
#define IMU_ACCEL_X_SENS_NUM 3791
Definition at line 48 of file imu_nps.h.
IMU_ACCEL_Y_SENS
#define IMU_ACCEL_Y_SENS 37.91
Definition at line 50 of file imu_nps.h.
IMU_ACCEL_Y_SENS_DEN
#define IMU_ACCEL_Y_SENS_DEN 100
Definition at line 52 of file imu_nps.h.
IMU_ACCEL_Y_SENS_NUM
#define IMU_ACCEL_Y_SENS_NUM 3791
Definition at line 51 of file imu_nps.h.
IMU_ACCEL_Z_SENS
#define IMU_ACCEL_Z_SENS 39.24
Definition at line 53 of file imu_nps.h.
IMU_ACCEL_Z_SENS_DEN
#define IMU_ACCEL_Z_SENS_DEN 100
Definition at line 55 of file imu_nps.h.
IMU_ACCEL_Z_SENS_NUM
#define IMU_ACCEL_Z_SENS_NUM 3924
Definition at line 54 of file imu_nps.h.
IMU_GYRO_P_SENS
#define IMU_GYRO_P_SENS 4.359
we just define some defaults for aspirin v1.5 for now
Definition at line 32 of file imu_nps.h.
IMU_GYRO_P_SENS_DEN
#define IMU_GYRO_P_SENS_DEN 1000
Definition at line 34 of file imu_nps.h.
IMU_GYRO_P_SENS_NUM
#define IMU_GYRO_P_SENS_NUM 4359
Definition at line 33 of file imu_nps.h.
IMU_GYRO_Q_SENS
#define IMU_GYRO_Q_SENS 4.359
Definition at line 35 of file imu_nps.h.
IMU_GYRO_Q_SENS_DEN
#define IMU_GYRO_Q_SENS_DEN 1000
Definition at line 37 of file imu_nps.h.
IMU_GYRO_Q_SENS_NUM
#define IMU_GYRO_Q_SENS_NUM 4359
Definition at line 36 of file imu_nps.h.
IMU_GYRO_R_SENS
#define IMU_GYRO_R_SENS 4.359
Definition at line 38 of file imu_nps.h.
IMU_GYRO_R_SENS_DEN
#define IMU_GYRO_R_SENS_DEN 1000
Definition at line 40 of file imu_nps.h.
IMU_GYRO_R_SENS_NUM
#define IMU_GYRO_R_SENS_NUM 4359
Definition at line 39 of file imu_nps.h.
IMU_MAG_X_SENS
#define IMU_MAG_X_SENS 3.5
Definition at line 60 of file imu_nps.h.
IMU_MAG_X_SENS_DEN
#define IMU_MAG_X_SENS_DEN 2
Definition at line 62 of file imu_nps.h.
IMU_MAG_X_SENS_NUM
#define IMU_MAG_X_SENS_NUM 7
Definition at line 61 of file imu_nps.h.
IMU_MAG_Y_SENS
#define IMU_MAG_Y_SENS 3.5
Definition at line 63 of file imu_nps.h.
IMU_MAG_Y_SENS_DEN
#define IMU_MAG_Y_SENS_DEN 2
Definition at line 65 of file imu_nps.h.
IMU_MAG_Y_SENS_NUM
#define IMU_MAG_Y_SENS_NUM 7
Definition at line 64 of file imu_nps.h.
IMU_MAG_Z_SENS
#define IMU_MAG_Z_SENS 3.5
Definition at line 66 of file imu_nps.h.
IMU_MAG_Z_SENS_DEN
#define IMU_MAG_Z_SENS_DEN 2
Definition at line 68 of file imu_nps.h.
IMU_MAG_Z_SENS_NUM
#define IMU_MAG_Z_SENS_NUM 7
Definition at line 67 of file imu_nps.h.
Function Documentation
imu_feed_gyro_accel()
void imu_feed_gyro_accel (void)
Definition at line 40 of file imu_nps.c.
References ImuNps::accel_available, Imu::accel_unscaled, ImuNps::gyro_available, Imu::gyro_unscaled, imu, imu_nps, RATES_ASSIGN, sensors, and VECT3_ASSIGN.
Referenced by nps_autopilot_run_step().
imu_feed_mag()
void imu_feed_mag (void)
Definition at line 53 of file imu_nps.c.
References imu, imu_nps, ImuNps::mag_available, Imu::mag_unscaled, sensors, and VECT3_ASSIGN.
Referenced by nps_autopilot_run_step().
imu_nps_event()
void imu_nps_event (void)
Definition at line 61 of file imu_nps.c.
References Imu::accel, ImuNps::accel_available, get_sys_time_usec(), Imu::gyro, ImuNps::gyro_available, imu, IMU_BOARD_ID, imu_nps, imu_scale_accel(), imu_scale_gyro(), imu_scale_mag(), Imu::mag, and ImuNps::mag_available.
imu_nps_init()
void imu_nps_init (void)
Definition at line 30 of file imu_nps.c.
References ImuNps::accel_available, ImuNps::gyro_available, imu_nps, and ImuNps::mag_available.
Variable Documentation
imu_nps
struct ImuNps imu_nps
Definition at line 28 of file imu_nps.c.
Referenced by imu_feed_gyro_accel(), imu_feed_mag(), imu_nps_event(), and imu_nps_init().