Paparazzi UAS: sw/airborne/modules/ins/ins_ekf2.h File Reference
ins_ekf2.h File Reference
#include "modules/ahrs/ahrs.h"
#include "modules/ins/ins.h"
Data Structures
struct ekf2_parameters_t
Functions
void ins_ekf2_init (void)
void ins_ekf2_update (void)
void ins_ekf2_change_param (int32_t unk)
void ins_ekf2_remove_gps (int32_t mode)
Variables
struct ekf2_parameters_t ekf2_params
Detailed Description
INS based in the EKF2 of PX4
Definition in file ins_ekf2.h.
Data Structure Documentation
ekf2_parameters_t
struct ekf2_parameters_t
Definition at line 39 of file ins_ekf2.h.
Data Fields
int32_t fusion_mode
int32_t mag_fusion_type
Function Documentation
ins_ekf2_change_param()
void ins_ekf2_change_param (int32_t unk)
Definition at line 518 of file ins_ekf2.cpp.
References ekf2_params, ekf_params, and ekf2_parameters_t::mag_fusion_type.
ins_ekf2_init()
void ins_ekf2_init (void)
Definition at line 374 of file ins_ekf2.cpp.
References ABI_BROADCAST, accel_cb(), accel_ev, ekf2_t::accel_stamp, ekf2_t::accel_valid, agl_cb(), agl_ev, baro_cb(), baro_ev, body_to_imu_cb(), body_to_imu_ev, DefaultPeriodic, ekf, ekf2, ekf_params, ekf2_t::flow_stamp, ekf2_t::got_imu_data, gps_cb(), gps_ev, gyro_cb(), gyro_ev, ekf2_t::gyro_stamp, ekf2_t::gyro_valid, INS_EKF2_ACCEL_ID, INS_EKF2_AGL_ID, INS_EKF2_BARO_ID, INS_EKF2_FLOW_INNOV_GATE, INS_EKF2_FLOW_NOISE, INS_EKF2_FLOW_NOISE_QMIN, INS_EKF2_FLOW_OFFSET_X, INS_EKF2_FLOW_OFFSET_Y, INS_EKF2_FLOW_OFFSET_Z, INS_EKF2_FLOW_SENSOR_DELAY, INS_EKF2_FUSION_MODE, INS_EKF2_GPS_CHECK_MASK, INS_EKF2_GPS_ID, INS_EKF2_GYRO_ID, INS_EKF2_MAG_ID, INS_EKF2_MAX_FLOW_RATE, INS_EKF2_MIN_FLOW_QUALITY, INS_EKF2_OF_ID, INS_EKF2_RANGE_MAIN_AGL, INS_EKF2_SONAR_MAX_RANGE, INS_EKF2_SONAR_MIN_RANGE, INS_EKF2_VDIST_SENSOR_TYPE, ekf2_t::ltp_stamp, mag_cb(), mag_ev, ekf2_t::offset_x, ekf2_t::offset_y, ekf2_t::offset_z, optical_flow_cb(), optical_flow_ev, ekf2_t::quat_reset_counter, register_periodic_telemetry(), send_ahrs_bias(), send_filter_status(), send_ins_ekf2(), send_ins_ekf2_ext(), send_ins_ref(), and send_wind_info_ret().
ins_ekf2_remove_gps()
void ins_ekf2_remove_gps (int32_t mode)
Definition at line 523 of file ins_ekf2.cpp.
References ekf2_params, ekf_params, ekf2_parameters_t::fusion_mode, INS_EKF2_FUSION_MODE, and mode.
ins_ekf2_update()
void ins_ekf2_update (void)
Definition at line 440 of file ins_ekf2.cpp.
References LlaCoor_i::alt, autopilot_in_flight(), ekf, ekf2, ekf2_t::got_imu_data, LlaCoor_i::lat, LlaCoor_i::lon, ekf2_t::ltp_def, ltp_def_from_lla_i(), ekf2_t::ltp_stamp, nps_bypass_ins, sim_overwrite_ins(), stateSetAccelNed_f(), stateSetLocalOrigin_i(), stateSetPositionNed_f(), stateSetSpeedNed_f(), waypoints_localize_all(), NedCoor_f::x, NedCoor_f::y, and NedCoor_f::z.
Variable Documentation
ekf2_params
struct ekf2_parameters_t ekf2_params
Definition at line 259 of file ins_ekf2.cpp.
Referenced by ins_ekf2_change_param(), and ins_ekf2_remove_gps().