Paparazzi UAS: sw/airborne/modules/intermcu/intermcu_fbw.c File Reference
intermcu_fbw.c File Reference
Rotorcraft Inter-MCU on FlyByWire.
#include "intermcu_fbw.h"
#include "pprzlink/intermcu_msg.h"
#include "modules/radio_control/radio_control.h"
#include "modules/energy/electrical.h"
#include "mcu_periph/uart.h"
#include "modules/telemetry/telemetry_intermcu.h"
#include "modules/spektrum_soft_bind/spektrum_soft_bind_fbw.h"
#include <BOARD_CONFIG>
#include "modules/core/abi.h"
#include "modules/gps/gps.h"
Macros
#define ABI_C
#define IMCU_GPS_ID GPS_MULTI_ID
Functions
static void intermcu_parse_msg (void(*commands_frame_handler)(void))
static void gps_cb (uint8_t sender_id, uint32_t stamp, struct GpsState *gps_s)
void intermcu_init (void)
void intermcu_periodic (void)
void intermcu_on_rc_frame (uint8_t fbw_mode)
void intermcu_send_status (uint8_t mode)
void InterMcuEvent (void(*frame_handler)(void))
Variables
struct intermcu_t intermcu
uint8_t imcu_msg_buf [128]
The InterMCU message buffer.
pprz_t intermcu_commands [COMMANDS_NB]
bool autopilot_motors_on = false
static abi_event gps_ev
Detailed Description
Rotorcraft Inter-MCU on FlyByWire.
Definition in file intermcu_fbw.c.
Macro Definition Documentation
ABI_C
#define ABI_C
Definition at line 27 of file intermcu_fbw.c.
IMCU_GPS_ID
#define IMCU_GPS_ID GPS_MULTI_ID
Definition at line 74 of file intermcu_fbw.c.
Function Documentation
gps_cb()
static void gps_cb (uint8_t sender_id, uint32_t stamp, struct GpsState * gps_s) static
Definition at line 233 of file intermcu_fbw.c.
References LlaCoor_i::alt, GpsState::course, intermcu_t::device, GpsState::ecef_pos, GpsState::ecef_vel, GpsState::fix, GpsState::gspeed, GpsState::hmsl, intermcu, INTERMCU_FBW, GpsState::lla_pos, GpsState::num_sv, GpsState::pacc, GpsState::sacc, intermcu_t::transport, EcefCoor_i::x, EcefCoor_i::y, and EcefCoor_i::z.
Referenced by intermcu_init().
intermcu_init()
void intermcu_init (void)
Definition at line 83 of file intermcu_fbw.c.
References gps_cb(), gps_ev, IMCU_GPS_ID, intermcu, sys_time_register_timer(), and intermcu_t::transport.
Referenced by main_init().
intermcu_on_rc_frame()
void intermcu_on_rc_frame (uint8_t fbw_mode)
Definition at line 106 of file intermcu_fbw.c.
References intermcu_t::device, fbw_mode, intermcu, INTERMCU_FBW, INTERMCU_RADIO_AUX1, INTERMCU_RADIO_AUX2, INTERMCU_RADIO_AUX3, INTERMCU_RADIO_KILL_SWITCH, INTERMCU_RADIO_MODE, INTERMCU_RADIO_PITCH, INTERMCU_RADIO_ROLL, INTERMCU_RADIO_THROTTLE, INTERMCU_RADIO_YAW, RADIO_AUX1, RADIO_AUX2, RADIO_AUX3, radio_control, RADIO_CONTROL_NB_CHANNEL, RADIO_KILL_SWITCH, RADIO_MODE, RADIO_PITCH, RADIO_ROLL, RADIO_THROTTLE, RADIO_YAW, intermcu_t::transport, and RadioControl::values.
Referenced by fbw_on_rc_frame().
intermcu_parse_msg()
static void intermcu_parse_msg (void(*)(void) commands_frame_handler) static
Definition at line 148 of file intermcu_fbw.c.
References autopilot_motors_on, intermcu_t::cmd_status, imcu_msg_buf, intermcu, INTERMCU_CLR_CMD_STATUS, INTERMCU_CMD_MOTORS_ON, intermcu_commands, INTERMCU_GET_CMD_STATUS, INTERMCU_OK, msg, received_spektrum_soft_bind(), intermcu_t::status, telemetry_intermcu_on_msg(), and intermcu_t::time_since_last_frame.
Referenced by InterMcuEvent().
intermcu_periodic()
void intermcu_periodic (void)
Definition at line 96 of file intermcu_fbw.c.
References intermcu, INTERMCU_LOST, INTERMCU_LOST_CNT, intermcu_t::status, and intermcu_t::time_since_last_frame.
Referenced by main_periodic().
intermcu_send_status()
void intermcu_send_status (uint8_t mode)
Definition at line 139 of file intermcu_fbw.c.
References Electrical::current, intermcu_t::device, electrical, RadioControl::frame_rate, intermcu, INTERMCU_FBW, mode, radio_control, RadioControl::status, intermcu_t::transport, and Electrical::vsupply.
Referenced by telemetry_periodic().
InterMcuEvent()
void InterMcuEvent (void(*)(void) frame_handler)
Definition at line 199 of file intermcu_fbw.c.
References intermcu_t::device, imcu_msg_buf, intermcu, intermcu_parse_msg(), intermcu_t::msg_available, and intermcu_t::transport.
Referenced by main_event().
Variable Documentation
autopilot_motors_on
bool autopilot_motors_on = false
Definition at line 64 of file intermcu_fbw.c.
Referenced by intermcu_parse_msg(), and main_periodic().
gps_ev
abi_event gps_ev static
Definition at line 79 of file intermcu_fbw.c.
Referenced by intermcu_init().
imcu_msg_buf
uint8_t imcu_msg_buf[128]
The InterMCU message buffer.
Definition at line 61 of file intermcu_fbw.c.
Referenced by intermcu_parse_msg(), and InterMcuEvent().
intermcu
struct intermcu_t intermcu
Initial value:
= {
  .device = (&((INTERMCU_LINK).device)),
  .enabled = true,
  .msg_available = false
}
Definition at line 56 of file intermcu_fbw.c.
Referenced by fbw_on_rc_frame(), fbw_safety_check(), gps_cb(), intermcu_init(), intermcu_on_rc_frame(), intermcu_parse_msg(), intermcu_periodic(), intermcu_send_status(), InterMcuEvent(), main_periodic(), opa_controller_periodic(), telemetry_intermcu_event(), and telemetry_intermcu_send_message().
intermcu_commands
pprz_t intermcu_commands[COMMANDS_NB]
Definition at line 63 of file intermcu_fbw.c.
Referenced by fbw_on_ap_command(), and intermcu_parse_msg().