Paparazzi UAS: sw/airborne/modules/intermcu/intermcu_ap.c File Reference
intermcu_ap.c File Reference
Rotorcraft Inter-MCU on the autopilot.
#include "intermcu_ap.h"
#include "pprzlink/intermcu_msg.h"
#include "modules/radio_control/radio_control.h"
#include "mcu_periph/uart.h"
#include "modules/energy/electrical.h"
#include "autopilot.h"
#include "modules/datalink/telemetry.h"
Functions
static void intermcu_parse_msg (void(*rc_frame_handler)(void))
static void send_status (struct transport_tx *trans, struct link_device *dev)
void intermcu_init (void)
void intermcu_periodic (void)
void intermcu_set_enabled (bool value)
void intermcu_set_actuators (pprz_t *command_values, uint8_t ap_mode)
void intermcu_send_spektrum_bind (void)
void RadioControlEvent (void(*frame_handler)(void))
Variables
struct intermcu_t intermcu
uint8_t imcu_msg_buf [128]
The InterMCU message buffer.
static struct fbw_status_t fbw_status
Detailed Description
Rotorcraft Inter-MCU on the autopilot.
Definition in file intermcu_ap.c.
Function Documentation
intermcu_init()
void intermcu_init (void)
Definition at line 71 of file intermcu_ap.c.
References DefaultPeriodic, GPS_FIX_NONE, GPS_IMCU_ID, intermcu, register_periodic_telemetry(), send_status(), and intermcu_t::transport.
intermcu_parse_msg()
static void intermcu_parse_msg (void(*)(void) rc_frame_handler) inline static
Definition at line 138 of file intermcu_ap.c.
References Electrical::current, fbw_status_t::electrical, fbw_status, RadioControl::frame_cpt, fbw_status_t::frame_rate, get_sys_time_usec(), GPS_FIX_3D, GPS_IMCU_ID, GPS_VALID_COURSE_BIT, GPS_VALID_HMSL_BIT, GPS_VALID_POS_ECEF_BIT, GPS_VALID_VEL_ECEF_BIT, imcu_msg_buf, intermcu, fbw_status_t::mode, msg, sys_time::nb_sec, sys_time::nb_sec_rem, radio_control, RC_OK, fbw_status_t::rc_status, RadioControl::status, intermcu_t::status, telemetry_intermcu_on_msg(), RadioControl::time_since_last_frame, RadioControl::values, and Electrical::vsupply.
Referenced by RadioControlEvent().
intermcu_periodic()
void intermcu_periodic (void)
Definition at line 90 of file intermcu_ap.c.
References gps_periodic_check(), intermcu, INTERMCU_LOST, INTERMCU_LOST_CNT, intermcu_t::status, and intermcu_t::time_since_last_frame.
intermcu_send_spektrum_bind()
void intermcu_send_spektrum_bind (void)
Definition at line 129 of file intermcu_ap.c.
References intermcu_t::device, intermcu_t::enabled, intermcu, INTERMCU_AP, and intermcu_t::transport.
Referenced by spektrum_soft_bind_click().
intermcu_set_actuators()
void intermcu_set_actuators (pprz_t * command_values, uint8_t ap_mode)
Definition at line 111 of file intermcu_ap.c.
References autopilot_get_motors_on(), intermcu_t::cmd_status, intermcu_t::device, intermcu_t::enabled, intermcu, INTERMCU_AP, INTERMCU_CMD_MOTORS_ON, INTERMCU_SET_CMD_STATUS, and intermcu_t::transport.
Referenced by handle_periodic_tasks().
intermcu_set_enabled()
void intermcu_set_enabled (bool value)
Definition at line 105 of file intermcu_ap.c.
References intermcu_t::enabled, and intermcu.
Referenced by px4flash_event().
RadioControlEvent()
void RadioControlEvent (void(*)(void) frame_handler)
Definition at line 231 of file intermcu_ap.c.
References intermcu_t::device, intermcu_t::enabled, imcu_msg_buf, intermcu, intermcu_parse_msg(), intermcu_t::msg_available, and intermcu_t::transport.
send_status()
static void send_status (struct transport_tx * trans, struct link_device * dev) static
Definition at line 62 of file intermcu_ap.c.
References Electrical::current, dev, fbw_status_t::electrical, fbw_status, fbw_status_t::frame_rate, fbw_status_t::mode, fbw_status_t::rc_status, and Electrical::vsupply.
Referenced by intermcu_init().
Variable Documentation
fbw_status
struct fbw_status_t fbw_status static
Definition at line 47 of file intermcu_ap.c.
Referenced by intermcu_parse_msg(), and send_status().
imcu_msg_buf
uint8_t imcu_msg_buf[128]
The InterMCU message buffer.
Definition at line 46 of file intermcu_ap.c.
Referenced by intermcu_parse_msg(), and RadioControlEvent().
intermcu
struct intermcu_t intermcu
Initial value:
= {
  .device = (&((INTERMCU_LINK).device)),
  .enabled = true,
  .msg_available = false,
}
Definition at line 41 of file intermcu_ap.c.
Referenced by intermcu_init(), intermcu_parse_msg(), intermcu_periodic(), intermcu_send_spektrum_bind(), intermcu_set_actuators(), intermcu_set_enabled(), and RadioControlEvent().