Paparazzi UAS: sw/airborne/boards/bebop/isp/libisp.h File Reference
libisp.h File Reference
#include "reg_avi.h"
#include "modules/computer_vision/lib/v4l/v4l2.h"
Data Structures
struct libisp_context
struct libisp_config
struct isp_yuv_stats_t
Macros
#define AVI_DEFINE_NODE(EXPANDER)
#define EXPAND_AS_ENUM(_node) _node,
#define EXPAND_AS_PROTOTYPE(_node)
Enumerations
enum { ISP_NODE_NR }
Functions
int configure_isp (struct v4l2_device *dev)
int isp_get_statistics_yuv (struct isp_yuv_stats_t *yuv_stats)
int isp_request_statistics_yuv_window (uint16_t x_start, uint16_t x_end, uint16_t y_start, uint16_t y_end, uint16_t x_odd_inc, uint16_t y_odd_inc)
Data Structure Documentation
libisp_context
struct libisp_context
Definition at line 50 of file libisp.h.
Data Fields
unsigned long avi_base
int devmem
unsigned offsets[ISP_NODE_NR]
libisp_config
struct libisp_config
Definition at line 57 of file libisp.h.
Data Fields
struct avi_isp_bayer_regs bayer < Chromatic abberation (Disabled for now)
Demosaicking parameters
struct avi_isp_chain_bayer_inter_regs bayer_inter Enable or disable bayer ISP functions by bypassing them.
struct avi_isp_chain_yuv_inter_regs chain_yuv_inter YUV chain bypass configuration (enable/disable features)
struct avi_isp_chroma_regs chroma Color space conversion.
struct avi_isp_color_correction_regs color_correction Color correction parameters.
struct avi_isp_dead_pixel_correction_regs dead_pixel_correction Dead pixel correction (disabled)
struct avi_isp_denoising_regs denoising Denoising parameters.
struct avi_isp_edge_enhancement_color_reduction_filter_regs eecrf Edge enhancement + Color reduction.
struct avi_isp_edge_enhancement_color_reduction_filter_ee_lut_regs eecrf_lut Edge enhancement + Color correction lut.
struct avi_isp_gamma_corrector_regs gamma_corrector Gamma corrector (Curves)
struct avi_isp_gamma_corrector_bv_lut_regs gc_bv_lut Gamma corrector BV lut.
struct avi_isp_gamma_corrector_gu_lut_regs gc_gu_lut Gamma corrector GU lut.
struct avi_isp_gamma_corrector_ry_lut_regs gc_ry_lut Gamma corrector RY lut.
struct avi_isp_green_imbalance_regs green_imbalance Green imbalance correction.
struct avi_isp_green_imbalance_green_blue_coeff_mem_regs grim_gb Green imbalance GB coefficients.
struct avi_isp_green_imbalance_green_red_coeff_mem_regs grim_gr Green imbalance GR coefficients.
struct avi_isp_lens_shading_correction_regs lens_shading_correction Lens shade correction.
struct avi_isp_lens_shading_correction_blue_coeff_mem_regs lsc_blue_coeffs Lens shade correction blue coefficients.
struct avi_isp_lens_shading_correction_green_coeff_mem_regs lsc_green_coeffs Lens shade correction green coefficients.
struct avi_isp_lens_shading_correction_red_coeff_mem_regs lsc_red_coeffs Lens shade correction red coefficients.
struct avi_isp_pedestal_regs pedestal Pedestral parameters (substract from pixels)
struct avi_isp_statistics_bayer_regs statistics_bayer Statistics bayer parameters.
struct avi_isp_statistics_yuv_regs statistics_yuv YUV statistics parameters.
struct avi_isp_vlformat_32to40_regs vlformat_32to40 Conversion factor (10bit to 10bit default)
struct avi_isp_vlformat_40to32_regs vlformat_40to32 Conversion factor (10bit to 10bit default)
isp_yuv_stats_t
struct isp_yuv_stats_t
Definition at line 91 of file libisp.h.
Data Fields
uint32_t ae_histogram_Y[256]
uint32_t awb_nb_grey_pixels
uint32_t awb_sum_U
uint32_t awb_sum_V
uint32_t awb_sum_Y
uint32_t nb_valid_Y
Macro Definition Documentation
AVI_DEFINE_NODE
#define AVI_DEFINE_NODE (EXPANDER)
Definition at line 7 of file libisp.h.
EXPAND_AS_ENUM
#define EXPAND_AS_ENUM (_node) _node,
Definition at line 41 of file libisp.h.
EXPAND_AS_PROTOTYPE
#define EXPAND_AS_PROTOTYPE (_node)
Value:
  void avi_isp_ ## _node ## _set_registers(struct libisp_context *, \
      struct avi_isp_ ## _node ## _regs const *regs);   \
  void avi_isp_ ## _node ## _get_registers(struct libisp_context *, \
      struct avi_isp_ ## _node ## _regs *regs);
Definition at line 106 of file libisp.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
ISP_NODE_NR
Definition at line 44 of file libisp.h.
Function Documentation
configure_isp()
int configure_isp (struct v4l2_device * dev)
Definition at line 177 of file libisp.c.
References libisp_config::bayer, libisp_config::bayer_inter, libisp_config::chain_yuv_inter, libisp_config::chroma, libisp_config::color_correction, libisp_config::dead_pixel_correction, libisp_config::denoising, dev, libisp_config::eecrf, libisp_config::eecrf_lut, libisp_config::gamma_corrector, libisp_config::gc_bv_lut, libisp_config::gc_gu_lut, libisp_config::gc_ry_lut, libisp_config::green_imbalance, libisp_config::grim_gb, libisp_config::grim_gr, isp_config, isp_ctx, libisp_config::lens_shading_correction, libisp_config::lsc_blue_coeffs, libisp_config::lsc_green_coeffs, libisp_config::lsc_red_coeffs, open_isp_fd(), libisp_config::pedestal, libisp_config::statistics_bayer, libisp_config::statistics_yuv, libisp_config::vlformat_32to40, and libisp_config::vlformat_40to32.
Referenced by video_thread_function().
isp_get_statistics_yuv()
int isp_get_statistics_yuv (struct isp_yuv_stats_t * yuv_stats)
Definition at line 261 of file libisp.c.
References isp_yuv_stats_t::ae_histogram_Y, avi_isp_statistics_yuv_ae_histogram_y_regs::ae_histogram_y, avi_isp_statistics_yuv_regs::ae_nb_valid_y, AVI_ISP_STAT_YUV_MAX_WAIT, isp_yuv_stats_t::awb_nb_grey_pixels, avi_isp_statistics_yuv_regs::awb_nb_grey_pixels, isp_yuv_stats_t::awb_sum_U, avi_isp_statistics_yuv_regs::awb_sum_u, isp_yuv_stats_t::awb_sum_V, avi_isp_statistics_yuv_regs::awb_sum_v, isp_yuv_stats_t::awb_sum_Y, avi_isp_statistics_yuv_regs::awb_sum_y, curWait, libisp_context::devmem, isp_config, isp_ctx, isp_set_statistics_yuv_window(), avi_isp_statistics_yuv_regs::measure_req, avi_isp_statistics_yuv_regs::measure_status, isp_yuv_stats_t::nb_valid_Y, libisp_config::statistics_yuv, and VERBOSE_PRINT.
Referenced by update_ae_awb().
isp_request_statistics_yuv_window()
int isp_request_statistics_yuv_window (uint16_t x_start, uint16_t x_end, uint16_t y_start, uint16_t y_end, uint16_t x_odd_inc, uint16_t y_odd_inc)
Definition at line 214 of file libisp.c.
References requestWindow, and VERBOSE_PRINT.
Referenced by mt9f002_init(), and mt9f002_setting_update_resolution().