Paparazzi UAS: sw/airborne/modules/intermcu/link_mcu_can.c File Reference
link_mcu_can.c File Reference
#include "modules/intermcu/link_mcu_can.h"
#include "mcu_periph/can.h"
#include "led.h"
#include "modules/core/commands.h"
Macros
#define MSG_INTERMCU_COMMAND_MASTER_ID 0x01
#define MSG_INTERMCU_COMMAND_EXTRA_ID 0x02
#define MSG_INTERMCU_RADIO_LOW_ID 0x04
#define MSG_INTERMCU_RADIO_HIGH_ID 0x05
#define MSG_INTERMCU_TRIM_ID 0x09
#define MSG_INTERMCU_FBW_STATUS_ID 0x10
#define INTERMCU_COMMAND(_intermcu_payload, nr) (pprz_t)((uint16_t)(*((uint8_t*)_intermcu_payload+0+(2*(nr)))|*((uint8_t*)_intermcu_payload+1+(2*(nr)))<<8))
Functions
void link_mcu_on_can_msg (uint32_t id, uint8_t *data, int len)
void link_mcu_init (void)
void link_mcu_event_task (void)
Variables
union {
uint8_t data [8]
pprz_t cmd [4]
} imcu_cmd_mstr
union {
uint8_t data [8]
pprz_t cmd [4]
} imcu_cmd_ext
union {
uint8_t data [8]
pprz_t cmd [4]
} imcu_chan1
union {
uint8_t data [8]
pprz_t cmd [4]
} imcu_chan2
union {
uint8_t data [8]
pprz_t cmd [4]
} imcu_trim
struct link_mcu_msg link_mcu_from_ap_msg
struct link_mcu_msg link_mcu_from_fbw_msg
Macro Definition Documentation
INTERMCU_COMMAND
#define INTERMCU_COMMAND (_intermcu_payload, nr) (pprz_t)((uint16_t)(*((uint8_t*)_intermcu_payload+0+(2*(nr)))|*((uint8_t*)_intermcu_payload+1+(2*(nr)))<<8))
Definition at line 50 of file link_mcu_can.c.
MSG_INTERMCU_COMMAND_EXTRA_ID
#define MSG_INTERMCU_COMMAND_EXTRA_ID 0x02
Definition at line 35 of file link_mcu_can.c.
MSG_INTERMCU_COMMAND_MASTER_ID
#define MSG_INTERMCU_COMMAND_MASTER_ID 0x01
Definition at line 34 of file link_mcu_can.c.
MSG_INTERMCU_FBW_STATUS_ID
#define MSG_INTERMCU_FBW_STATUS_ID 0x10
Definition at line 42 of file link_mcu_can.c.
MSG_INTERMCU_RADIO_HIGH_ID
#define MSG_INTERMCU_RADIO_HIGH_ID 0x05
Definition at line 38 of file link_mcu_can.c.
MSG_INTERMCU_RADIO_LOW_ID
#define MSG_INTERMCU_RADIO_LOW_ID 0x04
Definition at line 37 of file link_mcu_can.c.
MSG_INTERMCU_TRIM_ID
#define MSG_INTERMCU_TRIM_ID 0x09
Definition at line 40 of file link_mcu_can.c.
Function Documentation
link_mcu_event_task()
void link_mcu_event_task (void)
Definition at line 229 of file link_mcu_can.c.
Referenced by event_task_ap().
link_mcu_init()
void link_mcu_init (void)
Definition at line 216 of file link_mcu_can.c.
Referenced by init_fbw().
link_mcu_on_can_msg()
void link_mcu_on_can_msg (uint32_t id, uint8_t * data, int len)
Definition at line 57 of file link_mcu_can.c.
References ap_state, f, fbw_state, inter_mcu_received_ap, inter_mcu_received_fbw, INTERMCU_COMMAND, LED_TOGGLE, MSG_INTERMCU_COMMAND_EXTRA_ID, MSG_INTERMCU_COMMAND_MASTER_ID, MSG_INTERMCU_FBW_STATUS_ID, MSG_INTERMCU_RADIO_HIGH_ID, MSG_INTERMCU_RADIO_LOW_ID, MSG_INTERMCU_TRIM_ID, and RADIO_CONTROL_NB_CHANNEL.
Referenced by link_mcu_init().
Variable Documentation
imcu_chan1
union { ... } imcu_chan1
imcu_chan2
union { ... } imcu_chan2
imcu_cmd_ext
union { ... } imcu_cmd_ext
imcu_cmd_mstr
union { ... } imcu_cmd_mstr
imcu_trim
union { ... } imcu_trim
link_mcu_from_ap_msg
struct link_mcu_msg link_mcu_from_ap_msg
Definition at line 176 of file link_mcu_can.c.
link_mcu_from_fbw_msg
struct link_mcu_msg link_mcu_from_fbw_msg
Definition at line 177 of file link_mcu_can.c.