Paparazzi UAS: sw/airborne/firmwares/rotorcraft/main.h File Reference
main.h File Reference
Macros
#define STATIC_INLINE static inline
Functions
STATIC_INLINE void main_init (void)
Main initialization.
STATIC_INLINE void main_event (void)
STATIC_INLINE void handle_periodic_tasks (void)
STATIC_INLINE void main_periodic (void)
STATIC_INLINE void telemetry_periodic (void)
STATIC_INLINE void failsafe_check (void)
Detailed Description
Rotorcraft main loop.
Definition in file main.h.
Macro Definition Documentation
STATIC_INLINE
#define STATIC_INLINE static inline
Definition at line 34 of file main.h.
Function Documentation
failsafe_check()
STATIC_INLINE void failsafe_check (void)
Definition at line 201 of file main_ap.c.
handle_periodic_tasks()
STATIC_INLINE void handle_periodic_tasks (void)
Definition at line 128 of file main_ap.c.
Referenced by main(), nps_autopilot_run_step(), thd_ap(), and thd_fbw().
main_event()
static void main_event (void) inline
Definition at line 103 of file setup_actuators.c.
main_init()
static void main_init (void) inline
Main initialization.
Definition at line 71 of file setup_actuators.c.
main_periodic()
static void main_periodic (void) inline
Definition at line 90 of file setup_actuators.c.
telemetry_periodic()
STATIC_INLINE void telemetry_periodic (void)
Definition at line 177 of file main_ap.c.