Paparazzi UAS: sw/airborne/modules/mission/mission_common.c File Reference
mission_common.c File Reference
messages parser for mission interface
#include "modules/mission/mission_common.h"
#include <string.h>
#include "generated/flight_plan.h"
#include "generated/airframe.h"
#include "modules/datalink/datalink.h"
#include "modules/datalink/downlink.h"
Macros
#define MISSION_CHECK_UNIQUE_ID TRUE
Functions
void mission_init (void)
Init mission structure.
bool mission_insert (enum MissionInsertMode insert, struct _mission_element *element)
Insert a mission element according to the insertion mode.
bool mission_register (mission_custom_cb cb, char *type)
Register a new navigation or action callback function.
static struct _mission_registered * mission_get_registered (char *type)
struct _mission_element * mission_get_from_index (uint8_t index)
Get mission element by index.
bool mission_element_convert (struct _mission_element *el)
Convert mission element's points format if needed.
struct _mission_element * mission_get (void)
Get current mission element.
void mission_status_report (void)
Report mission status.
int mission_parse_GOTO_WP (uint8_t *buf)
Parsing functions called when a mission message is received.
int mission_parse_GOTO_WP_LLA (uint8_t *buf)
int mission_parse_CIRCLE (uint8_t *buf)
int mission_parse_CIRCLE_LLA (uint8_t *buf)
int mission_parse_SEGMENT (uint8_t *buf)
int mission_parse_SEGMENT_LLA (uint8_t *buf)
int mission_parse_PATH (uint8_t *buf)
int mission_parse_PATH_LLA (uint8_t *buf)
int mission_parse_CUSTOM (uint8_t *buf)
int mission_parse_UPDATE (uint8_t *buf)
int mission_parse_GOTO_MISSION (uint8_t *buf)
int mission_parse_NEXT_MISSION (uint8_t *buf)
int mission_parse_END_MISSION (uint8_t *buf)
Variables
struct _mission mission = { 0 }
Detailed Description
messages parser for mission interface
Definition in file mission_common.c.
Macro Definition Documentation
MISSION_CHECK_UNIQUE_ID
#define MISSION_CHECK_UNIQUE_ID TRUE
Definition at line 37 of file mission_common.c.
Function Documentation
mission_element_convert()
bool mission_element_convert (struct _mission_element * el)
Convert mission element's points format if needed.
Parameters
el pointer to the mission element
Returns
return TRUE if conversion is succesful, FALSE otherwise
Definition at line 158 of file mission_common.c.
Referenced by mission_insert().
mission_get()
struct _mission_element* mission_get (void)
Get current mission element.
Returns
return a pointer to the next mission element or NULL if no more elements
Definition at line 162 of file mission_common.c.
References _mission::current_idx, _mission::elements, _mission::insert_idx, and mission.
Referenced by mission_run().
mission_get_from_index()
struct _mission_element* mission_get_from_index (uint8_t index)
Get mission element by index.
Returns
return a pointer to the mission element or NULL if no more elements
Definition at line 142 of file mission_common.c.
References _mission::current_idx, _mission::elements, _mission_element::index, _mission::insert_idx, mission, and MISSION_ELEMENT_NB.
Referenced by mission_insert(), and mission_parse_UPDATE().
mission_get_registered()
static struct _mission_registered* mission_get_registered (char * type) static
Definition at line 131 of file mission_common.c.
References mission, MISSION_REGISTER_NB, _mission::registered, type(), and _mission_registered::type.
Referenced by mission_parse_CUSTOM().
mission_init()
void mission_init (void)
Init mission structure.
Definition at line 42 of file mission_common.c.
References _mission::current_idx, _mission::element_time, _mission::insert_idx, and mission.
mission_insert()
bool mission_insert (enum MissionInsertMode insert, struct _mission_element * element)
Insert a mission element according to the insertion mode.
Parameters
insert insertion mode
element mission element structure
Returns
return TRUE if insertion is succesful, FALSE otherwise
Definition at line 60 of file mission_common.c.
References Append, _mission::current_idx, _mission::element_time, _mission::elements, _mission_element::index, _mission::insert_idx, mission, mission_element_convert(), MISSION_ELEMENT_NB, mission_get_from_index(), Prepend, ReplaceAll, ReplaceCurrent, and ReplaceNexts.
Referenced by mission_parse_CIRCLE(), mission_parse_CIRCLE_LLA(), mission_parse_CUSTOM(), mission_parse_GOTO_WP(), mission_parse_GOTO_WP_LLA(), mission_parse_PATH(), mission_parse_PATH_LLA(), mission_parse_SEGMENT(), and mission_parse_SEGMENT_LLA().
mission_parse_CIRCLE()
int mission_parse_CIRCLE (uint8_t * buf)
Definition at line 235 of file mission_common.c.
References _mission_element::duration, _mission_element::element, _mission_element::index, mission_insert(), MissionCircle, and _mission_element::type.
mission_parse_CIRCLE_LLA()
int mission_parse_CIRCLE_LLA (uint8_t * buf)
Definition at line 253 of file mission_common.c.
References LlaCoor_i::alt, _mission_element::duration, _mission_element::element, _mission_element::index, LlaCoor_i::lat, LlaCoor_i::lon, mission_insert(), mission_point_of_lla(), MissionCircle, and _mission_element::type.
mission_parse_CUSTOM()
int mission_parse_CUSTOM (uint8_t * buf)
Definition at line 391 of file mission_common.c.
References _mission_element::duration, _mission_element::element, _mission_element::index, mission_get_registered(), mission_insert(), MissionCustom, and _mission_element::type.
mission_parse_END_MISSION()
int mission_parse_END_MISSION (uint8_t * buf)
Definition at line 473 of file mission_common.c.
References _mission::current_idx, _mission::element_time, _mission::insert_idx, and mission.
mission_parse_GOTO_MISSION()
int mission_parse_GOTO_MISSION (uint8_t * buf)
Definition at line 445 of file mission_common.c.
References _mission::current_idx, _mission::element_time, mission, and MISSION_ELEMENT_NB.
mission_parse_GOTO_WP()
int mission_parse_GOTO_WP (uint8_t * buf)
Parsing functions called when a mission message is received.
Definition at line 197 of file mission_common.c.
References _mission_element::duration, _mission_element::element, _mission_element::index, mission_insert(), MissionWP, and _mission_element::type.
mission_parse_GOTO_WP_LLA()
int mission_parse_GOTO_WP_LLA (uint8_t * buf)
Definition at line 214 of file mission_common.c.
References LlaCoor_i::alt, _mission_element::duration, _mission_element::element, _mission_element::index, LlaCoor_i::lat, LlaCoor_i::lon, mission_insert(), mission_point_of_lla(), MissionWP, and _mission_element::type.
mission_parse_NEXT_MISSION()
int mission_parse_NEXT_MISSION (uint8_t * buf)
Definition at line 460 of file mission_common.c.
References _mission::current_idx, _mission::element_time, _mission::insert_idx, mission, and MISSION_ELEMENT_NB.
mission_parse_PATH()
int mission_parse_PATH (uint8_t * buf)
Definition at line 320 of file mission_common.c.
References _mission_element::duration, _mission_element::element, _mission_element::index, mission_insert(), MISSION_PATH_NB, MissionPath, and _mission_element::type.
mission_parse_PATH_LLA()
int mission_parse_PATH_LLA (uint8_t * buf)
Definition at line 352 of file mission_common.c.
References LlaCoor_i::alt, _mission_element::duration, _mission_element::element, _mission_element::index, LlaCoor_i::lat, LlaCoor_i::lon, mission_insert(), MISSION_PATH_NB, mission_point_of_lla(), MissionPath, and _mission_element::type.
mission_parse_SEGMENT()
int mission_parse_SEGMENT (uint8_t * buf)
Definition at line 275 of file mission_common.c.
References _mission_element::duration, _mission_element::element, _mission_element::index, mission_insert(), MissionSegment, and _mission_element::type.
mission_parse_SEGMENT_LLA()
int mission_parse_SEGMENT_LLA (uint8_t * buf)
Definition at line 295 of file mission_common.c.
References LlaCoor_i::alt, _mission_element::duration, _mission_element::element, _mission_element::index, LlaCoor_i::lat, LlaCoor_i::lon, mission_insert(), mission_point_of_lla(), MissionSegment, and _mission_element::type.
mission_parse_UPDATE()
int mission_parse_UPDATE (uint8_t * buf)
Definition at line 413 of file mission_common.c.
References _mission_element::duration, _mission_element::element, f, MISSION_CUSTOM_MAX, mission_get_from_index(), MissionCircle, MissionCustom, MissionPath, MissionSegment, MissionUpdate, MissionWP, and _mission_element::type.
mission_register()
bool mission_register (mission_custom_cb cb, char * type)
Register a new navigation or action callback function.
Parameters
cb callback f(nb, param array)
type string identifier with 5 characters max (+ 1 '\0' char)
Returns
return TRUE if register is succesful, FALSE otherwise
Definition at line 115 of file mission_common.c.
References _mission_registered::cb, mission, MISSION_REGISTER_NB, MISSION_TYPE_SIZE, _mission::registered, type(), and _mission_registered::type.
Referenced by nav_flower_init(), nav_lace_init(), nav_line_init(), nav_rosette_init(), nav_spiral_3D_init(), and nav_trinity_init().
mission_status_report()
void mission_status_report (void)
Report mission status.
Send mission status over datalink
Definition at line 172 of file mission_common.c.
References _mission::current_idx, DefaultChannel, DefaultDevice, _mission_element::duration, _mission::element_time, _mission::elements, _mission_element::index, _mission::insert_idx, mission, and MISSION_ELEMENT_NB.
Variable Documentation
mission
struct _mission mission = { 0 }
Definition at line 40 of file mission_common.c.
Referenced by mission_get(), mission_get_from_index(), mission_get_registered(), mission_init(), mission_insert(), mission_nav_circle(), mission_parse_END_MISSION(), mission_parse_GOTO_MISSION(), mission_parse_NEXT_MISSION(), mission_register(), mission_run(), and mission_status_report().