Paparazzi UAS: sw/airborne/peripherals/mpl3115.c File Reference
mpl3115.c File Reference
#include "peripherals/mpl3115.h"
#include "std.h"
Functions
void mpl3115_init (struct Mpl3115 *mpl, struct i2c_periph *i2c_p, uint8_t addr)
static void mpl3115_send_config (struct Mpl3115 *mpl)
void mpl3115_configure (struct Mpl3115 *mpl)
void mpl3115_read (struct Mpl3115 *mpl)
void mpl3115_event (struct Mpl3115 *mpl)
void mpl3115_periodic (struct Mpl3115 *mpl)
Detailed Description
Driver for MPL3115A2 baro sensor.
Definition in file mpl3115.c.
Function Documentation
mpl3115_configure()
void mpl3115_configure (struct Mpl3115 * mpl)
Definition at line 81 of file mpl3115.c.
References I2CTransDone, I2CTransSuccess, Mpl3115::init_status, mpl3115_send_config(), MPL_CONF_UNINIT, i2c_transaction::status, and Mpl3115::trans.
Referenced by mpl3115_periodic().
mpl3115_event()
void mpl3115_event (struct Mpl3115 * mpl)
Definition at line 107 of file mpl3115.c.
References Mpl3115::alt_mode, Mpl3115::altitude, i2c_transaction::buf, Mpl3115::data_available, I2CTransDone, I2CTransFailed, I2CTransSuccess, Mpl3115::init_status, Mpl3115::initialized, mpl3115_send_config(), MPL_CONF_UNINIT, Mpl3115::pressure, Mpl3115::raw_mode, Mpl3115::req_trans, i2c_transaction::status, Mpl3115::temperature, and Mpl3115::trans.
Referenced by apogee_baro_event(), and baro_mpl3115_read_event().
mpl3115_init()
void mpl3115_init (struct Mpl3115 * mpl, struct i2c_periph * i2c_p, uint8_t addr)
Definition at line 31 of file mpl3115.c.
References Mpl3115::alt_mode, Mpl3115::altitude, Mpl3115::i2c_p, I2CTransDone, Mpl3115::init_status, Mpl3115::initialized, MPL_CONF_UNINIT, Mpl3115::pressure, Mpl3115::raw_mode, Mpl3115::req_trans, i2c_transaction::slave_addr, i2c_transaction::status, Mpl3115::temperature, and Mpl3115::trans.
Referenced by baro_init(), and baro_mpl3115_init().
mpl3115_periodic()
void mpl3115_periodic (struct Mpl3115 * mpl)
Definition at line 153 of file mpl3115.c.
References Mpl3115::initialized, mpl3115_configure(), and mpl3115_read().
Referenced by baro_mpl3115_read_periodic(), and baro_periodic().
mpl3115_read()
void mpl3115_read (struct Mpl3115 * mpl)
Definition at line 92 of file mpl3115.c.
References Mpl3115::alt_mode, i2c_transaction::buf, Mpl3115::i2c_p, i2c_transceive(), i2c_transmit(), I2CTransDone, Mpl3115::initialized, MPL3115_OST_BIT, MPL3115_OVERSAMPLING, MPL3115_REG_CTRL_REG1, MPL3115_REG_STATUS, Mpl3115::raw_mode, Mpl3115::req_trans, i2c_transaction::slave_addr, i2c_transaction::status, and Mpl3115::trans.
Referenced by mpl3115_periodic().
mpl3115_send_config()
static void mpl3115_send_config (struct Mpl3115 * mpl) static
Definition at line 55 of file mpl3115.c.
References Mpl3115::alt_mode, i2c_transaction::buf, Mpl3115::i2c_p, i2c_transmit(), I2CTransDone, Mpl3115::init_status, Mpl3115::initialized, MPL3115_OVERSAMPLING, MPL3115_PT_DATA_CFG, MPL3115_REG_CTRL_REG1, MPL3115_REG_PT_DATA_CFG, MPL_CONF_CTRL1, MPL_CONF_DONE, MPL_CONF_PT_DATA, Mpl3115::raw_mode, i2c_transaction::slave_addr, i2c_transaction::status, and Mpl3115::trans.
Referenced by mpl3115_configure(), and mpl3115_event().