Paparazzi UAS: sw/airborne/modules/nav/nav_skid_landing.h File Reference
nav_skid_landing.h File Reference
Landing on skidpads See video of the landing: https://www.youtube.com/watch?v=aYrB7s3oeX4 Standard landing procedure: 1) circle down passing AF waypoint (from left or right) 2) once low enough follow line to TD waypoint 3) once low enough flare.
#include "std.h"
#include "paparazzi.h"
Functions
void nav_skid_landing_setup (uint8_t afwp, uint8_t tdwp, float radius)
bool nav_skid_landing_run (void)
void nav_skid_landing_glide (uint8_t from_wp, uint8_t to_wp)
Detailed Description
Landing on skidpads See video of the landing: https://www.youtube.com/watch?v=aYrB7s3oeX4 Standard landing procedure: 1) circle down passing AF waypoint (from left or right) 2) once low enough follow line to TD waypoint 3) once low enough flare.
Use this in your airfame config file: <section name="LANDING" prefix="SKID_LANDING_"> <define name="AF_HEIGHT" value="50" unit="m"> <define name="FINAL_HEIGHT" value="50" unit="m"> <define name="FINAL_STAGE_TIME" value="10" unit="s"> </section>
Also define: V_CTL_LANDING_THROTTLE_PGAIN - landing throttle P gain V_CTL_LANDING_THROTTLE_IGAIN - landing throttle I gain V_CTL_LANDING_THROTTLE_MAX - max landing throttle V_CTL_LANDING_DESIRED_SPEED - desired landing speed V_CTL_LANDING_PITCH_PGAIN - landing P gain V_CTL_LANDING_PITCH_IGAIN - landing I gain V_CTL_LANDING_PITCH_LIMITS - pitch limits during landing V_CTL_LANDING_PITCH_FLARE - flare P gain V_CTL_LANDING_ALT_THROTTLE_KILL - AGL to kill throttle during landing V_CTL_LANDING_ALT_FLARE - AGL to initiate final flare
to properly use landing control loop
Definition in file nav_skid_landing.h.
Function Documentation
nav_skid_landing_glide()
void nav_skid_landing_glide (uint8_t from_wp, uint8_t to_wp)
Definition at line 182 of file nav_skid_landing.c.
References point::a, distance_equation(), nav_altitude, stateGetPositionEnu_f(), stateGetPositionUtm_f(), v_ctl_mode, V_CTL_MODE_LANDING, waypoints, point::x, FloatVect2::x, EnuCoor_f::x, point::y, FloatVect2::y, and EnuCoor_f::y.
Referenced by nav_skid_landing_run().
nav_skid_landing_run()
bool nav_skid_landing_run (void)
Definition at line 127 of file nav_skid_landing.c.
References Approach, approach_quadrant, autopilot_set_kill_throttle(), autopilot_throttle_killed(), aw_waypoint, CircleDown, Final, land_circle, land_circle_quadrant, land_radius, LandingWait, nav_circle_XY(), nav_init_stage(), nav_route_xy(), nav_skid_landing_glide(), NavCircleCount, NavQdrCloseTo, NavVerticalAltitudeMode, NavVerticalAutoThrottleMode, skid_landing_status, stateGetPositionUtm_f(), td_waypoint, TRUE, waypoints, FloatVect2::x, and FloatVect2::y.
nav_skid_landing_setup()
void nav_skid_landing_setup (uint8_t afwp, uint8_t tdwp, float radius)
Definition at line 94 of file nav_skid_landing.c.
References UtmCoor_f::alt, approach_quadrant, aw_waypoint, CircleDown, final_land_altitude, final_land_count, land_app_alt, land_circle, land_circle_quadrant, land_radius, SKID_LANDING_FINAL_HEIGHT, skid_landing_status, stateGetPositionUtm_f(), td_waypoint, waypoints, point::x, FloatVect2::x, point::y, and FloatVect2::y.