Paparazzi UAS: sw/airborne/modules/nav/nav_line.h File Reference
nav_line.h File Reference
#include "std.h"
Functions
void nav_line_init (void)
void nav_line_setup (void)
bool nav_line_run (uint8_t wp1, uint8_t wp2, float radius)
Detailed Description
Fixedwing navigation along a line with nice U-turns.
Definition in file nav_line.h.
Function Documentation
nav_line_init()
void nav_line_init (void)
Definition at line 56 of file nav_line.c.
References mission_register().
nav_line_run()
bool nav_line_run (uint8_t wp1, uint8_t wp2, float radius)
Definition at line 68 of file nav_line.c.
References point::a, CARROT, LQC11, LQC12, LQC21, LQC22, LR12, LR21, LTC1, LTC2, nav_circle_XY(), nav_init_stage(), NavApproachingFrom, NavQdrCloseTo, NavSegment, NavVerticalAltitudeMode, NavVerticalAutoThrottleMode, WaypointAlt, waypoints, WaypointX, WaypointY, point::x, and point::y.
nav_line_setup()
void nav_line_setup (void)
Definition at line 63 of file nav_line.c.
References LR12.