Paparazzi UAS: sw/airborne/filters/notch_filter.h File Reference
notch_filter.h File Reference
Second order notch filter.
#include "std.h"
Data Structures
struct SecondOrderNotchFilter
Functions
static void notch_filter_set_sampling_frequency (struct SecondOrderNotchFilter *filter, uint16_t frequency)
Set sampling frequency of the notch filter.
static void notch_filter_set_bandwidth (struct SecondOrderNotchFilter *filter, float bandwidth)
Set bandwidth of the notch filter.
static void notch_filter_set_filter_frequency (struct SecondOrderNotchFilter *filter, float frequency)
Set notch filter frequency in Hz.
static void notch_filter_update (struct SecondOrderNotchFilter *filter, int32_t *input_signal, int32_t *output_signal)
Notch filter propagate.
static void notch_filter_init (struct SecondOrderNotchFilter *filter, float cutoff_frequency, float bandwidth, uint16_t sample_frequency)
Initialize second order notch filter.
Detailed Description
Second order notch filter.
Definition in file notch_filter.h.
Data Structure Documentation
SecondOrderNotchFilter
struct SecondOrderNotchFilter
Definition at line 32 of file notch_filter.h.
Data Fields
float costheta
float d2
float Ts
int32_t xn1
int32_t xn2
int32_t yn1
int32_t yn2
Function Documentation
notch_filter_init()
static void notch_filter_init (struct SecondOrderNotchFilter * filter, float cutoff_frequency, float bandwidth, uint16_t sample_frequency) inline static
Initialize second order notch filter.
Discrete implementation: y[n] = b * y[n-1] - d^2 * y[n-2] + a * x[n] - b * x[n-1] + a * x[n-2]
Parameters
cutoff_frequency frequency to attenuate [Hz]
bandwidth bandwidth of the filter [Hz]
sample_frequency frequency at which the filter is updated
Definition at line 101 of file notch_filter.h.
References notch_filter_set_bandwidth(), notch_filter_set_filter_frequency(), notch_filter_set_sampling_frequency(), SecondOrderNotchFilter::xn1, SecondOrderNotchFilter::xn2, SecondOrderNotchFilter::yn1, and SecondOrderNotchFilter::yn2.
Referenced by stabilization_attitude_init().
notch_filter_set_bandwidth()
static void notch_filter_set_bandwidth (struct SecondOrderNotchFilter * filter, float bandwidth) inline static
Set bandwidth of the notch filter.
Parameters
bandwidth bandwidth of the filter [Hz]
Definition at line 55 of file notch_filter.h.
References SecondOrderNotchFilter::d2, and SecondOrderNotchFilter::Ts.
Referenced by notch_filter_init().
notch_filter_set_filter_frequency()
static void notch_filter_set_filter_frequency (struct SecondOrderNotchFilter * filter, float frequency) inline static
Set notch filter frequency in Hz.
Parameters
frequency to attenuate [Hz]
Definition at line 65 of file notch_filter.h.
References SecondOrderNotchFilter::costheta, and SecondOrderNotchFilter::Ts.
Referenced by indi_apply_notch_filters(), and notch_filter_init().
notch_filter_set_sampling_frequency()
static void notch_filter_set_sampling_frequency (struct SecondOrderNotchFilter * filter, uint16_t frequency) inline static
Set sampling frequency of the notch filter.
Parameters
frequency frequency at which the filter is updated
Definition at line 46 of file notch_filter.h.
References SecondOrderNotchFilter::Ts.
Referenced by notch_filter_init().
notch_filter_update()
static void notch_filter_update (struct SecondOrderNotchFilter * filter, int32_t * input_signal, int32_t * output_signal) inline static
Notch filter propagate.
Discrete implementation: y[n] = b * y[n-1] - d^2 * y[n-2] + a * x[n] - b * x[n-1] + a * x[n-2]
Parameters
input_signal input x[n]
output_signal output y[n]
Definition at line 79 of file notch_filter.h.
References b, SecondOrderNotchFilter::costheta, SecondOrderNotchFilter::d2, SecondOrderNotchFilter::xn1, SecondOrderNotchFilter::xn2, SecondOrderNotchFilter::yn1, and SecondOrderNotchFilter::yn2.
Referenced by indi_apply_notch_filters().