Paparazzi UAS: sw/simulator/nps/nps_ivy.h File Reference
nps_ivy.h File Reference
#include "nps_fdm.h"
#include "nps_sensors.h"
Functions
void nps_ivy_init (char *ivy_bus)
void nps_ivy_display (struct NpsFdm *fdm_ivy, struct NpsSensors *sensors_ivy)
void nps_ivy_send_WORLD_ENV_REQ (void)
Variables
bool nps_ivy_send_world_env
Function Documentation
nps_ivy_display()
void nps_ivy_display (struct NpsFdm * fdm_ivy, struct NpsSensors * sensors_ivy)
Definition at line 205 of file nps_ivy.c.
References NpsSensors::accel, NpsFdm::agl, LlaCoor_d::alt, NpsSensorGyro::bias_initial, NpsSensorGyro::bias_random_walk_value, NpsFdm::body_ecef_rotvel, double_quat_vmult(), NpsSensors::gyro, NpsFdm::hmsl, LlaCoor_d::lat, NpsFdm::lla_pos_geoc, NpsFdm::lla_pos_geod, NpsFdm::lla_pos_pprz, LlaCoor_d::lon, NpsFdm::ltp_h, NpsFdm::ltp_to_body_eulers, NpsFdm::ltp_to_body_quat, NpsFdm::ltpprz_ecef_accel, NpsFdm::ltpprz_ecef_vel, NpsFdm::ltpprz_pos, NpsSensorAccel::neutral, nps_ivy_send_world_env, nps_ivy_send_WORLD_ENV_REQ(), DoubleRates::p, DoubleEulers::phi, DoubleEulers::psi, DoubleRates::q, DoubleRates::r, RATE_FLOAT_OF_BFP, DoubleEulers::theta, NpsSensorAccel::value, NpsFdm::wind, DoubleVect3::x, NedCoor_d::x, DoubleVect3::y, NedCoor_d::y, DoubleVect3::z, and NedCoor_d::z.
Referenced by nps_main_display().
nps_ivy_init()
void nps_ivy_init (char * ivy_bus)
Definition at line 59 of file nps_ivy.c.
References ap_launch_index, find_launch_index(), ivy_main_loop(), nps_ivy_send_world_env, on_DL_SETTING(), on_WORLD_ENV(), and th_ivy_main.
Referenced by nps_main_display().
nps_ivy_send_WORLD_ENV_REQ()
void nps_ivy_send_WORLD_ENV_REQ (void)
Definition at line 125 of file nps_ivy.c.
References fdm, NpsFdm::hmsl, ivyPtr, LlaCoor_d::lat, NpsFdm::lla_pos_pprz, LlaCoor_d::lon, NpsFdm::ltpprz_pos, nps_ivy_send_world_env, on_WORLD_ENV(), seq, NedCoor_d::x, NedCoor_d::y, and NedCoor_d::z.
Referenced by nps_ivy_display().
Variable Documentation
nps_ivy_send_world_env
bool nps_ivy_send_world_env
Definition at line 7 of file nps_ivy.h.
Referenced by nps_atmosphere_update(), nps_ivy_display(), nps_ivy_init(), and nps_ivy_send_WORLD_ENV_REQ().