Paparazzi UAS: sw/simulator/nps/nps_sensor_accel.c File Reference
nps_sensor_accel.c File Reference
#include "nps_sensor_accel.h"
#include "generated/airframe.h"
#include "nps_fdm.h"
#include "nps_random.h"
#include <NPS_SENSORS_PARAMS>
#include "math/pprz_algebra_int.h"
Functions
void nps_sensor_accel_init (struct NpsSensorAccel *accel, double time)
void nps_sensor_accel_run_step (struct NpsSensorAccel *accel, double time, struct DoubleRMat *body_to_imu)
Function Documentation
nps_sensor_accel_init()
void nps_sensor_accel_init (struct NpsSensorAccel * accel, double time)
Definition at line 10 of file nps_sensor_accel.c.
References NpsSensorAccel::bias, NpsSensorAccel::data_available, FALSE, FLOAT_MAT33_DIAG, FLOAT_VECT3_ZERO, NpsSensorAccel::max, NpsSensorAccel::min, NpsSensorAccel::neutral, NpsSensorAccel::next_update, NpsSensorAccel::noise_std_dev, NpsSensorAccel::sensitivity, NpsSensorAccel::value, and VECT3_ASSIGN.
Referenced by nps_sensors_init().
nps_sensor_accel_run_step()
void nps_sensor_accel_run_step (struct NpsSensorAccel * accel, double time, struct DoubleRMat * body_to_imu)
Definition at line 27 of file nps_sensor_accel.c.
References NpsSensorAccel::bias, NpsFdm::body_accel, body_to_imu, NpsSensorAccel::data_available, double_vect3_add_gaussian_noise(), DOUBLE_VECT3_ROUND, fdm, DoubleMat33::m, MAT33_VECT3_MUL, NpsSensorAccel::max, NpsSensorAccel::min, NpsSensorAccel::neutral, NpsSensorAccel::next_update, NpsSensorAccel::noise_std_dev, NpsSensorAccel::sensitivity, TRUE, NpsSensorAccel::value, VECT3_ADD, VECT3_BOUND_CUBE, VECT3_COPY, and VECT3_EW_MUL.
Referenced by nps_sensors_run_step().