Paparazzi UAS: sw/airborne/math/pprz_stat.h File Reference
pprz_stat.h File Reference
Statistics functions.
#include "std.h"
Functions
int32_t mean_i (int32_t *array, uint32_t n_elements)
Compute the mean value of an array This is implemented using floats to handle scaling of all variables.
int32_t variance_i (int32_t *array, uint32_t n_elements)
Compute the variance of an array of values (integer).
int32_t covariance_i (int32_t *array1, int32_t *array2, uint32_t n_elements)
Compute the covariance of two arrays V(X) = E[(X-E[X])(Y-E[Y])] = E[XY] - E[X]E[Y] where E[X] is the expected value of X This is implemented using floats to handle scaling of all variables.
float sum_f (float *array, uint32_t n_elements)
Compute the sum array elements.
float mean_f (float *arr, uint32_t n_elements)
Compute the mean value of an array (float)
float variance_f (float *array, uint32_t n_elements)
Compute the variance of an array of values (float).
float covariance_f (float *array1, float *array2, uint32_t n_elements)
Compute the covariance of two arrays V(X) = E[(X-E[X])(Y-E[Y])] = E[XY] - E[X]E[Y] where E[X] is the expected value of X.
Detailed Description
Statistics functions.
Definition in file pprz_stat.h.
Function Documentation
covariance_f()
float covariance_f (float * arr1, float * arr2, uint32_t n_elements)
Compute the covariance of two arrays V(X) = E[(X-E[X])(Y-E[Y])] = E[XY] - E[X]E[Y] where E[X] is the expected value of X.
Parameters
[in] *array1 The first array
[in] *array2 The second array
[in] n_elements Number of elements in the arrays
Returns
covariance
Definition at line 152 of file pprz_stat.c.
Referenced by cloud_sensor_callback(), set_cov_div(), set_cov_flow(), and variance_f().
covariance_i()
int32_t covariance_i (int32_t * array1, int32_t * array2, uint32_t n_elements)
Compute the covariance of two arrays V(X) = E[(X-E[X])(Y-E[Y])] = E[XY] - E[X]E[Y] where E[X] is the expected value of X This is implemented using floats to handle scaling of all variables.
Parameters
[in] *array1 The first array
[in] *array2 The second array
[in] n_elements Number of elements in the arrays
Returns
covariance
Definition at line 78 of file pprz_stat.c.
Referenced by variance_i().
mean_f()
float mean_f (float * array, uint32_t n_elements)
Compute the mean value of an array (float)
Parameters
[in] *array The array
[in] n_elements Number of elements in the array
Returns
mean
Definition at line 122 of file pprz_stat.c.
References array, and sum_f().
Referenced by cloud_sensor_callback().
mean_i()
int32_t mean_i (int32_t * array, uint32_t n_elements)
Compute the mean value of an array This is implemented using floats to handle scaling of all variables.
Parameters
[in] *array The array
[in] n_elements Number of elements in the array
Returns
mean
Definition at line 39 of file pprz_stat.c.
References array.
sum_f()
float sum_f (float * array, uint32_t n_elements)
Compute the sum array elements.
Parameters
[in] *array The first array
[in] n_elements Number of elements in the arrays
Returns
array sum
Compute the sum array elements.
Parameters
[in] *array The array
[in] n_elements Number of elements in the arrays
Returns
array sum
Definition at line 106 of file pprz_stat.c.
References array.
Referenced by mean_f().
variance_f()
float variance_f (float * array, uint32_t n_elements)
Compute the variance of an array of values (float).
The variance is a measure of how far a set of numbers is spread out V(X) = E[(X-E[X])^2] = E[X^2] - E[X]^2 where E[X] is the expected value of X
Parameters
array Pointer to an array of float
n_elements Number of values in the array
Returns
variance
Definition at line 139 of file pprz_stat.c.
References array, and covariance_f().
Referenced by baro_cb(), cloud_sensor_callback(), and cloud_sensor_init().
variance_i()
int32_t variance_i (int32_t * array, uint32_t n_elements)
Compute the variance of an array of values (integer).
The variance is a measure of how far a set of numbers is spread out V(X) = E[(X-E[X])^2] = E[X^2] - E[X]^2 where E[X] is the expected value of X This is implemented using floats to handle scaling of all variables
Parameters
array pointer to an array of integer
n_elements number of elements in the array
Returns
variance
Definition at line 64 of file pprz_stat.c.
References array, and covariance_i().