Paparazzi UAS: sw/airborne/modules/system_identification/pprz_wave.c File Reference
pprz_wave.c File Reference
#include "std.h"
#include "math.h"
#include "pprz_wave.h"
Functions
void wave_init (struct wave_t *wave, float start_time_s, float current_time_s, float frequency_hz, float lag_rad)
void wave_reset (struct wave_t *wave, float current_time_s)
bool wave_is_running (struct wave_t *wave)
float wave_update (struct wave_t *wave, float current_time_s)
Detailed Description
Author
Alessandro Collicelli System excitation pure sine wave
Definition in file pprz_wave.c.
Function Documentation
wave_init()
void wave_init (struct wave_t * wave, float start_time_s, float current_time_s, float frequency_hz, float lag_rad)
Definition at line 33 of file pprz_wave.c.
References wave_t::current_time_s, wave_t::current_value, wave_t::frequency_hz, wave_t::is_running, wave_t::lag_rad, and wave_t::start_time_s.
Referenced by sys_id_wave_activate_handler(), sys_id_wave_frequency_hz_set(), sys_id_wave_init(), and sys_id_wave_lag_rad_set().
wave_is_running()
bool wave_is_running (struct wave_t * wave)
Definition at line 52 of file pprz_wave.c.
References wave_t::is_running.
Referenced by sys_id_wave_run().
wave_reset()
void wave_reset (struct wave_t * wave, float current_time_s)
Definition at line 45 of file pprz_wave.c.
References wave_t::current_time_s, wave_t::current_value, and wave_t::start_time_s.
Referenced by start_wave(), and stop_wave().
wave_update()
float wave_update (struct wave_t * wave, float current_time_s)
Definition at line 57 of file pprz_wave.c.
References wave_t::current_value, wave_t::frequency_hz, wave_t::lag_rad, and wave_t::start_time_s.
Referenced by sys_id_wave_run().