Paparazzi UAS: sw/airborne/math/pprz_random.c File Reference
pprz_random.c File Reference
#include "pprz_random.h"
#include <time.h>
Functions
void init_random (void)
double rand_uniform (void)
double rand_gaussian (void)
Detailed Description
Author
Joost Meulenbeld Random number functions
Joost Meulenbeld
Functions for getting random numbers. The rand_gaussian() internally uses the rand_uniform(). rand_uniform() uses rand() internally which is initialized with the current time on rand_init(). This means that the board doesn't need an internal rng but comes at the cost of more computations.
Usage: rand_init(); // initialize once
float random_number = rand_uniform();
Definition in file pprz_random.c.
Function Documentation
init_random()
void init_random (void)
Definition at line 35 of file pprz_random.c.
References get_sys_time_msec().
Referenced by actuators_uavcan_init(), and sys_id_chirp_init().
rand_gaussian()
double rand_gaussian (void)
Definition at line 53 of file pprz_random.c.
References rand_uniform().
Referenced by set_current_chirp_values().
rand_uniform()
double rand_uniform (void)
Definition at line 45 of file pprz_random.c.
Referenced by actuators_uavcan_send_esc(), and rand_gaussian().