Paparazzi UAS: sw/airborne/math/pprz_trig_int.c File Reference
pprz_trig_int.c File Reference
Paparazzi fixed point trig functions.
#include "pprz_trig_int.h"
#include "pprz_algebra_int.h"
Macros
#define R_FRAC 14
Functions
int pprz_trig_int_init (void)
int32_t pprz_itrig_sin (int32_t angle)
int32_t pprz_itrig_cos (int32_t angle)
int32_t int32_atan2 (int32_t y, int32_t x)
int32_t int32_atan2_2 (int32_t y, int32_t x)
Variables
PPRZ_TRIG_CONST int16_t pprz_trig_int [6434]
Detailed Description
Paparazzi fixed point trig functions.
Definition in file pprz_trig_int.c.
Macro Definition Documentation
R_FRAC
#define R_FRAC 14
Definition at line 903 of file pprz_trig_int.c.
Function Documentation
int32_atan2()
int32_t int32_atan2 (int32_t y, int32_t x)
Definition at line 905 of file pprz_trig_int.c.
References c1, c2, INT32_ANGLE_PI_4, and R_FRAC.
Referenced by nav_circle(), rotorcraft_cam_periodic(), and stateCalcHorizontalSpeedDir_i().
int32_atan2_2()
int32_t int32_atan2_2 (int32_t y, int32_t x)
Definition at line 927 of file pprz_trig_int.c.
References ANGLE_BFP_OF_REAL, c1, c2, INT32_ANGLE_FRAC, INT32_ANGLE_PI_4, and R_FRAC.
Referenced by nav_oval().
pprz_itrig_cos()
int32_t pprz_itrig_cos (int32_t angle)
Definition at line 894 of file pprz_trig_int.c.
References INT32_ANGLE_PI_2, and pprz_itrig_sin().
Referenced by stabilization_attitude_run().
pprz_itrig_sin()
int32_t pprz_itrig_sin (int32_t angle)
Definition at line 865 of file pprz_trig_int.c.
References ANGLE_BFP_OF_REAL, ANGLE_FLOAT_OF_BFP, INT32_ANGLE_NORMALIZE, INT32_ANGLE_PI, INT32_ANGLE_PI_2, and pprz_trig_int.
Referenced by pprz_itrig_cos(), and stabilization_attitude_run().
pprz_trig_int_init()
int pprz_trig_int_init (void)
Definition at line 860 of file pprz_trig_int.c.
Variable Documentation
pprz_trig_int
PPRZ_TRIG_CONST int16_t pprz_trig_int[6434]
Definition at line 31 of file pprz_trig_int.c.
Referenced by pprz_itrig_sin().