Paparazzi UAS: sw/airborne/modules/system_identification/pprz_doublet.c File Reference
pprz_doublet.c File Reference
#include "pprz_doublet.h"
#include "std.h"
Functions
void doublet_init (struct doublet_t *doublet, float length_s, float extra_waiting_time_s, float current_time_s, bool mod3211)
void doublet_reset (struct doublet_t *doublet, float current_time_s)
bool doublet_is_running (struct doublet_t *doublet, float current_time_s)
float doublet_update (struct doublet_t *doublet, float current_time_s)
Detailed Description
Author
Alessandro Colllicelli Mathematical implementation of doublet for system identification
A doublet is a maneuver used during system identification procedures. The standard doublet input (1) is constituted by two consecutive step input. The two step inputs are equal in step amplitude and time lenght but opposite in sign. The standard 3-2-1-1 doublet input (2) is constituded by four step input, with decresing length in time, equal amplitude and alternating in sign.
           ______
          |      |
(1) _________| | ___________ Standard doublet input shape | | |______|
           __________________              ______
          |                  |            |      |
(2) _________| | | | _________ 3-2-1-1 doublet input shape | | | | |____________| |______|
Definition in file pprz_doublet.c.
Function Documentation
doublet_init()
void doublet_init (struct doublet_t * doublet, float length_s, float extra_waiting_time_s, float current_time_s, bool mod3211)
Definition at line 31 of file pprz_doublet.c.
References doublet_t::current_time_s, doublet_t::current_value, doublet, doublet_t::mod3211, doublet_t::t0, doublet_t::t1, doublet_t::t2, doublet_t::t3, doublet_t::t4, doublet_t::t5, doublet_t::tf, and doublet_t::total_length_s.
Referenced by sys_id_doublet_activate_handler(), and sys_id_doublet_init().
doublet_is_running()
bool doublet_is_running (struct doublet_t * doublet, float current_time_s)
Definition at line 63 of file pprz_doublet.c.
References doublet, doublet_t::t0, and doublet_t::total_length_s.
Referenced by doublet_update(), and sys_id_doublet_run().
doublet_reset()
void doublet_reset (struct doublet_t * doublet, float current_time_s)
Definition at line 57 of file pprz_doublet.c.
References doublet_t::current_time_s, doublet_t::current_value, doublet, and doublet_t::t0.
Referenced by start_doublet(), and stop_doublet().
doublet_update()
float doublet_update (struct doublet_t * doublet, float current_time_s)
Definition at line 68 of file pprz_doublet.c.
References doublet_t::current_value, doublet, doublet_is_running(), doublet_t::mod3211, doublet_t::t0, doublet_t::t1, doublet_t::t2, doublet_t::t3, and doublet_t::t4.
Referenced by sys_id_doublet_run().