Paparazzi UAS: sw/airborne/math/pprz_polyfit_float.h File Reference
pprz_polyfit_float.h File Reference
Polynomial regression.
Functions
void pprz_polyfit_float (float *x, float *y, int n, int p, float *c)
Polynomial regression.
Detailed Description
Polynomial regression.
Definition in file pprz_polyfit_float.h.
Function Documentation
pprz_polyfit_float()
void pprz_polyfit_float (float * x, float * y, int n, int p, float * c)
Polynomial regression.
Polynomial regression is a form of linear regression in which the relationship between the independent variable x and the dependent variable y is modelled as an nth order polynomial.
Considering the regression model:
in matrix form
where
The vector of estimated polynomial regression coefficients using ordinary least squares estimation is
http://en.wikipedia.org/wiki/Polynomial_regression http://fr.wikipedia.org/wiki/R%C3%A9gression_polynomiale http://www.arachnoid.com/sage/polynomial.html
Parameters
[in] x pointer to the input array of independent variable X [n]
[in] y pointer to the input array of dependent variable Y [n]
[in] n number of input measurments
[in] p degree of the output polynomial
[out] c pointer to the output array of polynomial coefficients [p]
Polynomial regression is a form of linear regression in which the relationship between the independent variable x and the dependent variable y is modelled as an nth order polynomial.
Considering the regression model:
in matrix form
where
The vector of estimated polynomial regression coefficients using ordinary least squares estimation is
http://en.wikipedia.org/wiki/Polynomial_regression http://fr.wikipedia.org/wiki/R%C3%A9gression_polynomiale http://www.arachnoid.com/sage/polynomial.html
Parameters
[in] x pointer to the input array of independent variable X [n]
[in] y pointer to the input array of dependent variable Y [n]
[in] n number of input measurments
[in] p degree of the output polynomial
[out] c pointer to the output array of polynomial coefficients [p+1]
Definition at line 63 of file pprz_polyfit_float.c.
References float_mat_zero(), float_vect_zero(), MAKE_MATRIX_PTR, p, pprz_svd_float(), pprz_svd_solve_float(), and mesonh.mesonh_atmosphere::T.