Paparazzi UAS: sw/airborne/modules/radio_control/hott.c File Reference
hott.c File Reference
#include "modules/radio_control/radio_control.h"
#include "modules/radio_control/hott.h"
#include <BOARD_CONFIG>
#include "modules/datalink/telemetry.h"
Functions
static void send_hott (struct transport_tx *trans, struct link_device *dev)
void radio_control_impl_init (void)
static void hott_decode_event (void)
void radio_control_impl_event (void(*_received_frame_handler)(void))
RC event function with handler callback.
Variables
struct SHott hott
HOTT struct.
Detailed Description
Single HOTT radio_control SUMD
Definition in file hott.c.
Function Documentation
hott_decode_event()
static void hott_decode_event (void) inline static
Definition at line 61 of file hott.c.
References hott, and hott_common_decode_event().
Referenced by radio_control_impl_event().
radio_control_impl_event()
void radio_control_impl_event (void(*)(void) _received_frame_handler)
RC event function with handler callback.
PPM frames are normalized using the IIR filter.
Definition at line 66 of file hott.c.
References SHott::frame_available, RadioControl::frame_cpt, hott, hott_decode_event(), SHott::pulses, radio_control, RadioControl::radio_ok_cpt, RC_OK, RadioControl::status, and RadioControl::time_since_last_frame.
radio_control_impl_init()
void radio_control_impl_init (void)
Definition at line 48 of file hott.c.
References DefaultPeriodic, hott, hott_common_init(), register_periodic_telemetry(), and send_hott().
send_hott()
static void send_hott (struct transport_tx * trans, struct link_device * dev) static
Definition at line 39 of file hott.c.
References dev, RadioControl::frame_rate, hott, HOTT_NB_CHANNEL, SHott::ppm, and radio_control.
Referenced by radio_control_impl_init().
Variable Documentation
hott
struct SHott hott
HOTT struct.
Definition at line 33 of file hott.c.
Referenced by hott_decode_event(), radio_control_impl_event(), radio_control_impl_init(), and send_hott().