Paparazzi UAS: sw/airborne/firmwares/rover/autopilot_firmware.c File Reference
autopilot_firmware.c File Reference
#include "firmwares/rover/autopilot_firmware.h"
#include "generated/modules.h"
#include <stdint.h>
#include "modules/energy/electrical.h"
#include "modules/datalink/telemetry.h"
#include "modules/radio_control/radio_control.h"
#include "modules/gps/gps.h"
#include "modules/nav/nav_geofence.h"
Functions
static void send_status (struct transport_tx *trans, struct link_device *dev)
static void send_energy (struct transport_tx *trans, struct link_device *dev)
static void send_fp (struct transport_tx *trans, struct link_device *dev)
static void send_rotorcraft_rc (struct transport_tx *trans, struct link_device *dev)
void autopilot_firmware_init (void)
Init function.
void autopilot_event (void)
autopilot event function
Function Documentation
autopilot_event()
void autopilot_event (void)
autopilot event function
Autopilot event check function.
Definition at line 137 of file autopilot_firmware.c.
autopilot_firmware_init()
void autopilot_firmware_init (void)
Init function.
Definition at line 123 of file autopilot_firmware.c.
References ap_electrical, Electrical::bat_critical, Electrical::bat_low, Electrical::charge, Electrical::current, DefaultPeriodic, Electrical::energy, register_periodic_telemetry(), send_airspeed(), send_desired(), send_energy(), send_estimator(), send_fp(), send_mode(), send_rotorcraft_rc(), send_status(), and Electrical::vsupply.
send_energy()
static void send_energy (struct transport_tx * trans, struct link_device * dev) static
Definition at line 70 of file autopilot_firmware.c.
References autopilot, Electrical::charge, Electrical::current, dev, electrical, Electrical::energy, MAX_PPRZ, pprz_autopilot::throttle, and Electrical::vsupply.
Referenced by autopilot_firmware_init().
send_fp()
static void send_fp (struct transport_tx * trans, struct link_device * dev) static
Definition at line 78 of file autopilot_firmware.c.
References ANGLE_BFP_OF_REAL, autopilot, RoverNavigation::carrot, dev, pprz_autopilot::flight_time, RoverNavigation::heading, nav, Int32Eulers::phi, POS_BFP_OF_REAL, Int32Eulers::psi, stateGetNedToBodyEulers_i(), stateGetPositionEnu_i(), stateGetSpeedEnu_i(), Int32Eulers::theta, pprz_autopilot::throttle, NedCoor_f::x, EnuCoor_f::x, EnuCoor_i::x, EnuCoor_f::y, EnuCoor_i::y, and EnuCoor_i::z.
Referenced by autopilot_firmware_init().
send_rotorcraft_rc()
static void send_rotorcraft_rc (struct transport_tx * trans, struct link_device * dev) static
Definition at line 105 of file autopilot_firmware.c.
References dev, radio_control, RADIO_KILL_SWITCH, RADIO_MODE, RADIO_PITCH, RADIO_ROLL, RADIO_THROTTLE, RADIO_YAW, RadioControl::status, and RadioControl::values.
Referenced by autopilot_firmware_init().
send_status()
static void send_status (struct transport_tx * trans, struct link_device * dev) static
Definition at line 55 of file autopilot_firmware.c.
References autopilot, dev, electrical, GpsState::fix, RadioControl::frame_rate, gps, pprz_autopilot::mode, pprz_autopilot::motors_on, sys_time::nb_sec, radio_control, RadioControl::status, and Electrical::vsupply.
Referenced by autopilot_firmware_init().