Paparazzi UAS: sw/airborne/firmwares/rover/main_ap.h File Reference
main_ap.h File Reference
Functions
void main_init (void)
Main initialization.
void main_event (void)
void handle_periodic_tasks (void)
void main_periodic (void)
void telemetry_periodic (void)
void failsafe_check (void)
Detailed Description
Rover main loop.
Definition in file main_ap.h.
Function Documentation
failsafe_check()
void failsafe_check (void)
Definition at line 201 of file main_ap.c.
References AP_MODE_FAILSAFE, AP_MODE_FLIP, AP_MODE_GUIDED, AP_MODE_HOME, AP_MODE_KILL, AP_MODE_MODULE, AP_MODE_NAV, autopilot_check_in_flight(), autopilot_get_mode(), autopilot_get_motors_on(), autopilot_set_mode(), Electrical::bat_critical, datalink_time, electrical, GpsIsLost, radio_control, RC_LOST_MODE, RC_OK, RC_REALLY_LOST, and RadioControl::status.
Referenced by handle_periodic_tasks(), and main_init().
handle_periodic_tasks()
void handle_periodic_tasks (void)
Definition at line 128 of file main_ap.c.
References autopilot, autopilot_get_mode(), autopilot_in_flight(), commands, datalink_time, electrical_periodic(), electrical_tid, failsafe_check(), failsafe_tid, pprz_autopilot::flight_time, intermcu_set_actuators(), LED_PERIODIC, main_periodic(), main_periodic_tid, modules_datalink_tid, modules_gnc_tid, modules_mcu_core_tid, modules_radio_control_tid, modules_sensors_tid, modules_tid, radio_control_periodic_task(), radio_control_tid, sys_time_check_and_ack_timer(), TELEMETRY_FREQUENCY, telemetry_periodic(), telemetry_tid, and throttle_curve_run().
main_event()
void main_event (void) inline
Definition at line 246 of file main_ap.c.
References autopilot, autopilot_on_rc_frame(), fbw_on_ap_command(), fbw_on_rc_frame(), InterMcuEvent(), mcu_event(), RadioControlEvent, and pprz_autopilot::use_rc.
main_init()
void main_init (void) inline
Main initialization.
Definition at line 80 of file main_ap.c.
References Imu::body_to_imu, DATALINK_PERIOD, electrical_init(), electrical_tid, f, failsafe_check(), failsafe_tid, fbw_mode, FBW_MODE_FAILSAFE, imu, intermcu_init(), main_periodic_tid, mcu_init(), modules_datalink_tid, modules_gnc_tid, modules_mcu_core_tid, modules_radio_control_tid, modules_sensors_tid, modules_tid, motor_mixing_init(), orientationGetQuat_f(), radio_control_init(), radio_control_tid, SENSORS_PERIOD, SYS_PERIOD, sys_time_register_timer(), sys_time_register_timer_offset(), and telemetry_tid.
main_periodic()
void main_periodic (void) inline
Definition at line 174 of file main_fbw.c.
References autopilot_get_mode(), autopilot_motors_on, commands, commands_failsafe, fbw_mode, FBW_MODE_AUTO, FBW_MODE_FAILSAFE, FBW_MODE_MANUAL, fbw_motors_on, fbw_safety_check(), intermcu, intermcu_periodic(), LED_OFF, LED_ON, LED_PERIODIC, LED_TOGGLE, PPRZ_BAUD, and SetCommands.
Referenced by handle_periodic_tasks().
telemetry_periodic()
void telemetry_periodic (void)
Definition at line 177 of file main_ap.c.
References autopilot_send_version(), DefaultChannel, DefaultDevice, DefaultPeriodic, fbw_mode, and intermcu_send_status().
Referenced by handle_periodic_tasks().