Paparazzi UAS: sw/airborne/firmwares/rover/main_ap.c File Reference
main_ap.c File Reference
#include <inttypes.h>
#include "led.h"
#include "modules/radio_control/radio_control.h"
#include "firmwares/rover/main_ap.h"
#include "generated/modules.h"
#include "modules/core/abi.h"
Macros
#define MODULES_C
#define ABI_C
#define SYS_PERIOD (1.f / PERIODIC_FREQUENCY)
#define SENSORS_PERIOD (1.f / PERIODIC_FREQUENCY)
#define DATALINK_PERIOD (1.f / TELEMETRY_FREQUENCY)
#define RC_LOST_MODE AP_MODE_FAILSAFE
mode to enter when RC is lost while using a mode with RC input (not AP_MODE_NAV)
Functions
void main_init (void)
Main initialization.
void handle_periodic_tasks (void)
void telemetry_periodic (void)
void failsafe_check (void)
void main_event (void)
Variables
tid_t modules_mcu_core_tid
IDs for timers.
tid_t modules_sensors_tid
tid_t modules_radio_control_tid
tid_t modules_gnc_tid
tid_t modules_datalink_tid
tid_t modules_default_tid
tid_t failsafe_tid
id for failsafe_check() timer FIXME
Detailed Description
Rover main loop.
Definition in file main_ap.c.
Macro Definition Documentation
ABI_C
#define ABI_C
Definition at line 30 of file main_ap.c.
DATALINK_PERIOD
#define DATALINK_PERIOD (1.f / TELEMETRY_FREQUENCY)
Definition at line 74 of file main_ap.c.
MODULES_C
#define MODULES_C
Definition at line 28 of file main_ap.c.
RC_LOST_MODE
#define RC_LOST_MODE AP_MODE_FAILSAFE
mode to enter when RC is lost while using a mode with RC input (not AP_MODE_NAV)
Definition at line 185 of file main_ap.c.
SENSORS_PERIOD
#define SENSORS_PERIOD (1.f / PERIODIC_FREQUENCY)
Definition at line 73 of file main_ap.c.
SYS_PERIOD
#define SYS_PERIOD (1.f / PERIODIC_FREQUENCY)
Definition at line 72 of file main_ap.c.
Function Documentation
failsafe_check()
void failsafe_check (void)
Definition at line 188 of file main_ap.c.
References AP_MODE_FAILSAFE, AP_MODE_FLIP, AP_MODE_GUIDED, AP_MODE_HOME, AP_MODE_KILL, AP_MODE_MODULE, AP_MODE_NAV, autopilot_check_in_flight(), autopilot_get_mode(), autopilot_get_motors_on(), autopilot_set_mode(), Electrical::bat_critical, datalink_time, electrical, GpsIsLost, radio_control, RC_LOST_MODE, RC_OK, RC_REALLY_LOST, and RadioControl::status.
handle_periodic_tasks()
void handle_periodic_tasks (void)
Definition at line 122 of file main_ap.c.
References autopilot, autopilot_get_mode(), autopilot_in_flight(), commands, datalink_time, failsafe_check(), failsafe_tid, pprz_autopilot::flight_time, intermcu_set_actuators(), LED_PERIODIC, modules_datalink_tid, modules_gnc_tid, modules_mcu_core_tid, modules_radio_control_tid, modules_sensors_tid, radio_control_periodic_task(), sys_time_check_and_ack_timer(), TELEMETRY_FREQUENCY, telemetry_periodic(), and throttle_curve_run().
Referenced by main(), nps_autopilot_run_step(), thd_ap(), and thd_fbw().
main_event()
void main_event (void) inline
Definition at line 193 of file main_ap.c.
References autopilot, autopilot_on_rc_frame(), RadioControlEvent, and pprz_autopilot::use_rc.
main_init()
void main_init (void) inline
Main initialization.
Definition at line 76 of file main_ap.c.
References Imu::body_to_imu, DATALINK_PERIOD, f, failsafe_check(), failsafe_tid, imu, modules_datalink_tid, modules_gnc_tid, modules_mcu_core_tid, modules_radio_control_tid, modules_sensors_tid, orientationGetQuat_f(), radio_control_init(), SENSORS_PERIOD, SYS_PERIOD, sys_time_register_timer(), and sys_time_register_timer_offset().
telemetry_periodic()
void telemetry_periodic (void)
Definition at line 164 of file main_ap.c.
References autopilot_send_version(), DefaultChannel, DefaultDevice, and DefaultPeriodic.
Variable Documentation
failsafe_tid
tid_t failsafe_tid
id for failsafe_check() timer FIXME
Definition at line 70 of file main_ap.c.
modules_datalink_tid
tid_t modules_datalink_tid
Definition at line 68 of file main_ap.c.
modules_default_tid
tid_t modules_default_tid
Definition at line 69 of file main_ap.c.
modules_gnc_tid
tid_t modules_gnc_tid
Definition at line 67 of file main_ap.c.
modules_mcu_core_tid
tid_t modules_mcu_core_tid
IDs for timers.
Definition at line 64 of file main_ap.c.
modules_radio_control_tid
tid_t modules_radio_control_tid
Definition at line 66 of file main_ap.c.
modules_sensors_tid
tid_t modules_sensors_tid
Definition at line 65 of file main_ap.c.