Paparazzi UAS: sw/airborne/modules/radio_control/sbus_dual.c File Reference
sbus_dual.c File Reference
#include "modules/radio_control/radio_control.h"
#include "modules/radio_control/sbus_dual.h"
#include <BOARD_CONFIG>
#include "mcu_periph/uart.h"
#include <string.h>
#include "modules/datalink/telemetry.h"
Macros
#define RC_POLARITY_GPIO_PORT 0
#define RC_POLARITY_GPIO_PIN 0
#define RC2_POLARITY_GPIO_PORT RC_POLARITY_GPIO_PORT
#define RC2_POLARITY_GPIO_PIN RC_POLARITY_GPIO_PIN
Functions
static void send_sbus (struct transport_tx *trans, struct link_device *dev)
void radio_control_impl_init (void)
static void sbus_dual_decode_event (void)
void radio_control_impl_event (void(*_received_frame_handler)(void))
RC event function with handler callback.
Variables
struct Sbus sbus1 sbus2
SBUS struct.
Detailed Description
Dual SBUS radio_control
Definition in file sbus_dual.c.
Macro Definition Documentation
RC2_POLARITY_GPIO_PIN
#define RC2_POLARITY_GPIO_PIN RC_POLARITY_GPIO_PIN
Definition at line 44 of file sbus_dual.c.
RC2_POLARITY_GPIO_PORT
#define RC2_POLARITY_GPIO_PORT RC_POLARITY_GPIO_PORT
Definition at line 41 of file sbus_dual.c.
RC_POLARITY_GPIO_PIN
#define RC_POLARITY_GPIO_PIN 0
Definition at line 37 of file sbus_dual.c.
RC_POLARITY_GPIO_PORT
#define RC_POLARITY_GPIO_PORT 0
Definition at line 34 of file sbus_dual.c.
Function Documentation
radio_control_impl_event()
void radio_control_impl_event (void(*)(void) _received_frame_handler)
RC event function with handler callback.
PPM frames are normalized using the IIR filter.
Definition at line 80 of file sbus_dual.c.
References Sbus::frame_available, RadioControl::frame_cpt, Sbus::pulses, radio_control, RadioControl::radio_ok_cpt, RC_OK, sbus2, sbus_dual_decode_event(), RadioControl::status, and RadioControl::time_since_last_frame.
radio_control_impl_init()
void radio_control_impl_init (void)
Definition at line 63 of file sbus_dual.c.
References DefaultPeriodic, RC2_POLARITY_GPIO_PIN, RC2_POLARITY_GPIO_PORT, RC_POLARITY_GPIO_PIN, RC_POLARITY_GPIO_PORT, register_periodic_telemetry(), sbus2, sbus_common_init(), and send_sbus().
sbus_dual_decode_event()
static void sbus_dual_decode_event (void) inline static
Definition at line 74 of file sbus_dual.c.
References sbus2, and sbus_common_decode_event().
Referenced by radio_control_impl_event().
send_sbus()
static void send_sbus (struct transport_tx * trans, struct link_device * dev) static
Definition at line 54 of file sbus_dual.c.
References dev, RadioControl::frame_rate, radio_control, and SBUS_NB_CHANNEL.
Referenced by radio_control_impl_init().
Variable Documentation
sbus2
struct Sbus sbus1 sbus2
SBUS struct.
Definition at line 48 of file sbus_dual.c.
Referenced by radio_control_impl_event(), radio_control_impl_init(), and sbus_dual_decode_event().