Paparazzi UAS: sw/airborne/modules/ctrl/scheduling_indi_simple.c File Reference
scheduling_indi_simple.c File Reference
#include "modules/ctrl/scheduling_indi_simple.h"
#include "firmwares/rotorcraft/stabilization/stabilization_indi_simple.h"
#include "firmwares/rotorcraft/guidance/guidance_indi_hybrid.h"
#include "firmwares/rotorcraft/guidance/guidance_h.h"
#include "generated/airframe.h"
#include "state.h"
Macros
#define INDI_SCHEDULING_LOWER_BOUND_G1 0.0001
Functions
void ctrl_eff_scheduling_init (void)
Initialises periodic loop;.
void ctrl_eff_scheduling_periodic (void)
Periodic function that interpolates between gain sets depending on the scheduling variable.
Variables
int32_t use_scheduling = 1
static float g_forward [3] = {STABILIZATION_INDI_FORWARD_G1_P, STABILIZATION_INDI_FORWARD_G1_Q, STABILIZATION_INDI_FORWARD_G1_R}
static float g_hover [3] = {STABILIZATION_INDI_G1_P, STABILIZATION_INDI_G1_Q, STABILIZATION_INDI_G1_R}
Macro Definition Documentation
INDI_SCHEDULING_LOWER_BOUND_G1
#define INDI_SCHEDULING_LOWER_BOUND_G1 0.0001
Definition at line 32 of file scheduling_indi_simple.c.
Function Documentation
ctrl_eff_scheduling_init()
void ctrl_eff_scheduling_init (void)
Initialises periodic loop;.
Definition at line 41 of file scheduling_indi_simple.c.
References g1g2_forward, g1g2_hover, g2_both, and INDI_G_SCALING.
ctrl_eff_scheduling_periodic()
void ctrl_eff_scheduling_periodic (void)
Periodic function that interpolates between gain sets depending on the scheduling variable.
Definition at line 45 of file scheduling_indi_simple.c.
References actuator_state_filt_vect, Bwls, ctrl_eff_scheduling_periodic_a(), ctrl_eff_scheduling_periodic_b(), IndiVariables::g1, g_forward, g_hover, guidance_indi_specific_force_gain, indi, INDI_G_SCALING, INDI_SCHEDULING_LOWER_BOUND_G1, FloatRates::p, FloatRates::q, FloatRates::r, radio_control, stateGetAirspeed_f(), stateGetNedToBodyEulers_f(), use_scheduling, and RadioControl::values.
Variable Documentation
g_forward
float g_forward[3] = {STABILIZATION_INDI_FORWARD_G1_P, STABILIZATION_INDI_FORWARD_G1_Q, STABILIZATION_INDI_FORWARD_G1_R} static
Definition at line 36 of file scheduling_indi_simple.c.
Referenced by ctrl_eff_scheduling_periodic().
g_hover
float g_hover[3] = {STABILIZATION_INDI_G1_P, STABILIZATION_INDI_G1_Q, STABILIZATION_INDI_G1_R} static
Definition at line 38 of file scheduling_indi_simple.c.
Referenced by ctrl_eff_scheduling_periodic().
use_scheduling
int32_t use_scheduling = 1
Definition at line 34 of file scheduling_indi_simple.c.
Referenced by ctrl_eff_scheduling_periodic().