Paparazzi UAS: sw/airborne/modules/loggers/sdlog_chibios.h File Reference
sdlog_chibios.h File Reference
#include "std.h"
#include "modules/loggers/sdlog_chibios/sdLog.h"
#include "pprzlink/pprzlink_device.h"
Data Structures
struct chibios_sdlog
chibios_sdlog structure
Functions
void sdlog_chibios_init (void)
void sdlog_chibios_finish (bool flush)
void chibios_sdlog_init (struct chibios_sdlog *sdlog, FileDes *file)
init chibios_sdlog structure
Variables
FileDes pprzLogFile
struct chibios_sdlog chibios_sdlog
Data Structure Documentation
chibios_sdlog
struct chibios_sdlog
chibios_sdlog structure
Definition at line 54 of file sdlog_chibios.h.
Data Fields
struct link_device device Generic device interface.
FileDes * file
Function Documentation
chibios_sdlog_init()
void chibios_sdlog_init (struct chibios_sdlog * sdlog, FileDes * file)
init chibios_sdlog structure
Definition at line 165 of file sdlog_chibios.c.
References chibios_sdlog::device, chibios_sdlog::file, null_byte_function(), null_function(), sdlog_check_free_space(), sdlog_send(), sdlog_transmit(), and sdlog_transmit_buffer().
Referenced by flight_recorder_init(), and thd_startlog().
sdlog_chibios_finish()
void sdlog_chibios_finish (bool flush)
Definition at line 196 of file sdlog_chibios.c.
References chibios_sdlog_status, mcu_periph_energy_save(), pprzLogFile, SDLOG_STOPPED, and sdLogFinish().
Referenced by thd_bat_survey(), and thdUsbStorage().
sdlog_chibios_init()
void sdlog_chibios_init (void)
Definition at line 180 of file sdlog_chibios.c.
References chibios_sdlog_status, DefaultPeriodic, register_periodic_telemetry(), SDLOG_STOPPED, send_sdlog_status(), thd_startlog(), and usbStorageStartPolling().
Variable Documentation
chibios_sdlog
struct chibios_sdlog chibios_sdlog
Definition at line 88 of file sdlog_chibios.c.
pprzLogFile
FileDes pprzLogFile
Definition at line 86 of file sdlog_chibios.c.
Referenced by airspeed_cb(), airspeed_ets_read_event(), aoa_pwm_update(), apogee_baro_event(), baro_cb(), dw1000_arduino_periodic(), gps_cb(), gps_ubx_parse(), gyro_cb(), humid_sht_periodic(), incidence_cb(), ins_float_invariant_propagate(), ins_mekf_wind_wrapper_init(), logger_control_effectiveness_periodic(), logger_control_effectiveness_start(), mag_cb(), mf_daq_send_report(), mf_ptu_periodic(), pressure_diff_cb(), process_data(), sdlog_chibios_finish(), temod_event(), thd_startlog(), wind_estimator_init(), and wind_estimator_step().