Paparazzi UAS: sw/airborne/arch/linux/serial_port.h File Reference
serial_port.h File Reference
#include <termios.h>
Data Structures
struct SerialPort
Functions
struct SerialPort * serial_port_new (void)
void serial_port_free (struct SerialPort *me)
void serial_port_flush (struct SerialPort *me)
void serial_port_flush_output (struct SerialPort *me)
int serial_port_open_raw (struct SerialPort *me, const char *device, speed_t speed)
int serial_port_open (struct SerialPort *me, const char *device, void(*term_conf_callback)(struct termios *, speed_t *))
void serial_port_close (struct SerialPort *me)
int serial_port_set_baudrate (struct SerialPort *me, speed_t speed)
int serial_port_set_bits_stop_parity (struct SerialPort *me, const int bits, const int stop, const int parity)
Data Structure Documentation
SerialPort
struct SerialPort
Definition at line 29 of file serial_port.h.
Data Fields
struct termios cur_termios
int fd
struct termios orig_termios
Function Documentation
serial_port_close()
void serial_port_close (struct SerialPort * me)
Definition at line 184 of file serial_port.c.
References SerialPort::fd, SerialPort::orig_termios, TRACE, and TRACE_ERROR.
Referenced by uart_periph_open().
serial_port_flush()
void serial_port_flush (struct SerialPort * me)
Definition at line 89 of file serial_port.c.
References SerialPort::fd, TRACE, and TRACE_ERROR.
Referenced by serial_port_open(), and serial_port_open_raw().
serial_port_flush_output()
void serial_port_flush_output (struct SerialPort * me)
Definition at line 100 of file serial_port.c.
References SerialPort::fd, TRACE, and TRACE_ERROR.
serial_port_free()
void serial_port_free (struct SerialPort * me)
Definition at line 80 of file serial_port.c.
Referenced by uart_periph_open().
serial_port_new()
struct SerialPort* serial_port_new (void)
Definition at line 74 of file serial_port.c.
Referenced by uart_periph_open().
serial_port_open()
int serial_port_open (struct SerialPort * me, const char * device, void(*)(struct termios *, speed_t *) term_conf_callback)
Definition at line 153 of file serial_port.c.
References SerialPort::cur_termios, SerialPort::fd, SerialPort::orig_termios, serial_port_flush(), TRACE, and TRACE_ERROR.
serial_port_open_raw()
int serial_port_open_raw (struct SerialPort * me, const char * device, speed_t speed)
Definition at line 111 of file serial_port.c.
References SerialPort::cur_termios, SerialPort::fd, IUCLC, SerialPort::orig_termios, serial_port_flush(), TRACE, and TRACE_ERROR.
Referenced by uart_periph_open().
serial_port_set_baudrate()
int serial_port_set_baudrate (struct SerialPort * me, speed_t speed)
Definition at line 210 of file serial_port.c.
References SerialPort::cur_termios, SerialPort::fd, TRACE, and TRACE_ERROR.
Referenced by uart_periph_set_baudrate().
serial_port_set_bits_stop_parity()
int serial_port_set_bits_stop_parity (struct SerialPort * me, const int bits, const int stop, const int parity)
Definition at line 224 of file serial_port.c.
References SerialPort::cur_termios, SerialPort::fd, TRACE, TRACE_ERROR, UBITS_7, UPARITY_EVEN, UPARITY_ODD, and USTOP_1.
Referenced by uart_periph_set_bits_stop_parity().