Paparazzi UAS: sw/airborne/firmwares/rotorcraft/stabilization/stabilization_attitude_ref_euler_float.h File Reference
stabilization_attitude_ref_euler_float.h File Reference
#include "math/pprz_algebra_float.h"
#include "attitude_ref_saturate_naive.h"
Data Structures
struct FloatRefModel
Attitude reference model parameters (float)
struct AttRefEulerFloat
Attitude reference state/output (euler float)
Functions
void attitude_ref_euler_float_init (struct AttRefEulerFloat *ref)
void attitude_ref_euler_float_enter (struct AttRefEulerFloat *ref, float psi)
void attitude_ref_euler_float_update (struct AttRefEulerFloat *ref, struct FloatEulers *sp_eulers, float dt)
Data Structure Documentation
FloatRefModel
struct FloatRefModel
Attitude reference model parameters (float)
Definition at line 29 of file stabilization_attitude_ref_euler_float.h.
Data Fields
struct FloatRates omega
struct FloatRates two_omega2 cached value of 2*omega*omega
struct FloatRates zeta
AttRefEulerFloat
struct AttRefEulerFloat
Attitude reference state/output (euler float)
Definition at line 35 of file stabilization_attitude_ref_euler_float.h.
Data Fields
struct FloatRates accel
struct FloatEulers euler
struct FloatRefModel model
struct FloatRates rate
struct FloatRefSat saturation
Function Documentation
attitude_ref_euler_float_enter()
void attitude_ref_euler_float_enter (struct AttRefEulerFloat * ref, float psi)
Definition at line 62 of file stabilization_attitude_ref_euler_float.c.
References ref, and reset_psi_ref().
Referenced by stabilization_attitude_enter().
attitude_ref_euler_float_init()
void attitude_ref_euler_float_init (struct AttRefEulerFloat * ref)
Definition at line 41 of file stabilization_attitude_ref_euler_float.c.
References FLOAT_EULERS_ZERO, FLOAT_RATES_ZERO, ref, STABILIZATION_ATTITUDE_REF_MAX_P, STABILIZATION_ATTITUDE_REF_MAX_PDOT, STABILIZATION_ATTITUDE_REF_MAX_Q, STABILIZATION_ATTITUDE_REF_MAX_QDOT, STABILIZATION_ATTITUDE_REF_MAX_R, and STABILIZATION_ATTITUDE_REF_MAX_RDOT.
Referenced by stabilization_attitude_init().
attitude_ref_euler_float_update()
void attitude_ref_euler_float_update (struct AttRefEulerFloat * ref, struct FloatEulers * sp_eulers, float dt)
Definition at line 67 of file stabilization_attitude_ref_euler_float.c.
References attitude_ref_float_saturate_naive(), EULERS_ADD, EULERS_ASSIGN, EULERS_DIFF, FLOAT_ANGLE_NORMALIZE, FloatRates::p, FloatEulers::phi, FloatEulers::psi, FloatRates::q, FloatRates::r, RATES_ADD, RATES_SMUL, ref, and FloatEulers::theta.
Referenced by stabilization_attitude_run().