Paparazzi UAS: sw/airborne/modules/stereocam/stereocam.c File Reference
stereocam.c File Reference
interface to TU Delft serial stereocam Include stereocam.xml to your airframe file. Parameters STEREO_PORT, STEREO_BAUD, SEND_STEREO should be configured with stereocam.xml.
#include "modules/stereocam/stereocam.h"
#include "mcu_periph/uart.h"
#include "modules/datalink/telemetry.h"
#include "pprzlink/messages.h"
#include "pprzlink/intermcu_msg.h"
#include "mcu_periph/sys_time.h"
#include "modules/core/abi.h"
#include "stereocam_follow_me/follow_me.h"
#include "filters/median_filter.h"
Macros
#define FORWARD_IMAGE_DATA FALSE
#define STEREO_BODY_TO_STEREO_PHI 0
#define STEREO_BODY_TO_STEREO_THETA 0
#define STEREO_BODY_TO_STEREO_PSI 0
#define STEREOCAM_USE_MEDIAN_FILTER 0
Functions
void stereocam_init (void)
static void stereocam_parse_msg (void)
void stereocam_event (void)
void state2stereocam (void)
Variables
struct stereocam_t stereocam
static uint8_t stereocam_msg_buf [256]
The message buffer for the stereocamera.
struct MedianFilter3Float medianfilter
Detailed Description
interface to TU Delft serial stereocam Include stereocam.xml to your airframe file. Parameters STEREO_PORT, STEREO_BAUD, SEND_STEREO should be configured with stereocam.xml.
Definition in file stereocam.c.
Macro Definition Documentation
FORWARD_IMAGE_DATA
#define FORWARD_IMAGE_DATA FALSE
Definition at line 44 of file stereocam.c.
STEREO_BODY_TO_STEREO_PHI
#define STEREO_BODY_TO_STEREO_PHI 0
Definition at line 71 of file stereocam.c.
STEREO_BODY_TO_STEREO_PSI
#define STEREO_BODY_TO_STEREO_PSI 0
Definition at line 79 of file stereocam.c.
STEREO_BODY_TO_STEREO_THETA
#define STEREO_BODY_TO_STEREO_THETA 0
Definition at line 75 of file stereocam.c.
STEREOCAM_USE_MEDIAN_FILTER
#define STEREOCAM_USE_MEDIAN_FILTER 0
Definition at line 89 of file stereocam.c.
Function Documentation
state2stereocam()
void state2stereocam (void)
Definition at line 216 of file stereocam.c.
References stereocam_t::body_to_cam, cam_angles(), stereocam_t::device, float_rmat_mult(), stateGetNedToBodyEulers_f(), stereocam, and stereocam_t::transport.
stereocam_event()
void stereocam_event (void)
Definition at line 202 of file stereocam.c.
References stereocam_t::device, stereocam_t::msg_available, stereocam, stereocam_msg_buf, stereocam_parse_msg(), and stereocam_t::transport.
stereocam_init()
void stereocam_init (void)
Definition at line 95 of file stereocam.c.
References stereocam_t::body_to_cam, float_rmat_of_eulers, InitMedianFilterVect3Float, MEDIAN_DEFAULT_SIZE, medianfilter, STEREO_BODY_TO_STEREO_PHI, STEREO_BODY_TO_STEREO_PSI, STEREO_BODY_TO_STEREO_THETA, stereocam, and stereocam_t::transport.
stereocam_parse_msg()
static void stereocam_parse_msg (void) static
Definition at line 107 of file stereocam.c.
References stereocam_t::body_to_cam, DefaultChannel, DefaultDevice, float_rmat_transp_vmult(), follow_me(), get_sys_time_usec(), h(), medianfilter, stereocam, stereocam_msg_buf, STEREOCAM_USE_MEDIAN_FILTER, type(), UpdateMedianFilterVect3Float, VEL_STEREOCAM_ID, FloatVect3::x, FloatVect3::y, and FloatVect3::z.
Referenced by stereocam_event().
Variable Documentation
medianfilter
struct MedianFilter3Float medianfilter
Definition at line 93 of file stereocam.c.
Referenced by stereocam_init(), and stereocam_parse_msg().
stereocam
struct stereocam_t stereocam
Initial value:
= {
  .device = (&((UART_LINK).device)),
  .msg_available = false
}
Definition at line 82 of file stereocam.c.
Referenced by state2stereocam(), stereocam_event(), stereocam_init(), and stereocam_parse_msg().
stereocam_msg_buf
uint8_t stereocam_msg_buf[256] static
The message buffer for the stereocamera.
Definition at line 86 of file stereocam.c.
Referenced by stereocam_event(), and stereocam_parse_msg().