Paparazzi UAS: microrl_t Struct Reference
microrl_t Struct Reference
#include <microrl.h>
Data Fields
ring_history_t ring_hist
char * prompt_str
char cmdline [_COMMAND_LINE_LEN]
int cmdlen
int cursor
const char * tkn_arr [_COMMAND_TOKEN_NMB]
void(* execute)(int argc, const char *const *argv)
const char **(* get_completion)(int argc, const char *const *argv)
void(* print)(const char *)
void(* sigint)(void)
Detailed Description
Definition at line 65 of file microrl.h.
Field Documentation
cmdlen
int microrl_t::cmdlen
Definition at line 71 of file microrl.h.
Referenced by escape_process(), hist_search(), microrl_backspace(), microrl_init(), microrl_insert_char(), microrl_insert_text(), new_line_handler(), and terminal_print_line().
cmdline
char microrl_t::cmdline[_COMMAND_LINE_LEN]
Definition at line 70 of file microrl.h.
Referenced by hist_search(), microrl_backspace(), microrl_get_complite(), microrl_init(), microrl_insert_text(), new_line_handler(), split(), and terminal_print_line().
cursor
int microrl_t::cursor
Definition at line 72 of file microrl.h.
Referenced by escape_process(), hist_search(), microrl_backspace(), microrl_get_complite(), microrl_init(), microrl_insert_char(), microrl_insert_text(), and new_line_handler().
execute
void(* microrl_t::execute) (int argc, const char *const *argv)
Definition at line 74 of file microrl.h.
Referenced by microrl_init(), microrl_set_execute_callback(), and new_line_handler().
get_completion
const char**(* microrl_t::get_completion) (int argc, const char *const *argv)
Definition at line 75 of file microrl.h.
Referenced by microrl_get_complite(), microrl_init(), and microrl_set_complete_callback().
print
void(* microrl_t::print) (const char *)
Definition at line 76 of file microrl.h.
Referenced by microrl_get_complite(), microrl_init(), microrl_insert_char(), new_line_handler(), print_prompt(), terminal_backspace(), terminal_move_cursor(), terminal_newline(), terminal_print_line(), and terminal_reset_cursor().
prompt_str
char* microrl_t::prompt_str
Definition at line 69 of file microrl.h.
Referenced by microrl_init(), and print_prompt().
ring_hist
ring_history_t microrl_t::ring_hist
Definition at line 67 of file microrl.h.
Referenced by hist_search(), microrl_init(), and new_line_handler().
sigint
void(* microrl_t::sigint) (void)
Definition at line 78 of file microrl.h.
Referenced by microrl_init(), microrl_insert_char(), and microrl_set_sigint_callback().
tkn_arr
const char* microrl_t::tkn_arr[_COMMAND_TOKEN_NMB]
Definition at line 73 of file microrl.h.
Referenced by microrl_get_complite(), new_line_handler(), and split().
The documentation for this struct was generated from the following file:
sw/airborne/arch/chibios/modules/core/microrl/microrl.h