Paparazzi UAS: sw/airborne/modules/radio_control/superbitrf_rc.h File Reference
superbitrf_rc.h File Reference
#include "modules/datalink/superbitrf.h"
Macros
#define RADIO_CONTROL_NB_CHANNEL 14
#define RADIO_THROTTLE 0
#define RADIO_ROLL 1
#define RADIO_PITCH 2
#define RADIO_YAW 3
#define RADIO_GEAR 4
#define RADIO_FLAP 5
#define RADIO_AUX1 5
#define RADIO_AUX2 6
#define RADIO_AUX3 7
#define RADIO_AUX4 8
#define RADIO_AUX5 9
#define RADIO_AUX6 10
#define RADIO_AUX7 11
#define RADIO_AUX8 12
#define RADIO_AUX9 13
#define RADIO_MODE RADIO_GEAR
#define RadioControlEvent(_received_frame_handler) radio_control_impl_event(_received_frame_handler)
Functions
void radio_control_impl_event (void(*_received_frame_handler)(void))
RC event function with handler callback.
Detailed Description
DSM2 and DSMX radio control implementation for the cyrf6936 2.4GHz radio chip trough SPI
Definition in file superbitrf_rc.h.
Macro Definition Documentation
RADIO_AUX1
#define RADIO_AUX1 5
Definition at line 60 of file superbitrf_rc.h.
RADIO_AUX2
#define RADIO_AUX2 6
Definition at line 63 of file superbitrf_rc.h.
RADIO_AUX3
#define RADIO_AUX3 7
Definition at line 66 of file superbitrf_rc.h.
RADIO_AUX4
#define RADIO_AUX4 8
Definition at line 69 of file superbitrf_rc.h.
RADIO_AUX5
#define RADIO_AUX5 9
Definition at line 72 of file superbitrf_rc.h.
RADIO_AUX6
#define RADIO_AUX6 10
Definition at line 75 of file superbitrf_rc.h.
RADIO_AUX7
#define RADIO_AUX7 11
Definition at line 78 of file superbitrf_rc.h.
RADIO_AUX8
#define RADIO_AUX8 12
Definition at line 81 of file superbitrf_rc.h.
RADIO_AUX9
#define RADIO_AUX9 13
Definition at line 84 of file superbitrf_rc.h.
RADIO_CONTROL_NB_CHANNEL
#define RADIO_CONTROL_NB_CHANNEL 14
Definition at line 33 of file superbitrf_rc.h.
RADIO_FLAP
#define RADIO_FLAP 5
Definition at line 57 of file superbitrf_rc.h.
RADIO_GEAR
#define RADIO_GEAR 4
Definition at line 54 of file superbitrf_rc.h.
RADIO_MODE
#define RADIO_MODE RADIO_GEAR
Definition at line 89 of file superbitrf_rc.h.
RADIO_PITCH
#define RADIO_PITCH 2
Definition at line 48 of file superbitrf_rc.h.
RADIO_ROLL
#define RADIO_ROLL 1
Definition at line 45 of file superbitrf_rc.h.
RADIO_THROTTLE
#define RADIO_THROTTLE 0
Definition at line 42 of file superbitrf_rc.h.
RADIO_YAW
#define RADIO_YAW 3
Definition at line 51 of file superbitrf_rc.h.
RadioControlEvent
#define RadioControlEvent (_received_frame_handler) radio_control_impl_event(_received_frame_handler)
Definition at line 98 of file superbitrf_rc.h.
Function Documentation
radio_control_impl_event()
void radio_control_impl_event (void(*)(void) _received_frame_handler)
RC event function with handler callback.
PPM frames are normalized using the IIR filter.
Definition at line 61 of file cc2500_paparazzi.c.
References SuperbitRF::cyrf6936, cyrf6936_event(), SHott::frame_available, Sbus::frame_available, RadioControl::frame_cpt, frsky_raw, hott, hott_decode_event(), SuperbitRF::num_channels, ppm_frame_available, ppm_pulses, SHott::pulses, Sbus::pulses, radio_control, RADIO_CONTROL_NB_CHANNEL, RadioControl::radio_ok_cpt, rc_datalink_normalize(), rc_dl_frame_available, rc_dl_values, Sbus::rc_failsafe, SuperbitRF::rc_frame_available, Sbus::rc_lost, RC_OK, RC_REALLY_LOST, SuperbitRF::rc_values, rxRuntimeConfig_s::rcFrameStatusFn, rxRuntimeConfig_s::rcProcessFrameFn, rxRuntimeConfig_s::rcReadRawFn, RX_FRAME_COMPLETE, rxRuntimeConfig, sbus, sbus2, sbus_decode_event(), sbus_dual_decode_event(), RadioControl::status, superbitrf, superbitrf_event(), superbitrf_rc_normalize(), RadioControl::time_since_last_frame, and RadioControl::values.