Paparazzi UAS: sw/airborne/modules/switching/switch_uart.c File Reference
switch_uart.c File Reference
#include "modules/switching/switch_uart.h"
#include "mcu_periph/uart.h"
Macros
#define DROP_STRINGLEN 19
Functions
void periodic_switch_uart (void)
void drop_ball (uint8_t number)
Variables
uint8_t switch_uart_channel = 0
uint8_t switch_uart_status = 0
static uint8_t drop_string [] = "<Drop_Paintball_Now"
Macro Definition Documentation
DROP_STRINGLEN
#define DROP_STRINGLEN 19
Definition at line 33 of file switch_uart.c.
Function Documentation
drop_ball()
void drop_ball (uint8_t number)
Definition at line 44 of file switch_uart.c.
References drop_string, DROP_STRINGLEN, last, and uart_put_byte().
periodic_switch_uart()
void periodic_switch_uart (void)
Definition at line 36 of file switch_uart.c.
References switch_uart_status, uart_char_available(), and uart_getch().
Variable Documentation
drop_string
uint8_t drop_string[] = "<Drop_Paintball_Now" static
Definition at line 32 of file switch_uart.c.
Referenced by drop_ball().
switch_uart_channel
uint8_t switch_uart_channel = 0
Definition at line 29 of file switch_uart.c.
switch_uart_status
uint8_t switch_uart_status = 0
Definition at line 30 of file switch_uart.c.
Referenced by periodic_switch_uart().