Paparazzi UAS: sw/airborne/modules/telemetry/telemetry_intermcu.h File Reference
telemetry_intermcu.h File Reference
Telemetry through InterMCU.
#include "std.h"
Functions
void telemetry_intermcu_init (void)
void telemetry_intermcu_periodic (void)
void telemetry_intermcu_event (void)
void telemetry_intermcu_on_msg (uint8_t *msg, uint8_t size)
Detailed Description
Telemetry through InterMCU.
Definition in file telemetry_intermcu.h.
Function Documentation
telemetry_intermcu_event()
void telemetry_intermcu_event (void)
Definition at line 67 of file telemetry_intermcu_ap.c.
References intermcu_t::device, fbw_mode, FBW_MODE_FAILSAFE, intermcu, INTERMCU_FBW, telemetry_intermcu_t::msg_received, telemetry_intermcu_t::rx_buffer, telemetry_intermcu, telemetry_intermcu_t::trans, and intermcu_t::transport.
telemetry_intermcu_init()
void telemetry_intermcu_init (void)
Definition at line 47 of file telemetry_intermcu_ap.c.
References telemetry_intermcu_t::dev, telemetry_intermcu, telemetry_intermcu_check_free_space(), telemetry_intermcu_put_buffer(), telemetry_intermcu_put_byte(), telemetry_intermcu_send_message(), and telemetry_intermcu_t::trans.
telemetry_intermcu_on_msg()
void telemetry_intermcu_on_msg (uint8_t * msg, uint8_t size)
Definition at line 72 of file telemetry_intermcu_ap.c.
References datalink_nb_msgs, datalink_time, telemetry_intermcu_t::dev, dl_parse_msg(), msg, telemetry_intermcu, telemetry_intermcu_repack(), and telemetry_intermcu_t::trans.
Referenced by intermcu_parse_msg().
telemetry_intermcu_periodic()
void telemetry_intermcu_periodic (void)
Definition at line 61 of file telemetry_intermcu_ap.c.
References DefaultPeriodic, telemetry_intermcu_t::dev, telemetry_intermcu, and telemetry_intermcu_t::trans.