Paparazzi UAS: sw/airborne/arch/chibios/modules/tlsf/tlsf_malloc_arch.c File Reference
tlsf_malloc_arch.c File Reference
#include <ch.h>
#include <tlsf.h>
#include "modules/tlsf/tlsf_malloc.h"
Data Structures
struct _tlsf_memory_heap_t
Macros
#define error_cb NULL
Functions
static void stat_tlsf_walker (void *ptr, size_t size, int used, void *user)
void tlsf_init_heaps (void)
void * tlsf_get_heap_addr (const tlsf_memory_heap_t *heap)
void * tlsf_malloc_r (tlsf_memory_heap_t *heap, size_t bytes)
void * tlsf_memalign_r (tlsf_memory_heap_t *heap, size_t align, size_t bytes)
void * tlsf_realloc_r (tlsf_memory_heap_t *heap, void *ptr, size_t bytes)
void tlsf_free_r (tlsf_memory_heap_t *heap, void *ptr)
void tlsf_stat_r (tlsf_memory_heap_t *heap, struct tlsf_stat_t *stat)
int tlsf_check_r (tlsf_memory_heap_t *heap)
Detailed Description
Dynamic memory allocation based on TLSF library.
Definition in file tlsf_malloc_arch.c.
Data Structure Documentation
_tlsf_memory_heap_t
struct _tlsf_memory_heap_t
Definition at line 33 of file tlsf_malloc_arch.c.
Data Fields
mutex_t * mtx
tlsf_t tlsf
Macro Definition Documentation
error_cb
#define error_cb NULL
Definition at line 71 of file tlsf_malloc_arch.c.
Function Documentation
stat_tlsf_walker()
static void stat_tlsf_walker (void * ptr, size_t size, int used, void * user) static
Definition at line 151 of file tlsf_malloc_arch.c.
References tlsf_stat_t::mfree, and tlsf_stat_t::mused.
Referenced by tlsf_stat_r().
tlsf_check_r()
int tlsf_check_r (tlsf_memory_heap_t * heap)
Definition at line 137 of file tlsf_malloc_arch.c.
References _tlsf_memory_heap_t::mtx, and _tlsf_memory_heap_t::tlsf.
tlsf_free_r()
void tlsf_free_r (tlsf_memory_heap_t * heap, void * ptr)
Definition at line 119 of file tlsf_malloc_arch.c.
References _tlsf_memory_heap_t::mtx, and _tlsf_memory_heap_t::tlsf.
Referenced by msgqueue_send_timeout().
tlsf_get_heap_addr()
void* tlsf_get_heap_addr (const tlsf_memory_heap_t * heap)
Definition at line 90 of file tlsf_malloc_arch.c.
References _tlsf_memory_heap_t::tlsf.
Referenced by msgqueue_pop_timeout(), and msgqueue_send_timeout().
tlsf_init_heaps()
void tlsf_init_heaps (void)
Definition at line 74 of file tlsf_malloc_arch.c.
References error_cb, HEAP_CCM, HEAP_CCM_SIZE, _tlsf_memory_heap_t::mtx, and _tlsf_memory_heap_t::tlsf.
tlsf_malloc_r()
void* tlsf_malloc_r (tlsf_memory_heap_t * heap, size_t bytes)
Definition at line 95 of file tlsf_malloc_arch.c.
References _tlsf_memory_heap_t::mtx, and _tlsf_memory_heap_t::tlsf.
Referenced by msgqueue_copy_send_timeout().
tlsf_memalign_r()
void* tlsf_memalign_r (tlsf_memory_heap_t * heap, size_t align, size_t bytes)
Definition at line 103 of file tlsf_malloc_arch.c.
References _tlsf_memory_heap_t::mtx, and _tlsf_memory_heap_t::tlsf.
tlsf_realloc_r()
void* tlsf_realloc_r (tlsf_memory_heap_t * heap, void * ptr, size_t bytes)
Definition at line 111 of file tlsf_malloc_arch.c.
References _tlsf_memory_heap_t::mtx, and _tlsf_memory_heap_t::tlsf.
tlsf_stat_r()
void tlsf_stat_r (tlsf_memory_heap_t * heap, struct tlsf_stat_t * stat)
Definition at line 127 of file tlsf_malloc_arch.c.
References tlsf_stat_t::mfree, _tlsf_memory_heap_t::mtx, tlsf_stat_t::mused, stat_tlsf_walker(), and _tlsf_memory_heap_t::tlsf.