Paparazzi UAS: sw/airborne/arch/chibios/modules/uavcan/uavcan.c File Reference
uavcan.c File Reference
#include "uavcan.h"
Macros
#define UAVCAN_NODE_ID 100
#define UAVCAN_BAUDRATE 1000000
Functions
static THD_FUNCTION (uavcan_rx, p)
static THD_FUNCTION (uavcan_tx, p)
static void onTransferReceived (CanardInstance *ins, CanardRxTransfer *transfer)
Whenever a valid and 'accepted' transfer is received.
static bool shouldAcceptTransfer (const CanardInstance *ins, uint64_t *out_data_type_signature, uint16_t data_type_id, CanardTransferType transfer_type, uint8_t source_node_id)
If we should accept this transfer.
static void uavcanInitIface (struct uavcan_iface_t *iface)
Initialize uavcan interface.
void uavcan_init (void)
Initialize all uavcan interfaces.
void uavcan_bind (uint16_t data_type_id, uint64_t data_type_signature, uavcan_event *ev, uavcan_callback cb)
Bind to a receiving message from uavcan.
void uavcan_broadcast (struct uavcan_iface_t *iface, uint64_t data_type_signature, uint16_t data_type_id, uint8_t priority, const void *payload, uint16_t payload_len)
Broadcast an uavcan message to a specific interface.
Variables
static uavcan_event * uavcan_event_hd = NULL
Detailed Description
Interface from actuators to ChibiOS CAN driver using UAVCan
Definition in file uavcan.c.
Macro Definition Documentation
UAVCAN_BAUDRATE
#define UAVCAN_BAUDRATE 1000000
Definition at line 34 of file uavcan.c.
UAVCAN_NODE_ID
#define UAVCAN_NODE_ID 100
Definition at line 30 of file uavcan.c.
Function Documentation
onTransferReceived()
static void onTransferReceived (CanardInstance * ins, CanardRxTransfer * transfer) static
Whenever a valid and 'accepted' transfer is received.
Definition at line 194 of file uavcan.c.
References abi_struct::cb, ev, abi_struct::next, transfer(), and uavcan_event_hd.
Referenced by uavcanInitIface().
shouldAcceptTransfer()
static bool shouldAcceptTransfer (const CanardInstance * ins, uint64_t * out_data_type_signature, uint16_t data_type_id, CanardTransferType transfer_type, uint8_t source_node_id) static
If we should accept this transfer.
Definition at line 209 of file uavcan.c.
References ev, abi_struct::next, and uavcan_event_hd.
Referenced by uavcanInitIface().
THD_FUNCTION() [1/2]
static THD_FUNCTION (uavcan_rx , p) static
Definition at line 100 of file uavcan.c.
References uavcan_iface_t::can_driver, uavcan_iface_t::canard, uavcan_iface_t::mutex, and p.
THD_FUNCTION() [2/2]
static THD_FUNCTION (uavcan_tx , p) static
Definition at line 137 of file uavcan.c.
References uavcan_iface_t::can_driver, uavcan_iface_t::canard, uavcan_iface_t::mutex, p, and uavcan_iface_t::tx_request.
uavcan_bind()
void uavcan_bind (uint16_t data_type_id, uint64_t data_type_signature, uavcan_event * ev, uavcan_callback cb)
Bind to a receiving message from uavcan.
Definition at line 267 of file uavcan.c.
References abi_struct::cb, ev, abi_struct::next, and uavcan_event_hd.
Referenced by actuators_uavcan_init().
uavcan_broadcast()
void uavcan_broadcast (struct uavcan_iface_t * iface, uint64_t data_type_signature, uint16_t data_type_id, uint8_t priority, const void * payload, uint16_t payload_len)
Broadcast an uavcan message to a specific interface.
Definition at line 282 of file uavcan.c.
References uavcan_iface_t::canard, uavcan_iface_t::initialized, uavcan_iface_t::mutex, uavcan_iface_t::transfer_id, and uavcan_iface_t::tx_request.
Referenced by actuators_uavcan_commit().
uavcan_init()
void uavcan_init (void)
Initialize all uavcan interfaces.
uavcan interfaces
Definition at line 254 of file uavcan.c.
References uavcanInitIface().
uavcanInitIface()
static void uavcanInitIface (struct uavcan_iface_t * iface) static
Initialize uavcan interface.
Definition at line 230 of file uavcan.c.
References uavcan_iface_t::can_cfg, uavcan_iface_t::can_driver, uavcan_iface_t::canard, uavcan_iface_t::canard_memory_pool, uavcan_iface_t::mutex, uavcan_iface_t::node_id, onTransferReceived(), shouldAcceptTransfer(), uavcan_iface_t::thread_rx_wa, uavcan_iface_t::thread_rx_wa_size, and uavcan_iface_t::tx_request.
Referenced by uavcan_init().
Variable Documentation
uavcan_event_hd
uavcan_event* uavcan_event_hd = NULL static
Definition at line 37 of file uavcan.c.
Referenced by onTransferReceived(), shouldAcceptTransfer(), and uavcan_bind().