Paparazzi UAS: sw/airborne/modules/digital_cam/video_cam_ctrl.c File Reference
video_cam_ctrl.c File Reference
#include "video_cam_ctrl.h"
#include "generated/modules.h"
#include "modules/digital_cam/dc.h"
#include "modules/computer_vision/video_capture.h"
Functions
void digital_cam_video_init (void)
void digital_cam_video_periodic (void)
void dc_send_command (uint8_t cmd)
Send Command To Camera.
Function Documentation
dc_send_command()
void dc_send_command (uint8_t cmd)
Send Command To Camera.
Definition at line 50 of file video_cam_ctrl.c.
References atmega_i2c_cam_ctrl_send(), DC_OFF, DC_ON, dc_send_command_common(), dc_send_shot_position(), DC_SHOOT, DC_TALLER, DC_WIDER, and video_capture_shoot().
digital_cam_video_init()
void digital_cam_video_init (void)
Definition at line 33 of file video_cam_ctrl.c.
References dc_init().
digital_cam_video_periodic()
void digital_cam_video_periodic (void)
Definition at line 39 of file video_cam_ctrl.c.
References dc_periodic().