Paparazzi UAS: sw/airborne/modules/computer_vision/video_usb_logger.c File Reference
video_usb_logger.c File Reference
#include "video_usb_logger.h"
#include <stdio.h>
#include "state.h"
#include "viewvideo.h"
#include "cv.h"
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include "computer_vision/lib/encoding/jpeg.h"
#include "pose_history/pose_history.h"
Macros
#define VIDEO_USB_LOGGER_PATH /data/video/usb
Set the default File logger path to the USB drive.
#define VIDEO_USB_LOGGER_FPS 0
Default FPS (zero means run at camera fps)
Functions
static void save_shot_on_disk (struct image_t *img, struct image_t *img_jpeg)
static struct image_t * log_image (struct image_t *img, uint8_t camera_id)
void video_usb_logger_start (void)
Start the file logger and open a new file.
void video_usb_logger_stop (void)
Stop the logger an nicely close the file.
void video_usb_logger_periodic (void)
Variables
static FILE * video_usb_logger = NULL
The file pointer.
struct image_t img_jpeg_global
bool created_jpeg = FALSE
char foldername [512]
int shotNumber = 0
Macro Definition Documentation
VIDEO_USB_LOGGER_FPS
#define VIDEO_USB_LOGGER_FPS 0
Default FPS (zero means run at camera fps)
Definition at line 47 of file video_usb_logger.c.
VIDEO_USB_LOGGER_PATH
#define VIDEO_USB_LOGGER_PATH /data/video/usb
Set the default File logger path to the USB drive.
Definition at line 43 of file video_usb_logger.c.
Function Documentation
log_image()
static struct image_t* log_image (struct image_t * img, uint8_t camera_id) static
Definition at line 114 of file video_usb_logger.c.
References created_jpeg, image_t::h, image_create(), IMAGE_JPEG, img_jpeg_global, save_shot_on_disk(), TRUE, and image_t::w.
Referenced by video_usb_logger_start().
save_shot_on_disk()
static void save_shot_on_disk (struct image_t * img, struct image_t * img_jpeg) static
Log the values to a csv file
Definition at line 58 of file video_usb_logger.c.
References counter, pose_t::eulers, foldername, get_rotation_at_timestamp(), jpeg_encode_image(), FloatRates::p, FloatEulers::phi, FloatEulers::psi, FloatRates::q, FloatRates::r, pose_t::rates, shotNumber, sonar, stateGetAccelNed_i(), stateGetPositionNed_i(), FloatEulers::theta, TRUE, video_usb_logger, write_exif_jpeg(), NedCoor_i::x, NedCoor_i::y, and NedCoor_i::z.
Referenced by log_image().
video_usb_logger_periodic()
void video_usb_logger_periodic (void)
Definition at line 163 of file video_usb_logger.c.
video_usb_logger_start()
void video_usb_logger_start (void)
Start the file logger and open a new file.
Definition at line 127 of file video_usb_logger.c.
References counter, cv_add_to_device(), foldername, log_image(), video_usb_logger, VIDEO_USB_LOGGER_FPS, and VIDEO_USB_LOGGER_PATH.
video_usb_logger_stop()
void video_usb_logger_stop (void)
Stop the logger an nicely close the file.
Definition at line 155 of file video_usb_logger.c.
References video_usb_logger.
Variable Documentation
created_jpeg
bool created_jpeg = FALSE
Definition at line 54 of file video_usb_logger.c.
Referenced by log_image().
foldername
char foldername[512]
Definition at line 55 of file video_usb_logger.c.
Referenced by save_shot_on_disk(), and video_usb_logger_start().
img_jpeg_global
struct image_t img_jpeg_global
Definition at line 53 of file video_usb_logger.c.
Referenced by log_image().
shotNumber
int shotNumber = 0
Definition at line 56 of file video_usb_logger.c.
Referenced by save_shot_on_disk().
video_usb_logger
FILE* video_usb_logger = NULL static
The file pointer.
Definition at line 52 of file video_usb_logger.c.
Referenced by save_shot_on_disk(), video_usb_logger_start(), and video_usb_logger_stop().